#!/bin/bash
set -euo pipefail

echo "=============================="
echo "[*] User login/history details:"
echo "=============================="

# Get all users
USERS=$(sudo sacli UserPropGet | jq -r 'keys[]')

for user in $USERS; do
    echo "User: $user"
    # User properties
    sudo sacli UserPropGet | jq -r --arg u "$user" '
    .[$u] | 
    "  type: \(.type // "N/A")
      superuser: \(.prop_superuser // "false")
      last login: \(.last_login // "N/A")
      login history: \(.login_history // "N/A")
      failed logins: \(.failed_logins // "0")
      autogenerated password: \(.prop_autogenerate // "false")
    "'
    echo "------------------------------"
done
echo "=============================="
