Os/161: device Struct Reference
device Struct Reference
#include <device.h>
Data Fields
int(* d_open)(struct device *, int flags_from_open)
int(* d_close)(struct device *)
int(* d_io)(struct device *, struct uio *)
int(* d_ioctl)(struct device *, int op, userptr_t data)
blkcnt_t d_blocks
blksize_t d_blocksize
dev_t d_devnumber
void * d_data
Detailed Description
Definition at line 44 of file device.h.
Field Documentation
blkcnt_t d_blocks
Definition at line 50 of file device.h.
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), dev_gettype(), dev_stat(), dev_truncate(), dev_tryseek(), devnull_create(), lhd_io(), and sfs_domount().
blksize_t d_blocksize
Definition at line 51 of file device.h.
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), dev_stat(), dev_truncate(), dev_tryseek(), devnull_create(), and sfs_domount().
int(* d_close)(struct device *)
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), dev_close(), and devnull_create().
void* d_data
Definition at line 55 of file device.h.
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), devnull_create(), lhd_io(), and randio().
dev_t d_devnumber
Definition at line 53 of file device.h.
Referenced by dev_stat(), devnull_create(), and vfs_doadd().
int(* d_io)(struct device *, struct uio *)
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), dev_read(), dev_write(), devnull_create(), and sfs_rwblock().
int(* d_ioctl)(struct device *, int op, userptr_t data)
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), dev_ioctl(), and devnull_create().
int(* d_open)(struct device *, int flags_from_open)
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), dev_open(), and devnull_create().
The documentation for this struct was generated from the following file:
kern/include/device.h