Os/161: build/install/include/err.h File Reference
build/install/include/err.h File Reference
#include <kern/types.h>
Functions
void warn (const char *fmt,...)
void warnx (const char *fmt,...)
void err (int exitcode, const char *fmt,...)
void errx (int exitcode, const char *fmt,...)
void vwarn (const char *fmt, __va_list)
void vwarnx (const char *fmt, __va_list)
void verr (int exitcode, const char *fmt, __va_list)
void verrx (int exitcode, const char *fmt, __va_list)
Function Documentation
void err (int exitcode, const char * fmt, ...)
Definition at line 176 of file err.c.
Referenced by __malloc_init(), big_file(), cat(), cleanup(), closedisk(), closeit(), complain(), concur(), copy(), dir_test(), diskread(), diskwrite(), dobadreads(), docat(), docreatestress(), dohardlink(), doreadat0(), doreadateof(), doreadone(), doreadstress(), doremove(), dorename(), dorm(), dosymlink(), dowritestress(), dowritestress2(), finish(), firstread(), fstest_read(), fstest_remove(), fstest_write(), hog(), isdir(), killdir(), listdir(), main(), makeprocs(), mkfile(), opendisk(), openit(), print(), readateof(), readit(), readone(), recursedir(), setup(), sink(), spawnv(), startup(), subproc_read(), subproc_write(), syscall(), tail(), test2(), test3(), test4(), test5(), test6(), test7(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), and whalemating().
void errx (int exitcode, const char * fmt, ...)
Definition at line 185 of file err.c.
Referenced by __malloc_init(), __malloc_sbrk(), __malloc_split(), __malloc_trymerge(), addmemory(), big_file(), check(), check_buffer(), check_sb(), domalloc(), doreadat0(), doreadateof(), doreadone(), dumpsb(), firstread(), free(), main(), malloc(), mkfile(), opendisk(), option(), readateof(), readit(), readone(), subproc_read(), test3(), test6(), test7(), writebitmap(), and writesuper().
void verr (int exitcode, const char * fmt, __va_list)
Definition at line 138 of file err.c.
Referenced by err().
void verrx (int exitcode, const char * fmt, __va_list)
Definition at line 146 of file err.c.
Referenced by errx().
void vwarn (const char * fmt, __va_list)
Definition at line 124 of file err.c.
Referenced by warn().
void vwarnx (const char * fmt, __va_list)
Definition at line 131 of file err.c.
Referenced by warnx().
void warn (const char * fmt, ...)
Definition at line 158 of file err.c.
Referenced by cmd_chdir(), create_testdir(), create_testfile(), create_testlink(), docommand(), dofork(), dorm(), dowait(), dowaitpoll(), dup2_self(), enforce_sbrk(), exec_common_fork(), forkoff(), ftruncate_fd_device(), getdirentry_setup(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_pasteof(), main(), makeprocs(), open_testfile(), report_survival(), report_test(), report_test2(), sbrk_unalignedneg(), sbrk_unalignedpos(), wait_badflags(), wait_badstatus(), wait_parent(), wait_siblings(), wait_siblings_child(), wait_unaligned(), and waitall().
void warnx (const char * fmt, ...)
Definition at line 167 of file err.c.
Referenced by __malloc_init(), adjust_filelinks(), bitmap_mark(), check(), check_bitmap(), check_dir(), check_dir_entry(), check_inode_blocks(), check_root_dir(), check_sb(), check_timing(), dirread(), dirwrite(), docommand(), dorm(), dowait(), dumpdir(), dup2_self(), enforce_sbrk(), exec_common_fork(), free(), lseek_file_stdin(), lseek_loc_pasteof(), main(), malloc(), open_testfile(), reboot_badflags(), report_test(), report_test2(), reportbits(), runtest(), sbrk_unalignedneg(), sbrk_unalignedpos(), test3(), test4(), test5(), test_dup2(), triple(), wait_siblings(), and waitall().