Os/161: user/include/stdio.h File Reference
user/include/stdio.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Defines
#define EOF (-1)
Functions
int __vprintf (void(*sendfunc)(void *clientdata, const char *, size_t len), void *clientdata, const char *fmt, __va_list ap)
int printf (const char *fmt,...)
int vprintf (const char *fmt, __va_list ap)
int snprintf (char *buf, size_t len, const char *fmt,...)
int vsnprintf (char *buf, size_t len, const char *fmt, __va_list ap)
int puts (const char *)
int __puts (const char *)
int putchar (int)
int getchar (void)
Define Documentation
#define EOF (-1)
Definition at line 42 of file stdio.h.
Function Documentation
int __puts (const char *)
Definition at line 40 of file __puts.c.
References count, and putchar().
int __vprintf (void(*)(void *clientdata, const char *, size_t len) sendfunc, void * clientdata, const char * fmt, __va_list ap)
int getchar (void)
Definition at line 39 of file getchar.c.
References ch, EOF, read(), and STDIN_FILENO.
int printf (const char * fmt, ...)
Definition at line 55 of file printf.c.
References va_end, va_start, and vprintf().
int putchar (int)
Definition at line 41 of file putchar.c.
References EOF, STDOUT_FILENO, and write().
int puts (const char *)
Definition at line 37 of file puts.c.
References __puts(), and putchar().
int snprintf (char * buf, size_t len, const char * fmt, ...)
Definition at line 148 of file snprintf.c.
References va_end, va_start, and vsnprintf().
int vprintf (const char * fmt, __va_list ap)
Definition at line 67 of file printf.c.
References __printf_send(), __vprintf(), and NULL.
int vsnprintf (char * buf, size_t len, const char * fmt, __va_list ap)
Definition at line 99 of file snprintf.c.
References __snprintf_send(), __vprintf(), SNP::buf, SNP::buflen, and SNP::bufpos.