Os/161: user/include/stdlib.h File Reference
user/include/stdlib.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Defines
#define RAND_MAX 0x7fffffff
Functions
int atoi (const char *)
void abort (void)
void exit (int code)
int system (const char *command)
long random (void)
void srandom (unsigned long seed)
char * initstate (unsigned long, char *, size_t)
char * setstate (char *)
void * malloc (size_t size)
void free (void *ptr)
Define Documentation
#define RAND_MAX 0x7fffffff
Definition at line 61 of file stdlib.h.
Function Documentation
void abort (void)
Definition at line 42 of file abort.c.
References _exit().
int atoi (const char *)
Definition at line 50 of file atoi.c.
References NULL, and strchr().
void exit (int code)
Definition at line 38 of file exit.c.
References _exit().
void free (void * ptr)
Definition at line 482 of file malloc.c.
References __heapbase, __malloc_deadbeef(), __malloc_trymerge(), errx(), M_DATA, M_NEXT, M_OK, M_PREV, M_SIZE, NULL, and warnx().
char* initstate (unsigned long, char * , size_t)
Definition at line 282 of file random.c.
References assert, BREAK_0, BREAK_1, BREAK_2, BREAK_3, BREAK_4, DEG_0, DEG_1, DEG_2, DEG_3, DEG_4, LOCKME, MAX_TYPES, NULL, SEP_0, SEP_1, SEP_2, SEP_3, SEP_4, srandom_unlocked(), TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
void* malloc (size_t size)
Definition at line 333 of file malloc.c.
References __heapbase, __malloc_init(), __malloc_sbrk(), __malloc_split(), errx(), M_DATA, M_MKFIELD, M_NEXTOFF, M_OK, M_SIZE, NULL, and warnx().
long random (void)
Definition at line 151 of file random.c.
References LOCKME, NULL, panic(), random_unlocked(), random_softc::rs_devdata, random_softc::rs_random, and UNLOCKME.
char* setstate (char *)
Definition at line 354 of file random.c.
References assert, degrees, LOCKME, MAX_TYPES, NULL, seps, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
void srandom (unsigned long seed)
Definition at line 250 of file random.c.
References LOCKME, srandom_unlocked(), and UNLOCKME.
int system (const char * command)
Definition at line 45 of file system.c.
References _exit(), E2BIG, errno, execv(), fork(), MAXARGS, MAXCMDSIZE, NULL, pid, strcpy(), strlen(), strtok(), and waitpid().