Os/161: kern/include/syscall.h File Reference
kern/include/syscall.h File Reference
Functions
void syscall (struct trapframe *tf)
void enter_forked_process (struct trapframe *tf)
void enter_new_process (int argc, userptr_t argv, vaddr_t stackptr, vaddr_t entrypoint)
int sys_reboot (int code)
int sys___time (userptr_t user_seconds, userptr_t user_nanoseconds)
int sys_open (const char *filename, int flags, int *retval)
int sys_write (int fd, const void *buf, size_t nbytes, int *retval)
int sys_read (int fd, const void *buf, size_t buflen, int *retval)
int sys_close (int fd)
int sys_dup2 (int old_fd, int new_fd, int *retval)
off_t sys_lseek (int fd, off_t pos, int whence, int *retval)
void _exit (int exitcode)
pid_t waitpid (pid_t pid, int *status, int options, int *retval)
pid_t sys_fork (struct trapframe *tf, int *retval)
pid_t sys_getpid (int *retval)
int sys_execv (const char *program, char **args)
Function Documentation
void _exit (int exitcode)
Definition at line 30 of file exit_syscall.c.
void enter_forked_process (struct trapframe * tf)
Definition at line 224 of file syscall.c.
References mips_usermode(), trapframe::tf_a3, trapframe::tf_epc, and trapframe::tf_v0.
Referenced by thread_fork2().
void enter_new_process (int argc, userptr_t argv, vaddr_t stackptr, vaddr_t entrypoint)
Definition at line 418 of file trap.c.
References bzero(), CST_IEp, CST_IRQMASK, CST_KUp, mips_usermode(), trapframe::tf_a0, trapframe::tf_a1, trapframe::tf_epc, trapframe::tf_sp, and trapframe::tf_status.
Referenced by runprogram(), and sys_execv().
int sys___time (userptr_t user_seconds, userptr_t user_nanoseconds)
Definition at line 39 of file time_syscalls.c.
References copyout(), and gettime().
Referenced by syscall().
int sys_close (int fd)
Definition at line 33 of file close_syscall.c.
References EBADF, errno, kfree(), MAX_FD, NULL, vfs_close(), and file::vfs_node.
Referenced by syscall().
int sys_dup2 (int old_fd, int new_fd, int * retval)
Definition at line 36 of file dup2_syscall.c.
References EBADF, EMFILE, errno, kfree(), kmalloc(), MAX_FD, NULL, file::readable, vfs_close(), file::vfs_node, vnode_incopen(), vnode_incref(), and file::writeable.
Referenced by syscall().
int sys_execv (const char * program, char ** args)
Definition at line 32 of file execv_syscall.c.
References as_activate(), as_create(), as_define_stack(), as_destroy(), copyinstr(), copyout(), EINVAL, ENOMEM, enter_new_process(), errno, KASSERT, kfree(), kmalloc(), load_elf(), NULL, O_RDONLY, panic(), STACK_OFFSET, strlen(), vfs_close(), and vfs_open().
Referenced by syscall().
pid_t sys_fork (struct trapframe * tf, int * retval)
Definition at line 27 of file fork_syscall.c.
References thread_fork2().
Referenced by syscall().
pid_t sys_getpid (int * retval)
Definition at line 25 of file getpid_syscall.c.
Referenced by syscall().
off_t sys_lseek (int fd, off_t pos, int whence, int * retval)
Definition at line 42 of file lseek_syscall.c.
References EBADF, EINVAL, errno, ESPIPE, iovec::iov_len, MAX_FD, NULL, file::offset, SEEK_CUR, SEEK_END, SEEK_SET, uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, UIO_USERSPACE, file::vfs_node, VOP_READ, and VOP_TRYSEEK.
Referenced by syscall().
int sys_open (const char * filename, int flags, int * retval)
Definition at line 35 of file open_syscall.c.
References EINVAL, EMFILE, errno, fd, kmalloc(), MAX_FD, NULL, O_ACCMODE, O_RDONLY, O_RDWR, O_WRONLY, file::offset, file::readable, file::vfs_node, vfs_open(), and file::writeable.
Referenced by syscall().
int sys_read (int fd, const void * buf, size_t buflen, int * retval)
Definition at line 38 of file read_syscall.c.
References EBADF, EFAULT, EIO, errno, iovec::iov_len, NULL, file::offset, file::readable, splhigh(), splx(), uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, UIO_USERISPACE, file::vfs_node, and VOP_READ.
Referenced by syscall().
int sys_reboot (int code)
Definition at line 175 of file main.c.
References EINVAL, kprintf(), mainbus_halt(), mainbus_poweroff(), mainbus_reboot(), panic(), RB_HALT, RB_POWEROFF, RB_REBOOT, and shutdown().
Referenced by cmd_quit(), and syscall().
int sys_write (int fd, const void * buf, size_t nbytes, int * retval)
Definition at line 40 of file write_syscall.c.
References EBADF, EFAULT, EIO, errno, iovec::iov_len, NULL, file::offset, splhigh(), splx(), uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, UIO_USERISPACE, UIO_WRITE, file::vfs_node, VOP_WRITE, and file::writeable.
Referenced by syscall().
void syscall (struct trapframe * tf)
Definition at line 97 of file syscall.c.
References _exit(), copyin(), ENOSYS, err(), KASSERT, kprintf(), NULL, sys___time(), SYS___time, SYS__exit, sys_close(), SYS_close, sys_dup2(), SYS_dup2, sys_execv(), SYS_execv, sys_fork(), SYS_fork, sys_getpid(), SYS_getpid, sys_lseek(), SYS_lseek, sys_open(), SYS_open, sys_read(), SYS_read, sys_reboot(), SYS_reboot, SYS_waitpid, sys_write(), SYS_write, trapframe::tf_a0, trapframe::tf_a1, trapframe::tf_a2, trapframe::tf_a3, trapframe::tf_epc, trapframe::tf_sp, trapframe::tf_v0, and waitpid().
Referenced by mips_trap().
pid_t waitpid (pid_t pid, int * status, int options, int * retval)
Definition at line 40 of file waitpid_syscall.c.
References clocksleep(), EFAULT, EINVAL, ESRCH, thread::exit_code, MAX_THREAD, NULL, pid_used, splhigh(), and splx().