Os/161: build/install/include/stdlib.h File Reference
build/install/include/stdlib.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Defines
#define RAND_MAX 0x7fffffff
Functions
int atoi (const char *)
void abort (void)
void exit (int code)
int system (const char *command)
long random (void)
void srandom (unsigned long seed)
char * initstate (unsigned long, char *, size_t)
char * setstate (char *)
void * malloc (size_t size)
void free (void *ptr)
Define Documentation
#define RAND_MAX 0x7fffffff
Definition at line 61 of file stdlib.h.
Function Documentation
void abort (void)
Definition at line 42 of file abort.c.
Referenced by __bad_assert().
int atoi (const char *)
Definition at line 50 of file atoi.c.
Referenced by cmd_exit(), cmd_wait(), doargs(), main(), and threadtest3().
void exit (int code)
Definition at line 38 of file exit.c.
Referenced by _exit(), assemble(), checksize_bins(), checksize_merge(), checksize_valid(), cmd_exit(), doargs(), doclose(), doexactread(), dofork(), doforkall(), dohardlink(), dolseek(), doopen(), doread(), dovalidate(), dowait(), dowrite(), exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), genkeys(), getsize(), go(), main(), makeprocs(), mergebins(), runit(), setup(), sort(), sortbins(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), usage(), validate(), verr(), verrx(), wait_badflags(), wait_badstatus(), and wait_unaligned().
void free (void * ptr)
Definition at line 482 of file malloc.c.
Referenced by addmemory(), check_dir(), test1(), test2(), test3(), test4(), and test567().
char* initstate (unsigned long, char * , size_t)
Definition at line 282 of file random.c.
void* malloc (size_t size)
Definition at line 333 of file malloc.c.
Referenced by domalloc(), test1(), test2(), test3(), test4(), and test567().
long random (void)
Definition at line 151 of file random.c.
Referenced by bitmaptest(), choose_name(), compute_thread(), genkeys(), genkeys_sub(), initarray(), randchar(), readallrandomly(), sleepalot_thread(), test567(), testa(), thread_startup(), and waker_thread().
char* setstate (char *)
Definition at line 354 of file random.c.
void srandom (unsigned long seed)
Definition at line 250 of file random.c.
Referenced by genkeys(), genkeys_sub(), initarray(), main(), readallrandomly(), and test567().
int system (const char * command)
Definition at line 45 of file system.c.