Os/161: kern/arch/mips/include/spinlock.h File Reference
kern/arch/mips/include/spinlock.h File Reference
#include <cdefs.h>
Defines
#define SPINLOCK_DATA_INITIALIZER 0
Typedefs
typedef unsigned spinlock_data_t
Functions
void spinlock_data_set (volatile spinlock_data_t *sd, unsigned val)
spinlock_data_t spinlock_data_get (volatile spinlock_data_t *sd)
spinlock_data_t spinlock_data_testandset (volatile spinlock_data_t *sd)
Define Documentation
#define SPINLOCK_DATA_INITIALIZER 0
Definition at line 40 of file spinlock.h.
Typedef Documentation
typedef unsigned spinlock_data_t
Definition at line 37 of file spinlock.h.
Function Documentation
SPINLOCK_INLINE spinlock_data_t spinlock_data_get (volatile spinlock_data_t * sd)
Definition at line 58 of file spinlock.h.
Referenced by spinlock_acquire(), and spinlock_cleanup().
SPINLOCK_INLINE void spinlock_data_set (volatile spinlock_data_t * sd, unsigned val)
Definition at line 51 of file spinlock.h.
Referenced by spinlock_init(), and spinlock_release().
SPINLOCK_INLINE spinlock_data_t spinlock_data_testandset (volatile spinlock_data_t * sd)
Definition at line 65 of file spinlock.h.
Referenced by spinlock_acquire().