Os/161: kern/dev/generic/random.c File Reference
kern/dev/generic/random.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <lib.h>
#include <uio.h>
#include <vfs.h>
#include <generic/random.h>
#include "autoconf.h"
Functions
static int randopen (struct device *dev, int openflags)
static int randclose (struct device *dev)
static int randio (struct device *dev, struct uio *uio)
static int randioctl (struct device *dev, int op, userptr_t data)
int config_random (struct random_softc *rs, int unit)
uint32_t random (void)
uint32_t randmax (void)
Variables
static struct random_softc * the_random = NULL
Function Documentation
int config_random (struct random_softc * rs, int unit)
Definition at line 116 of file random.c.
References device::d_blocks, device::d_blocksize, device::d_close, device::d_data, device::d_io, device::d_ioctl, device::d_open, ENODEV, KASSERT, NULL, randclose(), randio(), randioctl(), randopen(), random_softc::rs_dev, and vfs_adddev().
Referenced by tryattach_random_to_lrandom().
static int randclose (struct device * dev) [static]
Definition at line 74 of file random.c.
Referenced by config_random().
static int randio (struct device * dev, struct uio * uio) [static]
Definition at line 85 of file random.c.
References device::d_data, EIO, random_softc::rs_devdata, random_softc::rs_read, UIO_READ, and uio::uio_rw.
Referenced by config_random().
static int randioctl (struct device * dev, int op, userptr_t data) [static]
Definition at line 101 of file random.c.
References EIOCTL.
Referenced by config_random().
uint32_t randmax (void)
Definition at line 160 of file random.c.
References NULL, panic(), random_softc::rs_devdata, and random_softc::rs_randmax.
uint32_t random (void)
Definition at line 151 of file random.c.
static int randopen (struct device * dev, int openflags) [static]
Definition at line 58 of file random.c.
References EIO, and O_RDONLY.
Referenced by config_random().
Variable Documentation
struct random_softc* the_random = NULL [static]
Definition at line 50 of file random.c.