Os/161: kern/include/thread.h File Reference
kern/include/thread.h File Reference
#include <spinlock.h>
#include <threadlist.h>
#include <kern/file.h>
#include <mips/trapframe.h>
#include <machine/thread.h>
Data Structures
struct thread
Defines
#define STACK_OFFSET (512)
#define MAX_THREAD 1024
#define STACK_SIZE 4096
#define STACK_MASK (~(vaddr_t)(STACK_SIZE-1))
#define SAME_STACK(p1, p2) (((p1) & STACK_MASK) == ((p2) & STACK_MASK))
Enumerations
enum threadstate_t { S_RUN, S_READY, S_SLEEP, S_ZOMBIE }
Functions
void thread_bootstrap (void)
void thread_start_cpus (void)
void thread_panic (void)
void thread_shutdown (void)
int thread_fork (const char *name, void(*func)(void *, unsigned long), void *data1, unsigned long data2, struct thread **ret)
void thread_exit (void)
void thread_yield (void)
void schedule (void)
void thread_consider_migration (void)
int find_nextpid (void)
pid_t thread_fork2 (struct trapframe *tf, int *retval)
Define Documentation
#define MAX_THREAD 1024
Definition at line 53 of file thread.h.
Referenced by _exit(), find_nextpid(), thread_bootstrap(), and waitpid().
#define SAME_STACK (p1, p2) (((p1) & STACK_MASK) == ((p2) & STACK_MASK))
Definition at line 62 of file thread.h.
Referenced by mips_trap(), and mips_usermode().
#define STACK_MASK (~(vaddr_t)(STACK_SIZE-1))
Definition at line 59 of file thread.h.
#define STACK_OFFSET (512)
Definition at line 51 of file thread.h.
Referenced by runprogram(), and sys_execv().
#define STACK_SIZE 4096
Definition at line 56 of file thread.h.
Referenced by cpu_create(), cpu_machdep_init(), mips_trap(), mips_usermode(), switchframe_init(), thread_fork(), and thread_fork2().
Enumeration Type Documentation
enum threadstate_t
Enumerator:
S_RUN
S_READY
S_SLEEP
S_ZOMBIE
Definition at line 65 of file thread.h.
Function Documentation
int find_nextpid (void)
Definition at line 1415 of file thread.c.
References MAX_THREAD, pid_index, and pid_used.
Referenced by thread_fork(), and thread_fork2().
void schedule (void)
Definition at line 915 of file thread.c.
Referenced by hardclock().
void thread_bootstrap (void)
Definition at line 372 of file thread.c.
References allcpus, cpu::c_curthread, cpu_create(), curcpu, INIT_CURCPU, MAX_THREAD, NULL, thread::parent_id, pid_index, pid_used, and thread::thread_id.
Referenced by boot().
void thread_consider_migration (void)
Definition at line 941 of file thread.c.
References allcpus, cpu::c_isidle, cpu::c_number, cpu::c_runqueue, cpu::c_runqueue_lock, curcpu, DB_THREADS, DEBUG, DIVROUNDUP, ipi_send(), IPI_UNIDLE, KASSERT, NULL, spinlock_acquire(), spinlock_release(), thread::t_cpu, thread::t_name, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_isempty(), threadlist_remhead(), threadlist_remtail(), and threadlist::tl_count.
Referenced by hardclock().
void thread_exit (void)
Definition at line 852 of file thread.c.
References as_activate(), as_destroy(), kfree(), thread::last_fd, MAX_FD, NULL, panic(), S_ZOMBIE, splhigh(), thread::t_addrspace, thread::t_cwd, thread::table_fd, thread_checkstack(), thread_switch(), and VOP_DECREF.
Referenced by _exit(), cmd_quit(), cpu_hatch(), cvtestthread(), fail(), and thread_startup().
int thread_fork (const char * name, void(*)(void *, unsigned long) func, void * data1, unsigned long data2, struct thread ** ret)
Referenced by common_prog(), cvtest(), docreatestress(), doreadstress(), dowritestress(), dowritestress2(), locktest(), make_computes(), make_sleepalots(), mallocstress(), runthreads(), semtest(), and whalemating().
pid_t thread_fork2 (struct trapframe * tf, int * retval)
Definition at line 1298 of file thread.c.
References as_copy(), EMPROC, ENOMEM, enter_forked_process(), errno, find_nextpid(), kfree(), kmalloc(), thread::last_fd, MAX_FD, memmove(), NULL, thread::parent_id, pid_index, pid_used, splhigh(), splx(), STACK_SIZE, switchframe_init(), thread::t_addrspace, thread::t_cpu, thread::t_cwd, thread::t_iplhigh_count, thread::t_name, thread::t_stack, thread::table_fd, thread_checkstack_init(), thread_create(), thread::thread_id, thread_make_runnable(), VOP_DECREF, and VOP_INCREF.
Referenced by sys_fork().
void thread_panic (void)
Definition at line 315 of file thread.c.
References curcpu, ipi_broadcast(), IPI_PANIC, and NULL.
Referenced by panic().
void thread_shutdown (void)
Definition at line 357 of file thread.c.
References ipi_broadcast(), and IPI_OFFLINE.
Referenced by shutdown().
void thread_start_cpus (void)
Definition at line 452 of file thread.c.
References allcpus, cpu_identify(), kprintf(), mainbus_start_cpus(), NULL, P(), sem_create(), and sem_destroy().
Referenced by boot().
void thread_yield (void)
Definition at line 900 of file thread.c.
References NULL, S_READY, and thread_switch().
Referenced by compute_thread(), hardclock(), thread_startup(), and waker_thread().