Os/161: kern/include/vm.h File Reference
kern/include/vm.h File Reference
#include <machine/vm.h>
Defines
#define VM_FAULT_READ 0
#define VM_FAULT_WRITE 1
#define VM_FAULT_READONLY 2
Functions
void vm_bootstrap (void)
int vm_fault (int faulttype, vaddr_t faultaddress)
vaddr_t alloc_kpages (int npages)
void free_kpages (vaddr_t addr)
void vm_tlbshootdown_all (void)
void vm_tlbshootdown (const struct tlbshootdown *)
Define Documentation
#define VM_FAULT_READ 0
Definition at line 43 of file vm.h.
Referenced by mips_trap(), and vm_fault().
#define VM_FAULT_READONLY 2
Definition at line 45 of file vm.h.
Referenced by mips_trap(), and vm_fault().
#define VM_FAULT_WRITE 1
Definition at line 44 of file vm.h.
Referenced by mips_trap(), and vm_fault().
Function Documentation
vaddr_t alloc_kpages (int npages)
Definition at line 78 of file dumbvm.c.
References getppages(), and PADDR_TO_KVADDR.
Referenced by kmalloc(), and subpage_kmalloc().
void free_kpages (vaddr_t addr)
Definition at line 89 of file dumbvm.c.
Referenced by kfree(), subpage_kfree(), and subpage_kmalloc().
void vm_bootstrap (void)
Definition at line 57 of file dumbvm.c.
Referenced by boot().
int vm_fault (int faulttype, vaddr_t faultaddress)
Definition at line 110 of file dumbvm.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, addrspace::as_stackpbase, addrspace::as_vbase1, addrspace::as_vbase2, DB_VM, DEBUG, DUMBVM_STACKPAGES, EFAULT, EINVAL, KASSERT, kprintf(), NULL, NUM_TLB, PAGE_FRAME, PAGE_SIZE, panic(), splhigh(), splx(), tlb_read(), tlb_write(), TLBLO_DIRTY, TLBLO_VALID, USERSTACK, VM_FAULT_READ, VM_FAULT_READONLY, and VM_FAULT_WRITE.
Referenced by mips_trap().
void vm_tlbshootdown (const struct tlbshootdown *)
Definition at line 103 of file dumbvm.c.
References panic().
Referenced by interprocessor_interrupt().
void vm_tlbshootdown_all (void)
Definition at line 97 of file dumbvm.c.
References panic().
Referenced by interprocessor_interrupt().