Os/161: kern/arch/mips/vm/dumbvm.c File Reference
kern/arch/mips/vm/dumbvm.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <spl.h>
#include <spinlock.h>
#include <thread.h>
#include <current.h>
#include <mips/tlb.h>
#include <addrspace.h>
#include <vm.h>
Defines
#define DUMBVM_STACKPAGES 12
Functions
void vm_bootstrap (void)
static paddr_t getppages (unsigned long npages)
vaddr_t alloc_kpages (int npages)
void free_kpages (vaddr_t addr)
void vm_tlbshootdown_all (void)
void vm_tlbshootdown (const struct tlbshootdown *ts)
int vm_fault (int faulttype, vaddr_t faultaddress)
struct addrspace * as_create (void)
void as_destroy (struct addrspace *as)
void as_activate (struct addrspace *as)
int as_define_region (struct addrspace *as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
static void as_zero_region (paddr_t paddr, unsigned npages)
int as_prepare_load (struct addrspace *as)
int as_complete_load (struct addrspace *as)
int as_define_stack (struct addrspace *as, vaddr_t *stackptr)
int as_copy (struct addrspace *old, struct addrspace **ret)
Variables
static struct spinlock stealmem_lock = SPINLOCK_INITIALIZER
Define Documentation
#define DUMBVM_STACKPAGES 12
Definition at line 49 of file dumbvm.c.
Referenced by as_copy(), as_prepare_load(), and vm_fault().
Function Documentation
vaddr_t alloc_kpages (int npages)
Definition at line 78 of file dumbvm.c.
References getppages(), and PADDR_TO_KVADDR.
Referenced by kmalloc(), and subpage_kmalloc().
void as_activate (struct addrspace * as)
Definition at line 228 of file dumbvm.c.
Referenced by runprogram(), sys_execv(), thread_exit(), thread_startup(), and thread_switch().
int as_complete_load (struct addrspace * as)
Definition at line 320 of file dumbvm.c.
Referenced by load_elf().
int as_copy (struct addrspace * old, struct addrspace ** ret)
Definition at line 336 of file dumbvm.c.
Referenced by thread_fork2().
struct addrspace* as_create (void) [read]
Definition at line 203 of file dumbvm.c.
Referenced by as_copy(), runprogram(), and sys_execv().
int as_define_region (struct addrspace * as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
Definition at line 245 of file dumbvm.c.
Referenced by load_elf().
int as_define_stack (struct addrspace * as, vaddr_t * stackptr)
Definition at line 327 of file dumbvm.c.
Referenced by runprogram(), and sys_execv().
void as_destroy (struct addrspace * as)
Definition at line 222 of file dumbvm.c.
Referenced by as_copy(), sys_execv(), and thread_exit().
int as_prepare_load (struct addrspace * as)
Definition at line 291 of file dumbvm.c.
Referenced by as_copy(), and load_elf().
static void as_zero_region (paddr_t paddr, unsigned npages) [static]
Definition at line 285 of file dumbvm.c.
References bzero(), PADDR_TO_KVADDR, and PAGE_SIZE.
Referenced by as_prepare_load().
void free_kpages (vaddr_t addr)
Definition at line 89 of file dumbvm.c.
Referenced by kfree(), subpage_kfree(), and subpage_kmalloc().
static paddr_t getppages (unsigned long npages) [static]
Definition at line 64 of file dumbvm.c.
References ram_stealmem(), spinlock_acquire(), and spinlock_release().
Referenced by alloc_kpages(), and as_prepare_load().
void vm_bootstrap (void)
Definition at line 57 of file dumbvm.c.
Referenced by boot().
int vm_fault (int faulttype, vaddr_t faultaddress)
Definition at line 110 of file dumbvm.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, addrspace::as_stackpbase, addrspace::as_vbase1, addrspace::as_vbase2, DB_VM, DEBUG, DUMBVM_STACKPAGES, EFAULT, EINVAL, KASSERT, kprintf(), NULL, NUM_TLB, PAGE_FRAME, PAGE_SIZE, panic(), splhigh(), splx(), tlb_read(), tlb_write(), TLBLO_DIRTY, TLBLO_VALID, USERSTACK, VM_FAULT_READ, VM_FAULT_READONLY, and VM_FAULT_WRITE.
Referenced by mips_trap().
void vm_tlbshootdown (const struct tlbshootdown * ts)
Definition at line 103 of file dumbvm.c.
References panic().
Referenced by interprocessor_interrupt().
void vm_tlbshootdown_all (void)
Definition at line 97 of file dumbvm.c.
References panic().
Referenced by interprocessor_interrupt().
Variable Documentation
struct spinlock stealmem_lock = SPINLOCK_INITIALIZER [static]
Definition at line 54 of file dumbvm.c.