Os/161: kern/compile/ASST0/autoconf.h File Reference
kern/compile/ASST0/autoconf.h File Reference
Functions
void autoconf_lamebus (struct lamebus_softc *dev, int unit)
struct emu_softc * attach_emu_to_lamebus (int devunit, struct lamebus_softc *bus)
struct ltrace_softc * attach_ltrace_to_lamebus (int devunit, struct lamebus_softc *bus)
struct ltimer_softc * attach_ltimer_to_lamebus (int devunit, struct lamebus_softc *bus)
struct lrandom_softc * attach_lrandom_to_lamebus (int devunit, struct lamebus_softc *bus)
struct lhd_softc * attach_lhd_to_lamebus (int devunit, struct lamebus_softc *bus)
struct lser_softc * attach_lser_to_lamebus (int devunit, struct lamebus_softc *bus)
struct beep_softc * attach_beep_to_ltimer (int devunit, struct ltimer_softc *bus)
struct con_softc * attach_con_to_lser (int devunit, struct lser_softc *bus)
struct rtclock_softc * attach_rtclock_to_ltimer (int devunit, struct ltimer_softc *bus)
struct random_softc * attach_random_to_lrandom (int devunit, struct lrandom_softc *bus)
int config_emu (struct emu_softc *dev, int unit)
int config_ltrace (struct ltrace_softc *dev, int unit)
int config_ltimer (struct ltimer_softc *dev, int unit)
int config_lrandom (struct lrandom_softc *dev, int unit)
int config_lhd (struct lhd_softc *dev, int unit)
int config_lser (struct lser_softc *dev, int unit)
int config_beep (struct beep_softc *dev, int unit)
int config_con (struct con_softc *dev, int unit)
int config_rtclock (struct rtclock_softc *dev, int unit)
int config_random (struct random_softc *dev, int unit)
void pseudoconfig (void)
Function Documentation
struct beep_softc* attach_beep_to_ltimer (int devunit, struct ltimer_softc * bus) [read]
Definition at line 42 of file beep_ltimer.c.
Referenced by tryattach_beep_to_ltimer().
struct con_softc* attach_con_to_lser (int devunit, struct lser_softc * bus) [read]
Definition at line 42 of file con_lser.c.
Referenced by tryattach_con_to_lser().
struct emu_softc* attach_emu_to_lamebus (int devunit, struct lamebus_softc * bus) [read]
Definition at line 46 of file emu_att.c.
Referenced by tryattach_emu_to_lamebus().
struct lhd_softc* attach_lhd_to_lamebus (int devunit, struct lamebus_softc * bus) [read]
Definition at line 45 of file lhd_att.c.
Referenced by tryattach_lhd_to_lamebus().
struct lrandom_softc* attach_lrandom_to_lamebus (int devunit, struct lamebus_softc * bus) [read]
Definition at line 42 of file lrandom_att.c.
Referenced by tryattach_lrandom_to_lamebus().
struct lser_softc* attach_lser_to_lamebus (int devunit, struct lamebus_softc * bus) [read]
Definition at line 64 of file lser_att.c.
Referenced by tryattach_lser_to_lamebus().
struct ltimer_softc* attach_ltimer_to_lamebus (int devunit, struct lamebus_softc * bus) [read]
Definition at line 45 of file ltimer_att.c.
Referenced by tryattach_ltimer_to_lamebus().
struct ltrace_softc* attach_ltrace_to_lamebus (int devunit, struct lamebus_softc * bus) [read]
Definition at line 42 of file ltrace_att.c.
Referenced by tryattach_ltrace_to_lamebus().
struct random_softc* attach_random_to_lrandom (int devunit, struct lrandom_softc * bus) [read]
Definition at line 42 of file random_lrandom.c.
Referenced by tryattach_random_to_lrandom().
struct rtclock_softc* attach_rtclock_to_ltimer (int devunit, struct ltimer_softc * bus) [read]
Definition at line 48 of file rtclock_ltimer.c.
Referenced by tryattach_rtclock_to_ltimer().
void autoconf_lamebus (struct lamebus_softc * dev, int unit)
Definition at line 326 of file autoconf.c.
int config_beep (struct beep_softc * dev, int unit)
Definition at line 50 of file beep.c.
Referenced by tryattach_beep_to_ltimer().
int config_con (struct con_softc * dev, int unit)
Definition at line 399 of file console.c.
Referenced by tryattach_con_to_lser().
int config_emu (struct emu_softc * dev, int unit)
Definition at line 1333 of file emu.c.
Referenced by tryattach_emu_to_lamebus().
int config_lhd (struct lhd_softc * dev, int unit)
Definition at line 282 of file lhd.c.
Referenced by tryattach_lhd_to_lamebus().
int config_lrandom (struct lrandom_softc * dev, int unit)
Definition at line 47 of file lrandom.c.
Referenced by tryattach_lrandom_to_lamebus().
int config_lser (struct lser_softc * dev, int unit)
Definition at line 184 of file lser.c.
Referenced by tryattach_lser_to_lamebus().
int config_ltimer (struct ltimer_softc * dev, int unit)
Definition at line 58 of file ltimer.c.
Referenced by tryattach_ltimer_to_lamebus().
int config_ltrace (struct ltrace_softc * dev, int unit)
Definition at line 81 of file ltrace.c.
Referenced by tryattach_ltrace_to_lamebus().
int config_random (struct random_softc * dev, int unit)
Definition at line 116 of file random.c.
Referenced by tryattach_random_to_lrandom().
int config_rtclock (struct rtclock_softc * dev, int unit)
Definition at line 53 of file rtclock.c.
Referenced by tryattach_rtclock_to_ltimer().
void pseudoconfig (void)
Definition at line 407 of file autoconf.c.