Os/161: kern/arch/mips/syscall/syscall.c File Reference
kern/arch/mips/syscall/syscall.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <syscall.h>
#include <kern/syscall.h>
#include <lib.h>
#include <mips/trapframe.h>
#include <thread.h>
#include <current.h>
#include <copyinout.h>
#include <kern/file.h>
Functions
void syscall (struct trapframe *tf)
void enter_forked_process (struct trapframe *tf)
Function Documentation
void enter_forked_process (struct trapframe * tf)
Definition at line 224 of file syscall.c.
References mips_usermode(), trapframe::tf_a3, trapframe::tf_epc, and trapframe::tf_v0.
Referenced by thread_fork2().
void syscall (struct trapframe * tf)
Definition at line 97 of file syscall.c.
References _exit(), copyin(), ENOSYS, err(), KASSERT, kprintf(), NULL, sys___time(), SYS___time, SYS__exit, sys_close(), SYS_close, sys_dup2(), SYS_dup2, sys_execv(), SYS_execv, sys_fork(), SYS_fork, sys_getpid(), SYS_getpid, sys_lseek(), SYS_lseek, sys_open(), SYS_open, sys_read(), SYS_read, sys_reboot(), SYS_reboot, SYS_waitpid, sys_write(), SYS_write, trapframe::tf_a0, trapframe::tf_a1, trapframe::tf_a2, trapframe::tf_a3, trapframe::tf_epc, trapframe::tf_sp, trapframe::tf_v0, and waitpid().
Referenced by mips_trap().