Os/161: kern/dev/generic/console.h File Reference
kern/dev/generic/console.h File Reference
Data Structures
struct con_softc
Defines
#define CONSOLE_INPUT_BUFFER_SIZE 32
Functions
void con_input (void *cs, int ch)
void con_start (void *cs)
Define Documentation
#define CONSOLE_INPUT_BUFFER_SIZE 32
Definition at line 40 of file console.h.
Referenced by con_input(), and getch_intr().
Function Documentation
void con_input (void * cs, int ch)
Definition at line 182 of file console.c.
References CONSOLE_INPUT_BUFFER_SIZE, con_softc::cs_gotchars, con_softc::cs_gotchars_head, con_softc::cs_gotchars_tail, con_softc::cs_rsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().
void con_start (void * cs)
Definition at line 203 of file console.c.
References con_softc::cs_wsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().