Os/161: kern/dev/generic/console.c File Reference
kern/dev/generic/console.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <generic/console.h>
#include <vfs.h>
#include <device.h>
#include "autoconf.h"
Defines
#define DELAYBUFSIZE 1024
Functions
static void putch_delayed (int ch)
static void flush_delay_buf (void)
static void putch_polled (struct con_softc *cs, int ch)
static void putch_prepare_polled (struct con_softc *cs)
static void putch_complete_polled (struct con_softc *cs)
static void putch_intr (struct con_softc *cs, int ch)
static int getch_intr (struct con_softc *cs)
void con_input (void *vcs, int ch)
void con_start (void *vcs)
void putch (int ch)
void putch_prepare (void)
void putch_complete (void)
int getch (void)
static int con_open (struct device *dev, int openflags)
static int con_close (struct device *dev)
static int con_io (struct device *dev, struct uio *uio)
static int con_ioctl (struct device *dev, int op, userptr_t data)
static int attach_console_to_vfs (struct con_softc *cs)
int config_con (struct con_softc *cs, int unit)
Variables
static struct con_softc * the_console = NULL
static struct lock * con_userlock_read = NULL
static struct lock * con_userlock_write = NULL
static char delayed_outbuf [DELAYBUFSIZE]
static size_t delayed_outbuf_pos = 0
Define Documentation
#define DELAYBUFSIZE 1024
Definition at line 84 of file console.c.
Function Documentation
static int attach_console_to_vfs (struct con_softc * cs) [static]
Definition at line 365 of file console.c.
References con_close(), con_io(), con_ioctl(), con_open(), device::d_blocks, device::d_blocksize, device::d_close, device::d_data, device::d_io, device::d_ioctl, device::d_open, ENOMEM, kfree(), kmalloc(), NULL, and vfs_adddev().
Referenced by config_con().
static int con_close (struct device * dev) [static]
Definition at line 295 of file console.c.
Referenced by attach_console_to_vfs().
void con_input (void * vcs, int ch)
Definition at line 182 of file console.c.
References CONSOLE_INPUT_BUFFER_SIZE, con_softc::cs_gotchars, con_softc::cs_gotchars_head, con_softc::cs_gotchars_tail, con_softc::cs_rsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().
static int con_io (struct device * dev, struct uio * uio) [static]
Definition at line 303 of file console.c.
References ch, getch(), KASSERT, lock_acquire(), lock_release(), NULL, putch(), UIO_READ, uio::uio_resid, uio::uio_rw, and uiomove().
Referenced by attach_console_to_vfs().
static int con_ioctl (struct device * dev, int op, userptr_t data) [static]
Definition at line 354 of file console.c.
References EINVAL.
Referenced by attach_console_to_vfs().
static int con_open (struct device * dev, int openflags) [static]
Definition at line 286 of file console.c.
Referenced by attach_console_to_vfs().
void con_start (void * vcs)
Definition at line 203 of file console.c.
References con_softc::cs_wsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().
int config_con (struct con_softc * cs, int unit)
Definition at line 399 of file console.c.
References attach_console_to_vfs(), con_softc::cs_gotchars_head, con_softc::cs_gotchars_tail, con_softc::cs_rsem, con_softc::cs_wsem, ENODEV, ENOMEM, flush_delay_buf(), KASSERT, lock_create(), lock_destroy(), NULL, sem_create(), and sem_destroy().
Referenced by tryattach_con_to_lser().
static void flush_delay_buf (void) [static]
Definition at line 103 of file console.c.
References delayed_outbuf, delayed_outbuf_pos, and putch().
Referenced by config_con().
int getch (void)
Definition at line 269 of file console.c.
References getch_intr(), KASSERT, and NULL.
Referenced by con_io(), and kgets().
static int getch_intr (struct con_softc * cs) [static]
Definition at line 161 of file console.c.
References CONSOLE_INPUT_BUFFER_SIZE, con_softc::cs_gotchars, con_softc::cs_gotchars_tail, con_softc::cs_rsem, and P().
Referenced by getch().
void putch (int ch)
Definition at line 221 of file console.c.
References NULL, putch_delayed(), putch_intr(), and putch_polled().
Referenced by backsp(), con_io(), console_send(), flush_delay_buf(), kgets(), loudthread(), and quietthread().
void putch_complete (void)
Definition at line 253 of file console.c.
References NULL, and putch_complete_polled().
Referenced by kprintf(), and panic().
static void putch_complete_polled (struct con_softc * cs) [static]
Definition at line 136 of file console.c.
References con_softc::cs_devdata, con_softc::cs_endpolling, and NULL.
Referenced by putch_complete().
static void putch_delayed (int ch) [static]
Definition at line 90 of file console.c.
References delayed_outbuf, delayed_outbuf_pos, and KASSERT.
Referenced by putch().
static void putch_intr (struct con_softc * cs, int ch) [static]
Definition at line 150 of file console.c.
References con_softc::cs_devdata, con_softc::cs_send, con_softc::cs_wsem, and P().
Referenced by putch().
static void putch_polled (struct con_softc * cs, int ch) [static]
Definition at line 120 of file console.c.
References con_softc::cs_devdata, and con_softc::cs_sendpolled.
Referenced by putch().
void putch_prepare (void)
Definition at line 237 of file console.c.
References NULL, and putch_prepare_polled().
Referenced by kprintf(), and panic().
static void putch_prepare_polled (struct con_softc * cs) [static]
Definition at line 127 of file console.c.
References con_softc::cs_devdata, con_softc::cs_startpolling, and NULL.
Referenced by putch_prepare().
Variable Documentation
struct lock* con_userlock_read = NULL [static]
Definition at line 74 of file console.c.
struct lock* con_userlock_write = NULL [static]
Definition at line 75 of file console.c.
char delayed_outbuf[DELAYBUFSIZE] [static]
Definition at line 85 of file console.c.
Referenced by flush_delay_buf(), and putch_delayed().
size_t delayed_outbuf_pos = 0 [static]
Definition at line 86 of file console.c.
Referenced by flush_delay_buf(), and putch_delayed().
struct con_softc* the_console = NULL [static]
Definition at line 68 of file console.c.