Os/161: kern/dev/lamebus/lamebus.c File Reference
kern/dev/lamebus/lamebus.c File Reference
#include <types.h>
#include <lib.h>
#include <cpu.h>
#include <spinlock.h>
#include <current.h>
#include <lamebus/lamebus.h>
Defines
#define CFGREG_VID 0
#define CFGREG_DID 4
#define CFGREG_DRL 8
#define CTLREG_RAMSZ 0x200
#define CTLREG_IRQS 0x204
#define CTLREG_PWR 0x208
#define CTLREG_IRQE 0x20c
#define CTLREG_CPUS 0x210
#define CTLREG_CPUE 0x214
#define CTLREG_SELF 0x218
#define CTLCPU_CIRQE 0x000
#define CTLCPU_CIPI 0x004
#define CTLCPU_CRAM 0x300
Functions
static uint32_t read_cfg_register (struct lamebus_softc *lb, int slot, uint32_t offset)
static void write_cfg_register (struct lamebus_softc *lb, int slot, uint32_t offset, uint32_t val)
static uint32_t read_ctl_register (struct lamebus_softc *lb, uint32_t offset)
static void write_ctl_register (struct lamebus_softc *lb, uint32_t offset, uint32_t val)
static void write_ctlcpu_register (struct lamebus_softc *lb, unsigned hw_cpunum, uint32_t offset, uint32_t val)
void lamebus_find_cpus (struct lamebus_softc *lamebus)
void lamebus_start_cpus (struct lamebus_softc *lamebus)
int lamebus_probe (struct lamebus_softc *sc, uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t highver)
void lamebus_mark (struct lamebus_softc *sc, int slot)
void lamebus_unmark (struct lamebus_softc *sc, int slot)
void lamebus_attach_interrupt (struct lamebus_softc *sc, int slot, void *devdata, void(*irqfunc)(void *devdata))
void lamebus_detach_interrupt (struct lamebus_softc *sc, int slot)
void lamebus_mask_interrupt (struct lamebus_softc *lamebus, int slot)
void lamebus_unmask_interrupt (struct lamebus_softc *lamebus, int slot)
void lamebus_interrupt (struct lamebus_softc *lamebus)
void lamebus_poweroff (struct lamebus_softc *lamebus)
uint32_t lamebus_ramsize (void)
void lamebus_assert_ipi (struct lamebus_softc *lamebus, struct cpu *target)
void lamebus_clear_ipi (struct lamebus_softc *lamebus, struct cpu *target)
struct lamebus_softc * lamebus_init (void)
Define Documentation
#define CFGREG_DID 4
Definition at line 43 of file lamebus.c.
Referenced by lamebus_probe().
#define CFGREG_DRL 8
Definition at line 44 of file lamebus.c.
Referenced by lamebus_probe().
#define CFGREG_VID 0
Definition at line 42 of file lamebus.c.
Referenced by lamebus_probe().
#define CTLCPU_CIPI 0x004
Definition at line 57 of file lamebus.c.
Referenced by lamebus_assert_ipi(), and lamebus_clear_ipi().
#define CTLCPU_CIRQE 0x000
Definition at line 56 of file lamebus.c.
Referenced by lamebus_find_cpus().
#define CTLCPU_CRAM 0x300
Definition at line 58 of file lamebus.c.
Referenced by lamebus_start_cpus().
#define CTLREG_CPUE 0x214
Definition at line 52 of file lamebus.c.
Referenced by lamebus_start_cpus().
#define CTLREG_CPUS 0x210
Definition at line 51 of file lamebus.c.
Referenced by lamebus_find_cpus(), and lamebus_start_cpus().
#define CTLREG_IRQE 0x20c
Definition at line 50 of file lamebus.c.
Referenced by lamebus_mask_interrupt(), and lamebus_unmask_interrupt().
#define CTLREG_IRQS 0x204
Definition at line 48 of file lamebus.c.
Referenced by lamebus_interrupt().
#define CTLREG_PWR 0x208
Definition at line 49 of file lamebus.c.
Referenced by lamebus_poweroff().
#define CTLREG_RAMSZ 0x200
Definition at line 47 of file lamebus.c.
Referenced by lamebus_ramsize().
#define CTLREG_SELF 0x218
Definition at line 53 of file lamebus.c.
Referenced by lamebus_find_cpus(), and lamebus_start_cpus().
Function Documentation
void lamebus_assert_ipi (struct lamebus_softc * lamebus, struct cpu * target)
Definition at line 589 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, and write_ctlcpu_register().
Referenced by mainbus_send_ipi().
void lamebus_attach_interrupt (struct lamebus_softc * sc, int slot, void * devdata, void(*)(void *devdata) irqfunc)
Definition at line 325 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), and attach_ltimer_to_lamebus().
void lamebus_clear_ipi (struct lamebus_softc * lamebus, struct cpu * target)
Definition at line 596 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, and write_ctlcpu_register().
Referenced by mainbus_interrupt().
void lamebus_detach_interrupt (struct lamebus_softc * sc, int slot)
Definition at line 353 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
void lamebus_find_cpus (struct lamebus_softc * lamebus)
Definition at line 127 of file lamebus.c.
References cpu_create(), CTLCPU_CIRQE, CTLREG_CPUS, CTLREG_SELF, curcpu, read_ctl_register(), and write_ctlcpu_register().
Referenced by mainbus_bootstrap().
struct lamebus_softc* lamebus_init (void) [read]
Definition at line 607 of file lamebus.c.
References kmalloc(), lamebus, LB_CONTROLLER_SLOT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), and spinlock_init().
Referenced by mainbus_bootstrap().
void lamebus_interrupt (struct lamebus_softc * lamebus)
Definition at line 407 of file lamebus.c.
References CTLREG_IRQS, curcpu, KASSERT, kprintf(), LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), read_ctl_register(), spinlock_acquire(), and spinlock_release().
Referenced by mainbus_interrupt().
void lamebus_mark (struct lamebus_softc * sc, int slot)
Definition at line 284 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
void lamebus_mask_interrupt (struct lamebus_softc * lamebus, int slot)
Definition at line 377 of file lamebus.c.
References CTLREG_IRQE, KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
Referenced by do_lamebus_mask_interrupt().
void lamebus_poweroff (struct lamebus_softc * lamebus)
Definition at line 556 of file lamebus.c.
References cpu_halt(), cpu_irqoff(), CTLREG_PWR, and write_ctl_register().
Referenced by mainbus_poweroff().
int lamebus_probe (struct lamebus_softc * sc, uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t highver)
Definition at line 228 of file lamebus.c.
References CFGREG_DID, CFGREG_DRL, CFGREG_VID, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, read_cfg_register(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lnet_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
uint32_t lamebus_ramsize (void)
Definition at line 573 of file lamebus.c.
References CTLREG_RAMSZ, NULL, and read_ctl_register().
Referenced by mainbus_ramsize().
void lamebus_start_cpus (struct lamebus_softc * lamebus)
Definition at line 184 of file lamebus.c.
References cpu_start_secondary(), CTLCPU_CRAM, CTLREG_CPUE, CTLREG_CPUS, CTLREG_SELF, lamebus_map_area(), LB_CONTROLLER_SLOT, LB_CTLCPU_OFFSET, LB_CTLCPU_SIZE, read_ctl_register(), and write_ctl_register().
Referenced by mainbus_start_cpus().
void lamebus_unmark (struct lamebus_softc * sc, int slot)
Definition at line 304 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
void lamebus_unmask_interrupt (struct lamebus_softc * lamebus, int slot)
Definition at line 390 of file lamebus.c.
References CTLREG_IRQE, KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
Referenced by do_lamebus_unmask_interrupt().
static uint32_t read_cfg_register (struct lamebus_softc * lb, int slot, uint32_t offset) [inline, static]
Definition at line 67 of file lamebus.c.
References lamebus_read_register(), LB_CONFIG_SIZE, and LB_CONTROLLER_SLOT.
Referenced by lamebus_probe(), and read_ctl_register().
static uint32_t read_ctl_register (struct lamebus_softc * lb, uint32_t offset) [inline, static]
Definition at line 93 of file lamebus.c.
References LB_CONTROLLER_SLOT, and read_cfg_register().
Referenced by lamebus_find_cpus(), lamebus_interrupt(), lamebus_mask_interrupt(), lamebus_ramsize(), lamebus_start_cpus(), and lamebus_unmask_interrupt().
static void write_cfg_register (struct lamebus_softc * lb, int slot, uint32_t offset, uint32_t val) [inline, static]
Definition at line 80 of file lamebus.c.
References lamebus_write_register(), LB_CONFIG_SIZE, and LB_CONTROLLER_SLOT.
Referenced by write_ctl_register().
static void write_ctl_register (struct lamebus_softc * lb, uint32_t offset, uint32_t val) [inline, static]
Definition at line 105 of file lamebus.c.
References LB_CONTROLLER_SLOT, and write_cfg_register().
Referenced by lamebus_mask_interrupt(), lamebus_poweroff(), lamebus_start_cpus(), and lamebus_unmask_interrupt().
static void write_ctlcpu_register (struct lamebus_softc * lb, unsigned hw_cpunum, uint32_t offset, uint32_t val) [inline, static]
Definition at line 116 of file lamebus.c.
References lamebus_write_register(), LB_CONTROLLER_SLOT, LB_CTLCPU_OFFSET, and LB_CTLCPU_SIZE.
Referenced by lamebus_assert_ipi(), lamebus_clear_ipi(), and lamebus_find_cpus().