Os/161: kern/include/spinlock.h File Reference
kern/include/spinlock.h File Reference
#include <cdefs.h>
#include <machine/spinlock.h>
Data Structures
struct spinlock
Defines
#define SPINLOCK_INLINE INLINE
#define SPINLOCK_INITIALIZER { SPINLOCK_DATA_INITIALIZER, NULL }
Functions
void spinlock_init (struct spinlock *lk)
void spinlock_cleanup (struct spinlock *lk)
void spinlock_acquire (struct spinlock *lk)
void spinlock_release (struct spinlock *lk)
bool spinlock_do_i_hold (struct spinlock *lk)
Define Documentation
#define SPINLOCK_INITIALIZER { SPINLOCK_DATA_INITIALIZER, NULL }
Definition at line 65 of file spinlock.h.
#define SPINLOCK_INLINE INLINE
Definition at line 42 of file spinlock.h.
Function Documentation
void spinlock_acquire (struct spinlock * lk)
Definition at line 73 of file spinlock.c.
References curcpu, CURCPU_EXISTS, IPL_HIGH, IPL_NONE, spinlock::lk_holder, spinlock::lk_lock, NULL, panic(), spinlock_data_get(), spinlock_data_testandset(), and splraise().
Referenced by getppages(), interprocessor_interrupt(), ipi_send(), ipi_tlbshootdown(), kheap_printstats(), kprintf(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_interrupt(), lamebus_mark(), lamebus_mask_interrupt(), lamebus_probe(), lamebus_unmark(), lamebus_unmask_interrupt(), lscreen_irq(), lscreen_write(), lser_irq(), lser_write(), lser_writepolled(), P(), subpage_kfree(), subpage_kmalloc(), thread_consider_migration(), thread_make_runnable(), thread_switch(), V(), wchan_isempty(), wchan_lock(), wchan_wakeall(), and wchan_wakeone().
void spinlock_cleanup (struct spinlock * lk)
Definition at line 59 of file spinlock.c.
References KASSERT, spinlock::lk_holder, spinlock::lk_lock, NULL, and spinlock_data_get().
Referenced by sem_destroy(), and wchan_destroy().
bool spinlock_do_i_hold (struct spinlock * lk)
Definition at line 133 of file spinlock.c.
References curcpu, CURCPU_EXISTS, and spinlock::lk_holder.
Referenced by dumpsubpage(), lser_poll_until_write(), and thread_make_runnable().
void spinlock_init (struct spinlock * lk)
Definition at line 49 of file spinlock.c.
References spinlock::lk_holder, spinlock::lk_lock, NULL, and spinlock_data_set().
Referenced by config_lscreen(), config_lser(), cpu_create(), kprintf_bootstrap(), lamebus_init(), sem_create(), and wchan_create().
void spinlock_release (struct spinlock * lk)
Definition at line 117 of file spinlock.c.
References curcpu, CURCPU_EXISTS, IPL_HIGH, IPL_NONE, KASSERT, spinlock::lk_holder, spinlock::lk_lock, NULL, spinlock_data_set(), and spllower().
Referenced by getppages(), interprocessor_interrupt(), ipi_send(), ipi_tlbshootdown(), kheap_printstats(), kprintf(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_interrupt(), lamebus_mark(), lamebus_mask_interrupt(), lamebus_probe(), lamebus_unmark(), lamebus_unmask_interrupt(), lscreen_irq(), lscreen_write(), lser_irq(), lser_write(), lser_writepolled(), P(), subpage_kfree(), subpage_kmalloc(), thread_consider_migration(), thread_make_runnable(), thread_startup(), thread_switch(), V(), wchan_isempty(), wchan_unlock(), wchan_wakeall(), and wchan_wakeone().