Os/161: kern/dev/lamebus/emu.c File Reference
kern/dev/lamebus/emu.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <stat.h>
#include <lib.h>
#include <array.h>
#include <uio.h>
#include <synch.h>
#include <lamebus/emu.h>
#include <platform/bus.h>
#include <vfs.h>
#include <emufs.h>
#include "autoconf.h"
Defines
#define REG_HANDLE 0
#define REG_OFFSET 4
#define REG_IOLEN 8
#define REG_OPER 12
#define REG_RESULT 16
#define EMU_BUFFER 32768
#define EMU_OP_OPEN 1
#define EMU_OP_CREATE 2
#define EMU_OP_EXCLCREATE 3
#define EMU_OP_CLOSE 4
#define EMU_OP_READ 5
#define EMU_OP_READDIR 6
#define EMU_OP_WRITE 7
#define EMU_OP_GETSIZE 8
#define EMU_OP_TRUNC 9
#define EMU_RES_SUCCESS 1
#define EMU_RES_BADHANDLE 2
#define EMU_RES_BADOP 3
#define EMU_RES_BADPATH 4
#define EMU_RES_BADSIZE 5
#define EMU_RES_EXISTS 6
#define EMU_RES_ISDIR 7
#define EMU_RES_MEDIA 8
#define EMU_RES_NOHANDLES 9
#define EMU_RES_NOSPACE 10
#define EMU_RES_NOTDIR 11
#define EMU_RES_UNKNOWN 12
#define EMU_RES_UNSUPP 13
Functions
static uint32_t emu_rreg (struct emu_softc *sc, uint32_t reg)
static void emu_wreg (struct emu_softc *sc, uint32_t reg, uint32_t val)
void emu_irq (void *dev)
static uint32_t translate_err (struct emu_softc *sc, uint32_t code)
static int emu_waitdone (struct emu_softc *sc)
static int emu_open (struct emu_softc *sc, uint32_t handle, const char *name, bool create, bool excl, mode_t mode, uint32_t *newhandle, int *newisdir)
static int emu_close (struct emu_softc *sc, uint32_t handle)
static int emu_doread (struct emu_softc *sc, uint32_t handle, uint32_t len, uint32_t op, struct uio *uio)
static int emu_read (struct emu_softc *sc, uint32_t handle, uint32_t len, struct uio *uio)
static int emu_readdir (struct emu_softc *sc, uint32_t handle, uint32_t len, struct uio *uio)
static int emu_write (struct emu_softc *sc, uint32_t handle, uint32_t len, struct uio *uio)
static int emu_getsize (struct emu_softc *sc, uint32_t handle, off_t *retval)
static int emu_trunc (struct emu_softc *sc, uint32_t handle, off_t len)
static int emufs_loadvnode (struct emufs_fs *ef, uint32_t handle, int isdir, struct emufs_vnode **ret)
static int emufs_open (struct vnode *v, int openflags)
static int emufs_opendir (struct vnode *v, int openflags)
static int emufs_close (struct vnode *v)
static int emufs_reclaim (struct vnode *v)
static int emufs_read (struct vnode *v, struct uio *uio)
static int emufs_getdirentry (struct vnode *v, struct uio *uio)
static int emufs_write (struct vnode *v, struct uio *uio)
static int emufs_ioctl (struct vnode *v, int op, userptr_t data)
static int emufs_stat (struct vnode *v, struct stat *statbuf)
static int emufs_file_gettype (struct vnode *v, uint32_t *result)
static int emufs_dir_gettype (struct vnode *v, uint32_t *result)
static int emufs_tryseek (struct vnode *v, off_t pos)
static int emufs_fsync (struct vnode *v)
static int emufs_truncate (struct vnode *v, off_t len)
static int emufs_creat (struct vnode *dir, const char *name, bool excl, mode_t mode, struct vnode **ret)
static int emufs_lookup (struct vnode *dir, char *pathname, struct vnode **ret)
static int emufs_lookparent (struct vnode *dir, char *pathname, struct vnode **ret, char *buf, size_t len)
static int emufs_namefile (struct vnode *v, struct uio *uio)
static int emufs_mmap (struct vnode *v)
static int emufs_dir_tryseek (struct vnode *v, off_t pos)
static int emufs_symlink (struct vnode *v, const char *contents, const char *name)
static int emufs_mkdir (struct vnode *v, const char *name, mode_t mode)
static int emufs_link (struct vnode *v, const char *name, struct vnode *target)
static int emufs_remove (struct vnode *v, const char *name)
static int emufs_rmdir (struct vnode *v, const char *name)
static int emufs_rename (struct vnode *v1, const char *n1, struct vnode *v2, const char *n2)
static int emufs_void_op_isdir (struct vnode *v)
static int emufs_uio_op_isdir (struct vnode *v, struct uio *uio)
static int emufs_uio_op_notdir (struct vnode *v, struct uio *uio)
static int emufs_name_op_notdir (struct vnode *v, const char *name)
static int emufs_readlink_notlink (struct vnode *v, struct uio *uio)
static int emufs_creat_notdir (struct vnode *v, const char *name, bool excl, mode_t mode, struct vnode **retval)
static int emufs_symlink_notdir (struct vnode *v, const char *contents, const char *name)
static int emufs_mkdir_notdir (struct vnode *v, const char *name, mode_t mode)
static int emufs_link_notdir (struct vnode *v, const char *name, struct vnode *target)
static int emufs_rename_notdir (struct vnode *v1, const char *n1, struct vnode *v2, const char *n2)
static int emufs_lookup_notdir (struct vnode *v, char *pathname, struct vnode **result)
static int emufs_lookparent_notdir (struct vnode *v, char *pathname, struct vnode **result, char *buf, size_t len)
static int emufs_truncate_isdir (struct vnode *v, off_t len)
static int emufs_sync (struct fs *fs)
static const char * emufs_getvolname (struct fs *fs)
static struct vnode * emufs_getroot (struct fs *fs)
static int emufs_unmount (struct fs *fs)
static int emufs_addtovfs (struct emu_softc *sc, const char *devname)
int config_emu (struct emu_softc *sc, int emuno)
Variables
static struct vnode_ops emufs_fileops
static struct vnode_ops emufs_dirops
Define Documentation
#define EMU_BUFFER 32768
Definition at line 65 of file emu.c.
Referenced by config_emu().
#define EMU_OP_CLOSE 4
Definition at line 71 of file emu.c.
Referenced by emu_close().
#define EMU_OP_CREATE 2
Definition at line 69 of file emu.c.
Referenced by emu_open().
#define EMU_OP_EXCLCREATE 3
Definition at line 70 of file emu.c.
Referenced by emu_open().
#define EMU_OP_GETSIZE 8
Definition at line 75 of file emu.c.
Referenced by emu_getsize().
#define EMU_OP_OPEN 1
Definition at line 68 of file emu.c.
Referenced by emu_open().
#define EMU_OP_READ 5
Definition at line 72 of file emu.c.
Referenced by emu_read().
#define EMU_OP_READDIR 6
Definition at line 73 of file emu.c.
Referenced by emu_readdir().
#define EMU_OP_TRUNC 9
Definition at line 76 of file emu.c.
Referenced by emu_trunc().
#define EMU_OP_WRITE 7
Definition at line 74 of file emu.c.
Referenced by emu_write().
#define EMU_RES_BADHANDLE 2
Definition at line 80 of file emu.c.
Referenced by translate_err().
#define EMU_RES_BADOP 3
Definition at line 81 of file emu.c.
Referenced by translate_err().
#define EMU_RES_BADPATH 4
Definition at line 82 of file emu.c.
Referenced by translate_err().
#define EMU_RES_BADSIZE 5
Definition at line 83 of file emu.c.
Referenced by translate_err().
#define EMU_RES_EXISTS 6
Definition at line 84 of file emu.c.
Referenced by translate_err().
#define EMU_RES_ISDIR 7
Definition at line 85 of file emu.c.
Referenced by translate_err().
#define EMU_RES_MEDIA 8
Definition at line 86 of file emu.c.
Referenced by translate_err().
#define EMU_RES_NOHANDLES 9
Definition at line 87 of file emu.c.
Referenced by translate_err().
#define EMU_RES_NOSPACE 10
Definition at line 88 of file emu.c.
Referenced by translate_err().
#define EMU_RES_NOTDIR 11
Definition at line 89 of file emu.c.
Referenced by translate_err().
#define EMU_RES_SUCCESS 1
Definition at line 79 of file emu.c.
Referenced by translate_err().
#define EMU_RES_UNKNOWN 12
Definition at line 90 of file emu.c.
Referenced by translate_err().
#define EMU_RES_UNSUPP 13
Definition at line 91 of file emu.c.
Referenced by translate_err().
#define REG_HANDLE 0
Definition at line 58 of file emu.c.
Referenced by emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), and emu_write().
#define REG_IOLEN 8
Definition at line 60 of file emu.c.
Referenced by emu_doread(), emu_getsize(), emu_open(), emu_trunc(), and emu_write().
#define REG_OFFSET 4
Definition at line 59 of file emu.c.
Referenced by emu_doread(), and emu_write().
#define REG_OPER 12
Definition at line 61 of file emu.c.
Referenced by emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), and emu_write().
#define REG_RESULT 16
Definition at line 62 of file emu.c.
Referenced by emu_irq().
Function Documentation
int config_emu (struct emu_softc * sc, int emuno)
Definition at line 1333 of file emu.c.
References bus_map_area, emu_softc::e_busdata, emu_softc::e_buspos, emu_softc::e_iobuf, emu_softc::e_lock, emu_softc::e_sem, EMU_BUFFER, emufs_addtovfs(), ENOMEM, lock_create(), lock_destroy(), name, NULL, sem_create(), and snprintf().
Referenced by tryattach_emu_to_lamebus().
static int emu_close (struct emu_softc * sc, uint32_t handle) [static]
Definition at line 229 of file emu.c.
References emu_softc::e_lock, emu_softc::e_unit, EIO, EMU_OP_CLOSE, emu_waitdone(), emu_wreg(), kprintf(), lock_acquire(), lock_do_i_hold(), lock_release(), REG_HANDLE, and REG_OPER.
Referenced by emufs_creat(), emufs_lookup(), and emufs_reclaim().
static int emu_doread (struct emu_softc * sc, uint32_t handle, uint32_t len, uint32_t op, struct uio * uio) [static]
Definition at line 267 of file emu.c.
References emu_softc::e_iobuf, emu_softc::e_lock, emu_rreg(), emu_waitdone(), emu_wreg(), KASSERT, lock_acquire(), lock_release(), REG_HANDLE, REG_IOLEN, REG_OFFSET, REG_OPER, uio::uio_offset, UIO_READ, uio::uio_rw, and uiomove().
Referenced by emu_read(), and emu_readdir().
static int emu_getsize (struct emu_softc * sc, uint32_t handle, off_t * retval) [static]
Definition at line 352 of file emu.c.
References emu_softc::e_lock, EMU_OP_GETSIZE, emu_rreg(), emu_waitdone(), emu_wreg(), lock_acquire(), lock_release(), REG_HANDLE, REG_IOLEN, and REG_OPER.
Referenced by emufs_stat().
void emu_irq (void * dev)
Definition at line 124 of file emu.c.
References emu_softc::e_result, emu_softc::e_sem, emu_rreg(), emu_wreg(), REG_RESULT, and V().
Referenced by attach_emu_to_lamebus().
static int emu_open (struct emu_softc * sc, uint32_t handle, const char * name, bool create, bool excl, mode_t mode, uint32_t * newhandle, int * newisdir) [static]
Definition at line 181 of file emu.c.
References emu_softc::e_iobuf, emu_softc::e_lock, EMU_MAXIO, EMU_OP_CREATE, EMU_OP_EXCLCREATE, EMU_OP_OPEN, emu_rreg(), emu_waitdone(), emu_wreg(), ENAMETOOLONG, lock_acquire(), lock_release(), REG_HANDLE, REG_IOLEN, REG_OPER, strcpy(), and strlen().
Referenced by emufs_creat(), and emufs_lookup().
static int emu_read (struct emu_softc * sc, uint32_t handle, uint32_t len, struct uio * uio) [static]
Definition at line 299 of file emu.c.
References emu_doread(), and EMU_OP_READ.
Referenced by emufs_read().
static int emu_readdir (struct emu_softc * sc, uint32_t handle, uint32_t len, struct uio * uio) [static]
Definition at line 310 of file emu.c.
References emu_doread(), and EMU_OP_READDIR.
Referenced by emufs_getdirentry().
static uint32_t emu_rreg (struct emu_softc * sc, uint32_t reg) [inline, static]
Definition at line 104 of file emu.c.
References bus_read_register, emu_softc::e_busdata, and emu_softc::e_buspos.
Referenced by emu_doread(), emu_getsize(), emu_irq(), and emu_open().
static int emu_trunc (struct emu_softc * sc, uint32_t handle, off_t len) [static]
Definition at line 374 of file emu.c.
References emu_softc::e_lock, EMU_OP_TRUNC, emu_waitdone(), emu_wreg(), lock_acquire(), lock_release(), REG_HANDLE, REG_IOLEN, and REG_OPER.
Referenced by emufs_truncate().
static int emu_waitdone (struct emu_softc * sc) [static]
Definition at line 167 of file emu.c.
References emu_softc::e_result, emu_softc::e_sem, P(), and translate_err().
Referenced by emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), and emu_write().
static void emu_wreg (struct emu_softc * sc, uint32_t reg, uint32_t val) [inline, static]
Definition at line 115 of file emu.c.
References bus_write_register, emu_softc::e_busdata, and emu_softc::e_buspos.
Referenced by emu_close(), emu_doread(), emu_getsize(), emu_irq(), emu_open(), emu_trunc(), and emu_write().
static int emu_write (struct emu_softc * sc, uint32_t handle, uint32_t len, struct uio * uio) [static]
Definition at line 321 of file emu.c.
References emu_softc::e_iobuf, emu_softc::e_lock, EMU_OP_WRITE, emu_waitdone(), emu_wreg(), KASSERT, lock_acquire(), lock_release(), REG_HANDLE, REG_IOLEN, REG_OFFSET, REG_OPER, uio::uio_offset, uio::uio_rw, UIO_WRITE, and uiomove().
Referenced by emufs_write().
static int emufs_addtovfs (struct emu_softc * sc, const char * devname) [static]
Definition at line 1284 of file emu.c.
References emufs_fs::ef_emu, emufs_fs::ef_fs, emufs_fs::ef_root, emufs_fs::ef_vnodes, EMU_ROOTHANDLE, emufs_getroot(), emufs_getvolname(), emufs_loadvnode(), emufs_sync(), emufs_unmount(), ENOMEM, emufs_vnode::ev_v, fs::fs_data, fs::fs_getroot, fs::fs_getvolname, fs::fs_sync, fs::fs_unmount, KASSERT, kfree(), kmalloc(), NULL, vfs_addfs(), and VOP_DECREF.
Referenced by config_emu().
static int emufs_close (struct vnode * v) [static]
Definition at line 454 of file emu.c.
static int emufs_creat (struct vnode * dir, const char * name, bool excl, mode_t mode, struct vnode ** ret) [static]
Definition at line 728 of file emu.c.
References emu_close(), emu_open(), emufs_loadvnode(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, fs::fs_data, isdir(), vnode::vn_data, and vnode::vn_fs.
static int emufs_creat_notdir (struct vnode * v, const char * name, bool excl, mode_t mode, struct vnode ** retval) [static]
Definition at line 985 of file emu.c.
References ENOTDIR.
static int emufs_dir_gettype (struct vnode * v, uint32_t * result) [static]
Definition at line 677 of file emu.c.
References S_IFDIR.
static int emufs_dir_tryseek (struct vnode * v, off_t pos) [static]
Definition at line 857 of file emu.c.
References EUNIMP.
static int emufs_file_gettype (struct vnode * v, uint32_t * result) [static]
Definition at line 665 of file emu.c.
References S_IFREG.
static int emufs_fsync (struct vnode * v) [static]
Definition at line 706 of file emu.c.
static int emufs_getdirentry (struct vnode * v, struct uio * uio) [static]
Definition at line 563 of file emu.c.
References EMU_MAXIO, emu_readdir(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, KASSERT, UIO_READ, uio::uio_resid, uio::uio_rw, and vnode::vn_data.
static struct vnode* emufs_getroot (struct fs * fs) [static, read]
Definition at line 1248 of file emu.c.
References emufs_fs::ef_root, emufs_vnode::ev_v, fs::fs_data, KASSERT, NULL, and VOP_INCREF.
Referenced by emufs_addtovfs().
static const char* emufs_getvolname (struct fs * fs) [static]
Definition at line 1236 of file emu.c.
References NULL.
Referenced by emufs_addtovfs().
static int emufs_ioctl (struct vnode * v, int op, userptr_t data) [static]
Definition at line 619 of file emu.c.
References EINVAL.
static int emufs_link (struct vnode * v, const char * name, struct vnode * target) [static]
Definition at line 886 of file emu.c.
References EUNIMP.
static int emufs_link_notdir (struct vnode * v, const char * name, struct vnode * target) [static]
Definition at line 1018 of file emu.c.
References ENOTDIR.
static int emufs_loadvnode (struct emufs_fs * ef, uint32_t handle, int isdir, struct emufs_vnode ** ret) [static]
Definition at line 1148 of file emu.c.
References emu_softc::e_lock, emufs_fs::ef_emu, emufs_fs::ef_fs, emufs_fs::ef_vnodes, ENOMEM, emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, kfree(), kmalloc(), lock_acquire(), lock_release(), NULL, num, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, VOP_CLEANUP, VOP_INCREF, and VOP_INIT.
Referenced by emufs_addtovfs(), emufs_creat(), and emufs_lookup().
static int emufs_lookparent (struct vnode * dir, char * pathname, struct vnode ** ret, char * buf, size_t len) [static]
Definition at line 789 of file emu.c.
References emufs_lookup(), ENAMETOOLONG, NULL, strcpy(), strlen(), strrchr(), and VOP_INCREF.
static int emufs_lookparent_notdir (struct vnode * v, char * pathname, struct vnode ** result, char * buf, size_t len) [static]
Definition at line 1050 of file emu.c.
References ENOTDIR.
static int emufs_lookup (struct vnode * dir, char * pathname, struct vnode ** ret) [static]
Definition at line 759 of file emu.c.
References emu_close(), emu_open(), emufs_loadvnode(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, fs::fs_data, isdir(), vnode::vn_data, and vnode::vn_fs.
Referenced by emufs_lookparent().
static int emufs_lookup_notdir (struct vnode * v, char * pathname, struct vnode ** result) [static]
Definition at line 1040 of file emu.c.
References ENOTDIR.
static int emufs_mkdir (struct vnode * v, const char * name, mode_t mode) [static]
Definition at line 876 of file emu.c.
References EUNIMP.
static int emufs_mkdir_notdir (struct vnode * v, const char * name, mode_t mode) [static]
Definition at line 1008 of file emu.c.
References ENOTDIR.
static int emufs_mmap (struct vnode * v) [static]
Definition at line 843 of file emu.c.
References EUNIMP.
static int emufs_name_op_notdir (struct vnode * v, const char * name) [static]
Definition at line 967 of file emu.c.
References ENOTDIR.
static int emufs_namefile (struct vnode * v, struct uio * uio) [static]
Definition at line 821 of file emu.c.
References emufs_fs::ef_root, EUNIMP, fs::fs_data, vnode::vn_data, and vnode::vn_fs.
static int emufs_open (struct vnode * v, int openflags) [static]
Definition at line 407 of file emu.c.
References EUNIMP, and O_APPEND.
static int emufs_opendir (struct vnode * v, int openflags) [static]
Definition at line 431 of file emu.c.
References EISDIR, O_ACCMODE, O_APPEND, O_RDONLY, O_RDWR, and O_WRONLY.
static int emufs_read (struct vnode * v, struct uio * uio) [static]
Definition at line 527 of file emu.c.
References EMU_MAXIO, emu_read(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, KASSERT, UIO_READ, uio::uio_resid, uio::uio_rw, and vnode::vn_data.
static int emufs_readlink_notlink (struct vnode * v, struct uio * uio) [static]
Definition at line 976 of file emu.c.
References EINVAL.
static int emufs_reclaim (struct vnode * v) [static]
Definition at line 467 of file emu.c.
References emu_softc::e_lock, emu_softc::e_unit, EBUSY, emufs_fs::ef_emu, emufs_fs::ef_vnodes, emu_close(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, fs::fs_data, kfree(), lock_acquire(), lock_release(), num, panic(), vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, vnode::vn_fs, vnode::vn_refcount, and VOP_CLEANUP.
static int emufs_remove (struct vnode * v, const char * name) [static]
Definition at line 896 of file emu.c.
References EUNIMP.
static int emufs_rename (struct vnode * v1, const char * n1, struct vnode * v2, const char * n2) [static]
Definition at line 914 of file emu.c.
References EUNIMP.
static int emufs_rename_notdir (struct vnode * v1, const char * n1, struct vnode * v2, const char * n2) [static]
Definition at line 1028 of file emu.c.
References ENOTDIR.
static int emufs_rmdir (struct vnode * v, const char * name) [static]
Definition at line 905 of file emu.c.
References EUNIMP.
static int emufs_stat (struct vnode * v, struct stat * statbuf) [static]
Definition at line 637 of file emu.c.
References bzero(), emu_getsize(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, stat::st_blocks, stat::st_mode, stat::st_nlink, stat::st_size, vnode::vn_data, and VOP_GETTYPE.
static int emufs_symlink (struct vnode * v, const char * contents, const char * name) [static]
Definition at line 866 of file emu.c.
References EUNIMP.
static int emufs_symlink_notdir (struct vnode * v, const char * contents, const char * name) [static]
Definition at line 998 of file emu.c.
References ENOTDIR.
static int emufs_sync (struct fs * fs) [static]
Definition at line 1225 of file emu.c.
Referenced by emufs_addtovfs().
static int emufs_truncate (struct vnode * v, off_t len) [static]
Definition at line 717 of file emu.c.
References emu_trunc(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, and vnode::vn_data.
static int emufs_truncate_isdir (struct vnode * v, off_t len) [static]
Definition at line 1064 of file emu.c.
References ENOTDIR.
static int emufs_tryseek (struct vnode * v, off_t pos) [static]
Definition at line 689 of file emu.c.
References EINVAL.
static int emufs_uio_op_isdir (struct vnode * v, struct uio * uio) [static]
Definition at line 949 of file emu.c.
References EISDIR.
static int emufs_uio_op_notdir (struct vnode * v, struct uio * uio) [static]
Definition at line 958 of file emu.c.
References ENOTDIR.
static int emufs_unmount (struct fs * fs) [static]
Definition at line 1268 of file emu.c.
References EBUSY.
Referenced by emufs_addtovfs().
static int emufs_void_op_isdir (struct vnode * v) [static]
Definition at line 941 of file emu.c.
References EISDIR.
static int emufs_write (struct vnode * v, struct uio * uio) [static]
Definition at line 583 of file emu.c.
References EMU_MAXIO, emu_write(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, KASSERT, uio::uio_resid, uio::uio_rw, UIO_WRITE, and vnode::vn_data.
static uint32_t translate_err (struct emu_softc * sc, uint32_t code) [static]
Definition at line 140 of file emu.c.
References emu_softc::e_unit, EAGAIN, EEXIST, EIO, EISDIR, EMU_RES_BADHANDLE, EMU_RES_BADOP, EMU_RES_BADPATH, EMU_RES_BADSIZE, EMU_RES_EXISTS, EMU_RES_ISDIR, EMU_RES_MEDIA, EMU_RES_NOHANDLES, EMU_RES_NOSPACE, EMU_RES_NOTDIR, EMU_RES_SUCCESS, EMU_RES_UNKNOWN, EMU_RES_UNSUPP, ENFILE, ENOENT, ENOSPC, ENOTDIR, EUNIMP, kprintf(), and panic().
Referenced by emu_waitdone().
Variable Documentation
struct vnode_ops emufs_dirops [static]
Definition at line 1111 of file emu.c.
struct vnode_ops emufs_fileops [static]
Definition at line 1076 of file emu.c.