Os/161: kern/fs/sfs/sfs_vnode.c File Reference
kern/fs/sfs/sfs_vnode.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <stat.h>
#include <lib.h>
#include <array.h>
#include <bitmap.h>
#include <uio.h>
#include <synch.h>
#include <vfs.h>
#include <device.h>
#include <sfs.h>
Defines
#define ISDIR ((void *)sfs_isdir)
#define NOTDIR ((void *)sfs_notdir)
#define UNIMP ((void *)sfs_unimp)
Functions
static int sfs_loadvnode (struct sfs_fs *sfs, uint32_t ino, int type, struct sfs_vnode **ret)
static int sfs_clearblock (struct sfs_fs *sfs, uint32_t block)
static int sfs_sync_inode (struct sfs_vnode *sv)
static int sfs_balloc (struct sfs_fs *sfs, uint32_t *diskblock)
static void sfs_bfree (struct sfs_fs *sfs, uint32_t diskblock)
static int sfs_bused (struct sfs_fs *sfs, uint32_t diskblock)
static int sfs_bmap (struct sfs_vnode *sv, uint32_t fileblock, int doalloc, uint32_t *diskblock)
static int sfs_partialio (struct sfs_vnode *sv, struct uio *uio, uint32_t skipstart, uint32_t len)
static int sfs_blockio (struct sfs_vnode *sv, struct uio *uio)
static int sfs_io (struct sfs_vnode *sv, struct uio *uio)
static int sfs_readdir (struct sfs_vnode *sv, struct sfs_dir *sd, int slot)
static int sfs_writedir (struct sfs_vnode *sv, struct sfs_dir *sd, int slot)
static int sfs_dir_nentries (struct sfs_vnode *sv)
static int sfs_dir_findname (struct sfs_vnode *sv, const char *name, uint32_t *ino, int *slot, int *emptyslot)
static int sfs_dir_link (struct sfs_vnode *sv, const char *name, uint32_t ino, int *slot)
static int sfs_dir_unlink (struct sfs_vnode *sv, int slot)
static int sfs_lookonce (struct sfs_vnode *sv, const char *name, struct sfs_vnode **ret, int *slot)
static int sfs_makeobj (struct sfs_fs *sfs, int type, struct sfs_vnode **ret)
static int sfs_open (struct vnode *v, int openflags)
static int sfs_opendir (struct vnode *v, int openflags)
static int sfs_close (struct vnode *v)
static int sfs_reclaim (struct vnode *v)
static int sfs_read (struct vnode *v, struct uio *uio)
static int sfs_write (struct vnode *v, struct uio *uio)
static int sfs_ioctl (struct vnode *v, int op, userptr_t data)
static int sfs_stat (struct vnode *v, struct stat *statbuf)
static int sfs_gettype (struct vnode *v, uint32_t *ret)
static int sfs_tryseek (struct vnode *v, off_t pos)
static int sfs_fsync (struct vnode *v)
static int sfs_mmap (struct vnode *v)
static int sfs_truncate (struct vnode *v, off_t len)
static int sfs_namefile (struct vnode *vv, struct uio *uio)
static int sfs_creat (struct vnode *v, const char *name, bool excl, mode_t mode, struct vnode **ret)
static int sfs_link (struct vnode *dir, const char *name, struct vnode *file)
static int sfs_remove (struct vnode *dir, const char *name)
static int sfs_rename (struct vnode *d1, const char *n1, struct vnode *d2, const char *n2)
static int sfs_lookparent (struct vnode *v, char *path, struct vnode **ret, char *buf, size_t buflen)
static int sfs_lookup (struct vnode *v, char *path, struct vnode **ret)
static int sfs_notdir (void)
static int sfs_isdir (void)
static int sfs_unimp (void)
struct vnode * sfs_getroot (struct fs *fs)
Variables
static struct vnode_ops sfs_fileops
static struct vnode_ops sfs_dirops
Define Documentation
#define ISDIR ((void *)sfs_isdir)
Definition at line 1571 of file sfs_vnode.c.
#define NOTDIR ((void *)sfs_notdir)
Definition at line 1572 of file sfs_vnode.c.
#define UNIMP ((void *)sfs_unimp)
Definition at line 1573 of file sfs_vnode.c.
Function Documentation
static int sfs_balloc (struct sfs_fs * sfs, uint32_t * diskblock) [static]
Definition at line 91 of file sfs_vnode.c.
References bitmap_alloc(), panic(), sfs_clearblock(), sfs_fs::sfs_freemap, sfs_fs::sfs_freemapdirty, sfs_fs::sfs_super, and sfs_super::sp_nblocks.
Referenced by sfs_bmap(), and sfs_makeobj().
static void sfs_bfree (struct sfs_fs * sfs, uint32_t diskblock) [static]
Definition at line 114 of file sfs_vnode.c.
References bitmap_unmark(), sfs_fs::sfs_freemap, and sfs_fs::sfs_freemapdirty.
Referenced by sfs_reclaim(), and sfs_truncate().
static int sfs_blockio (struct sfs_vnode * sv, struct uio * uio) [static]
Definition at line 383 of file sfs_vnode.c.
References fs::fs_data, KASSERT, SFS_BLOCKSIZE, sfs_bmap(), sfs_rwblock(), sfs_vnode::sv_v, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, UIO_WRITE, uiomovezeros(), and vnode::vn_fs.
Referenced by sfs_io().
static int sfs_bmap (struct sfs_vnode * sv, uint32_t fileblock, int doalloc, uint32_t * diskblock) [static]
Definition at line 146 of file sfs_vnode.c.
References bzero(), EFBIG, fs::fs_data, KASSERT, panic(), sfs_inode::sfi_direct, sfs_inode::sfi_indirect, sfs_balloc(), SFS_BLOCKSIZE, sfs_bused(), SFS_DBPERIDB, SFS_NDIRECT, sfs_rblock(), sfs_wblock(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, sfs_vnode::sv_v, and vnode::vn_fs.
Referenced by sfs_blockio(), and sfs_partialio().
static int sfs_bused (struct sfs_fs * sfs, uint32_t diskblock) [static]
Definition at line 125 of file sfs_vnode.c.
References bitmap_isset(), panic(), sfs_fs::sfs_freemap, sfs_fs::sfs_super, and sfs_super::sp_nblocks.
Referenced by sfs_bmap(), and sfs_loadvnode().
static int sfs_clearblock (struct sfs_fs * sfs, uint32_t block) [static]
Definition at line 59 of file sfs_vnode.c.
References SFS_BLOCKSIZE, and sfs_wblock().
Referenced by sfs_balloc().
static int sfs_close (struct vnode * v) [static]
Definition at line 876 of file sfs_vnode.c.
References VOP_FSYNC.
static int sfs_creat (struct vnode * v, const char * name, bool excl, mode_t mode, struct vnode ** ret) [static]
Definition at line 1253 of file sfs_vnode.c.
References EEXIST, ENOENT, fs::fs_data, NULL, sfs_inode::sfi_linkcount, sfs_dir_findname(), sfs_dir_link(), sfs_loadvnode(), sfs_makeobj(), SFS_TYPE_FILE, SFS_TYPE_INVAL, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, sfs_vnode::sv_v, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, vnode::vn_fs, and VOP_DECREF.
static int sfs_dir_findname (struct sfs_vnode * sv, const char * name, uint32_t * ino, int * slot, int * emptyslot) [static]
Definition at line 647 of file sfs_vnode.c.
References ENOENT, KASSERT, NULL, sfs_dir::sfd_ino, sfs_dir::sfd_name, sfs_dir_nentries(), SFS_NOINO, sfs_readdir(), and strcmp().
Referenced by sfs_creat(), sfs_dir_link(), and sfs_lookonce().
static int sfs_dir_link (struct sfs_vnode * sv, const char * name, uint32_t ino, int * slot) [static]
Definition at line 697 of file sfs_vnode.c.
References bzero(), EEXIST, ENAMETOOLONG, ENOENT, NULL, sfs_dir::sfd_ino, sfs_dir::sfd_name, sfs_dir_findname(), sfs_dir_nentries(), sfs_writedir(), strcpy(), and strlen().
Referenced by sfs_creat(), sfs_link(), and sfs_rename().
static int sfs_dir_nentries (struct sfs_vnode * sv) [static]
Definition at line 624 of file sfs_vnode.c.
References KASSERT, panic(), sfs_inode::sfi_size, sfs_inode::sfi_type, SFS_TYPE_DIR, sfs_vnode::sv_i, and sfs_vnode::sv_ino.
Referenced by sfs_dir_findname(), and sfs_dir_link().
static int sfs_dir_unlink (struct sfs_vnode * sv, int slot) [static]
Definition at line 741 of file sfs_vnode.c.
References bzero(), sfs_dir::sfd_ino, SFS_NOINO, and sfs_writedir().
Referenced by sfs_remove(), and sfs_rename().
static int sfs_fsync (struct vnode * v) [static]
Definition at line 1100 of file sfs_vnode.c.
References sfs_sync_inode(), vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
struct vnode* sfs_getroot (struct fs * fs) [read]
Definition at line 1764 of file sfs_vnode.c.
References fs::fs_data, panic(), sfs_loadvnode(), SFS_ROOT_LOCATION, SFS_TYPE_INVAL, sfs_vnode::sv_v, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by sfs_domount().
static int sfs_gettype (struct vnode * v, uint32_t * ret) [static]
Definition at line 1052 of file sfs_vnode.c.
References EINVAL, panic(), S_IFDIR, S_IFREG, sfs_inode::sfi_type, SFS_TYPE_DIR, SFS_TYPE_FILE, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
static int sfs_io (struct sfs_vnode * sv, struct uio * uio) [static]
Definition at line 448 of file sfs_vnode.c.
References KASSERT, nblocks, sfs_inode::sfi_size, sfs_blockio(), SFS_BLOCKSIZE, sfs_partialio(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, and UIO_WRITE.
Referenced by sfs_read(), sfs_readdir(), sfs_write(), and sfs_writedir().
static int sfs_ioctl (struct vnode * v, int op, userptr_t data) [static]
Definition at line 1005 of file sfs_vnode.c.
References EINVAL.
static int sfs_isdir (void) [static]
Definition at line 1553 of file sfs_vnode.c.
References EISDIR.
static int sfs_link (struct vnode * dir, const char * name, struct vnode * file) [static]
Definition at line 1326 of file sfs_vnode.c.
References f, KASSERT, NULL, sfs_inode::sfi_linkcount, sfs_dir_link(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, and vnode::vn_fs.
static int sfs_loadvnode (struct sfs_fs * sfs, uint32_t ino, int type, struct sfs_vnode ** ret) [static]
Definition at line 1651 of file sfs_vnode.c.
References ENOMEM, KASSERT, kfree(), kmalloc(), NULL, num, ops, panic(), sfs_inode::sfi_type, sfs_fs::sfs_absfs, sfs_bused(), sfs_rblock(), SFS_TYPE_DIR, SFS_TYPE_FILE, SFS_TYPE_INVAL, sfs_fs::sfs_vnodes, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, sfs_vnode::sv_v, vnode::vn_data, VOP_CLEANUP, VOP_INCREF, and VOP_INIT.
Referenced by sfs_creat(), sfs_getroot(), sfs_lookonce(), and sfs_makeobj().
static int sfs_lookonce (struct sfs_vnode * sv, const char * name, struct sfs_vnode ** ret, int * slot) [static]
Definition at line 759 of file sfs_vnode.c.
References fs::fs_data, NULL, panic(), sfs_dir_findname(), sfs_loadvnode(), SFS_TYPE_INVAL, sfs_vnode::sv_ino, sfs_vnode::sv_v, and vnode::vn_fs.
Referenced by sfs_lookup(), sfs_remove(), and sfs_rename().
static int sfs_lookparent (struct vnode * v, char * path, struct vnode ** ret, char * buf, size_t buflen) [static]
Definition at line 1484 of file sfs_vnode.c.
References ENAMETOOLONG, ENOTDIR, sfs_inode::sfi_type, SFS_TYPE_DIR, strcpy(), strlen(), sfs_vnode::sv_i, sfs_vnode::sv_v, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, and VOP_INCREF.
static int sfs_lookup (struct vnode * v, char * path, struct vnode ** ret) [static]
Definition at line 1517 of file sfs_vnode.c.
References ENOTDIR, NULL, sfs_inode::sfi_type, sfs_lookonce(), SFS_TYPE_DIR, sfs_vnode::sv_i, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
static int sfs_makeobj (struct sfs_fs * sfs, int type, struct sfs_vnode ** ret) [static]
Definition at line 794 of file sfs_vnode.c.
References sfs_balloc(), and sfs_loadvnode().
Referenced by sfs_creat().
static int sfs_mmap (struct vnode * v) [static]
Definition at line 1117 of file sfs_vnode.c.
References EUNIMP.
static int sfs_namefile (struct vnode * vv, struct uio * uio) [static]
Definition at line 1235 of file sfs_vnode.c.
References KASSERT, SFS_ROOT_LOCATION, sfs_vnode::sv_ino, and vnode::vn_data.
static int sfs_notdir (void) [static]
Definition at line 1546 of file sfs_vnode.c.
References ENOTDIR.
static int sfs_open (struct vnode * v, int openflags) [static]
Definition at line 825 of file sfs_vnode.c.
References EUNIMP, and O_APPEND.
static int sfs_opendir (struct vnode * v, int openflags) [static]
Definition at line 850 of file sfs_vnode.c.
References EISDIR, O_ACCMODE, O_APPEND, O_RDONLY, O_RDWR, and O_WRONLY.
static int sfs_partialio (struct sfs_vnode * sv, struct uio * uio, uint32_t skipstart, uint32_t len) [static]
Definition at line 308 of file sfs_vnode.c.
References bzero(), fs::fs_data, KASSERT, SFS_BLOCKSIZE, sfs_bmap(), sfs_rblock(), sfs_wblock(), sfs_vnode::sv_v, uio::uio_offset, UIO_READ, uio::uio_rw, UIO_WRITE, uiomove(), and vnode::vn_fs.
Referenced by sfs_io().
static int sfs_read (struct vnode * v, struct uio * uio) [static]
Definition at line 967 of file sfs_vnode.c.
References KASSERT, sfs_io(), UIO_READ, uio::uio_rw, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
static int sfs_readdir (struct sfs_vnode * sv, struct sfs_dir * sd, int slot) [static]
Definition at line 554 of file sfs_vnode.c.
References panic(), sfs_io(), sfs_vnode::sv_ino, uio_kinit(), UIO_READ, and uio::uio_resid.
Referenced by sfs_dir_findname().
static int sfs_reclaim (struct vnode * v) [static]
Definition at line 889 of file sfs_vnode.c.
References EBUSY, fs::fs_data, KASSERT, kfree(), num, panic(), sfs_inode::sfi_linkcount, sfs_bfree(), sfs_sync_inode(), sfs_fs::sfs_vnodes, sfs_vnode::sv_i, sfs_vnode::sv_ino, sfs_vnode::sv_v, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, vnode::vn_fs, vnode::vn_refcount, VOP_CLEANUP, and VOP_TRUNCATE.
static int sfs_remove (struct vnode * dir, const char * name) [static]
Definition at line 1356 of file sfs_vnode.c.
References KASSERT, sfs_inode::sfi_linkcount, sfs_dir_unlink(), sfs_lookonce(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_v, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, and VOP_DECREF.
static int sfs_rename (struct vnode * d1, const char * n1, struct vnode * d2, const char * n2) [static]
Definition at line 1396 of file sfs_vnode.c.
References KASSERT, kprintf(), panic(), sfs_inode::sfi_linkcount, sfs_inode::sfi_type, sfs_dir_link(), sfs_dir_unlink(), sfs_lookonce(), SFS_ROOT_LOCATION, SFS_TYPE_FILE, strerror(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, sfs_vnode::sv_v, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, and VOP_DECREF.
static int sfs_stat (struct vnode * v, struct stat * statbuf) [static]
Definition at line 1023 of file sfs_vnode.c.
References bzero(), sfs_inode::sfi_size, stat::st_blocks, stat::st_mode, stat::st_nlink, stat::st_size, sfs_vnode::sv_i, vnode::vn_data, and VOP_GETTYPE.
static int sfs_sync_inode (struct sfs_vnode * sv) [static]
Definition at line 69 of file sfs_vnode.c.
References fs::fs_data, sfs_wblock(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, sfs_vnode::sv_v, and vnode::vn_fs.
Referenced by sfs_fsync(), and sfs_reclaim().
static int sfs_truncate (struct vnode * v, off_t len) [static]
Definition at line 1128 of file sfs_vnode.c.
References DIVROUNDUP, fs::fs_data, KASSERT, sfs_inode::sfi_direct, sfs_inode::sfi_indirect, sfs_inode::sfi_size, sfs_bfree(), SFS_BLOCKSIZE, SFS_DBPERIDB, SFS_NDIRECT, sfs_rblock(), sfs_wblock(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_v, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, and vnode::vn_fs.
static int sfs_tryseek (struct vnode * v, off_t pos) [static]
Definition at line 1082 of file sfs_vnode.c.
References EINVAL.
static int sfs_unimp (void) [static]
Definition at line 1560 of file sfs_vnode.c.
References EUNIMP.
static int sfs_write (struct vnode * v, struct uio * uio) [static]
Definition at line 986 of file sfs_vnode.c.
References KASSERT, sfs_io(), uio::uio_rw, UIO_WRITE, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
static int sfs_writedir (struct sfs_vnode * sv, struct sfs_dir * sd, int slot) [static]
Definition at line 588 of file sfs_vnode.c.
References KASSERT, panic(), sfs_io(), sfs_vnode::sv_ino, uio_kinit(), uio::uio_resid, and UIO_WRITE.
Referenced by sfs_dir_link(), and sfs_dir_unlink().
Variable Documentation
struct vnode_ops sfs_dirops [static]
Definition at line 1613 of file sfs_vnode.c.
struct vnode_ops sfs_fileops [static]
Definition at line 1578 of file sfs_vnode.c.