Os/161: kern/dev/lamebus/lscreen_att.c File Reference
kern/dev/lamebus/lscreen_att.c File Reference
#include <types.h>
#include <lib.h>
#include <lamebus/lamebus.h>
#include <lamebus/lscreen.h>
#include "autoconf.h"
Defines
#define LOW_VERSION 1
#define HIGH_VERSION 1
Functions
struct lscreen_softc * attach_lscreen_to_lamebus (int lscreenno, struct lamebus_softc *sc)
Define Documentation
#define HIGH_VERSION 1
Definition at line 42 of file lscreen_att.c.
#define LOW_VERSION 1
Definition at line 40 of file lscreen_att.c.
Function Documentation
struct lscreen_softc* attach_lscreen_to_lamebus (int lscreenno, struct lamebus_softc * sc) [read]
Definition at line 45 of file lscreen_att.c.
References HIGH_VERSION, kmalloc(), lamebus_attach_interrupt(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_SCREEN, LOW_VERSION, lscreen_softc::ls_busdata, lscreen_softc::ls_buspos, lscreen_irq(), and NULL.