Os/161: kern/dev/lamebus/lrandom.c File Reference
kern/dev/lamebus/lrandom.c File Reference
#include <types.h>
#include <lib.h>
#include <uio.h>
#include <platform/bus.h>
#include <lamebus/lrandom.h>
#include "autoconf.h"
Defines
#define LR_REG_RAND 0
#define LR_RANDMAX 0xffffffff
Functions
int config_lrandom (struct lrandom_softc *lr, int lrandomno)
uint32_t lrandom_random (void *devdata)
uint32_t lrandom_randmax (void *devdata)
int lrandom_read (void *devdata, struct uio *uio)
Define Documentation
#define LR_RANDMAX 0xffffffff
Definition at line 44 of file lrandom.c.
Referenced by lrandom_randmax().
#define LR_REG_RAND 0
Definition at line 41 of file lrandom.c.
Referenced by lrandom_random(), and lrandom_read().
Function Documentation
int config_lrandom (struct lrandom_softc * lr, int lrandomno)
Definition at line 47 of file lrandom.c.
Referenced by tryattach_lrandom_to_lamebus().
uint32_t lrandom_randmax (void * devdata)
Definition at line 62 of file lrandom.c.
References LR_RANDMAX.
Referenced by attach_random_to_lrandom().
uint32_t lrandom_random (void * devdata)
Definition at line 55 of file lrandom.c.
References bus_read_register, lrandom_softc::lr_bus, lrandom_softc::lr_buspos, and LR_REG_RAND.
Referenced by attach_random_to_lrandom().
int lrandom_read (void * devdata, struct uio * uio)
Definition at line 69 of file lrandom.c.
References bus_read_register, lrandom_softc::lr_bus, lrandom_softc::lr_buspos, LR_REG_RAND, uio::uio_resid, and uiomove().
Referenced by attach_random_to_lrandom().