Os/161: kern/dev/lamebus/lrandom.h File Reference
kern/dev/lamebus/lrandom.h File Reference
Data Structures
struct lrandom_softc
Functions
uint32_t lrandom_random (void *devdata)
uint32_t lrandom_randmax (void *devdata)
int lrandom_read (void *, struct uio *)
Function Documentation
uint32_t lrandom_randmax (void * devdata)
Definition at line 62 of file lrandom.c.
References LR_RANDMAX.
Referenced by attach_random_to_lrandom().
uint32_t lrandom_random (void * devdata)
Definition at line 55 of file lrandom.c.
References bus_read_register, lrandom_softc::lr_bus, lrandom_softc::lr_buspos, and LR_REG_RAND.
Referenced by attach_random_to_lrandom().
int lrandom_read (void * , struct uio *)
Definition at line 69 of file lrandom.c.
References bus_read_register, lrandom_softc::lr_bus, lrandom_softc::lr_buspos, LR_REG_RAND, uio::uio_resid, and uiomove().
Referenced by attach_random_to_lrandom().