Os/161: common/libc/string/bzero.c File Reference
common/libc/string/bzero.c File Reference
#include <stdint.h>
#include <string.h>
Functions
void bzero (void *vblock, size_t len)
Function Documentation
void bzero (void * vblock, size_t len)
Definition at line 49 of file bzero.c.
Referenced by as_zero_region(), bitmap_create(), check_dir(), dev_stat(), dirread(), emufs_stat(), enter_new_process(), lscreen_newline(), sfs_bmap(), sfs_dir_link(), sfs_dir_unlink(), sfs_partialio(), sfs_stat(), switchframe_init(), writerootdir(), and writesuper().