Os/161: kern/dev/lamebus/lhd.c File Reference
kern/dev/lamebus/lhd.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <synch.h>
#include <platform/bus.h>
#include <vfs.h>
#include <lamebus/lhd.h>
#include "autoconf.h"
Defines
#define LHD_REG_NSECT 0
#define LHD_REG_STAT 4
#define LHD_REG_SECT 8
#define LHD_REG_RPM 12
#define LHD_IDLE 0
#define LHD_WORKING 1
#define LHD_OK 4
#define LHD_INVSECT 12
#define LHD_MEDIA 20
#define LHD_ISWRITE 2
#define LHD_STATEMASK 0x1d
#define LHD_BUFFER 32768
Functions
static uint32_t lhd_rdreg (struct lhd_softc *lh, uint32_t reg)
static void lhd_wreg (struct lhd_softc *lh, uint32_t reg, uint32_t val)
static int lhd_code_to_errno (struct lhd_softc *lh, int code)
static void lhd_iodone (struct lhd_softc *lh, int err)
void lhd_irq (void *vlh)
static int lhd_open (struct device *d, int openflags)
static int lhd_close (struct device *d)
static int lhd_ioctl (struct device *d, int op, userptr_t data)
static int lhd_io (struct device *d, struct uio *uio)
int config_lhd (struct lhd_softc *lh, int lhdno)
Define Documentation
#define LHD_BUFFER 32768
Definition at line 60 of file lhd.c.
Referenced by config_lhd().
#define LHD_IDLE 0
Definition at line 51 of file lhd.c.
Referenced by lhd_irq().
#define LHD_INVSECT 12
Definition at line 54 of file lhd.c.
Referenced by lhd_code_to_errno(), and lhd_irq().
#define LHD_ISWRITE 2
Definition at line 56 of file lhd.c.
Referenced by lhd_io().
#define LHD_MEDIA 20
Definition at line 55 of file lhd.c.
Referenced by lhd_code_to_errno(), and lhd_irq().
#define LHD_OK 4
Definition at line 53 of file lhd.c.
Referenced by lhd_code_to_errno(), and lhd_irq().
#define LHD_REG_NSECT 0
Definition at line 45 of file lhd.c.
Referenced by config_lhd().
#define LHD_REG_RPM 12
Definition at line 48 of file lhd.c.
#define LHD_REG_SECT 8
Definition at line 47 of file lhd.c.
Referenced by lhd_io().
#define LHD_REG_STAT 4
Definition at line 46 of file lhd.c.
Referenced by lhd_io(), and lhd_irq().
#define LHD_STATEMASK 0x1d
Definition at line 57 of file lhd.c.
Referenced by lhd_code_to_errno(), and lhd_irq().
#define LHD_WORKING 1
Definition at line 52 of file lhd.c.
Referenced by lhd_io(), and lhd_irq().
Function Documentation
int config_lhd (struct lhd_softc * lh, int lhdno)
Definition at line 282 of file lhd.c.
References bus_map_area, bus_read_register, device::d_blocks, device::d_blocksize, device::d_close, device::d_data, device::d_io, device::d_ioctl, device::d_open, ENOMEM, lhd_softc::lh_buf, lhd_softc::lh_busdata, lhd_softc::lh_buspos, lhd_softc::lh_clear, lhd_softc::lh_dev, lhd_softc::lh_done, LHD_BUFFER, lhd_close(), lhd_io(), lhd_ioctl(), lhd_open(), LHD_REG_NSECT, LHD_SECTSIZE, name, NULL, sem_create(), sem_destroy(), snprintf(), and vfs_adddev().
Referenced by tryattach_lhd_to_lamebus().
static int lhd_close (struct device * d) [static]
Definition at line 156 of file lhd.c.
Referenced by config_lhd().
static int lhd_code_to_errno (struct lhd_softc * lh, int code) [static]
Definition at line 86 of file lhd.c.
References EAGAIN, EINVAL, EIO, kprintf(), lhd_softc::lh_unit, LHD_INVSECT, LHD_MEDIA, LHD_OK, and LHD_STATEMASK.
Referenced by lhd_irq().
static int lhd_io (struct device * d, struct uio * uio) [static]
Definition at line 201 of file lhd.c.
References device::d_blocks, device::d_data, EINVAL, lhd_softc::lh_buf, lhd_softc::lh_clear, lhd_softc::lh_dev, lhd_softc::lh_done, lhd_softc::lh_result, LHD_ISWRITE, LHD_REG_SECT, LHD_REG_STAT, LHD_SECTSIZE, LHD_WORKING, lhd_wreg(), P(), uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, UIO_WRITE, uiomove(), and V().
Referenced by config_lhd().
static int lhd_ioctl (struct device * d, int op, userptr_t data) [static]
Definition at line 171 of file lhd.c.
References EIOCTL.
Referenced by config_lhd().
static void lhd_iodone (struct lhd_softc * lh, int err) [static]
Definition at line 103 of file lhd.c.
References lhd_softc::lh_done, lhd_softc::lh_result, and V().
Referenced by lhd_irq().
void lhd_irq (void * vlh)
Definition at line 115 of file lhd.c.
References lhd_code_to_errno(), LHD_IDLE, LHD_INVSECT, lhd_iodone(), LHD_MEDIA, LHD_OK, lhd_rdreg(), LHD_REG_STAT, LHD_STATEMASK, LHD_WORKING, and lhd_wreg().
Referenced by attach_lhd_to_lamebus().
static int lhd_open (struct device * d, int openflags) [static]
Definition at line 140 of file lhd.c.
Referenced by config_lhd().
static uint32_t lhd_rdreg (struct lhd_softc * lh, uint32_t reg) [inline, static]
Definition at line 67 of file lhd.c.
References bus_read_register, lhd_softc::lh_busdata, and lhd_softc::lh_buspos.
Referenced by lhd_irq().
static void lhd_wreg (struct lhd_softc * lh, uint32_t reg, uint32_t val) [inline, static]
Definition at line 77 of file lhd.c.
References bus_write_register, lhd_softc::lh_busdata, and lhd_softc::lh_buspos.
Referenced by lhd_io(), and lhd_irq().