Os/161: common/libc/string/strlen.c File Reference
common/libc/string/strlen.c File Reference
#include <string.h>
Functions
size_t strlen (const char *str)
Function Documentation
size_t strlen (const char * str)
Definition at line 47 of file strlen.c.
Referenced by __bad_assert(), __pf_printstuff(), __senderrstr(), check_dir(), checkfilesystem(), cmd_bootfs(), cmd_mount(), cmd_progthread(), cmd_unmount(), complain(), complainx(), dev_lookup(), dir_test(), dir_tryadd(), emu_open(), emufs_lookparent(), fstest_makename(), fstest_read(), fstest_write(), kstrdup(), lseek_file_stdin(), lseek_loc_pasteof(), main(), mkfile(), mkrawname(), open_testfile(), opendisk(), runprogram(), say(), sfs_dir_link(), sfs_lookparent(), strcat(), strrchr(), sys_execv(), system(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_setbootfs(), vscomplain(), and writesuper().