Os/161: kern/arch/mips/include/tlb.h File Reference
kern/arch/mips/include/tlb.h File Reference
Defines
#define TLBHI_VPAGE 0xfffff000
#define TLBLO_PPAGE 0xfffff000
#define TLBLO_NOCACHE 0x00000800
#define TLBLO_DIRTY 0x00000400
#define TLBLO_VALID 0x00000200
#define TLBHI_INVALID(entryno) ((0x80000+(entryno))<<12)
#define TLBLO_INVALID() (0)
#define NUM_TLB 64
Functions
void tlb_random (uint32_t entryhi, uint32_t entrylo)
void tlb_write (uint32_t entryhi, uint32_t entrylo, uint32_t index)
void tlb_read (uint32_t *entryhi, uint32_t *entrylo, uint32_t index)
int tlb_probe (uint32_t entryhi, uint32_t entrylo)
Define Documentation
#define NUM_TLB 64
Definition at line 102 of file tlb.h.
Referenced by as_activate(), and vm_fault().
#define TLBHI_INVALID (entryno) ((0x80000+(entryno))<<12)
Definition at line 95 of file tlb.h.
Referenced by as_activate().
#define TLBHI_VPAGE 0xfffff000
Definition at line 80 of file tlb.h.
#define TLBLO_DIRTY 0x00000400
Definition at line 86 of file tlb.h.
Referenced by vm_fault().
#define TLBLO_INVALID () (0)
Definition at line 96 of file tlb.h.
Referenced by as_activate().
#define TLBLO_NOCACHE 0x00000800
Definition at line 85 of file tlb.h.
#define TLBLO_PPAGE 0xfffff000
Definition at line 84 of file tlb.h.
#define TLBLO_VALID 0x00000200
Definition at line 87 of file tlb.h.
Referenced by vm_fault().
Function Documentation
int tlb_probe (uint32_t entryhi, uint32_t entrylo)
void tlb_random (uint32_t entryhi, uint32_t entrylo)
void tlb_read (uint32_t * entryhi, uint32_t * entrylo, uint32_t index)
Referenced by vm_fault().
void tlb_write (uint32_t entryhi, uint32_t entrylo, uint32_t index)
Referenced by as_activate(), and vm_fault().