Os/161: kern/include/array.h File Reference
kern/include/array.h File Reference
Data Structures
struct array
Defines
#define ARRAYS_CHECKED
#define ARRAYASSERT KASSERT
#define ARRAYINLINE INLINE
#define DECLARRAY_BYTYPE(ARRAY, T)
#define DEFARRAY_BYTYPE(ARRAY, T, INLINE)
#define DECLARRAY(T) DECLARRAY_BYTYPE(T##array, struct T)
#define DEFARRAY(T, INLINE) DEFARRAY_BYTYPE(T##array, struct T, INLINE)
Functions
struct array * array_create (void)
void array_destroy (struct array *)
void array_init (struct array *)
void array_cleanup (struct array *)
unsigned array_num (const struct array *)
void * array_get (const struct array *, unsigned index)
void array_set (const struct array *, unsigned index, void *val)
int array_setsize (struct array *, unsigned num)
int array_add (struct array *, void *val, unsigned *index_ret)
void array_remove (struct array *, unsigned index)
DECLARRAY_BYTYPE (stringarray, char)
DEFARRAY_BYTYPE (stringarray, char, ARRAYINLINE)
Define Documentation
#define ARRAYASSERT KASSERT
Definition at line 36 of file array.h.
Referenced by array_cleanup(), array_get(), array_remove(), and array_set().
#define ARRAYINLINE INLINE
Definition at line 82 of file array.h.
#define ARRAYS_CHECKED
Definition at line 33 of file array.h.
#define DECLARRAY (T) DECLARRAY_BYTYPE(T##array, struct T)
Definition at line 245 of file array.h.
#define DECLARRAY_BYTYPE (ARRAY, T)
Value:
struct ARRAY {                                          \
                struct array arr;                               \
        };                                                      \
                                                                \
        struct ARRAY *ARRAY##_create(void);                     \
        void ARRAY##_destroy(struct ARRAY *a);                  \
        void ARRAY##_init(struct ARRAY *a);                     \
        void ARRAY##_cleanup(struct ARRAY *a);                  \
        unsigned ARRAY##_num(const struct ARRAY *a);            \
        T *ARRAY##_get(const struct ARRAY *a, unsigned index);  \
        void ARRAY##_set(struct ARRAY *a, unsigned index, T *val); \
        int ARRAY##_setsize(struct ARRAY *a, unsigned num);     \
        int ARRAY##_add(struct ARRAY *a, T *val, unsigned *index_ret); \
        void ARRAY##_remove(struct ARRAY *a, unsigned index)
Definition at line 162 of file array.h.
#define DEFARRAY (T, INLINE) DEFARRAY_BYTYPE(T##array, struct T, INLINE)
Definition at line 246 of file array.h.
#define DEFARRAY_BYTYPE (ARRAY, T, INLINE)
Definition at line 178 of file array.h.
Function Documentation
ARRAYINLINE int array_add (struct array * a, void * val, unsigned * index_ret)
Definition at line 106 of file array.h.
References array_setsize(), NULL, array::num, and array::v.
Referenced by testa().
void array_cleanup (struct array *)
Definition at line 64 of file array.c.
References ARRAYASSERT, kfree(), NULL, array::num, and array::v.
Referenced by array_destroy().
struct array* array_create (void) [read]
Definition at line 38 of file array.c.
References array_init(), kmalloc(), and NULL.
Referenced by arraytest().
void array_destroy (struct array *)
Definition at line 50 of file array.c.
References array_cleanup(), and kfree().
Referenced by arraytest().
ARRAYINLINE void * array_get (const struct array * a, unsigned index)
Definition at line 92 of file array.h.
References ARRAYASSERT, num, and array::v.
Referenced by testa().
void array_init (struct array *)
Definition at line 57 of file array.c.
References array::max, NULL, array::num, and array::v.
Referenced by array_create().
ARRAYINLINE unsigned array_num (const struct array * a)
Definition at line 86 of file array.h.
References array::num.
Referenced by testa().
void array_remove (struct array * , unsigned index)
Definition at line 113 of file array.c.
References ARRAYASSERT, array::max, memmove(), num, array::num, and array::v.
Referenced by testa().
ARRAYINLINE void array_set (const struct array * a, unsigned index, void * val)
Definition at line 99 of file array.h.
References ARRAYASSERT, num, and array::v.
Referenced by testa().
int array_setsize (struct array * , unsigned num)
Definition at line 79 of file array.c.
References ENOMEM, kfree(), kmalloc(), array::max, memcpy(), NULL, array::num, and array::v.
Referenced by array_add(), arraytest(), and testa().
DECLARRAY_BYTYPE (stringarray , char)
DEFARRAY_BYTYPE (stringarray , char , ARRAYINLINE)