Os/161: kern/dev/generic/beep.c File Reference
kern/dev/generic/beep.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <generic/beep.h>
#include "autoconf.h"
Functions
int config_beep (struct beep_softc *bs, int unit)
void beep (void)
Variables
static struct beep_softc * the_beep = NULL
Function Documentation
void beep (void)
Definition at line 63 of file beep.c.
References beep_softc::bs_beep, beep_softc::bs_devdata, kprintf(), and NULL.
Referenced by kgets().
int config_beep (struct beep_softc * bs, int unit)
Definition at line 50 of file beep.c.
References ENODEV, KASSERT, and NULL.
Referenced by tryattach_beep_to_ltimer().
Variable Documentation
struct beep_softc* the_beep = NULL [static]
Definition at line 47 of file beep.c.