Os/161: kern/dev/lamebus/lser.h File Reference
kern/dev/lamebus/lser.h File Reference
#include <spinlock.h>
Data Structures
struct lser_softc
Functions
void lser_irq (void *sc)
void lser_write (void *sc, int ch)
void lser_startpolling (void *sc)
void lser_writepolled (void *sc, int ch)
void lser_endpolling (void *sc)
Function Documentation
void lser_endpolling (void * sc)
Definition at line 177 of file lser.c.
References lser_softc::ls_busdata, lser_softc::ls_buspos, and lser_softc::ls_unmaskinterrupt.
Referenced by attach_con_to_lser().
void lser_irq (void * sc)
Definition at line 47 of file lser.c.
References bus_read_register, bus_write_register, ch, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_devdata, lser_softc::ls_input, lser_softc::ls_lock, lser_softc::ls_start, lser_softc::ls_wbusy, LSER_IRQ_ACTIVE, LSER_IRQ_ENABLE, LSER_REG_CHAR, LSER_REG_RIRQ, LSER_REG_WIRQ, NULL, spinlock_acquire(), and spinlock_release().
Referenced by attach_lser_to_lamebus().
void lser_startpolling (void * sc)
Definition at line 170 of file lser.c.
References lser_softc::ls_busdata, lser_softc::ls_buspos, and lser_softc::ls_maskinterrupt.
Referenced by attach_con_to_lser().
void lser_write (void * sc, int ch)
Definition at line 87 of file lser.c.
References bus_write_register, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_REG_CHAR, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lser().
void lser_writepolled (void * sc, int ch)
Definition at line 130 of file lser.c.
References bus_write_register, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_IRQ_ENABLE, lser_poll_until_write(), LSER_REG_CHAR, LSER_REG_WIRQ, spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lser().