Os/161: kern/dev/lamebus/con_lscreen.c File Reference
kern/dev/lamebus/con_lscreen.c File Reference
#include <types.h>
#include <lib.h>
#include <generic/console.h>
#include <lamebus/lscreen.h>
#include "autoconf.h"
Functions
struct con_softc * attach_con_to_lscreen (int consno, struct lscreen_softc *ls)
Function Documentation
struct con_softc* attach_con_to_lscreen (int consno, struct lscreen_softc * ls) [read]
Definition at line 42 of file con_lscreen.c.
References con_input(), con_start(), con_softc::cs_devdata, con_softc::cs_endpolling, con_softc::cs_send, con_softc::cs_sendpolled, con_softc::cs_startpolling, kmalloc(), lscreen_softc::ls_devdata, lscreen_softc::ls_input, lscreen_softc::ls_start, lscreen_write(), and NULL.