Os/161: kern/lib/array.c File Reference
kern/lib/array.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
Defines
#define ARRAYINLINE
Functions
struct array * array_create (void)
void array_destroy (struct array *a)
void array_init (struct array *a)
void array_cleanup (struct array *a)
int array_setsize (struct array *a, unsigned num)
void array_remove (struct array *a, unsigned index)
Define Documentation
#define ARRAYINLINE
Definition at line 30 of file array.c.
Function Documentation
void array_cleanup (struct array * a)
Definition at line 64 of file array.c.
References ARRAYASSERT, kfree(), NULL, array::num, and array::v.
Referenced by array_destroy().
struct array* array_create (void) [read]
Definition at line 38 of file array.c.
References array_init(), kmalloc(), and NULL.
Referenced by arraytest().
void array_destroy (struct array * a)
Definition at line 50 of file array.c.
References array_cleanup(), and kfree().
Referenced by arraytest().
void array_init (struct array * a)
Definition at line 57 of file array.c.
References array::max, NULL, array::num, and array::v.
Referenced by array_create().
void array_remove (struct array * a, unsigned index)
Definition at line 113 of file array.c.
References ARRAYASSERT, array::max, memmove(), num, array::num, and array::v.
Referenced by testa().
int array_setsize (struct array * a, unsigned num)
Definition at line 79 of file array.c.
References ENOMEM, kfree(), kmalloc(), array::max, memcpy(), NULL, array::num, and array::v.
Referenced by array_add(), arraytest(), and testa().