Os/161: kern/lib/kprintf.c File Reference
kern/lib/kprintf.c File Reference
#include <types.h>
#include <kern/unistd.h>
#include <stdarg.h>
#include <lib.h>
#include <spl.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <mainbus.h>
#include <vfs.h>
Functions
void kprintf_bootstrap (void)
static void console_send (void *junk, const char *data, size_t len)
int kprintf (const char *fmt,...)
void panic (const char *fmt,...)
void badassert (const char *expr, const char *file, int line, const char *func)
Variables
uint32_t dbflags = 0
static struct lock * kprintf_lock
static struct spinlock kprintf_spinlock
Function Documentation
void badassert (const char * expr, const char * file, int line, const char * func)
Definition at line 206 of file kprintf.c.
References panic().
static void console_send (void * junk, const char * data, size_t len) [static]
Definition at line 79 of file kprintf.c.
References putch().
Referenced by kprintf(), and panic().
int kprintf (const char * fmt, ...)
Definition at line 94 of file kprintf.c.
References __vprintf(), console_send(), kprintf_spinlock, lock_acquire(), lock_release(), NULL, putch_complete(), putch_prepare(), spinlock_acquire(), spinlock_release(), va_end, and va_start.
void kprintf_bootstrap (void)
Definition at line 63 of file kprintf.c.
References KASSERT, kprintf_spinlock, lock_create(), NULL, panic(), and spinlock_init().
Referenced by boot().
void panic (const char * fmt, ...)
Definition at line 133 of file kprintf.c.
References __vprintf(), console_send(), kprintf(), mainbus_panic(), NULL, putch_complete(), putch_prepare(), splhigh(), thread_panic(), va_end, va_start, and vfs_sync().
Variable Documentation
uint32_t dbflags = 0
Definition at line 43 of file kprintf.c.
struct lock* kprintf_lock [static]
Definition at line 46 of file kprintf.c.
struct spinlock kprintf_spinlock [static]
Definition at line 49 of file kprintf.c.
Referenced by kprintf(), and kprintf_bootstrap().