Os/161: kern/test/fstest.c File Reference
kern/test/fstest.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <lib.h>
#include <uio.h>
#include <thread.h>
#include <synch.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
#include <test.h>
Defines
#define SLOGAN "HODIE MIHI - CRAS TIBI\n"
#define FILENAME "fstest.tmp"
#define NCHUNKS 720
#define NTHREADS 12
#define NCREATES 32
#define MAKENAME() fstest_makename(name, sizeof(name), fs, namesuffix)
#define DEFTEST(testname)
Functions
static void init_threadsem (void)
static void rotate (char *str, int amt)
static void fstest_makename (char *buf, size_t buflen, const char *fs, const char *namesuffix)
static int fstest_remove (const char *fs, const char *namesuffix)
static int fstest_write (const char *fs, const char *namesuffix, int stridesize, int stridepos)
static int fstest_read (const char *fs, const char *namesuffix)
static void dofstest (const char *filesys)
static void readstress_thread (void *fs, unsigned long num)
static void doreadstress (const char *filesys)
static void writestress_thread (void *fs, unsigned long num)
static void dowritestress (const char *filesys)
static void writestress2_thread (void *fs, unsigned long num)
static void dowritestress2 (const char *filesys)
static void createstress_thread (void *fs, unsigned long num)
static void docreatestress (const char *filesys)
static int checkfilesystem (int nargs, char **args)
DEFTEST (fstest)
DEFTEST (readstress)
DEFTEST (writestress)
DEFTEST (writestress2)
DEFTEST (createstress)
int printfile (int nargs, char **args)
Variables
static struct semaphore * threadsem = NULL
Define Documentation
#define DEFTEST (testname)
Value:
int                                             \
  testname(int nargs, char **args)                \
  {                                               \
        int result;                               \
        result = checkfilesystem(nargs, args);    \
        if (result) {                             \
                return result;                    \
        }                                         \
        do##testname(args[1]);                    \
        return 0;                                 \
  }
Definition at line 559 of file fstest.c.
#define FILENAME "fstest.tmp"
Definition at line 54 of file fstest.c.
Referenced by fstest_makename().
#define MAKENAME () fstest_makename(name, sizeof(name), fs, namesuffix)
Definition at line 110 of file fstest.c.
Referenced by fstest_read(), fstest_remove(), and fstest_write().
#define NCHUNKS 720
Definition at line 55 of file fstest.c.
Referenced by fstest_read(), and fstest_write().
#define NCREATES 32
Definition at line 57 of file fstest.c.
Referenced by createstress_thread().
#define NTHREADS 12
Definition at line 56 of file fstest.c.
Referenced by cvtest(), cvtestthread(), docreatestress(), doreadstress(), dowritestress(), dowritestress2(), locktest(), main(), mallocstress(), runthreads(), semtest(), and writestress2_thread().
#define SLOGAN "HODIE MIHI - CRAS TIBI\n"
Definition at line 53 of file fstest.c.
Referenced by fstest_read(), and fstest_write().
Function Documentation
static int checkfilesystem (int nargs, char ** args) [static]
Definition at line 540 of file fstest.c.
References EINVAL, kprintf(), and strlen().
static void createstress_thread (void * fs, unsigned long num) [static]
Definition at line 476 of file fstest.c.
References fstest_read(), fstest_remove(), fstest_write(), kprintf(), NCREATES, snprintf(), and V().
Referenced by docreatestress().
DEFTEST (createstress)
DEFTEST (writestress2)
DEFTEST (writestress)
DEFTEST (readstress)
DEFTEST (fstest)
static void docreatestress (const char * filesys) [static]
Definition at line 511 of file fstest.c.
References createstress_thread(), err(), init_threadsem(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), and thread_fork().
static void dofstest (const char * filesys) [static]
Definition at line 277 of file fstest.c.
References fstest_read(), fstest_remove(), fstest_write(), and kprintf().
static void doreadstress (const char * filesys) [static]
Definition at line 314 of file fstest.c.
References err(), fstest_remove(), fstest_write(), init_threadsem(), kprintf(), NTHREADS, NULL, P(), panic(), readstress_thread(), strerror(), and thread_fork().
static void dowritestress (const char * filesys) [static]
Definition at line 382 of file fstest.c.
References err(), init_threadsem(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), thread_fork(), and writestress_thread().
static void dowritestress2 (const char * filesys) [static]
Definition at line 425 of file fstest.c.
References err(), fstest_makename(), fstest_read(), fstest_remove(), init_threadsem(), kprintf(), name, NTHREADS, NULL, O_CREAT, O_TRUNC, O_WRONLY, P(), panic(), strerror(), thread_fork(), vfs_close(), vfs_open(), and writestress2_thread().
static void fstest_makename (char * buf, size_t buflen, const char * fs, const char * namesuffix) [static]
Definition at line 103 of file fstest.c.
References FILENAME, KASSERT, snprintf(), and strlen().
Referenced by dowritestress2().
static int fstest_read (const char * fs, const char * namesuffix) [static]
Definition at line 212 of file fstest.c.
References err(), kprintf(), MAKENAME, name, NCHUNKS, O_RDONLY, rotate(), SLOGAN, strcmp(), strcpy(), strerror(), strlen(), uio_kinit(), uio::uio_offset, UIO_READ, uio::uio_resid, vfs_close(), vfs_open(), and VOP_READ.
Referenced by createstress_thread(), dofstest(), dowritestress2(), readstress_thread(), and writestress_thread().
static int fstest_remove (const char * fs, const char * namesuffix) [static]
Definition at line 114 of file fstest.c.
References err(), kprintf(), MAKENAME, name, strcpy(), strerror(), and vfs_remove().
Referenced by createstress_thread(), dofstest(), doreadstress(), dowritestress2(), and writestress_thread().
static int fstest_write (const char * fs, const char * namesuffix, int stridesize, int stridepos) [static]
Definition at line 134 of file fstest.c.
References err(), KASSERT, kprintf(), MAKENAME, name, NCHUNKS, O_CREAT, O_TRUNC, O_WRONLY, pos, rotate(), SLOGAN, strcpy(), strerror(), strlen(), uio_kinit(), uio::uio_offset, uio::uio_resid, UIO_WRITE, vfs_close(), vfs_open(), vfs_remove(), and VOP_WRITE.
Referenced by createstress_thread(), dofstest(), doreadstress(), writestress2_thread(), and writestress_thread().
static void init_threadsem (void) [static]
Definition at line 63 of file fstest.c.
References NULL, panic(), and sem_create().
Referenced by docreatestress(), doreadstress(), dowritestress(), and dowritestress2().
int printfile (int nargs, char ** args)
Definition at line 581 of file fstest.c.
References EINVAL, kprintf(), O_RDONLY, O_WRONLY, strcpy(), strerror(), uio_kinit(), uio::uio_offset, UIO_READ, uio::uio_resid, UIO_WRITE, vfs_close(), vfs_open(), VOP_READ, and VOP_WRITE.
static void readstress_thread (void * fs, unsigned long num) [static]
Definition at line 303 of file fstest.c.
References fstest_read(), kprintf(), and V().
Referenced by doreadstress().
static void rotate (char * str, int amt) [static]
Definition at line 79 of file fstest.c.
References ch, and KASSERT.
Referenced by fstest_read(), and fstest_write().
static void writestress2_thread (void * fs, unsigned long num) [static]
Definition at line 410 of file fstest.c.
References fstest_write(), kprintf(), NTHREADS, and V().
Referenced by dowritestress2().
static void writestress_thread (void * fs, unsigned long num) [static]
Definition at line 353 of file fstest.c.
References fstest_read(), fstest_remove(), fstest_write(), kprintf(), snprintf(), and V().
Referenced by dowritestress().
Variable Documentation
struct semaphore* threadsem = NULL [static]
Definition at line 59 of file fstest.c.