Os/161: kern/include/test.h File Reference
kern/include/test.h File Reference
Functions
int whalemating (int, char **)
int arraytest (int, char **)
int bitmaptest (int, char **)
int queuetest (int, char **)
int threadtest (int, char **)
int threadtest2 (int, char **)
int threadtest3 (int, char **)
int semtest (int, char **)
int locktest (int, char **)
int cvtest (int, char **)
int fstest (int, char **)
int readstress (int, char **)
int writestress (int, char **)
int writestress2 (int, char **)
int createstress (int, char **)
int printfile (int, char **)
int malloctest (int, char **)
int mallocstress (int, char **)
int nettest (int, char **)
int runprogram (char *progname, int nargs, char **args)
void menu (char *argstr)
void kmain (char *bootstring)
Function Documentation
int arraytest (int , char **)
Definition at line 122 of file arraytest.c.
References array_create(), array_destroy(), array_setsize(), KASSERT, kprintf(), NULL, and testa().
int bitmaptest (int , char **)
Definition at line 38 of file bitmaptest.c.
References bitmap_alloc(), bitmap_create(), bitmap_isset(), bitmap_mark(), bitmap_unmark(), KASSERT, kprintf(), NULL, random(), and TESTSIZE.
int createstress (int , char **)
int cvtest (int , char **)
Definition at line 275 of file synchtest.c.
References cvtestthread(), inititems(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), testval1, and thread_fork().
int fstest (int , char **)
void kmain (char * bootstring)
Definition at line 212 of file main.c.
References boot(), and menu().
int locktest (int , char **)
Definition at line 196 of file synchtest.c.
References inititems(), kprintf(), locktestthread(), NTHREADS, NULL, P(), panic(), strerror(), and thread_fork().
int mallocstress (int , char **)
Definition at line 107 of file malloctest.c.
References kprintf(), mallocthread(), NTHREADS, NULL, P(), panic(), sem_create(), sem_destroy(), strerror(), and thread_fork().
int malloctest (int , char **)
Definition at line 94 of file malloctest.c.
References kprintf(), mallocthread(), and NULL.
void menu (char * argstr)
Definition at line 681 of file menu.c.
References kgets(), kprintf(), and menu_execute().
Referenced by kmain(), main(), and runit().
int nettest (int , char **)
Definition at line 38 of file nettest.c.
References kprintf().
int printfile (int , char **)
Definition at line 581 of file fstest.c.
References EINVAL, kprintf(), O_RDONLY, O_WRONLY, strcpy(), strerror(), uio_kinit(), uio::uio_offset, UIO_READ, uio::uio_resid, UIO_WRITE, vfs_close(), vfs_open(), VOP_READ, and VOP_WRITE.
int queuetest (int , char **)
int readstress (int , char **)
int runprogram (char * progname, int nargs, char ** args)
Definition at line 56 of file runprogram.c.
References as_activate(), as_create(), as_define_stack(), copyout(), EINVAL, ENOMEM, enter_new_process(), KASSERT, kfree(), kmalloc(), kstrdup(), load_elf(), NULL, O_RDONLY, panic(), STACK_OFFSET, strlen(), vfs_close(), and vfs_open().
Referenced by cmd_progthread().
int semtest (int , char **)
Definition at line 104 of file synchtest.c.
References inititems(), kprintf(), NTHREADS, NULL, P(), panic(), semtestthread(), strerror(), thread_fork(), and V().
int threadtest (int , char **)
Definition at line 122 of file threadtest.c.
References init_sem(), kprintf(), and runthreads().
int threadtest2 (int , char **)
Definition at line 136 of file threadtest.c.
References init_sem(), kprintf(), and runthreads().
int threadtest3 (int , char **)
Definition at line 255 of file tt3.c.
References atoi(), kprintf(), and runtest3().
int whalemating (int , char **)
Definition at line 73 of file whalemating.c.
References err(), female(), male(), matchmaker(), NMATING, NULL, panic(), strerror(), and thread_fork().
int writestress (int , char **)
int writestress2 (int , char **)