Os/161: kern/syscall/open_syscall.c File Reference
kern/syscall/open_syscall.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <vm.h>
#include <mainbus.h>
#include <vfs.h>
#include <device.h>
#include <syscall.h>
#include <kern/fcntl.h>
#include <kern/file.h>
Functions
int sys_open (const char *filename, int flags, int *retval)
Function Documentation
int sys_open (const char * filename, int flags, int * retval)
Definition at line 35 of file open_syscall.c.
References EINVAL, EMFILE, errno, fd, kmalloc(), MAX_FD, NULL, O_ACCMODE, O_RDONLY, O_RDWR, O_WRONLY, file::offset, file::readable, file::vfs_node, vfs_open(), and file::writeable.
Referenced by syscall().