Os/161: kern/include/bitmap.h File Reference
kern/include/bitmap.h File Reference
Functions
struct bitmap * bitmap_create (unsigned nbits)
void * bitmap_getdata (struct bitmap *)
int bitmap_alloc (struct bitmap *, unsigned *index)
void bitmap_mark (struct bitmap *, unsigned index)
void bitmap_unmark (struct bitmap *, unsigned index)
int bitmap_isset (struct bitmap *, unsigned index)
void bitmap_destroy (struct bitmap *)
Function Documentation
int bitmap_alloc (struct bitmap * , unsigned * index)
Definition at line 99 of file bitmap.c.
References BITS_PER_WORD, DIVROUNDUP, ENOSPC, KASSERT, bitmap::nbits, bitmap::v, WORD_ALLBITS, and WORD_TYPE.
Referenced by bitmaptest(), and sfs_balloc().
struct bitmap* bitmap_create (unsigned nbits) [read]
Definition at line 57 of file bitmap.c.
References BITS_PER_WORD, bzero(), DIVROUNDUP, KASSERT, kfree(), kmalloc(), bitmap::nbits, NULL, bitmap::v, and WORD_TYPE.
Referenced by bitmaptest(), and sfs_domount().
void bitmap_destroy (struct bitmap *)
Definition at line 172 of file bitmap.c.
References kfree(), and bitmap::v.
Referenced by sfs_domount(), and sfs_unmount().
void* bitmap_getdata (struct bitmap *)
Definition at line 93 of file bitmap.c.
References bitmap::v.
Referenced by sfs_mapio().
int bitmap_isset (struct bitmap * , unsigned index)
Definition at line 162 of file bitmap.c.
References bitmap_translate(), bitmap::v, and WORD_TYPE.
Referenced by bitmaptest(), and sfs_bused().
void bitmap_mark (struct bitmap * , unsigned index)
Definition at line 135 of file bitmap.c.
References bitmap_translate(), KASSERT, bitmap::nbits, bitmap::v, and WORD_TYPE.
Referenced by bitmaptest(), check_dir(), check_indirect_block(), check_inode_blocks(), check_sb(), and observe_filelink().
void bitmap_unmark (struct bitmap * , unsigned index)
Definition at line 148 of file bitmap.c.
References bitmap_translate(), KASSERT, bitmap::nbits, bitmap::v, and WORD_TYPE.
Referenced by bitmaptest(), and sfs_bfree().