Os/161: kern/include/threadprivate.h File Reference
kern/include/threadprivate.h File Reference
Functions
void thread_startup (void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
void thread_machdep_init (struct thread_machdep *tm)
void thread_machdep_cleanup (struct thread_machdep *tm)
void switchframe_switch (struct switchframe **prev, struct switchframe **next)
void switchframe_init (struct thread *, void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
Function Documentation
void switchframe_init (struct thread * , void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 55 of file switchframe.c.
References bzero(), mips_threadstart(), switchframe::sf_ra, switchframe::sf_s0, switchframe::sf_s1, switchframe::sf_s2, STACK_SIZE, thread::t_context, and thread::t_stack.
Referenced by thread_fork(), and thread_fork2().
void switchframe_switch (struct switchframe ** prev, struct switchframe ** next)
Referenced by thread_switch().
void thread_machdep_cleanup (struct thread_machdep * tm)
Definition at line 46 of file thread_machdep.c.
References KASSERT, NULL, and thread_machdep::tm_badfaultfunc.
Referenced by thread_destroy().
void thread_machdep_init (struct thread_machdep * tm)
Definition at line 40 of file thread_machdep.c.
References NULL, and thread_machdep::tm_badfaultfunc.
Referenced by thread_create().
void thread_startup (void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 799 of file thread.c.
References as_activate(), curcpu, exorcise(), NULL, random(), S_RUN, spinlock_release(), spl0(), thread::t_addrspace, thread::t_state, thread::t_wchan_name, thread_exit(), and thread_yield().