Os/161: user/bin/cat/cat.c File Reference
user/bin/cat/cat.c File Reference
#include <unistd.h>
#include <string.h>
#include <err.h>
Functions
static void docat (const char *name, int fd)
static void cat (const char *file)
int main (int argc, char *argv[])
Function Documentation
static void cat (const char * file) [static]
Definition at line 80 of file cat.c.
References close(), docat(), err(), fd, O_RDONLY, open(), STDIN_FILENO, and strcmp().
Referenced by main().
static void docat (const char * name, int fd) [static]
Definition at line 44 of file cat.c.
References err(), read(), STDOUT_FILENO, and write().
Referenced by cat(), and main().
int main (int argc, char * argv[])
Definition at line 106 of file cat.c.
References cat(), docat(), and STDIN_FILENO.