Os/161: kern/test/tt3.c File Reference
kern/test/tt3.c File Reference
#include <types.h>
#include <lib.h>
#include <wchan.h>
#include <thread.h>
#include <synch.h>
#include <test.h>
#include "opt-synchprobs.h"
Defines
#define DIM 70
#define SLEEPALOT_PRINTS 20
#define SLEEPALOT_ITERS 4
#define WAKER_WAKES 100
#define COMPUTE_ITERS 10
#define NWAITCHANS 12
Functions
static void setup (void)
static void sleepalot_thread (void *junk, unsigned long num)
static void waker_thread (void *junk1, unsigned long junk2)
static void make_sleepalots (int howmany)
static void compute_thread (void *junk1, unsigned long num)
static void make_computes (int howmany)
static void finish (int howmanytotal)
static void runtest3 (int nsleeps, int ncomputes)
int threadtest3 (int nargs, char **args)
Variables
static struct wchan * waitchans [NWAITCHANS]
static volatile int wakerdone
static struct semaphore * wakersem
static struct semaphore * donesem
Define Documentation
#define COMPUTE_ITERS 10
Definition at line 56 of file tt3.c.
Referenced by compute_thread().
#define DIM 70
Definition at line 47 of file tt3.c.
Referenced by addeq(), compute_thread(), do_move(), initialize_board(), main(), multiply(), populate_initial_matrixes(), print_board(), trace(), win_column(), win_diag_left(), win_diag_right(), and win_row().
#define NWAITCHANS 12
Definition at line 58 of file tt3.c.
Referenced by setup(), sleepalot_thread(), and waker_thread().
#define SLEEPALOT_ITERS 4
Definition at line 52 of file tt3.c.
Referenced by sleepalot_thread().
#define SLEEPALOT_PRINTS 20
Definition at line 51 of file tt3.c.
Referenced by sleepalot_thread().
#define WAKER_WAKES 100
Definition at line 54 of file tt3.c.
Referenced by waker_thread().
Function Documentation
static void compute_thread (void * junk1, unsigned long num) [static]
Definition at line 155 of file tt3.c.
References COMPUTE_ITERS, DIM, KASSERT, kfree(), kmalloc(), kprintf(), NULL, random(), thread_yield(), and V().
Referenced by make_computes().
static void finish (int howmanytotal) [static]
Definition at line 228 of file tt3.c.
References P(), V(), and wakerdone.
Referenced by runtest3().
static void make_computes (int howmany) [static]
Definition at line 212 of file tt3.c.
References compute_thread(), name, NULL, panic(), snprintf(), strerror(), and thread_fork().
Referenced by runtest3().
static void make_sleepalots (int howmany) [static]
Definition at line 135 of file tt3.c.
References name, NULL, panic(), sleepalot_thread(), snprintf(), strerror(), thread_fork(), and waker_thread().
Referenced by runtest3().
static void runtest3 (int nsleeps, int ncomputes) [static]
Definition at line 242 of file tt3.c.
References finish(), kprintf(), make_computes(), make_sleepalots(), and setup().
Referenced by threadtest3().
static void setup (void) [static]
Definition at line 67 of file tt3.c.
References kstrdup(), NULL, NWAITCHANS, sem_create(), snprintf(), wakerdone, and wchan_create().
Referenced by runtest3().
static void sleepalot_thread (void * junk, unsigned long num) [static]
Definition at line 85 of file tt3.c.
References kprintf(), NWAITCHANS, random(), SLEEPALOT_ITERS, SLEEPALOT_PRINTS, V(), wchan_lock(), and wchan_sleep().
Referenced by make_sleepalots().
int threadtest3 (int nargs, char ** args)
Definition at line 255 of file tt3.c.
References atoi(), kprintf(), and runtest3().
static void waker_thread (void * junk1, unsigned long junk2) [static]
Definition at line 106 of file tt3.c.
References NWAITCHANS, P(), random(), thread_yield(), V(), WAKER_WAKES, wakerdone, and wchan_wakeall().
Referenced by make_sleepalots().
Variable Documentation
struct semaphore* donesem [static]
Definition at line 63 of file tt3.c.
struct wchan* waitchans[NWAITCHANS] [static]
Definition at line 59 of file tt3.c.
volatile int wakerdone [static]
Definition at line 61 of file tt3.c.
Referenced by finish(), setup(), and waker_thread().
struct semaphore* wakersem [static]
Definition at line 62 of file tt3.c.