Os/161: kern/include/clock.h File Reference
kern/include/clock.h File Reference
#include "opt-synchprobs.h"
Defines
#define HZ 100
Functions
void hardclock_bootstrap (void)
void hardclock (void)
void timerclock (void)
void gettime (time_t *seconds, uint32_t *nanoseconds)
void getinterval (time_t secs1, uint32_t nsecs, time_t secs2, uint32_t nsecs2, time_t *rsecs, uint32_t *rnsecs)
void clocksleep (int seconds)
Define Documentation
#define HZ 100
Definition at line 56 of file clock.h.
Referenced by mainbus_bootstrap(), and mainbus_interrupt().
Function Documentation
void clocksleep (int seconds)
Definition at line 109 of file clock.c.
References wchan_lock(), and wchan_sleep().
Referenced by waitpid().
void getinterval (time_t secs1, uint32_t nsecs, time_t secs2, uint32_t nsecs2, time_t * rsecs, uint32_t * rnsecs)
Definition at line 57 of file menu.c.
Referenced by cmd_dispatch().
void gettime (time_t * seconds, uint32_t * nanoseconds)
Definition at line 66 of file rtclock.c.
References KASSERT, NULL, rtclock_softc::rtc_devdata, and rtclock_softc::rtc_gettime.
Referenced by cmd_dispatch(), cvtestthread(), and sys___time().
void hardclock (void)
Definition at line 89 of file clock.c.
References curcpu, MIGRATE_HARDCLOCKS, schedule(), SCHEDULE_HARDCLOCKS, thread_consider_migration(), and thread_yield().
Referenced by ltimer_irq(), and mainbus_interrupt().
void hardclock_bootstrap (void)
Definition at line 65 of file clock.c.
References NULL, panic(), and wchan_create().
Referenced by boot().
void timerclock (void)
Definition at line 78 of file clock.c.
References wchan_wakeall().
Referenced by ltimer_irq().