Os/161: kern/test/synchtest.c File Reference
kern/test/synchtest.c File Reference
#include <types.h>
#include <lib.h>
#include <clock.h>
#include <thread.h>
#include <synch.h>
#include <test.h>
Defines
#define NSEMLOOPS 63
#define NLOCKLOOPS 120
#define NCVLOOPS 5
#define NTHREADS 32
Functions
static void inititems (void)
static void semtestthread (void *junk, unsigned long num)
int semtest (int nargs, char **args)
static void fail (unsigned long num, const char *msg)
static void locktestthread (void *junk, unsigned long num)
int locktest (int nargs, char **args)
static void cvtestthread (void *junk, unsigned long num)
int cvtest (int nargs, char **args)
Variables
static volatile unsigned long testval1
static volatile unsigned long testval2
static volatile unsigned long testval3
static struct semaphore * testsem
static struct lock * testlock
static struct cv * testcv
static struct semaphore * donesem
Define Documentation
#define NCVLOOPS 5
Definition at line 43 of file synchtest.c.
Referenced by cvtestthread().
#define NLOCKLOOPS 120
Definition at line 42 of file synchtest.c.
Referenced by locktestthread().
#define NSEMLOOPS 63
Definition at line 41 of file synchtest.c.
Referenced by semtestthread().
#define NTHREADS 32
Definition at line 44 of file synchtest.c.
Function Documentation
int cvtest (int nargs, char ** args)
Definition at line 275 of file synchtest.c.
References cvtestthread(), inititems(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), testval1, and thread_fork().
static void cvtestthread (void * junk, unsigned long num) [static]
Definition at line 225 of file synchtest.c.
References cv_broadcast(), cv_wait(), gettime(), kprintf(), lock_acquire(), lock_release(), NCVLOOPS, NTHREADS, testval1, thread_exit(), and V().
Referenced by cvtest().
static void fail (unsigned long num, const char * msg) [static]
Definition at line 141 of file synchtest.c.
References kprintf(), lock_release(), thread_exit(), and V().
Referenced by locktestthread(), and vfs_unmount().
static void inititems (void) [static]
Definition at line 56 of file synchtest.c.
References cv_create(), lock_create(), NULL, panic(), and sem_create().
Referenced by cvtest(), locktest(), and semtest().
int locktest (int nargs, char ** args)
Definition at line 196 of file synchtest.c.
References inititems(), kprintf(), locktestthread(), NTHREADS, NULL, P(), panic(), strerror(), and thread_fork().
static void locktestthread (void * junk, unsigned long num) [static]
Definition at line 154 of file synchtest.c.
References fail(), lock_acquire(), lock_release(), NLOCKLOOPS, testval1, testval2, testval3, and V().
Referenced by locktest().
int semtest (int nargs, char ** args)
Definition at line 104 of file synchtest.c.
References inititems(), kprintf(), NTHREADS, NULL, P(), panic(), semtestthread(), strerror(), thread_fork(), and V().
static void semtestthread (void * junk, unsigned long num) [static]
Definition at line 86 of file synchtest.c.
References kprintf(), NSEMLOOPS, P(), and V().
Referenced by semtest().
Variable Documentation
struct semaphore* donesem [static]
Definition at line 52 of file synchtest.c.
struct cv* testcv [static]
Definition at line 51 of file synchtest.c.
struct lock* testlock [static]
Definition at line 50 of file synchtest.c.
struct semaphore* testsem [static]
Definition at line 49 of file synchtest.c.
volatile unsigned long testval1 [static]
Definition at line 46 of file synchtest.c.
Referenced by cvtest(), cvtestthread(), and locktestthread().
volatile unsigned long testval2 [static]
Definition at line 47 of file synchtest.c.
Referenced by locktestthread().
volatile unsigned long testval3 [static]
Definition at line 48 of file synchtest.c.
Referenced by locktestthread().