Os/161: user/testbin/badcall/test.h File Reference
user/testbin/badcall/test.h File Reference
Defines
#define TESTFILE "badcallfile"
#define TESTDIR "badcalldir"
#define TESTLINK "badcalllink"
Functions
void report_survival (int rv, int error, const char *desc)
void report_test (int rv, int error, int right_error, const char *desc)
void report_test2 (int rv, int error, int okerr1, int okerr2, const char *desc)
int open_testfile (const char *str)
int create_testfile (void)
int create_testdir (void)
int create_testlink (void)
void test_read_buf (void)
void test_write_buf (void)
void test_getdirentry_buf (void)
void test_getcwd_buf (void)
void test_readlink_buf (void)
void test_read_fd (void)
void test_write_fd (void)
void test_close_fd (void)
void test_ioctl_fd (void)
void test_lseek_fd (void)
void test_fsync_fd (void)
void test_ftruncate_fd (void)
void test_fstat_fd (void)
void test_getdirentry_fd (void)
void test_dup2_fd (void)
void test_open_path (void)
void test_remove_path (void)
void test_rename_paths (void)
void test_link_paths (void)
void test_mkdir_path (void)
void test_rmdir_path (void)
void test_chdir_path (void)
void test_symlink_paths (void)
void test_readlink_path (void)
void test_stat_path (void)
void test_lstat_path (void)
void test_execv (void)
void test_waitpid (void)
void test_open (void)
void test_read (void)
void test_write (void)
void test_close (void)
void test_reboot (void)
void test_sbrk (void)
void test_ioctl (void)
void test_lseek (void)
void test_fsync (void)
void test_ftruncate (void)
void test_fstat (void)
void test_remove (void)
void test_rename (void)
void test_link (void)
void test_mkdir (void)
void test_rmdir (void)
void test_chdir (void)
void test_getdirentry (void)
void test_symlink (void)
void test_readlink (void)
void test_dup2 (void)
void test_pipe (void)
void test_time (void)
void test_getcwd (void)
void test_stat (void)
void test_lstat (void)
Define Documentation
#define TESTDIR "badcalldir"
Definition at line 31 of file test.h.
Referenced by cleanup(), create_testdir(), link_dir(), link_empty1(), link_empty2(), main(), remove_dir(), rename_dot(), rename_dotdot(), rename_empty1(), rename_empty2(), and setup().
#define TESTFILE "badcallfile"
Definition at line 30 of file test.h.
Referenced by common_badpath(), create_testfile(), ftruncate_size_neg(), link_badpath1(), link_badpath2(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), open_testfile(), read_cleanup(), readlink_file(), rename_badpath1(), rename_badpath2(), rmdir_file(), symlink_badpath1(), symlink_badpath2(), wait_siblings(), wait_siblings_child(), and write_cleanup().
#define TESTLINK "badcalllink"
Definition at line 32 of file test.h.
Referenced by create_testlink(), readlink_badbuf(), readlink_cleanup(), and symlink_empty1().
Function Documentation
int create_testdir (void)
Definition at line 157 of file driver.c.
References mkdir(), TESTDIR, and warn().
Referenced by link_empty2(), remove_dir(), and rename_empty2().
int create_testfile (void)
Definition at line 138 of file driver.c.
References close(), fd, NULL, open_testfile(), TESTFILE, and warn().
Referenced by common_badpath(), and rmdir_file().
int create_testlink (void)
Definition at line 169 of file driver.c.
References symlink(), TESTLINK, and warn().
Referenced by readlink_setup().
int open_testfile (const char * str)
Definition at line 100 of file driver.c.
References close(), fd, lseek(), O_CREAT, O_RDWR, O_TRUNC, open(), SEEK_SET, strlen(), TESTFILE, warn(), warnx(), and write().
Referenced by create_testfile(), ftruncate_size_neg(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), read_setup(), readlink_file(), wait_siblings(), and write_setup().
void report_survival (int rv, int error, const char * desc)
Definition at line 57 of file driver.c.
References errno, finderror(), and warn().
Referenced by pipe_unaligned(), wait_parent(), wait_self(), wait_siblings_child(), and wait_unaligned().
void report_test (int rv, int error, int right_error, const char * desc)
Definition at line 65 of file driver.c.
References ENOSYS, errno, EUNIMP, finderror(), warn(), and warnx().
Referenced by any_badfd(), common_badbuf(), common_badpath(), dup2_fd2(), exec_badargs(), exec_badprog(), exec_onearg(), ftruncate_fd_device(), ftruncate_size_neg(), ioctl_badcode(), link_dir(), link_empty1(), link_empty2(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_whence_inval(), mkdir_dot(), mkdir_dotdot(), mkdir_empty(), one_ioctl_badbuf(), open_badflags(), pipe_badptr(), readlink_dir(), readlink_file(), reboot_badflags(), remove_dir(), rename_dot(), rename_dotdot(), rmdir_dot(), rmdir_empty(), rmdir_file(), symlink_empty2(), time_badnsecs(), time_badsecs(), wait_badflags(), and wait_badstatus().
void report_test2 (int rv, int error, int okerr1, int okerr2, const char * desc)
Definition at line 82 of file driver.c.
References ENOSYS, errno, EUNIMP, finderror(), warn(), and warnx().
Referenced by any_empty(), chdir_empty(), exec_emptyprog(), open_empty(), readlink_empty(), remove_dot(), remove_dotdot(), remove_empty(), rename_empty1(), rename_empty2(), rmdir_dotdot(), symlink_empty1(), and wait_badpid().
void test_chdir (void)
Definition at line 55 of file bad_chdir.c.
References chdir_empty(), and test_chdir_path().
void test_chdir_path (void)
Referenced by test_chdir().
void test_close (void)
Definition at line 37 of file bad_close.c.
References test_close_fd().
void test_close_fd (void)
Referenced by test_close().
void test_dup2 (void)
Definition at line 111 of file bad_dup2.c.
References dup2_fd2(), dup2_self(), IMPOSSIBLE_FD, OPEN_MAX, test_dup2_fd(), and warnx().
void test_dup2_fd (void)
Referenced by test_dup2().
void test_execv (void)
Definition at line 143 of file bad_execv.c.
References exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), and NULL.
void test_fstat (void)
Definition at line 109 of file bad_stat.c.
References any_badbuf(), badbuf_fstat(), and test_fstat_fd().
void test_fstat_fd (void)
Referenced by test_fstat().
void test_fsync (void)
Definition at line 37 of file bad_fsync.c.
References test_fsync_fd().
void test_fsync_fd (void)
Referenced by test_fsync().
void test_ftruncate (void)
Definition at line 83 of file bad_ftruncate.c.
References ftruncate_fd_device(), ftruncate_size_neg(), and test_ftruncate_fd().
void test_ftruncate_fd (void)
Referenced by test_ftruncate().
void test_getcwd (void)
Definition at line 37 of file bad_getcwd.c.
References test_getcwd_buf().
void test_getcwd_buf (void)
Referenced by test_getcwd().
void test_getdirentry (void)
Definition at line 37 of file bad_getdirentry.c.
References test_getdirentry_buf(), and test_getdirentry_fd().
void test_getdirentry_buf (void)
Referenced by test_getdirentry().
void test_getdirentry_fd (void)
Referenced by test_getdirentry().
void test_ioctl (void)
Definition at line 95 of file bad_ioctl.c.
References ioctl_badbuf(), ioctl_badcode(), and test_ioctl_fd().
void test_ioctl_fd (void)
Referenced by test_ioctl().
void test_link (void)
Definition at line 75 of file bad_link.c.
References link_dir(), link_empty1(), link_empty2(), and test_link_paths().
void test_link_paths (void)
Referenced by test_link().
void test_lseek (void)
Definition at line 239 of file bad_lseek.c.
References lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), and test_lseek_fd().
void test_lseek_fd (void)
Referenced by test_lseek().
void test_lstat (void)
Definition at line 116 of file bad_stat.c.
References any_badbuf(), any_empty(), badbuf_lstat(), lstat(), and test_lstat_path().
void test_lstat_path (void)
Referenced by test_lstat().
void test_mkdir (void)
Definition at line 76 of file bad_mkdir.c.
References mkdir_dot(), mkdir_dotdot(), mkdir_empty(), and test_mkdir_path().
void test_mkdir_path (void)
Referenced by test_mkdir().
void test_open (void)
Definition at line 69 of file bad_open.c.
References open_badflags(), open_empty(), and test_open_path().
void test_open_path (void)
Referenced by test_open().
void test_pipe (void)
Definition at line 71 of file bad_pipe.c.
References NULL, pipe_badptr(), and pipe_unaligned().
void test_read (void)
Definition at line 37 of file bad_read.c.
References test_read_buf(), and test_read_fd().
void test_read_buf (void)
Referenced by test_read().
void test_read_fd (void)
Referenced by test_read().
void test_readlink (void)
Definition at line 77 of file bad_readlink.c.
References readlink_dir(), readlink_empty(), readlink_file(), test_readlink_buf(), and test_readlink_path().
void test_readlink_buf (void)
Referenced by test_readlink().
void test_readlink_path (void)
Referenced by test_readlink().
void test_reboot (void)
Definition at line 58 of file bad_reboot.c.
References reboot_badflags().
void test_remove (void)
Definition at line 89 of file bad_remove.c.
References remove_dir(), remove_dot(), remove_dotdot(), remove_empty(), and test_remove_path().
void test_remove_path (void)
Referenced by test_remove().
void test_rename (void)
Definition at line 92 of file bad_rename.c.
References rename_dot(), rename_dotdot(), rename_empty1(), rename_empty2(), and test_rename_paths().
void test_rename_paths (void)
Referenced by test_rename().
void test_rmdir (void)
Definition at line 89 of file bad_rmdir.c.
References rmdir_dot(), rmdir_dotdot(), rmdir_empty(), rmdir_file(), and test_rmdir_path().
void test_rmdir_path (void)
Referenced by test_rmdir().
void test_sbrk (void)
Definition at line 129 of file bad_sbrk.c.
References sbrk_bigneg(), sbrk_bigpos(), sbrk_neg(), sbrk_unalignedneg(), and sbrk_unalignedpos().
void test_stat (void)
Definition at line 124 of file bad_stat.c.
References any_badbuf(), any_empty(), badbuf_stat(), and test_stat_path().
void test_stat_path (void)
Referenced by test_stat().
void test_symlink (void)
Definition at line 59 of file bad_symlink.c.
References symlink_empty1(), symlink_empty2(), and test_symlink_paths().
void test_symlink_paths (void)
Referenced by test_symlink().
void test_time (void)
Definition at line 67 of file bad_time.c.
References time_badnsecs(), and time_badsecs().
void test_waitpid (void)
Definition at line 270 of file bad_waitpid.c.
References NONEXIST_PID, NULL, wait_badflags(), wait_badpid(), wait_badstatus(), wait_parent(), wait_self(), wait_siblings(), and wait_unaligned().
void test_write (void)
Definition at line 37 of file bad_write.c.
References test_write_buf(), and test_write_fd().
void test_write_buf (void)
Referenced by test_write().
void test_write_fd (void)
Referenced by test_write().