Os/161: user/bin/ls/ls.c File Reference
user/bin/ls/ls.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <err.h>
Functions
static void option (int ch)
static const char * basename (const char *path)
static int isdir (const char *path)
static void printheader (const char *file)
static void print (const char *path)
static void listdir (const char *path, int showheader)
static void recursedir (const char *path)
static void listitem (const char *path, int showheader)
int main (int argc, char *argv[])
Variables
static int aopt = 0
static int dopt = 0
static int lopt = 0
static int Ropt = 0
static int sopt = 0
Function Documentation
static const char* basename (const char * path) [static]
Definition at line 76 of file ls.c.
References strrchr().
Referenced by print().
static int isdir (const char * path) [static]
Definition at line 92 of file ls.c.
References close(), err(), fd, fstat(), O_RDONLY, open(), S_ISDIR, and stat::st_mode.
Referenced by emufs_creat(), emufs_lookup(), listitem(), and recursedir().
static void listdir (const char * path, int showheader) [static]
Definition at line 193 of file ls.c.
References aopt, close(), err(), fd, getdirentry(), O_RDONLY, open(), print(), printheader(), and snprintf().
Referenced by listitem(), and recursedir().
static void listitem (const char * path, int showheader) [static]
Definition at line 288 of file ls.c.
References dopt, isdir(), listdir(), print(), recursedir(), and Ropt.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 302 of file ls.c.
References listitem(), and option().
static void option (int ch) [static]
Definition at line 58 of file ls.c.
References aopt, dopt, errx(), lopt, Ropt, and sopt.
Referenced by main().
static void print (const char * path) [static]
Definition at line 135 of file ls.c.
References basename(), close(), err(), fd, fstat(), lopt, O_RDONLY, open(), printf(), S_ISBLK, S_ISCHR, S_ISDIR, S_ISLNK, S_ISREG, sopt, stat::st_blocks, stat::st_mode, stat::st_nlink, and stat::st_size.
Referenced by listdir(), and listitem().
static void printheader (const char * file) [static]
Definition at line 116 of file ls.c.
References printf().
Referenced by listdir().
static void recursedir (const char * path) [static]
Definition at line 236 of file ls.c.
References aopt, close(), err(), fd, getdirentry(), isdir(), listdir(), O_RDONLY, open(), Ropt, snprintf(), and strcmp().
Referenced by listitem().
Variable Documentation
int aopt = 0 [static]
Definition at line 49 of file ls.c.
Referenced by listdir(), option(), and recursedir().
int dopt = 0 [static]
Definition at line 50 of file ls.c.
Referenced by listitem(), and option().
int lopt = 0 [static]
Definition at line 51 of file ls.c.
Referenced by option(), and print().
int Ropt = 0 [static]
Definition at line 52 of file ls.c.
Referenced by listitem(), option(), and recursedir().
int sopt = 0 [static]
Definition at line 53 of file ls.c.
Referenced by option(), and print().