Os/161: kern/vfs/device.c File Reference
kern/vfs/device.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <stat.h>
#include <lib.h>
#include <uio.h>
#include <synch.h>
#include <vnode.h>
#include <device.h>
Functions
static int dev_open (struct vnode *v, int flags)
static int dev_close (struct vnode *v)
static int dev_reclaim (struct vnode *v)
static int dev_read (struct vnode *v, struct uio *uio)
static int null_io (struct vnode *v, struct uio *uio)
static int dev_write (struct vnode *v, struct uio *uio)
static int dev_ioctl (struct vnode *v, int op, userptr_t data)
static int dev_stat (struct vnode *v, struct stat *statbuf)
static int dev_gettype (struct vnode *v, mode_t *ret)
static int dev_tryseek (struct vnode *v, off_t pos)
static int null_fsync (struct vnode *v)
static int dev_mmap (struct vnode *v)
static int dev_truncate (struct vnode *v, off_t len)
static int dev_namefile (struct vnode *v, struct uio *uio)
static int null_creat (struct vnode *v, const char *name, bool excl, mode_t mode, struct vnode **result)
static int null_mkdir (struct vnode *v, const char *name, mode_t mode)
static int null_symlink (struct vnode *v, const char *contents, const char *name)
static int null_nameop (struct vnode *v, const char *name)
static int null_link (struct vnode *v, const char *name, struct vnode *file)
static int null_rename (struct vnode *v, const char *n1, struct vnode *v2, const char *n2)
static int dev_lookup (struct vnode *dir, char *pathname, struct vnode **result)
static int dev_lookparent (struct vnode *dir, char *pathname, struct vnode **result, char *namebuf, size_t buflen)
struct vnode * dev_create_vnode (struct device *dev)
Variables
static struct vnode_ops dev_vnode_ops
Function Documentation
static int dev_close (struct vnode * v) [static]
Definition at line 70 of file device.c.
References device::d_close, and vnode::vn_data.
struct vnode* dev_create_vnode (struct device * dev) [read]
Definition at line 448 of file device.c.
References kmalloc(), NULL, panic(), strerror(), and VOP_INIT.
Referenced by vfs_doadd().
static int dev_gettype (struct vnode * v, mode_t * ret) [static]
Definition at line 185 of file device.c.
References device::d_blocks, S_IFBLK, S_IFCHR, and vnode::vn_data.
static int dev_ioctl (struct vnode * v, int op, userptr_t data) [static]
Definition at line 131 of file device.c.
References device::d_ioctl, and vnode::vn_data.
static int dev_lookparent (struct vnode * dir, char * pathname, struct vnode ** result, char * namebuf, size_t buflen) [static]
Definition at line 396 of file device.c.
References ENOTDIR.
static int dev_lookup (struct vnode * dir, char * pathname, struct vnode ** result) [static]
Definition at line 378 of file device.c.
References ENOENT, strlen(), and VOP_INCREF.
static int dev_mmap (struct vnode * v) [static]
Definition at line 249 of file device.c.
References EUNIMP.
static int dev_namefile (struct vnode * v, struct uio * uio) [static]
Definition at line 282 of file device.c.
static int dev_open (struct vnode * v, int flags) [static]
Definition at line 53 of file device.c.
References device::d_open, EINVAL, O_APPEND, O_CREAT, O_EXCL, O_TRUNC, and vnode::vn_data.
static int dev_read (struct vnode * v, struct uio * uio) [static]
Definition at line 94 of file device.c.
References device::d_io, KASSERT, UIO_READ, uio::uio_rw, and vnode::vn_data.
static int dev_reclaim (struct vnode * v) [static]
Definition at line 82 of file device.c.
static int dev_stat (struct vnode * v, struct stat * statbuf) [static]
Definition at line 144 of file device.c.
References bzero(), device::d_blocks, device::d_blocksize, device::d_devnumber, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, vnode::vn_data, and VOP_GETTYPE.
static int dev_truncate (struct vnode * v, off_t len) [static]
Definition at line 260 of file device.c.
References device::d_blocks, device::d_blocksize, EINVAL, and vnode::vn_data.
static int dev_tryseek (struct vnode * v, off_t pos) [static]
Definition at line 204 of file device.c.
References device::d_blocks, device::d_blocksize, EINVAL, ESPIPE, and vnode::vn_data.
static int dev_write (struct vnode * v, struct uio * uio) [static]
Definition at line 119 of file device.c.
References device::d_io, KASSERT, uio::uio_rw, UIO_WRITE, and vnode::vn_data.
static int null_creat (struct vnode * v, const char * name, bool excl, mode_t mode, struct vnode ** result) [static]
Definition at line 302 of file device.c.
References ENOTDIR.
static int null_fsync (struct vnode * v) [static]
Definition at line 237 of file device.c.
static int null_io (struct vnode * v, struct uio * uio) [static]
Definition at line 107 of file device.c.
References EINVAL.
static int null_link (struct vnode * v, const char * name, struct vnode * file) [static]
Definition at line 344 of file device.c.
References ENOTDIR.
static int null_mkdir (struct vnode * v, const char * name, mode_t mode) [static]
Definition at line 315 of file device.c.
References ENOTDIR.
static int null_nameop (struct vnode * v, const char * name) [static]
Definition at line 335 of file device.c.
References ENOTDIR.
static int null_rename (struct vnode * v, const char * n1, struct vnode * v2, const char * n2) [static]
Definition at line 354 of file device.c.
References ENOTDIR.
static int null_symlink (struct vnode * v, const char * contents, const char * name) [static]
Definition at line 325 of file device.c.
References ENOTDIR.
Variable Documentation
struct vnode_ops dev_vnode_ops [static]
Initial value:
 {
        VOP_MAGIC,
        dev_open,
        dev_close,
        dev_reclaim,
        dev_read,
        null_io,
        null_io,
        dev_write,
        dev_ioctl,
        dev_stat,
        dev_gettype,
        dev_tryseek,
        null_fsync,
        dev_mmap,
        dev_truncate,
        dev_namefile,
        null_creat,
        null_symlink,
        null_mkdir,
        null_link,
        null_nameop,
        null_nameop,
        null_rename,
        dev_lookup,
        dev_lookparent,
}
Definition at line 415 of file device.c.