Os/161: kern/thread/threadlist.c File Reference
kern/thread/threadlist.c File Reference
#include <types.h>
#include <lib.h>
#include <thread.h>
#include <threadlist.h>
Functions
void threadlistnode_init (struct threadlistnode *tln, struct thread *t)
void threadlistnode_cleanup (struct threadlistnode *tln)
void threadlist_init (struct threadlist *tl)
void threadlist_cleanup (struct threadlist *tl)
bool threadlist_isempty (struct threadlist *tl)
static void threadlist_insertafternode (struct threadlistnode *onlist, struct thread *t)
static void threadlist_insertbeforenode (struct thread *t, struct threadlistnode *onlist)
static void threadlist_removenode (struct threadlistnode *tln)
void threadlist_addhead (struct threadlist *tl, struct thread *t)
void threadlist_addtail (struct threadlist *tl, struct thread *t)
struct thread * threadlist_remhead (struct threadlist *tl)
struct thread * threadlist_remtail (struct threadlist *tl)
void threadlist_insertafter (struct threadlist *tl, struct thread *onlist, struct thread *addee)
void threadlist_insertbefore (struct threadlist *tl, struct thread *addee, struct thread *onlist)
void threadlist_remove (struct threadlist *tl, struct thread *t)
Function Documentation
void threadlist_addhead (struct threadlist * tl, struct thread * t)
Definition at line 163 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_insertafternode(), threadlist::tl_count, and threadlist::tl_head.
Referenced by thread_consider_migration().
void threadlist_addtail (struct threadlist * tl, struct thread * t)
Definition at line 173 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_insertbeforenode(), threadlist::tl_count, and threadlist::tl_tail.
Referenced by thread_consider_migration(), thread_make_runnable(), thread_switch(), and wchan_wakeall().
void threadlist_cleanup (struct threadlist * tl)
Definition at line 75 of file threadlist.c.
References DEBUGASSERT, KASSERT, NULL, threadlist_isempty(), threadlist::tl_count, threadlist::tl_head, threadlist::tl_tail, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by thread_consider_migration(), wchan_destroy(), and wchan_wakeall().
void threadlist_init (struct threadlist * tl)
Definition at line 61 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist::tl_count, threadlist::tl_head, threadlist::tl_tail, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by cpu_create(), thread_consider_migration(), wchan_create(), and wchan_wakeall().
void threadlist_insertafter (struct threadlist * tl, struct thread * onlist, struct thread * addee)
Definition at line 219 of file threadlist.c.
References thread::t_listnode, threadlist_insertafternode(), and threadlist::tl_count.
static void threadlist_insertafternode (struct threadlistnode * onlist, struct thread * t) [static]
Definition at line 107 of file threadlist.c.
References DEBUGASSERT, NULL, thread::t_listnode, threadlistnode::tln_next, and threadlistnode::tln_prev.
Referenced by threadlist_addhead(), and threadlist_insertafter().
void threadlist_insertbefore (struct threadlist * tl, struct thread * addee, struct thread * onlist)
Definition at line 227 of file threadlist.c.
References thread::t_listnode, threadlist_insertbeforenode(), and threadlist::tl_count.
static void threadlist_insertbeforenode (struct thread * t, struct threadlistnode * onlist) [static]
Definition at line 127 of file threadlist.c.
References DEBUGASSERT, NULL, thread::t_listnode, threadlistnode::tln_next, and threadlistnode::tln_prev.
Referenced by threadlist_addtail(), and threadlist_insertbefore().
bool threadlist_isempty (struct threadlist * tl)
Definition at line 92 of file threadlist.c.
References DEBUGASSERT, NULL, and threadlist::tl_count.
Referenced by thread_consider_migration(), thread_switch(), threadlist_cleanup(), and wchan_isempty().
struct thread* threadlist_remhead (struct threadlist * tl) [read]
Definition at line 183 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_removenode(), threadlist::tl_count, threadlist::tl_head, threadlistnode::tln_next, and threadlistnode::tln_self.
Referenced by exorcise(), thread_consider_migration(), thread_switch(), wchan_wakeall(), and wchan_wakeone().
void threadlist_remove (struct threadlist * tl, struct thread * t)
Definition at line 235 of file threadlist.c.
References DEBUGASSERT, thread::t_listnode, threadlist_removenode(), and threadlist::tl_count.
static void threadlist_removenode (struct threadlistnode * tln) [static]
Definition at line 147 of file threadlist.c.
References DEBUGASSERT, NULL, threadlistnode::tln_next, and threadlistnode::tln_prev.
Referenced by threadlist_remhead(), threadlist_remove(), and threadlist_remtail().
struct thread* threadlist_remtail (struct threadlist * tl) [read]
Definition at line 201 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_removenode(), threadlist::tl_count, threadlist::tl_tail, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by thread_consider_migration().
void threadlistnode_cleanup (struct threadlistnode * tln)
Definition at line 51 of file threadlist.c.
References DEBUGASSERT, KASSERT, NULL, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by thread_destroy().
void threadlistnode_init (struct threadlistnode * tln, struct thread * t)
Definition at line 40 of file threadlist.c.
References DEBUGASSERT, KASSERT, NULL, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by thread_create().