Os/161: kern/thread/thread.c File Reference
kern/thread/thread.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
#include <cpu.h>
#include <spl.h>
#include <spinlock.h>
#include <wchan.h>
#include <syscall.h>
#include <thread.h>
#include <threadlist.h>
#include <threadprivate.h>
#include <current.h>
#include <synch.h>
#include <addrspace.h>
#include <mainbus.h>
#include <vnode.h>
#include "opt-synchprobs.h"
Data Structures
struct wchan
Defines
#define THREAD_STACK_MAGIC 0xbaadf00d
Functions
DECLARRAY (cpu)
DEFARRAY (cpu,)
static void thread_checkstack_init (struct thread *thread)
static void thread_checkstack (struct thread *thread)
static struct thread * thread_create (const char *name)
struct cpu * cpu_create (unsigned hardware_number)
static void thread_destroy (struct thread *thread)
static void exorcise (void)
void thread_panic (void)
void thread_shutdown (void)
void thread_bootstrap (void)
void cpu_hatch (unsigned software_number)
void thread_start_cpus (void)
static void thread_make_runnable (struct thread *target, bool already_have_lock)
int thread_fork (const char *name, void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2, struct thread **ret)
static void thread_switch (threadstate_t newstate, struct wchan *wc)
void thread_startup (void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
void thread_exit (void)
void thread_yield (void)
void schedule (void)
void thread_consider_migration (void)
struct wchan * wchan_create (const char *name)
void wchan_destroy (struct wchan *wc)
void wchan_lock (struct wchan *wc)
void wchan_unlock (struct wchan *wc)
void wchan_sleep (struct wchan *wc)
void wchan_wakeone (struct wchan *wc)
void wchan_wakeall (struct wchan *wc)
bool wchan_isempty (struct wchan *wc)
void ipi_send (struct cpu *target, int code)
void ipi_broadcast (int code)
void ipi_tlbshootdown (struct cpu *target, const struct tlbshootdown *mapping)
void interprocessor_interrupt (void)
pid_t thread_fork2 (struct trapframe *tf, int *retval)
int find_nextpid (void)
Variables
char pid_used [MAX_THREAD]
static int pid_index
struct thread * thread_table [MAX_THREAD]
static struct cpuarray allcpus
static struct semaphore * cpu_startup_sem
Define Documentation
#define THREAD_STACK_MAGIC 0xbaadf00d
Definition at line 55 of file thread.c.
Referenced by thread_checkstack(), and thread_checkstack_init().
Function Documentation
struct cpu* cpu_create (unsigned hardware_number) [read]
Definition at line 190 of file thread.c.
References allcpus, cpu::c_curthread, cpu::c_hardclocks, cpu::c_hardware_number, cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_isidle, cpu::c_number, cpu::c_numshootdown, cpu::c_runqueue, cpu::c_runqueue_lock, cpu::c_self, cpu::c_zombies, cpu_machdep_init(), kmalloc(), NULL, panic(), snprintf(), spinlock_init(), STACK_SIZE, strerror(), thread::t_cpu, thread::t_stack, thread_checkstack_init(), thread_create(), and threadlist_init().
Referenced by lamebus_find_cpus(), and thread_bootstrap().
void cpu_hatch (unsigned software_number)
Definition at line 434 of file thread.c.
References cpu_identify(), curcpu, KASSERT, kprintf(), NULL, spl0(), thread_exit(), and V().
DECLARRAY (cpu)
DEFARRAY (cpu)
static void exorcise (void) [static]
Definition at line 298 of file thread.c.
References curcpu, KASSERT, NULL, S_ZOMBIE, thread::t_state, thread_destroy(), and threadlist_remhead().
int find_nextpid (void)
Definition at line 1415 of file thread.c.
References MAX_THREAD, pid_index, and pid_used.
Referenced by thread_fork(), and thread_fork2().
void interprocessor_interrupt (void)
Definition at line 1251 of file thread.c.
References cpu_halt(), curcpu, IPI_OFFLINE, IPI_PANIC, IPI_TLBSHOOTDOWN, IPI_UNIDLE, kprintf(), spinlock_acquire(), spinlock_release(), TLBSHOOTDOWN_ALL, vm_tlbshootdown(), and vm_tlbshootdown_all().
Referenced by mainbus_interrupt().
void ipi_broadcast (int code)
Definition at line 1215 of file thread.c.
References allcpus, curcpu, and ipi_send().
Referenced by thread_panic(), and thread_shutdown().
void ipi_send (struct cpu * target, int code)
Definition at line 1204 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, KASSERT, mainbus_send_ipi(), spinlock_acquire(), and spinlock_release().
Referenced by ipi_broadcast(), thread_consider_migration(), and thread_make_runnable().
void ipi_tlbshootdown (struct cpu * target, const struct tlbshootdown * mapping)
Definition at line 1229 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_numshootdown, cpu::c_shootdown, IPI_TLBSHOOTDOWN, mainbus_send_ipi(), spinlock_acquire(), spinlock_release(), TLBSHOOTDOWN_ALL, and TLBSHOOTDOWN_MAX.
void schedule (void)
Definition at line 915 of file thread.c.
Referenced by hardclock().
void thread_bootstrap (void)
Definition at line 372 of file thread.c.
References allcpus, cpu::c_curthread, cpu_create(), curcpu, INIT_CURCPU, MAX_THREAD, NULL, thread::parent_id, pid_index, pid_used, and thread::thread_id.
Referenced by boot().
static void thread_checkstack (struct thread * thread) [static]
Definition at line 110 of file thread.c.
References KASSERT, NULL, thread::t_stack, and THREAD_STACK_MAGIC.
Referenced by thread_exit(), and thread_switch().
static void thread_checkstack_init (struct thread * thread) [static]
Definition at line 90 of file thread.c.
References thread::t_stack, and THREAD_STACK_MAGIC.
Referenced by cpu_create(), thread_fork(), and thread_fork2().
void thread_consider_migration (void)
Definition at line 941 of file thread.c.
References allcpus, cpu::c_isidle, cpu::c_number, cpu::c_runqueue, cpu::c_runqueue_lock, curcpu, DB_THREADS, DEBUG, DIVROUNDUP, ipi_send(), IPI_UNIDLE, KASSERT, NULL, spinlock_acquire(), spinlock_release(), thread::t_cpu, thread::t_name, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_isempty(), threadlist_remhead(), threadlist_remtail(), and threadlist::tl_count.
Referenced by hardclock().
static struct thread* thread_create (const char * name) [static, read]
Definition at line 126 of file thread.c.
References con_attached, DEBUGASSERT, thread::exit_code, init_file_table(), IPL_HIGH, kfree(), kmalloc(), kstrdup(), NULL, thread::parent_id, S_READY, set_std_fd(), thread::t_addrspace, thread::t_context, thread::t_cpu, thread::t_curspl, thread::t_cwd, thread::t_in_interrupt, thread::t_iplhigh_count, thread::t_listnode, thread::t_machdep, thread::t_name, thread::t_stack, thread::t_state, thread::t_wchan_name, thread::thread_id, thread_machdep_init(), and threadlistnode_init().
Referenced by cpu_create(), thread_fork(), and thread_fork2().
static void thread_destroy (struct thread * thread) [static]
Definition at line 260 of file thread.c.
References KASSERT, kfree(), NULL, S_RUN, thread::t_addrspace, thread::t_cwd, thread::t_listnode, thread::t_machdep, thread::t_name, thread::t_stack, thread::t_state, thread::t_wchan_name, thread_machdep_cleanup(), and threadlistnode_cleanup().
Referenced by exorcise(), and thread_fork().
void thread_exit (void)
Definition at line 852 of file thread.c.
References as_activate(), as_destroy(), kfree(), thread::last_fd, MAX_FD, NULL, panic(), S_ZOMBIE, splhigh(), thread::t_addrspace, thread::t_cwd, thread::table_fd, thread_checkstack(), thread_switch(), and VOP_DECREF.
Referenced by _exit(), cmd_quit(), cpu_hatch(), cvtestthread(), fail(), and thread_startup().
int thread_fork (const char * name, void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2, struct thread ** ret)
Definition at line 518 of file thread.c.
References EAGAIN, ENOMEM, find_nextpid(), kfree(), kmalloc(), NULL, thread::parent_id, pid_index, pid_used, STACK_SIZE, switchframe_init(), thread::t_cpu, thread::t_cwd, thread::t_iplhigh_count, thread::t_name, thread::t_stack, thread_checkstack_init(), thread_create(), thread_destroy(), thread::thread_id, thread_make_runnable(), VOP_DECREF, and VOP_INCREF.
pid_t thread_fork2 (struct trapframe * tf, int * retval)
Definition at line 1298 of file thread.c.
References as_copy(), EMPROC, ENOMEM, enter_forked_process(), errno, find_nextpid(), kfree(), kmalloc(), thread::last_fd, MAX_FD, memmove(), NULL, thread::parent_id, pid_index, pid_used, splhigh(), splx(), STACK_SIZE, switchframe_init(), thread::t_addrspace, thread::t_cpu, thread::t_cwd, thread::t_iplhigh_count, thread::t_name, thread::t_stack, thread::table_fd, thread_checkstack_init(), thread_create(), thread::thread_id, thread_make_runnable(), VOP_DECREF, and VOP_INCREF.
Referenced by sys_fork().
static void thread_make_runnable (struct thread * target, bool already_have_lock) [static]
Definition at line 475 of file thread.c.
References cpu::c_isidle, cpu::c_runqueue, cpu::c_runqueue_lock, ipi_send(), IPI_UNIDLE, KASSERT, spinlock_acquire(), spinlock_do_i_hold(), spinlock_release(), thread::t_cpu, and threadlist_addtail().
Referenced by thread_fork(), thread_fork2(), thread_switch(), wchan_wakeall(), and wchan_wakeone().
void thread_panic (void)
Definition at line 315 of file thread.c.
References curcpu, ipi_broadcast(), IPI_PANIC, and NULL.
Referenced by panic().
void thread_shutdown (void)
Definition at line 357 of file thread.c.
References ipi_broadcast(), and IPI_OFFLINE.
Referenced by shutdown().
void thread_start_cpus (void)
Definition at line 452 of file thread.c.
References allcpus, cpu_identify(), kprintf(), mainbus_start_cpus(), NULL, P(), sem_create(), and sem_destroy().
Referenced by boot().
void thread_startup (void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 799 of file thread.c.
References as_activate(), curcpu, exorcise(), NULL, random(), S_RUN, spinlock_release(), spl0(), thread::t_addrspace, thread::t_state, thread::t_wchan_name, thread_exit(), and thread_yield().
static void thread_switch (threadstate_t newstate, struct wchan * wc) [static]
Definition at line 615 of file thread.c.
References as_activate(), cpu_idle(), curcpu, DEBUGASSERT, exorcise(), NULL, panic(), S_READY, S_RUN, S_SLEEP, S_ZOMBIE, spinlock_acquire(), spinlock_release(), splhigh(), splx(), switchframe_switch(), thread::t_addrspace, thread::t_context, thread::t_state, thread::t_wchan_name, thread_checkstack(), thread_make_runnable(), threadlist_addtail(), threadlist_isempty(), threadlist_remhead(), wchan::wc_name, wchan::wc_threads, and wchan_unlock().
Referenced by thread_exit(), thread_yield(), and wchan_sleep().
void thread_yield (void)
Definition at line 900 of file thread.c.
References NULL, S_READY, and thread_switch().
Referenced by compute_thread(), hardclock(), thread_startup(), and waker_thread().
struct wchan* wchan_create (const char * name) [read]
Definition at line 1060 of file thread.c.
References kmalloc(), NULL, spinlock_init(), threadlist_init(), wchan::wc_lock, wchan::wc_name, and wchan::wc_threads.
Referenced by hardclock_bootstrap(), sem_create(), and setup().
void wchan_destroy (struct wchan * wc)
Definition at line 1079 of file thread.c.
References kfree(), spinlock_cleanup(), threadlist_cleanup(), wchan::wc_lock, and wchan::wc_threads.
Referenced by sem_destroy().
bool wchan_isempty (struct wchan * wc)
Definition at line 1183 of file thread.c.
References spinlock_acquire(), spinlock_release(), threadlist_isempty(), wchan::wc_lock, and wchan::wc_threads.
void wchan_lock (struct wchan * wc)
Definition at line 1090 of file thread.c.
References spinlock_acquire(), and wchan::wc_lock.
Referenced by clocksleep(), P(), and sleepalot_thread().
void wchan_sleep (struct wchan * wc)
Definition at line 1108 of file thread.c.
References KASSERT, S_SLEEP, and thread_switch().
Referenced by clocksleep(), P(), and sleepalot_thread().
void wchan_unlock (struct wchan * wc)
Definition at line 1096 of file thread.c.
References spinlock_release(), and wchan::wc_lock.
Referenced by thread_switch().
void wchan_wakeall (struct wchan * wc)
Definition at line 1145 of file thread.c.
References NULL, spinlock_acquire(), spinlock_release(), thread_make_runnable(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_remhead(), wchan::wc_lock, and wchan::wc_threads.
Referenced by timerclock(), and waker_thread().
void wchan_wakeone (struct wchan * wc)
Definition at line 1120 of file thread.c.
References NULL, spinlock_acquire(), spinlock_release(), thread_make_runnable(), threadlist_remhead(), wchan::wc_lock, and wchan::wc_threads.
Referenced by V().
Variable Documentation
struct cpuarray allcpus [static]
Definition at line 76 of file thread.c.
Referenced by cpu_create(), ipi_broadcast(), thread_bootstrap(), thread_consider_migration(), and thread_start_cpus().
struct semaphore* cpu_startup_sem [static]
Definition at line 79 of file thread.c.
int pid_index [static]
Definition at line 61 of file thread.c.
Referenced by find_nextpid(), thread_bootstrap(), thread_fork(), and thread_fork2().
char pid_used[MAX_THREAD]
Definition at line 58 of file thread.c.
Referenced by _exit(), find_nextpid(), thread_bootstrap(), thread_fork(), thread_fork2(), and waitpid().
struct thread* thread_table[MAX_THREAD]
Definition at line 64 of file thread.c.