Os/161: kern/syscall/waitpid_syscall.c File Reference
kern/syscall/waitpid_syscall.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <spinlock.h>
#include <wchan.h>
#include <threadlist.h>
#include <threadprivate.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <vm.h>
#include <mainbus.h>
#include <vfs.h>
#include <device.h>
#include <syscall.h>
#include <kern/fcntl.h>
Functions
pid_t waitpid (pid_t pid, int *status, int options, int *retval)
Variables
char pid_used [MAX_THREAD]
struct thread * thread_table [MAX_THREAD]
Function Documentation
pid_t waitpid (pid_t pid, int * status, int options, int * retval)
Definition at line 40 of file waitpid_syscall.c.
References clocksleep(), EFAULT, EINVAL, ESRCH, thread::exit_code, MAX_THREAD, NULL, pid_used, splhigh(), and splx().
Variable Documentation
char pid_used[MAX_THREAD]
Definition at line 58 of file thread.c.
struct thread* thread_table[MAX_THREAD]
Definition at line 64 of file thread.c.