Os/161: kern/startup/main.c File Reference
kern/startup/main.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <vm.h>
#include <mainbus.h>
#include <vfs.h>
#include <device.h>
#include <syscall.h>
#include <test.h>
#include <version.h>
#include <kern/file.h>
#include "autoconf.h"
Functions
void hello (void)
static void boot (void)
static void shutdown (void)
int sys_reboot (int code)
void kmain (char *arguments)
Variables
const int buildversion
const char buildconfig []
bool con_attached
static const char harvard_copyright []
Function Documentation
static void boot (void) [static]
Definition at line 81 of file main.c.
References BASE_VERSION, buildconfig, buildversion, COMPILE_ASSERT, con_attached, GROUP_VERSION, hardclock_bootstrap(), harvard_copyright, hello(), KASSERT, kprintf(), kprintf_bootstrap(), mainbus_bootstrap(), pseudoconfig(), ram_bootstrap(), thread_bootstrap(), thread_start_cpus(), vfs_bootstrap(), vfs_setbootfs(), and vm_bootstrap().
Referenced by kmain().
void hello (void)
Definition at line 33 of file hello.c.
References kprintf().
Referenced by boot().
void kmain (char * arguments)
Definition at line 212 of file main.c.
References boot(), and menu().
static void shutdown (void) [static]
Definition at line 151 of file main.c.
References kprintf(), splhigh(), thread_shutdown(), vfs_clearbootfs(), vfs_clearcurdir(), and vfs_unmountall().
Referenced by sys_reboot().
int sys_reboot (int code)
Definition at line 175 of file main.c.
References EINVAL, kprintf(), mainbus_halt(), mainbus_poweroff(), mainbus_reboot(), panic(), RB_HALT, RB_POWEROFF, RB_REBOOT, and shutdown().
Referenced by cmd_quit(), and syscall().
Variable Documentation
const char buildconfig[]
Definition at line 3 of file vers.c.
Referenced by boot().
const int buildversion
Definition at line 2 of file vers.c.
Referenced by boot().
bool con_attached
Definition at line 18 of file file.h.
Referenced by boot(), and thread_create().
const char harvard_copyright[] [static]
Initial value:
    "Copyright (c) 2000, 2001, 2002, 2003, 2004, 2005, 2008, 2009\n"
    "   President and Fellows of Harvard College.  All rights reserved.\n"
Definition at line 71 of file main.c.
Referenced by boot().