Os/161: user/testbin/threadtest/threadtest.c File Reference
user/testbin/threadtest/threadtest.c File Reference
#include <unistd.h>
#include <sys/types.h>
#include <err.h>
#include <stdio.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <string.h>
Functions
int main ()
Function Documentation
int main (void)
Definition at line 22 of file threadtest.c.
References exit(), fork(), getpid(), printf(), and waitpid().