Os/161: kern/startup/menu.c File Reference
kern/startup/menu.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <limits.h>
#include <lib.h>
#include <uio.h>
#include <clock.h>
#include <thread.h>
#include <vfs.h>
#include <sfs.h>
#include <syscall.h>
#include <test.h>
#include "opt-synchprobs.h"
#include "opt-sfs.h"
#include "opt-net.h"
Defines
#define _PATH_SHELL "/bin/sh"
#define MAXMENUARGS 16
Functions
void getinterval (time_t s1, uint32_t ns1, time_t s2, uint32_t ns2, time_t *rs, uint32_t *rns)
static void cmd_progthread (void *ptr, unsigned long nargs)
static int common_prog (int nargs, char **args)
static int cmd_prog (int nargs, char **args)
static int cmd_shell (int nargs, char **args)
static int cmd_chdir (int nargs, char **args)
static int cmd_pwd (int nargs, char **args)
static int cmd_sync (int nargs, char **args)
static int cmd_panic (int nargs, char **args)
static int cmd_quit (int nargs, char **args)
static int cmd_mount (int nargs, char **args)
static int cmd_unmount (int nargs, char **args)
static int cmd_bootfs (int nargs, char **args)
static int cmd_kheapstats (int nargs, char **args)
static void showmenu (const char *name, const char *x[])
static int cmd_opsmenu (int n, char **a)
static int cmd_testmenu (int n, char **a)
static int cmd_mainmenu (int n, char **a)
static int cmd_dispatch (char *cmd)
static void menu_execute (char *line, int isargs)
void menu (char *args)
Variables
struct {
const char * name
int(* func)(const char *device)
} mounttable []
static const char * opsmenu []
static const char * testmenu []
static const char * mainmenu []
struct {
const char * name
int(* func)(int nargs, char **args)
} cmdtable []
Define Documentation
#define _PATH_SHELL "/bin/sh"
Definition at line 51 of file menu.c.
Referenced by cmd_shell().
#define MAXMENUARGS 16
Definition at line 53 of file menu.c.
Referenced by cmd_dispatch().
Function Documentation
static int cmd_bootfs (int nargs, char ** args) [static]
Definition at line 355 of file menu.c.
References EINVAL, kprintf(), strlen(), and vfs_setbootfs().
static int cmd_chdir (int nargs, char ** args) [static]
Definition at line 193 of file menu.c.
References EINVAL, kprintf(), and vfs_chdir().
static int cmd_dispatch (char * cmd) [static]
Definition at line 580 of file menu.c.
References cmdtable, E2BIG, EINVAL, getinterval(), gettime(), KASSERT, kprintf(), MAXMENUARGS, name, NULL, strcmp(), and strtok_r().
Referenced by menu_execute().
static int cmd_kheapstats (int nargs, char ** args) [static]
Definition at line 376 of file menu.c.
References kheap_printstats().
static int cmd_mainmenu (int n, char ** a) [static]
Definition at line 497 of file menu.c.
References mainmenu, and showmenu().
static int cmd_mount (int nargs, char ** args) [static]
Definition at line 296 of file menu.c.
References EINVAL, kprintf(), mounttable, name, strcmp(), and strlen().
static int cmd_opsmenu (int n, char ** a) [static]
Definition at line 432 of file menu.c.
References opsmenu, and showmenu().
static int cmd_panic (int nargs, char ** args) [static]
Definition at line 254 of file menu.c.
References panic().
static int cmd_prog (int nargs, char ** args) [static]
Definition at line 155 of file menu.c.
References common_prog(), EINVAL, and kprintf().
static void cmd_progthread (void * ptr, unsigned long nargs) [static]
Definition at line 86 of file menu.c.
References KASSERT, kprintf(), progname, runprogram(), strcpy(), strerror(), and strlen().
Referenced by common_prog().
static int cmd_pwd (int nargs, char ** args) [static]
Definition at line 208 of file menu.c.
References kprintf(), PATH_MAX, strerror(), uio_kinit(), UIO_READ, uio::uio_resid, and vfs_getcwd().
static int cmd_quit (int nargs, char ** args) [static]
Definition at line 268 of file menu.c.
References RB_POWEROFF, sys_reboot(), thread_exit(), and vfs_sync().
static int cmd_shell (int nargs, char ** args) [static]
Definition at line 175 of file menu.c.
References _PATH_SHELL, common_prog(), EINVAL, and kprintf().
static int cmd_sync (int nargs, char ** args) [static]
Definition at line 239 of file menu.c.
References vfs_sync().
static int cmd_testmenu (int n, char ** a) [static]
Definition at line 465 of file menu.c.
References kprintf(), showmenu(), and testmenu.
static int cmd_unmount (int nargs, char ** args) [static]
Definition at line 326 of file menu.c.
References EINVAL, kprintf(), strlen(), and vfs_unmount().
static int common_prog (int nargs, char ** args) [static]
Definition at line 129 of file menu.c.
References cmd_progthread(), kprintf(), NULL, strerror(), and thread_fork().
Referenced by cmd_prog(), and cmd_shell().
void getinterval (time_t s1, uint32_t ns1, time_t s2, uint32_t ns2, time_t * rs, uint32_t * rns)
Definition at line 57 of file menu.c.
Referenced by cmd_dispatch().
void menu (char * args)
Definition at line 681 of file menu.c.
References kgets(), kprintf(), and menu_execute().
Referenced by kmain(), main(), and runit().
static void menu_execute (char * line, int isargs) [static]
Definition at line 639 of file menu.c.
References cmd_dispatch(), kprintf(), NULL, panic(), strerror(), and strtok_r().
Referenced by menu().
static void showmenu (const char * name, const char * x[]) [static]
Definition at line 392 of file menu.c.
References kprintf().
Referenced by cmd_mainmenu(), cmd_opsmenu(), and cmd_testmenu().
Variable Documentation
struct { ... } cmdtable[] [static]
Referenced by cmd_dispatch().
int(* func)(int nargs, char **args) (const char * device)
const char* mainmenu[] [static]
Initial value:
 {
        "[?o] Operations menu                ",
        "[?t] Tests menu                     ",
        "[kh] Kernel heap stats              ",
        "[q] Quit and shut down              ",
        NULL
}
Definition at line 480 of file menu.c.
Referenced by cmd_mainmenu().
struct { ... } mounttable[] [static]
Referenced by cmd_mount().
const char* name
Definition at line 285 of file menu.c.
Referenced by bin(), cleanup(), cmd_dispatch(), cmd_mount(), config_emu(), config_lhd(), docommand(), doreadateof(), doreadone(), dovalidate(), dowritestress2(), fstest_read(), fstest_remove(), fstest_write(), main(), make_computes(), make_sleepalots(), menu(), mergebins(), mkdir_proc(), readit(), rmdir_proc(), runit(), runthreads(), setup(), sortbins(), validate(), vfs_doadd(), vfs_getcwd(), vfs_mkdir(), vfs_open(), vfs_remove(), and vfs_rmdir().
const char* opsmenu[] [static]
Initial value:
 {
        "[s]       Shell                     ",
        "[p]       Other program             ",
        "[mount]   Mount a filesystem        ",
        "[unmount] Unmount a filesystem      ",
        "[bootfs]  Set \"boot\" filesystem     ",
        "[pf]      Print a file              ",
        "[cd]      Change directory          ",
        "[pwd]     Print current directory   ",
        "[sync]    Sync filesystems          ",
        "[panic]   Intentional panic         ",
        "[q]       Quit and shut down        ",
        NULL
}
Definition at line 415 of file menu.c.
Referenced by cmd_opsmenu().
const char* testmenu[] [static]
Initial value:
 {
        "[at]  Array test                    ",
        "[bt]  Bitmap test                   ",
        "[km1] Kernel malloc test            ",
        "[km2] kmalloc stress test           ",
        "[tt1] Thread test 1                 ",
        "[tt2] Thread test 2                 ",
        "[tt3] Thread test 3                 ",
        "[sy1] Semaphore test                ",
        "[sy2] Lock test             (1)     ",
        "[sy3] CV test               (1)     ",
        "[fs1] Filesystem test               ",
        "[fs2] FS read stress        (4)     ",
        "[fs3] FS write stress       (4)     ",
        "[fs4] FS write stress 2     (4)     ",
        "[fs5] FS create stress      (4)     ",
        NULL
}
Definition at line 441 of file menu.c.
Referenced by cmd_testmenu().