Os/161: kern/syscall/file.c File Reference
kern/syscall/file.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <vm.h>
#include <mainbus.h>
#include <vfs.h>
#include <device.h>
#include <syscall.h>
#include <kern/fcntl.h>
#include <kern/file.h>
#include <uio.h>
Functions
void init_file_table (struct thread *thread)
void set_std_fd (struct thread *thread)
Function Documentation
void init_file_table (struct thread * thread)
Definition at line 30 of file file.c.
References MAX_FD, NULL, and thread::table_fd.
Referenced by thread_create().
void set_std_fd (struct thread * thread)
Definition at line 41 of file file.c.
References KASSERT, kfree(), kmalloc(), kstrdup(), thread::last_fd, NULL, O_RDONLY, O_RDWR, O_WRONLY, file::offset, panic(), file::readable, STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, strerror(), thread::table_fd, file::vfs_node, vfs_open(), and file::writeable.
Referenced by thread_create().