Os/161: kern/include/mainbus.h File Reference
kern/include/mainbus.h File Reference
Functions
void mainbus_bootstrap (void)
void mainbus_start_cpus (void)
void mainbus_interrupt (struct trapframe *)
size_t mainbus_ramsize (void)
void mainbus_send_ipi (struct cpu *target)
void mainbus_halt (void)
void mainbus_poweroff (void)
void mainbus_reboot (void)
void mainbus_panic (void)
Function Documentation
void mainbus_bootstrap (void)
Definition at line 84 of file lamebus_machdep.c.
References autoconf_lamebus(), CPU_FREQUENCY, HZ, KASSERT, kprintf(), lamebus_find_cpus(), lamebus_init(), mips_timer_set(), and spl0().
Referenced by boot().
void mainbus_halt (void)
Definition at line 208 of file lamebus_machdep.c.
References cpu_halt().
Referenced by sys_reboot().
void mainbus_interrupt (struct trapframe *)
Definition at line 255 of file lamebus_machdep.c.
References CPU_FREQUENCY, curcpu, hardclock(), HZ, interprocessor_interrupt(), KASSERT, lamebus_clear_ipi(), lamebus_interrupt(), LAMEBUS_IPI_BIT, LAMEBUS_IRQ_BIT, MIPS_TIMER_BIT, mips_timer_set(), panic(), and trapframe::tf_cause.
Referenced by mips_trap().
void mainbus_panic (void)
Definition at line 221 of file lamebus_machdep.c.
References mainbus_poweroff().
Referenced by panic().
void mainbus_poweroff (void)
Definition at line 174 of file lamebus_machdep.c.
References lamebus_poweroff().
Referenced by mainbus_panic(), mainbus_reboot(), and sys_reboot().
size_t mainbus_ramsize (void)
Definition at line 231 of file lamebus_machdep.c.
References lamebus_ramsize().
Referenced by ram_bootstrap().
void mainbus_reboot (void)
Definition at line 189 of file lamebus_machdep.c.
References kprintf(), and mainbus_poweroff().
Referenced by sys_reboot().
void mainbus_send_ipi (struct cpu * target)
Definition at line 240 of file lamebus_machdep.c.
References lamebus_assert_ipi().
Referenced by ipi_send(), and ipi_tlbshootdown().
void mainbus_start_cpus (void)
Definition at line 123 of file lamebus_machdep.c.
References lamebus_start_cpus().
Referenced by thread_start_cpus().