Os/161: kern/test/arraytest.c File Reference
kern/test/arraytest.c File Reference
#include <types.h>
#include <lib.h>
#include <array.h>
#include <test.h>
Defines
#define TESTSIZE 73
Functions
static void testa (struct array *a)
int arraytest (int nargs, char **args)
Define Documentation
#define TESTSIZE 73
Definition at line 35 of file arraytest.c.
Referenced by bitmaptest(), and testa().
Function Documentation
int arraytest (int nargs, char ** args)
Definition at line 122 of file arraytest.c.
References array_create(), array_destroy(), array_setsize(), KASSERT, kprintf(), NULL, and testa().
static void testa (struct array * a) [static]
Definition at line 39 of file arraytest.c.
References array_add(), array_get(), array_num(), array_remove(), array_set(), array_setsize(), KASSERT, NULL, random(), and TESTSIZE.
Referenced by arraytest().