Os/161: user/lib/libc/stdio/printf.c File Reference
user/lib/libc/stdio/printf.c File Reference
#include <stdio.h>
#include <stdarg.h>
Functions
static void __printf_send (void *mydata, const char *data, size_t len)
int printf (const char *fmt,...)
int vprintf (const char *fmt, va_list ap)
Function Documentation
static void __printf_send (void * mydata, const char * data, size_t len) [static]
Definition at line 43 of file printf.c.
References putchar().
Referenced by vprintf().
int printf (const char * fmt, ...)
Definition at line 55 of file printf.c.
References va_end, va_start, and vprintf().
Referenced by ask_yesno(), big_file(), BladeRunner(), checkblock(), cleanup(), cmd_chdir(), cmd_exit(), cmd_wait(), concur(), dir_test(), do_move(), dobadreads(), docommand(), dodirblock(), doreadat0(), doreadateof(), dotest(), dowait(), dowaitpoll(), dumpbits(), dumpdir(), dumpsb(), firstread(), geti(), interactive(), main(), makeprocs(), markblock(), menu(), print(), print_board(), print_instructions(), printheader(), printstatus(), readallonebyone(), readallrandomly(), runit(), setup(), subproc_read(), subproc_write(), test1(), test2(), test3(), test4(), test5(), test567(), test6(), test7(), ThreadRunner(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), and usage().
int vprintf (const char * fmt, va_list ap)
Definition at line 67 of file printf.c.
References __printf_send(), __vprintf(), and NULL.
Referenced by printf().