Os/161: kern/include/lib.h File Reference
kern/include/lib.h File Reference
#include <cdefs.h>
#include "opt-noasserts.h"
Defines
#define KASSERT(expr) ((expr) ? (void)0 : badassert(#expr, __FILE__, __LINE__, __func__))
#define DEBUGASSERT(expr) ((void)(expr))
#define DB_LOCORE 0x001
#define DB_SYSCALL 0x002
#define DB_INTERRUPT 0x004
#define DB_DEVICE 0x008
#define DB_THREADS 0x010
#define DB_VM 0x020
#define DB_EXEC 0x040
#define DB_VFS 0x080
#define DB_SFS 0x100
#define DB_NET 0x200
#define DB_NETFS 0x400
#define DB_KMALLOC 0x800
#define DEBUG(d,...) ((dbflags & (d)) ? kprintf(__VA_ARGS__) : 0)
#define RANDOM_MAX (randmax())
#define DIVROUNDUP(a, b) (((a)+(b)-1)/(b))
#define ROUNDUP(a, b) (DIVROUNDUP(a,b)*b)
Functions
uint32_t randmax (void)
uint32_t random (void)
void * kmalloc (size_t size)
void kfree (void *ptr)
void kheap_printstats (void)
size_t strlen (const char *str)
int strcmp (const char *str1, const char *str2)
char * strcpy (char *dest, const char *src)
char * strcat (char *dest, const char *src)
char * kstrdup (const char *str)
char * strchr (const char *searched, int searchfor)
char * strrchr (const char *searched, int searchfor)
char * strtok_r (char *buf, const char *seps, char **context)
void * memcpy (void *dest, const void *src, size_t len)
void * memmove (void *dest, const void *src, size_t len)
void bzero (void *ptr, size_t len)
int atoi (const char *str)
int snprintf (char *buf, size_t maxlen, const char *fmt,...) __PF(3
int const char * strerror (int errcode)
void putch (int ch)
void putch_prepare (void)
void putch_complete (void)
int getch (void)
void beep (void)
int kprintf (const char *format,...) __PF(1
int void panic (const char *format,...) __PF(1
int void void badassert (const char *expr, const char *file, int line, const char *func)
void kgets (char *buf, size_t maxbuflen)
void kprintf_bootstrap (void)
Variables
uint32_t dbflags
Define Documentation
#define DB_DEVICE 0x008
Definition at line 82 of file lib.h.
#define DB_EXEC 0x040
Definition at line 85 of file lib.h.
Referenced by load_segment().
#define DB_INTERRUPT 0x004
Definition at line 81 of file lib.h.
#define DB_KMALLOC 0x800
Definition at line 90 of file lib.h.
#define DB_LOCORE 0x001
Definition at line 79 of file lib.h.
#define DB_NET 0x200
Definition at line 88 of file lib.h.
#define DB_NETFS 0x400
Definition at line 89 of file lib.h.
#define DB_SFS 0x100
Definition at line 87 of file lib.h.
Referenced by sfs_rwblock().
#define DB_SYSCALL 0x002
Definition at line 80 of file lib.h.
Referenced by mips_trap().
#define DB_THREADS 0x010
Definition at line 83 of file lib.h.
Referenced by thread_consider_migration().
#define DB_VFS 0x080
Definition at line 86 of file lib.h.
#define DB_VM 0x020
Definition at line 84 of file lib.h.
Referenced by vm_fault().
#define DEBUG (d, ...) ((dbflags & (d)) ? kprintf(__VA_ARGS__) : 0)
Definition at line 110 of file lib.h.
Referenced by load_segment(), mips_trap(), sfs_rwblock(), thread_consider_migration(), and vm_fault().
#define DEBUGASSERT (expr) ((void)(expr))
Definition at line 70 of file lib.h.
Referenced by thread_create(), thread_switch(), threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_insertafternode(), threadlist_insertbeforenode(), threadlist_isempty(), threadlist_remhead(), threadlist_remove(), threadlist_removenode(), threadlist_remtail(), threadlistnode_cleanup(), and threadlistnode_init().
#define DIVROUNDUP (a, b) (((a)+(b)-1)/(b))
Definition at line 191 of file lib.h.
Referenced by bitmap_alloc(), bitmap_create(), sfs_truncate(), and thread_consider_migration().
#define KASSERT (expr) ((expr) ? (void)0 : badassert(#expr, __FILE__, __LINE__, __func__))
Definition at line 65 of file lib.h.
Referenced by allocpageref(), arraytest(), as_copy(), as_define_stack(), as_prepare_load(), badnames(), bitmap_alloc(), bitmap_create(), bitmap_mark(), bitmap_unmark(), bitmaptest(), boot(), cmd_dispatch(), cmd_progthread(), compute_thread(), con_io(), config_beep(), config_con(), config_random(), config_rtclock(), cpu_hatch(), cpu_machdep_init(), cv_destroy(), dev_read(), dev_write(), dumpsubpage(), emu_doread(), emu_write(), emufs_addtovfs(), emufs_getdirentry(), emufs_getroot(), emufs_read(), emufs_write(), exorcise(), findmount(), freepageref(), fstest_makename(), fstest_write(), getch(), getdevice(), gettime(), ipi_send(), kfree(), kill_curthread(), kprintf_bootstrap(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_interrupt(), lamebus_map_area(), lamebus_mark(), lamebus_mask_interrupt(), lamebus_unmark(), lamebus_unmask_interrupt(), lock_destroy(), lser_poll_until_write(), mainbus_bootstrap(), mainbus_interrupt(), mips_trap(), mips_usermode(), P(), putch_delayed(), remove_lists(), rotate(), runprogram(), sem_create(), sem_destroy(), set_std_fd(), sfs_blockio(), sfs_bmap(), sfs_dir_findname(), sfs_dir_nentries(), sfs_domount(), sfs_io(), sfs_link(), sfs_loadvnode(), sfs_namefile(), sfs_partialio(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_rwblock(), sfs_truncate(), sfs_unmount(), sfs_write(), sfs_writedir(), spinlock_cleanup(), spinlock_release(), spllower(), splraise(), subpage_kfree(), subpage_kmalloc(), sys_execv(), syscall(), testa(), thread_checkstack(), thread_consider_migration(), thread_destroy(), thread_machdep_cleanup(), thread_make_runnable(), threadlist_cleanup(), threadlistnode_cleanup(), threadlistnode_init(), uiomove(), uiomovezeros(), V(), vfs_biglock_release(), vfs_getcwd(), vfs_getdevname(), vfs_getroot(), vfs_mount(), vfs_open(), vfs_unmount(), vm_fault(), vnode_cleanup(), vnode_decopen(), vnode_decref(), vnode_incopen(), vnode_incref(), vnode_init(), and wchan_sleep().
#define RANDOM_MAX (randmax())
Definition at line 117 of file lib.h.
Referenced by bin(), dovalidate(), genkeys_sub(), and validate().
#define ROUNDUP (a, b) (DIVROUNDUP(a,b)*b)
Definition at line 192 of file lib.h.
Function Documentation
int atoi (const char * str)
Definition at line 50 of file atoi.c.
int void void badassert (const char * expr, const char * file, int line, const char * func)
Definition at line 206 of file kprintf.c.
References panic().
void beep (void)
Definition at line 63 of file beep.c.
References beep_softc::bs_beep, beep_softc::bs_devdata, kprintf(), and NULL.
Referenced by kgets().
void bzero (void * ptr, size_t len)
Definition at line 49 of file bzero.c.
int getch (void)
Definition at line 269 of file console.c.
References getch_intr(), KASSERT, and NULL.
Referenced by con_io(), and kgets().
void kfree (void * ptr)
Definition at line 622 of file kmalloc.c.
References free_kpages(), KASSERT, NULL, PAGE_SIZE, and subpage_kfree().
Referenced by array_cleanup(), array_destroy(), array_setsize(), as_destroy(), attach_console_to_vfs(), bitmap_create(), bitmap_destroy(), compute_thread(), cv_create(), cv_destroy(), emufs_addtovfs(), emufs_loadvnode(), emufs_reclaim(), lock_create(), lock_destroy(), mallocthread(), runprogram(), sem_create(), sem_destroy(), set_std_fd(), sfs_domount(), sfs_loadvnode(), sfs_reclaim(), sfs_unmount(), sys_close(), sys_dup2(), sys_execv(), thread_create(), thread_destroy(), thread_exit(), thread_fork(), thread_fork2(), vfs_doadd(), and wchan_destroy().
void kgets (char * buf, size_t maxbuflen)
Definition at line 54 of file kgets.c.
References backsp(), beep(), ch, getch(), kprintf(), pos, and putch().
Referenced by menu().
void kheap_printstats (void)
Definition at line 334 of file kmalloc.c.
References dumpsubpage(), kprintf(), pageref::next_all, NULL, spinlock_acquire(), and spinlock_release().
Referenced by cmd_kheapstats().
void* kmalloc (size_t size)
Definition at line 602 of file kmalloc.c.
References alloc_kpages(), LARGEST_SUBPAGE_SIZE, NULL, PAGE_SIZE, and subpage_kmalloc().
Referenced by array_create(), array_setsize(), as_create(), attach_beep_to_ltimer(), attach_con_to_lscreen(), attach_con_to_lser(), attach_console_to_vfs(), attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), attach_ltrace_to_lamebus(), attach_random_to_lrandom(), attach_rtclock_to_ltimer(), bitmap_create(), compute_thread(), cpu_create(), cv_create(), dev_create_vnode(), devnull_create(), emufs_addtovfs(), emufs_loadvnode(), kstrdup(), lamebus_init(), lock_create(), mallocthread(), mkrawname(), runprogram(), sem_create(), set_std_fd(), sfs_domount(), sfs_loadvnode(), sys_dup2(), sys_execv(), sys_open(), thread_create(), thread_fork(), thread_fork2(), vfs_doadd(), and wchan_create().
int kprintf (const char * format, ...)
Referenced by arraytest(), as_define_region(), attach_lnet_to_lamebus(), beep(), bitmaptest(), boot(), checkfilesystem(), cmd_bootfs(), cmd_chdir(), cmd_dispatch(), cmd_mount(), cmd_prog(), cmd_progthread(), cmd_pwd(), cmd_shell(), cmd_testmenu(), cmd_unmount(), common_prog(), compute_thread(), config_lnet(), cpu_hatch(), createstress_thread(), cvtest(), cvtestthread(), docreatestress(), dofstest(), doreadstress(), dowritestress(), dowritestress2(), dumpsubpage(), emu_close(), fail(), female(), fstest_read(), fstest_remove(), fstest_write(), hello(), interprocessor_interrupt(), kgets(), kheap_printstats(), kill_curthread(), lamebus_interrupt(), lhd_code_to_errno(), load_elf(), load_segment(), locktest(), mainbus_bootstrap(), mainbus_reboot(), male(), mallocstress(), malloctest(), mallocthread(), matchmaker(), menu(), menu_execute(), mips_trap(), nettest(), panic(), printfile(), ram_bootstrap(), readstress_thread(), runtest3(), semtest(), semtestthread(), sfs_domount(), sfs_rename(), sfs_rwblock(), showmenu(), shutdown(), sleepalot_thread(), subpage_kmalloc(), sys_reboot(), syscall(), thread_start_cpus(), threadtest(), threadtest2(), threadtest3(), translate_err(), tryattach_beep_to_ltimer(), tryattach_con_to_lser(), tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), tryattach_ltrace_to_lamebus(), tryattach_random_to_lrandom(), tryattach_rtclock_to_ltimer(), vfs_mount(), vfs_unmount(), vfs_unmountall(), vm_fault(), vnode_check(), vnode_decopen(), vnode_decref(), writestress2_thread(), and writestress_thread().
void kprintf_bootstrap (void)
Definition at line 63 of file kprintf.c.
References KASSERT, kprintf_spinlock, lock_create(), NULL, panic(), and spinlock_init().
Referenced by boot().
char* kstrdup (const char * str)
Definition at line 38 of file misc.c.
References kmalloc(), NULL, strcpy(), and strlen().
Referenced by cv_create(), lock_create(), runprogram(), sem_create(), set_std_fd(), setup(), thread_create(), and vfs_doadd().
void* memcpy (void * dest, const void * src, size_t len)
Definition at line 48 of file memcpy.c.
void* memmove (void * dest, const void * src, size_t len)
Definition at line 49 of file memmove.c.
int void panic (const char * format, ...)
Referenced by badassert(), blocktype(), cmd_panic(), cpu_create(), cvtest(), dev_create_vnode(), devnull_create(), docreatestress(), doreadstress(), dowritestress(), dowritestress2(), emufs_reclaim(), hardclock_bootstrap(), init_sem(), init_threadsem(), inititems(), kill_curthread(), kprintf_bootstrap(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_init(), lamebus_interrupt(), lamebus_mark(), lamebus_unmark(), locktest(), lser_write(), mainbus_interrupt(), make_computes(), make_sleepalots(), mallocstress(), menu_execute(), mips_trap(), randmax(), random(), runprogram(), runthreads(), semtest(), set_std_fd(), sfs_balloc(), sfs_bmap(), sfs_bused(), sfs_dir_nentries(), sfs_getroot(), sfs_gettype(), sfs_loadvnode(), sfs_lookonce(), sfs_readdir(), sfs_reclaim(), sfs_rename(), sfs_rwblock(), sfs_writedir(), spinlock_acquire(), strerror(), subpage_kfree(), sys_execv(), sys_reboot(), thread_exit(), thread_switch(), translate_err(), uiomove(), vfs_bootstrap(), vm_fault(), vm_tlbshootdown(), vm_tlbshootdown_all(), vnode_check(), and whalemating().
void putch (int ch)
Definition at line 221 of file console.c.
References NULL, putch_delayed(), putch_intr(), and putch_polled().
Referenced by backsp(), con_io(), console_send(), flush_delay_buf(), kgets(), loudthread(), and quietthread().
void putch_complete (void)
Definition at line 253 of file console.c.
References NULL, and putch_complete_polled().
Referenced by kprintf(), and panic().
void putch_prepare (void)
Definition at line 237 of file console.c.
References NULL, and putch_prepare_polled().
Referenced by kprintf(), and panic().
uint32_t randmax (void)
Definition at line 160 of file random.c.
References NULL, panic(), random_softc::rs_devdata, and random_softc::rs_randmax.
uint32_t random (void)
Definition at line 151 of file random.c.
int snprintf (char * buf, size_t maxlen, const char * fmt, ...)
Definition at line 148 of file snprintf.c.
References va_end, va_start, and vsnprintf().
Referenced by __bad_assert(), any_badfd(), any_empty(), binname(), blockusagestr(), check_dir(), check_dir_entry(), choose_name(), common_badbuf(), common_badpath(), config_emu(), config_lhd(), cpu_create(), createstress_thread(), fstest_makename(), killdir(), listdir(), main(), make_computes(), make_sleepalots(), mergedname(), one_ioctl_badbuf(), recursedir(), recursive_cleanup(), runthreads(), setup(), test3(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), validname(), vfs_setbootfs(), vscomplain(), and writestress_thread().
char* strcat (char * dest, const char * src)
Definition at line 47 of file strcat.c.
char* strchr (const char * searched, int searchfor)
Definition at line 47 of file strchr.c.
int strcmp (const char * str1, const char * str2)
Definition at line 48 of file strcmp.c.
char* strcpy (char * dest, const char * src)
Definition at line 46 of file strcpy.c.
int const char* strerror (int errcode)
Definition at line 55 of file misc.c.
size_t strlen (const char * str)
Definition at line 47 of file strlen.c.
char* strrchr (const char * searched, int searchfor)
Definition at line 47 of file strrchr.c.
char* strtok_r (char * buf, const char * seps, char ** context)
Definition at line 50 of file strtok_r.c.
Variable Documentation
uint32_t dbflags
Definition at line 43 of file kprintf.c.