Os/161: kern/syscall/write_syscall.c File Reference
kern/syscall/write_syscall.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <vm.h>
#include <vfs.h>
#include <mainbus.h>
#include <vnode.h>
#include <device.h>
#include <syscall.h>
#include <kern/fcntl.h>
#include <kern/file.h>
Functions
int sys_write (int fd, const void *buf, size_t nbytes, int *retval)
Function Documentation
int sys_write (int fd, const void * buf, size_t nbytes, int * retval)
Definition at line 40 of file write_syscall.c.
References EBADF, EFAULT, EIO, errno, iovec::iov_len, NULL, file::offset, splhigh(), splx(), uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, UIO_USERISPACE, UIO_WRITE, file::vfs_node, VOP_WRITE, and file::writeable.
Referenced by syscall().