Os/161: kern/include/synch.h File Reference
kern/include/synch.h File Reference
#include <spinlock.h>
Data Structures
struct semaphore
struct lock
struct cv
Functions
struct semaphore * sem_create (const char *name, int initial_count)
void sem_destroy (struct semaphore *)
void P (struct semaphore *)
void V (struct semaphore *)
struct lock * lock_create (const char *name)
void lock_acquire (struct lock *)
void lock_release (struct lock *)
bool lock_do_i_hold (struct lock *)
void lock_destroy (struct lock *)
struct cv * cv_create (const char *name)
void cv_destroy (struct cv *)
void cv_wait (struct cv *cv, struct lock *lock)
void cv_signal (struct cv *cv, struct lock *lock)
void cv_broadcast (struct cv *cv, struct lock *lock)
Function Documentation
void cv_broadcast (struct cv * cv, struct lock * lock)
Definition at line 262 of file synch.c.
Referenced by cvtestthread().
struct cv* cv_create (const char * name) [read]
Definition at line 214 of file synch.c.
References cv::cv_name, kfree(), kmalloc(), kstrdup(), and NULL.
Referenced by inititems().
void cv_destroy (struct cv *)
Definition at line 235 of file synch.c.
References cv::cv_name, KASSERT, kfree(), and NULL.
void cv_signal (struct cv * cv, struct lock * lock)
Definition at line 254 of file synch.c.
void cv_wait (struct cv * cv, struct lock * lock)
Definition at line 246 of file synch.c.
Referenced by cvtestthread().
void lock_acquire (struct lock *)
Definition at line 183 of file synch.c.
Referenced by con_io(), cvtestthread(), emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), emu_write(), emufs_loadvnode(), emufs_reclaim(), kprintf(), locktestthread(), and vfs_biglock_acquire().
struct lock* lock_create (const char * name) [read]
Definition at line 151 of file synch.c.
References kfree(), kmalloc(), kstrdup(), lock::lk_name, and NULL.
Referenced by config_con(), config_emu(), inititems(), kprintf_bootstrap(), and vfs_bootstrap().
void lock_destroy (struct lock *)
Definition at line 172 of file synch.c.
References KASSERT, kfree(), lock::lk_name, and NULL.
Referenced by config_con(), and config_emu().
bool lock_do_i_hold (struct lock *)
Definition at line 199 of file synch.c.
Referenced by emu_close(), vfs_biglock_acquire(), vfs_biglock_do_i_hold(), and vfs_biglock_release().
void lock_release (struct lock *)
Definition at line 191 of file synch.c.
Referenced by con_io(), cvtestthread(), emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), emu_write(), emufs_loadvnode(), emufs_reclaim(), fail(), kprintf(), locktestthread(), and vfs_biglock_release().
void P (struct semaphore *)
Definition at line 91 of file synch.c.
References KASSERT, NULL, semaphore::sem_count, semaphore::sem_lock, semaphore::sem_wchan, spinlock_acquire(), spinlock_release(), wchan_lock(), and wchan_sleep().
Referenced by cvtest(), docreatestress(), doreadstress(), dowritestress(), dowritestress2(), emu_waitdone(), finish(), getch_intr(), lhd_io(), locktest(), mallocstress(), putch_intr(), runthreads(), semtest(), semtestthread(), thread_start_cpus(), and waker_thread().
struct semaphore* sem_create (const char * name, int initial_count) [read]
Definition at line 48 of file synch.c.
References KASSERT, kfree(), kmalloc(), kstrdup(), NULL, semaphore::sem_count, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_init(), and wchan_create().
Referenced by config_con(), config_emu(), config_lhd(), init_sem(), init_threadsem(), inititems(), mallocstress(), setup(), and thread_start_cpus().
void sem_destroy (struct semaphore *)
Definition at line 79 of file synch.c.
References KASSERT, kfree(), NULL, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_cleanup(), and wchan_destroy().
Referenced by config_con(), config_lhd(), mallocstress(), and thread_start_cpus().
void V (struct semaphore *)
Definition at line 133 of file synch.c.
References KASSERT, NULL, semaphore::sem_count, semaphore::sem_lock, semaphore::sem_wchan, spinlock_acquire(), spinlock_release(), and wchan_wakeone().
Referenced by compute_thread(), con_input(), con_start(), cpu_hatch(), createstress_thread(), cvtestthread(), emu_irq(), fail(), finish(), lhd_io(), lhd_iodone(), locktestthread(), loudthread(), mallocthread(), quietthread(), readstress_thread(), semtest(), semtestthread(), sleepalot_thread(), waker_thread(), writestress2_thread(), and writestress_thread().