Os/161: kern/include/cpu.h File Reference
kern/include/cpu.h File Reference
#include <spinlock.h>
#include <threadlist.h>
#include <machine/vm.h>
Data Structures
struct cpu
Defines
#define TLBSHOOTDOWN_ALL (-1)
#define IPI_PANIC 0
#define IPI_OFFLINE 1
#define IPI_UNIDLE 2
#define IPI_TLBSHOOTDOWN 3
Functions
struct cpu * cpu_create (unsigned hardware_number)
void cpu_machdep_init (struct cpu *)
void cpu_start_secondary (void)
void cpu_hatch (unsigned software_number)
const char * cpu_identify (void)
void cpu_irqoff (void)
void cpu_irqon (void)
void cpu_idle (void)
void cpu_halt (void)
void ipi_send (struct cpu *target, int code)
void ipi_broadcast (int code)
void ipi_tlbshootdown (struct cpu *target, const struct tlbshootdown *mapping)
void interprocessor_interrupt (void)
Define Documentation
#define IPI_OFFLINE 1
Definition at line 162 of file cpu.h.
Referenced by interprocessor_interrupt(), and thread_shutdown().
#define IPI_PANIC 0
Definition at line 161 of file cpu.h.
Referenced by interprocessor_interrupt(), and thread_panic().
#define IPI_TLBSHOOTDOWN 3
Definition at line 164 of file cpu.h.
Referenced by interprocessor_interrupt(), and ipi_tlbshootdown().
#define IPI_UNIDLE 2
Definition at line 163 of file cpu.h.
Referenced by interprocessor_interrupt(), thread_consider_migration(), and thread_make_runnable().
#define TLBSHOOTDOWN_ALL (-1)
Definition at line 92 of file cpu.h.
Referenced by interprocessor_interrupt(), and ipi_tlbshootdown().
Function Documentation
struct cpu* cpu_create (unsigned hardware_number) [read]
Definition at line 190 of file thread.c.
References allcpus, cpu::c_curthread, cpu::c_hardclocks, cpu::c_hardware_number, cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_isidle, cpu::c_number, cpu::c_numshootdown, cpu::c_runqueue, cpu::c_runqueue_lock, cpu::c_self, cpu::c_zombies, cpu_machdep_init(), kmalloc(), NULL, panic(), snprintf(), spinlock_init(), STACK_SIZE, strerror(), thread::t_cpu, thread::t_stack, thread_checkstack_init(), thread_create(), and threadlist_init().
Referenced by lamebus_find_cpus(), and thread_bootstrap().
void cpu_halt (void)
Definition at line 230 of file cpu.c.
References cpu_irqoff(), and wait().
Referenced by interprocessor_interrupt(), lamebus_poweroff(), and mainbus_halt().
void cpu_hatch (unsigned software_number)
Definition at line 434 of file thread.c.
References cpu_identify(), curcpu, KASSERT, kprintf(), NULL, spl0(), thread_exit(), and V().
const char* cpu_identify (void)
Definition at line 100 of file cpu.c.
Referenced by cpu_hatch(), and thread_start_cpus().
void cpu_idle (void)
Definition at line 220 of file cpu.c.
References cpu_irqonoff(), and wait().
Referenced by thread_switch().
void cpu_irqoff (void)
Definition at line 150 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by cpu_halt(), lamebus_poweroff(), mips_trap(), mips_usermode(), and splraise().
void cpu_irqon (void)
Definition at line 137 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by spllower().
void cpu_machdep_init (struct cpu *)
Definition at line 68 of file cpu.c.
References cpu::c_curthread, cpu::c_number, cpustacks, cputhreads, KASSERT, MAXCPUS, NULL, STACK_SIZE, and thread::t_stack.
Referenced by cpu_create().
void cpu_start_secondary (void)
Referenced by lamebus_start_cpus().
void interprocessor_interrupt (void)
Definition at line 1251 of file thread.c.
References cpu_halt(), curcpu, IPI_OFFLINE, IPI_PANIC, IPI_TLBSHOOTDOWN, IPI_UNIDLE, kprintf(), spinlock_acquire(), spinlock_release(), TLBSHOOTDOWN_ALL, vm_tlbshootdown(), and vm_tlbshootdown_all().
Referenced by mainbus_interrupt().
void ipi_broadcast (int code)
Definition at line 1215 of file thread.c.
References allcpus, curcpu, and ipi_send().
Referenced by thread_panic(), and thread_shutdown().
void ipi_send (struct cpu * target, int code)
Definition at line 1204 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, KASSERT, mainbus_send_ipi(), spinlock_acquire(), and spinlock_release().
Referenced by ipi_broadcast(), thread_consider_migration(), and thread_make_runnable().
void ipi_tlbshootdown (struct cpu * target, const struct tlbshootdown * mapping)
Definition at line 1229 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_numshootdown, cpu::c_shootdown, IPI_TLBSHOOTDOWN, mainbus_send_ipi(), spinlock_acquire(), spinlock_release(), TLBSHOOTDOWN_ALL, and TLBSHOOTDOWN_MAX.