Os/161: kern/vfs/vfscwd.c File Reference
kern/vfs/vfscwd.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <stat.h>
#include <lib.h>
#include <uio.h>
#include <thread.h>
#include <current.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
Functions
int vfs_getcurdir (struct vnode **ret)
int vfs_setcurdir (struct vnode *dir)
int vfs_clearcurdir (void)
int vfs_chdir (char *path)
int vfs_getcwd (struct uio *uio)
Function Documentation
int vfs_chdir (char * path)
Definition at line 121 of file vfscwd.c.
References vfs_lookup(), vfs_setcurdir(), and VOP_DECREF.
Referenced by cmd_chdir(), and vfs_setbootfs().
int vfs_clearcurdir (void)
Definition at line 102 of file vfscwd.c.
References NULL, and VOP_DECREF.
Referenced by shutdown().
int vfs_getcurdir (struct vnode ** ret)
Definition at line 52 of file vfscwd.c.
References ENOENT, NULL, and VOP_INCREF.
Referenced by getdevice(), vfs_getcwd(), and vfs_setbootfs().
int vfs_getcwd (struct uio * uio)
Definition at line 141 of file vfscwd.c.
References FSOP_GETVOLNAME, KASSERT, name, NULL, strlen(), UIO_READ, uio::uio_rw, uiomove(), vfs_biglock_acquire(), vfs_biglock_release(), vfs_getcurdir(), vfs_getdevname(), vnode::vn_fs, VOP_DECREF, and VOP_NAMEFILE.
Referenced by cmd_pwd().
int vfs_setcurdir (struct vnode * dir)
Definition at line 72 of file vfscwd.c.
References ENOTDIR, NULL, S_IFDIR, VOP_DECREF, VOP_GETTYPE, and VOP_INCREF.
Referenced by vfs_chdir().