Os/161: kern/synchprobs/whalemating.c File Reference
kern/synchprobs/whalemating.c File Reference
#include <types.h>
#include <lib.h>
#include <thread.h>
#include <test.h>
Defines
#define NMATING 10
Functions
static void male (void *p, unsigned long which)
static void female (void *p, unsigned long which)
static void matchmaker (void *p, unsigned long which)
int whalemating (int nargs, char **args)
Define Documentation
#define NMATING 10
Definition at line 38 of file whalemating.c.
Referenced by whalemating().
Function Documentation
static void female (void * p, unsigned long which) [static]
Definition at line 52 of file whalemating.c.
References kprintf().
Referenced by whalemating().
static void male (void * p, unsigned long which) [static]
Definition at line 42 of file whalemating.c.
References kprintf().
Referenced by whalemating().
static void matchmaker (void * p, unsigned long which) [static]
Definition at line 62 of file whalemating.c.
References kprintf().
Referenced by whalemating().
int whalemating (int nargs, char ** args)
Definition at line 73 of file whalemating.c.
References err(), female(), male(), matchmaker(), NMATING, NULL, panic(), strerror(), and thread_fork().