Os/161: user/testbin/badcall/bad_waitpid.c File Reference
user/testbin/badcall/bad_waitpid.c File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void wait_badpid (int pid, const char *desc)
static void wait_badstatus (void *ptr, const char *desc)
static void wait_unaligned (void)
static void wait_badflags (void)
static void wait_self (void)
static void wait_parent (void)
static void wait_siblings_child (void)
static void wait_siblings (void)
void test_waitpid (void)
Function Documentation
void test_waitpid (void)
Definition at line 270 of file bad_waitpid.c.
References NONEXIST_PID, NULL, wait_badflags(), wait_badpid(), wait_badstatus(), wait_parent(), wait_self(), wait_siblings(), and wait_unaligned().
static void wait_badflags (void) [static]
Definition at line 104 of file bad_waitpid.c.
References EINVAL, errno, exit(), fork(), pid, report_test(), waitpid(), and warn().
Referenced by test_waitpid().
static void wait_badpid (int pid, const char * desc) [static]
Definition at line 45 of file bad_waitpid.c.
References EINVAL, errno, NOSUCHPID_ERROR, report_test2(), and waitpid().
Referenced by test_waitpid().
static void wait_badstatus (void * ptr, const char * desc) [static]
Definition at line 54 of file bad_waitpid.c.
References EFAULT, errno, exit(), fork(), pid, report_test(), waitpid(), and warn().
Referenced by test_waitpid().
static void wait_parent (void) [static]
Definition at line 133 of file bad_waitpid.c.
References _exit(), errno, fork(), getpid(), mypid, report_survival(), waitpid(), and warn().
Referenced by test_waitpid().
static void wait_self (void) [static]
Definition at line 124 of file bad_waitpid.c.
References errno, getpid(), report_survival(), and waitpid().
Referenced by test_waitpid().
static void wait_siblings (void) [static]
Definition at line 208 of file bad_waitpid.c.
References _exit(), close(), fd, fork(), NULL, open_testfile(), pids, TESTFILE, wait_siblings_child(), waitpid(), warn(), warnx(), and write().
Referenced by test_waitpid().
static void wait_siblings_child (void) [static]
Definition at line 157 of file bad_waitpid.c.
References close(), errno, fd, getpid(), lseek(), mypid, O_RDONLY, open(), pids, read(), report_survival(), SEEK_SET, TESTFILE, waitpid(), and warn().
Referenced by wait_siblings().
static void wait_unaligned (void) [static]
Definition at line 74 of file bad_waitpid.c.
References errno, exit(), fork(), pid, report_survival(), waitpid(), and warn().
Referenced by test_waitpid().