Os/161: user/testbin/badcall/bad_link.c File Reference
user/testbin/badcall/bad_link.c File Reference
#include <unistd.h>
#include <errno.h>
#include "test.h"
Functions
static void link_dir (void)
static void link_empty1 (void)
static void link_empty2 (void)
void test_link (void)
Function Documentation
static void link_dir (void) [static]
Definition at line 41 of file bad_link.c.
References EINVAL, errno, link(), report_test(), and TESTDIR.
Referenced by test_link().
static void link_empty1 (void) [static]
Definition at line 54 of file bad_link.c.
References EINVAL, errno, link(), report_test(), and TESTDIR.
Referenced by test_link().
static void link_empty2 (void) [static]
Definition at line 63 of file bad_link.c.
References create_testdir(), EINVAL, errno, link(), report_test(), rmdir(), and TESTDIR.
Referenced by test_link().
void test_link (void)
Definition at line 75 of file bad_link.c.
References link_dir(), link_empty1(), link_empty2(), and test_link_paths().