Os/161: user/testbin/badcall/common_fds.c File Reference
user/testbin/badcall/common_fds.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Defines
#define T(call)
#define TC(call)
Functions
static int read_badfd (int fd)
static int write_badfd (int fd)
static int close_badfd (int fd)
static int ioctl_badfd (int fd)
static int lseek_badfd (int fd)
static int fsync_badfd (int fd)
static int ftruncate_badfd (int fd)
static int fstat_badfd (int fd)
static int getdirentry_badfd (int fd)
static int dup2_badfd (int fd)
static void dup2_cleanup (void)
static void any_badfd (int(*func)(int fd), void(*cleanup)(void), const char *callname, int fd, const char *fddesc)
static void runtest (int(*func)(int fd), void(*cleanup)(void), const char *callname)
T (read)
T (write)
T (close)
T (ioctl)
T (lseek)
T (fsync)
T (ftruncate)
T (fstat)
T (getdirentry)
TC (dup2)
Define Documentation
#define T (call)
Value:
void                                          \
  test_##call##_fd(void)                        \
  {                                             \
        runtest(call##_badfd, NULL, #call);     \
  }
Definition at line 180 of file common_fds.c.
#define TC (call)
Value:
void                                          \
  test_##call##_fd(void)                        \
  {                                             \
        runtest(call##_badfd, call##_cleanup, #call);\
  }
Definition at line 187 of file common_fds.c.
Function Documentation
static void any_badfd (int(*)(int fd) func, void(*)(void) cleanup, const char * callname, int fd, const char * fddesc) [static]
Definition at line 136 of file common_fds.c.
References cleanup(), EBADF, errno, report_test(), and snprintf().
Referenced by runtest().
static int close_badfd (int fd) [static]
Definition at line 68 of file common_fds.c.
References close().
static int dup2_badfd (int fd) [static]
Definition at line 119 of file common_fds.c.
References CLOSED_FD, and dup2().
static void dup2_cleanup (void) [static]
Definition at line 127 of file common_fds.c.
References close(), and CLOSED_FD.
static int fstat_badfd (int fd) [static]
Definition at line 103 of file common_fds.c.
References fstat().
static int fsync_badfd (int fd) [static]
Definition at line 89 of file common_fds.c.
References fsync().
static int ftruncate_badfd (int fd) [static]
Definition at line 96 of file common_fds.c.
References ftruncate().
static int getdirentry_badfd (int fd) [static]
Definition at line 111 of file common_fds.c.
References getdirentry().
static int ioctl_badfd (int fd) [static]
Definition at line 75 of file common_fds.c.
References ioctl(), and NULL.
static int lseek_badfd (int fd) [static]
Definition at line 82 of file common_fds.c.
References lseek(), and SEEK_SET.
static int read_badfd (int fd) [static]
Definition at line 50 of file common_fds.c.
References read().
static void runtest (int(*)(int fd) func, void(*)(void) cleanup, const char * callname) [static]
Definition at line 152 of file common_fds.c.
References any_badfd(), cleanup(), CLOSED_FD, IMPOSSIBLE_FD, OPEN_MAX, and warnx().
T (getdirentry)
T (fstat)
T (ftruncate)
T (fsync)
T (lseek)
T (ioctl)
T (close)
T (write)
T (read)
TC (dup2)
static int write_badfd (int fd) [static]
Definition at line 58 of file common_fds.c.
References memset(), and write().