Os/161: user/testbin/badcall/bad_ftruncate.c File Reference
user/testbin/badcall/bad_ftruncate.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void ftruncate_fd_device (void)
static void ftruncate_size_neg (void)
void test_ftruncate (void)
Function Documentation
static void ftruncate_fd_device (void) [static]
Definition at line 48 of file bad_ftruncate.c.
References close(), EINVAL, errno, fd, ftruncate(), O_RDWR, open(), report_test(), and warn().
Referenced by test_ftruncate().
static void ftruncate_size_neg (void) [static]
Definition at line 66 of file bad_ftruncate.c.
References close(), EINVAL, errno, fd, ftruncate(), open_testfile(), report_test(), and TESTFILE.
Referenced by test_ftruncate().
void test_ftruncate (void)
Definition at line 83 of file bad_ftruncate.c.
References ftruncate_fd_device(), ftruncate_size_neg(), and test_ftruncate_fd().