Os/161: user/testbin/badcall/bad_rmdir.c File Reference
user/testbin/badcall/bad_rmdir.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void rmdir_file (void)
static void rmdir_dot (void)
static void rmdir_dotdot (void)
static void rmdir_empty (void)
void test_rmdir (void)
Function Documentation
static void rmdir_dot (void) [static]
Definition at line 61 of file bad_rmdir.c.
References EINVAL, errno, report_test(), and rmdir().
Referenced by test_rmdir().
static void rmdir_dotdot (void) [static]
Definition at line 71 of file bad_rmdir.c.
References EINVAL, ENOTEMPTY, errno, report_test2(), and rmdir().
Referenced by test_rmdir().
static void rmdir_empty (void) [static]
Definition at line 81 of file bad_rmdir.c.
References EINVAL, errno, report_test(), and rmdir().
Referenced by test_rmdir().
static void rmdir_file (void) [static]
Definition at line 48 of file bad_rmdir.c.
References create_testfile(), ENOTDIR, errno, report_test(), rmdir(), and TESTFILE.
Referenced by test_rmdir().
void test_rmdir (void)
Definition at line 89 of file bad_rmdir.c.
References rmdir_dot(), rmdir_dotdot(), rmdir_empty(), rmdir_file(), and test_rmdir_path().