Os/161: user/testbin/badcall/bad_reboot.c File Reference
user/testbin/badcall/bad_reboot.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void reboot_badflags (void)
void test_reboot (void)
Function Documentation
static void reboot_badflags (void) [static]
Definition at line 48 of file bad_reboot.c.
References EINVAL, errno, reboot(), report_test(), and warnx().
Referenced by test_reboot().
void test_reboot (void)
Definition at line 58 of file bad_reboot.c.
References reboot_badflags().