Os/161: user/testbin/dirtest/dirtest.c File Reference
user/testbin/dirtest/dirtest.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <err.h>
Defines
#define MAXLEVELS 5
Functions
int main (void)
Define Documentation
#define MAXLEVELS 5
Definition at line 49 of file dirtest.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 52 of file dirtest.c.
References err(), MAXLEVELS, mkdir(), printf(), rmdir(), strcat(), strcpy(), and strlen().