Os/161: user/testbin/parallelvm/parallelvm.c File Reference
user/testbin/parallelvm/parallelvm.c File Reference
#include <sys/types.h>
#include <sys/wait.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <err.h>
Data Structures
struct matrix
Defines
#define NJOBS 24
#define DIM 35
#define NMATS 11
#define JOBSIZE ((NMATS+1)*DIM*DIM*sizeof(int))
Functions
static void say (const char *fmt,...)
static void multiply (struct matrix *res, const struct matrix *m1, const struct matrix *m2)
static void addeq (struct matrix *m1, const struct matrix *m2)
static int trace (const struct matrix *m1)
static void populate_initial_matrixes (int mynum)
static void compute (int n)
static void computeall (int mynum)
static int answer (void)
static void go (int mynum)
static int status_is_failure (int status)
static void makeprocs (void)
int main ()
Variables
static const int right_answers [NJOBS]
static struct matrix mats [NMATS]
Define Documentation
#define DIM 35
Definition at line 50 of file parallelvm.c.
#define JOBSIZE ((NMATS+1)*DIM*DIM*sizeof(int))
Definition at line 52 of file parallelvm.c.
Referenced by makeprocs().
#define NJOBS 24
Definition at line 48 of file parallelvm.c.
Referenced by makeprocs().
#define NMATS 11
Definition at line 51 of file parallelvm.c.
Referenced by answer(), and computeall().
Function Documentation
static void addeq (struct matrix * m1, const struct matrix * m2) [static]
Definition at line 126 of file parallelvm.c.
References DIM, and matrix::m_data.
Referenced by compute().
static int answer (void) [static]
Definition at line 192 of file parallelvm.c.
References mats, NMATS, and trace().
Referenced by ask_yesno(), do_move(), and go().
static void compute (int n) [static]
Definition at line 168 of file parallelvm.c.
References addeq(), mats, and multiply().
Referenced by computeall().
static void computeall (int mynum) [static]
Definition at line 181 of file parallelvm.c.
References compute(), NMATS, and populate_initial_matrixes().
Referenced by go().
static void go (int mynum) [static]
Definition at line 199 of file parallelvm.c.
References answer(), computeall(), exit(), getpid(), right_answers, and say().
Referenced by makeprocs().
int main (void)
Definition at line 281 of file parallelvm.c.
References makeprocs().
static void makeprocs (void) [static]
Definition at line 238 of file parallelvm.c.
References err(), exit(), fork(), go(), JOBSIZE, NJOBS, pids, printf(), status_is_failure(), waitpid(), and warn().
Referenced by main().
static void multiply (struct matrix * res, const struct matrix * m1, const struct matrix * m2) [static]
Definition at line 109 of file parallelvm.c.
References DIM, and matrix::m_data.
Referenced by compute(), and populate_initial_matrixes().
static void populate_initial_matrixes (int mynum) [static]
Definition at line 153 of file parallelvm.c.
References DIM, matrix::m_data, mats, and multiply().
Referenced by computeall().
static void say (const char * fmt, ...) [static]
Definition at line 95 of file parallelvm.c.
References STDOUT_FILENO, strlen(), va_end, va_start, vsnprintf(), and write().
Referenced by go().
static int status_is_failure (int status) [static]
Definition at line 222 of file parallelvm.c.
References WEXITSTATUS, WIFEXITED, and WIFSIGNALED.
Referenced by makeprocs().
static int trace (const struct matrix * m1) [static]
Definition at line 138 of file parallelvm.c.
References DIM, and matrix::m_data.
Referenced by answer().
Variable Documentation
struct matrix mats[NMATS] [static]
Definition at line 149 of file parallelvm.c.
Referenced by answer(), compute(), and populate_initial_matrixes().
const int right_answers[NJOBS] [static]
Initial value:
 {
        -1337312809,
        356204544,
        -537881911,
        -65406976,
        1952063315,
        -843894784,
        1597000869,
        -993925120,
        838840559,
        -1616928768,
        -182386335,
        -364554240,
        251084843,
        -61403136,
        295326333,
        1488013312,
        1901440647,
        0,
        -1901440647,
        -1488013312,
        -295326333,
        61403136,
        -251084843,
        364554240,
}
Definition at line 54 of file parallelvm.c.
Referenced by go().