Os/161: user/lib/libc/string/strerror.c File Reference
user/lib/libc/string/strerror.c File Reference
#include <string.h>
#include <kern/errmsg.h>
Functions
const char * strerror (int errcode)
Function Documentation
const char* strerror (int errcode)
Definition at line 37 of file strerror.c.
References NULL, panic(), sys_errlist, and sys_nerr.
Referenced by __printerr(), cleanup_rmdir(), cmd_progthread(), cmd_pwd(), common_prog(), cpu_create(), cvtest(), dev_create_vnode(), devnull_create(), docreatestress(), dofork(), domkdir(), doreadstress(), dorename(), dormdir(), dowritestress(), dowritestress2(), fstest_read(), fstest_remove(), fstest_write(), locktest(), make_computes(), make_sleepalots(), mallocstress(), menu_execute(), printfile(), recursive_cleanup(), run(), runthreads(), semtest(), set_std_fd(), setup(), sfs_rename(), tryattach_beep_to_ltimer(), tryattach_con_to_lser(), tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), tryattach_ltrace_to_lamebus(), tryattach_random_to_lrandom(), tryattach_rtclock_to_ltimer(), vfs_unmountall(), vnode_decopen(), vnode_decref(), vscomplain(), and whalemating().