Os/161: user/sbin/mksfs/disk.c File Reference
user/sbin/mksfs/disk.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <assert.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <err.h>
#include "support.h"
#include "disk.h"
Defines
#define HOSTSTRING "System/161 Disk Image"
#define BLOCKSIZE 512
Functions
void opendisk (const char *path)
uint32_t diskblocksize (void)
uint32_t diskblocks (void)
void diskwrite (const void *data, uint32_t block)
void diskread (void *data, uint32_t block)
void closedisk (void)
Variables
static int fd = -1
static uint32_t nblocks
Define Documentation
#define BLOCKSIZE 512
Definition at line 44 of file disk.c.
Referenced by diskblocksize(), diskread(), diskwrite(), and opendisk().
#define HOSTSTRING "System/161 Disk Image"
Definition at line 43 of file disk.c.
Referenced by opendisk().
Function Documentation
void closedisk (void)
Definition at line 174 of file disk.c.
References assert, close(), err(), and fd.
Referenced by main().
uint32_t diskblocks (void)
Definition at line 101 of file disk.c.
References assert, fd, and nblocks.
Referenced by main().
uint32_t diskblocksize (void)
Definition at line 94 of file disk.c.
References assert, BLOCKSIZE, and fd.
Referenced by main().
void diskread (void * data, uint32_t block)
Definition at line 141 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, fd, lseek(), read(), and SEEK_SET.
Referenced by adjust_filelinks(), check_bitmap(), check_dir(), check_indirect_block(), check_root_dir(), check_sb(), dirread(), dodirblock(), dumpbits(), dumpdir(), dumpsb(), and ibmap().
void diskwrite (const void * data, uint32_t block)
Definition at line 108 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, fd, lseek(), SEEK_SET, and write().
Referenced by adjust_filelinks(), check_bitmap(), check_dir(), check_indirect_block(), check_root_dir(), check_sb(), dirwrite(), writebitmap(), writerootdir(), and writesuper().
void opendisk (const char * path)
Definition at line 54 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, errx(), fd, fstat(), HOSTSTRING, nblocks, O_RDWR, open(), read(), stat::st_size, strcmp(), and strlen().
Referenced by main().
Variable Documentation
int fd = -1 [static]
Definition at line 50 of file disk.c.
Referenced by assemble(), cat(), checksum_file(), closedisk(), concur(), create_testfile(), dir_test(), diskblocks(), diskblocksize(), diskread(), diskwrite(), docreate(), doopen(), dovalidate(), ftruncate_fd_device(), ftruncate_size_neg(), genkeys_sub(), getsize(), isdir(), listdir(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), main(), mkfile(), open_badflags(), open_testfile(), opendisk(), print(), randomize(), readlink_file(), recursedir(), sortbins(), subproc_read(), subproc_write(), sys_open(), test2(), test3(), test4(), test6(), validate(), wait_siblings(), and wait_siblings_child().
uint32_t nblocks [static]
Definition at line 51 of file disk.c.
Referenced by diskblocks(), dumpbits(), dumpdir(), main(), opendisk(), sfs_io(), and writebitmap().