Os/161: user/testbin/badcall/common_path.c File Reference
user/testbin/badcall/common_path.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Defines
#define T(call)
#define T2(call)
Functions
static int open_badpath (const char *path)
static int remove_badpath (const char *path)
static int rename_badpath1 (const char *path)
static int rename_badpath2 (const char *path)
static int link_badpath1 (const char *path)
static int link_badpath2 (const char *path)
static int mkdir_badpath (const char *path)
static int rmdir_badpath (const char *path)
static int chdir_badpath (const char *path)
static int symlink_badpath1 (const char *path)
static int symlink_badpath2 (const char *path)
static int readlink_badpath (const char *path)
static int lstat_badpath (const char *name)
static int stat_badpath (const char *name)
static void common_badpath (int(*func)(const char *path), int mk, int rm, const char *path, const char *call, const char *pathdesc)
static void any_badpath (int(*func)(const char *path), const char *call, int mk, int rm)
T (open)
T (remove)
T (mkdir)
T (rmdir)
T (chdir)
T (readlink)
T (stat)
T (lstat)
T2 (rename)
T2 (link)
T2 (symlink)
Define Documentation
#define T (call)
Value:
void                                  \
  test_##call##_path(void)              \
  {                                     \
        any_badpath(call##_badpath, #call, 0, 0); \
  }
Definition at line 185 of file common_path.c.
#define T2 (call)
Value:
void                                  \
  test_##call##_paths(void)             \
  {                                     \
        any_badpath(call##_badpath1, #call "(arg1)", 0, 1); \
        any_badpath(call##_badpath2, #call "(arg2)", 1, 1); \
  }
Definition at line 202 of file common_path.c.
Function Documentation
static void any_badpath (int(*)(const char *path) func, const char * call, int mk, int rm) [static]
Definition at line 175 of file common_path.c.
References common_badpath(), and NULL.
static int chdir_badpath (const char * path) [static]
Definition at line 105 of file common_path.c.
References chdir().
static void common_badpath (int(*)(const char *path) func, int mk, int rm, const char * path, const char * call, const char * pathdesc) [static]
Definition at line 152 of file common_path.c.
References create_testfile(), EFAULT, errno, report_test(), snprintf(), and TESTFILE.
Referenced by any_badpath().
static int link_badpath1 (const char * path) [static]
Definition at line 77 of file common_path.c.
References link(), and TESTFILE.
static int link_badpath2 (const char * path) [static]
Definition at line 84 of file common_path.c.
References link(), and TESTFILE.
static int lstat_badpath (const char * name) [static]
Definition at line 134 of file common_path.c.
References lstat().
static int mkdir_badpath (const char * path) [static]
Definition at line 91 of file common_path.c.
References mkdir().
static int open_badpath (const char * path) [static]
Definition at line 49 of file common_path.c.
References O_RDONLY, and open().
static int readlink_badpath (const char * path) [static]
Definition at line 126 of file common_path.c.
References readlink().
static int remove_badpath (const char * path) [static]
Definition at line 56 of file common_path.c.
static int rename_badpath1 (const char * path) [static]
Definition at line 63 of file common_path.c.
References rename(), and TESTFILE.
static int rename_badpath2 (const char * path) [static]
Definition at line 70 of file common_path.c.
References rename(), and TESTFILE.
static int rmdir_badpath (const char * path) [static]
Definition at line 98 of file common_path.c.
References rmdir().
static int stat_badpath (const char * name) [static]
Definition at line 142 of file common_path.c.
References stat().
static int symlink_badpath1 (const char * path) [static]
Definition at line 112 of file common_path.c.
References symlink(), and TESTFILE.
static int symlink_badpath2 (const char * path) [static]
Definition at line 119 of file common_path.c.
References symlink(), and TESTFILE.
T (lstat)
T (stat)
T (readlink)
T (chdir)
T (rmdir)
T (mkdir)
T (remove)
T (open)
T2 (symlink)
T2 (link)
T2 (rename)