Os/161: user/sbin/mksfs/mksfs.c File Reference
user/sbin/mksfs/mksfs.c File Reference
#include <sys/types.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>
#include <limits.h>
#include <err.h>
#include "support.h"
#include "kern/sfs.h"
#include "disk.h"
Defines
#define SWAPL(x) (x)
#define SWAPS(x) (x)
#define MAXBITBLOCKS 32
Functions
static void check (void)
static void writesuper (const char *volname, uint32_t nblocks)
static void writerootdir (void)
static void doallocbit (uint32_t bit)
static void writebitmap (uint32_t fsblocks)
int main (int argc, char **argv)
Variables
static char bitbuf [MAXBITBLOCKS *SFS_BLOCKSIZE]
Define Documentation
#define MAXBITBLOCKS 32
Definition at line 58 of file mksfs.c.
Referenced by writebitmap().
#define SWAPL (x) (x)
Definition at line 51 of file mksfs.c.
#define SWAPS (x) (x)
Definition at line 52 of file mksfs.c.
Function Documentation
static void check (void) [static]
Definition at line 62 of file mksfs.c.
References assert, and SFS_BLOCKSIZE.
Referenced by main().
static void doallocbit (uint32_t bit) [static]
Definition at line 107 of file mksfs.c.
References assert, bitbuf, and CHAR_BIT.
Referenced by writebitmap().
int main (int argc, char ** argv)
Definition at line 147 of file mksfs.c.
References check(), closedisk(), diskblocks(), diskblocksize(), errx(), hostcompat_init(), NULL, opendisk(), SFS_BLOCKSIZE, strchr(), strlen(), writebitmap(), writerootdir(), and writesuper().
static void writebitmap (uint32_t fsblocks) [static]
Definition at line 118 of file mksfs.c.
References bitbuf, diskwrite(), doallocbit(), errx(), MAXBITBLOCKS, nblocks, SFS_BITBLOCKS, SFS_BITMAPSIZE, SFS_BLOCKSIZE, SFS_MAP_LOCATION, SFS_ROOT_LOCATION, and SFS_SB_LOCATION.
Referenced by main().
static void writerootdir (void) [static]
Definition at line 90 of file mksfs.c.
References bzero(), diskwrite(), SFS_ROOT_LOCATION, SFS_TYPE_DIR, SWAPL, and SWAPS.
Referenced by main().
static void writesuper (const char * volname, uint32_t nblocks) [static]
Definition at line 71 of file mksfs.c.
References bzero(), diskwrite(), errx(), SFS_MAGIC, SFS_SB_LOCATION, SFS_VOLNAME_SIZE, strcpy(), strlen(), and SWAPL.
Referenced by main().
Variable Documentation
char bitbuf[MAXBITBLOCKS *SFS_BLOCKSIZE] [static]
Definition at line 103 of file mksfs.c.
Referenced by doallocbit(), and writebitmap().