Os/161: user/testbin/badcall/bad_mkdir.c File Reference
user/testbin/badcall/bad_mkdir.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void mkdir_dot (void)
static void mkdir_dotdot (void)
static void mkdir_empty (void)
void test_mkdir (void)
Function Documentation
static void mkdir_dot (void) [static]
Definition at line 48 of file bad_mkdir.c.
References EEXIST, errno, mkdir(), and report_test().
Referenced by test_mkdir().
static void mkdir_dotdot (void) [static]
Definition at line 58 of file bad_mkdir.c.
References EEXIST, errno, mkdir(), and report_test().
Referenced by test_mkdir().
static void mkdir_empty (void) [static]
Definition at line 68 of file bad_mkdir.c.
References EINVAL, errno, mkdir(), and report_test().
Referenced by test_mkdir().
void test_mkdir (void)
Definition at line 76 of file bad_mkdir.c.
References mkdir_dot(), mkdir_dotdot(), mkdir_empty(), and test_mkdir_path().