Os/161: user/sbin/sfsck/sfsck.c File Reference
user/sbin/sfsck/sfsck.c File Reference
#include <sys/types.h>
#include <assert.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <err.h>
#include "support.h"
#include "kern/sfs.h"
#include "disk.h"
Data Structures
struct inodememory
Defines
#define SWAPL(x) (x)
#define SWAPS(x) (x)
#define NO_REALLOC
#define NO_QSORT
#define EXIT_USAGE 4
#define EXIT_FATAL 3
#define EXIT_UNRECOV 2
#define EXIT_RECOV 1
#define EXIT_CLEAN 0
#define BMAP_ND SFS_NDIRECT
#define BMAP_D(sfi, x) ((sfi)->sfi_direct[(x)])
#define BMAP_NI 1
#define BMAP_I(sfi, x) ((void)(x), (sfi)->sfi_indirect)
#define BMAP_NII 0
#define BMAP_II(sfi, x) ((void)(x), (void)(sfi), 0)
#define BMAP_NIII 0
#define BMAP_III(sfi, x) ((void)(x), (void)(sfi), 0)
#define BMAP_DMAX BMAP_ND
#define BMAP_IMAX (BMAP_DMAX+SFS_DBPERIDB*BMAP_NI)
#define BMAP_IIMAX (BMAP_IMAX+SFS_DBPERIDB*BMAP_NII)
#define BMAP_IIIMAX (BMAP_IIMAX+SFS_DBPERIDB*BMAP_NIII)
#define BMAP_DSIZE 1
#define BMAP_ISIZE (BMAP_DSIZE*SFS_DBPERIDB)
#define BMAP_IISIZE (BMAP_ISIZE*SFS_DBPERIDB)
#define BMAP_IIISIZE (BMAP_IISIZE*SFS_DBPERIDB)
Enumerations
enum blockusage_t {
B_SUPERBLOCK, B_BITBLOCK, B_INODE, B_IBLOCK,
B_DIRDATA, B_DATA, B_TOFREE, B_PASTEND
}
Functions
static void setbadness (int code)
static void swapsb (struct sfs_super *sp)
static void swapinode (struct sfs_inode *sfi)
static void swapdir (struct sfs_dir *sfd)
static void swapindir (uint32_t *entries)
static void swapbits (uint8_t *bits)
static void * domalloc (size_t len)
static void bitmap_init (uint32_t bitblocks)
static const char * blockusagestr (blockusage_t how, uint32_t howdesc)
static void bitmap_mark (uint32_t block, blockusage_t how, uint32_t howdesc)
static int countbits (uint8_t val)
static void reportbits (uint32_t bitblock, uint32_t byte, uint8_t val, const char *what)
static void check_bitmap (void)
static void addmemory (uint32_t ino, uint32_t linkcount)
static int remember_dir (uint32_t ino, const char *pathsofar)
static void observe_filelink (uint32_t ino)
static void adjust_filelinks (void)
static int checknullstring (char *buf, size_t maxlen)
static int checkbadstring (char *buf)
static void check_sb (void)
static void check_indirect_block (uint32_t ino, uint32_t *ientry, uint32_t *blockp, uint32_t nblocks, uint32_t *badcountp, int isdir, int indirection)
static int check_inode_blocks (uint32_t ino, struct sfs_inode *sfi, int isdir)
static uint32_t ibmap (uint32_t iblock, uint32_t offset, uint32_t entrysize)
static uint32_t dobmap (const struct sfs_inode *sfi, uint32_t fileblock)
static void dirread (struct sfs_inode *sfi, struct sfs_dir *d, unsigned nd)
static void dirwrite (const struct sfs_inode *sfi, struct sfs_dir *d, int nd)
static int dirsortfunc (const void *aa, const void *bb)
static void qsort (int *data, int num, size_t size, int(*f)(const void *, const void *))
static void sortdir (int *vector, struct sfs_dir *d, int nd)
static int dir_tryadd (struct sfs_dir *d, int nd, const char *name, uint32_t ino)
static int check_dir_entry (const char *pathsofar, uint32_t index, struct sfs_dir *sfd)
static int check_dir (uint32_t ino, uint32_t parentino, const char *pathsofar)
static void check_root_dir (void)
int main (int argc, char **argv)
Variables
static int badness = 0
static uint32_t nblocks
static uint32_t bitblocks
static uint32_t uniquecounter = 1
static unsigned long count_blocks = 0
static unsigned long count_dirs = 0
static unsigned long count_files = 0
static uint8_t * bitmapdata
static uint8_t * tofreedata
static struct inodememory * inodes = NULL
static int ninodes = 0
static int maxinodes = 0
static struct sfs_dir * global_sortdirs
Define Documentation
#define BMAP_D (sfi, x) ((sfi)->sfi_direct[(x)])
Definition at line 733 of file sfsck.c.
Referenced by dobmap().
#define BMAP_DMAX BMAP_ND
Definition at line 769 of file sfsck.c.
Referenced by dobmap().
#define BMAP_DSIZE 1
Definition at line 774 of file sfsck.c.
Referenced by dobmap().
#define BMAP_I (sfi, x) ((void)(x), (sfi)->sfi_indirect)
Definition at line 740 of file sfsck.c.
Referenced by dobmap().
#define BMAP_II (sfi, x) ((void)(x), (void)(sfi), 0)
Definition at line 752 of file sfsck.c.
Referenced by dobmap().
#define BMAP_III (sfi, x) ((void)(x), (void)(sfi), 0)
Definition at line 765 of file sfsck.c.
Referenced by dobmap().
#define BMAP_IIIMAX (BMAP_IIMAX+SFS_DBPERIDB*BMAP_NIII)
Definition at line 772 of file sfsck.c.
Referenced by dobmap().
#define BMAP_IIISIZE (BMAP_IISIZE*SFS_DBPERIDB)
Definition at line 777 of file sfsck.c.
Referenced by dobmap().
#define BMAP_IIMAX (BMAP_IMAX+SFS_DBPERIDB*BMAP_NII)
Definition at line 771 of file sfsck.c.
Referenced by dobmap().
#define BMAP_IISIZE (BMAP_ISIZE*SFS_DBPERIDB)
Definition at line 776 of file sfsck.c.
Referenced by dobmap().
#define BMAP_IMAX (BMAP_DMAX+SFS_DBPERIDB*BMAP_NI)
Definition at line 770 of file sfsck.c.
Referenced by dobmap().
#define BMAP_ISIZE (BMAP_DSIZE*SFS_DBPERIDB)
Definition at line 775 of file sfsck.c.
Referenced by dobmap().
#define BMAP_ND SFS_NDIRECT
Definition at line 732 of file sfsck.c.
#define BMAP_NI 1
Definition at line 739 of file sfsck.c.
#define BMAP_NII 0
Definition at line 751 of file sfsck.c.
#define BMAP_NIII 0
Definition at line 764 of file sfsck.c.
#define EXIT_CLEAN 0
Definition at line 65 of file sfsck.c.
Referenced by main().
#define EXIT_FATAL 3
Definition at line 62 of file sfsck.c.
Referenced by addmemory(), domalloc(), and main().
#define EXIT_RECOV 1
Definition at line 64 of file sfsck.c.
Referenced by adjust_filelinks(), check_bitmap(), check_dir(), check_dir_entry(), check_inode_blocks(), check_root_dir(), check_sb(), and main().
#define EXIT_UNRECOV 2
Definition at line 63 of file sfsck.c.
Referenced by bitmap_mark(), check_dir(), check_sb(), dirwrite(), and main().
#define EXIT_USAGE 4
Definition at line 61 of file sfsck.c.
Referenced by main().
#define NO_QSORT
Definition at line 54 of file sfsck.c.
#define NO_REALLOC
Definition at line 53 of file sfsck.c.
#define SWAPL (x) (x)
Definition at line 51 of file sfsck.c.
#define SWAPS (x) (x)
Definition at line 52 of file sfsck.c.
Enumeration Type Documentation
enum blockusage_t
Enumerator:
B_SUPERBLOCK
B_BITBLOCK
B_INODE
B_IBLOCK
B_DIRDATA
B_DATA
B_TOFREE
B_PASTEND
Definition at line 172 of file sfsck.c.
Function Documentation
static void addmemory (uint32_t ino, uint32_t linkcount) [static]
Definition at line 386 of file sfsck.c.
References assert, domalloc(), errx(), EXIT_FATAL, free(), inodememory::ino, inodememory::linkcount, maxinodes, memcpy(), ninodes, and NULL.
Referenced by observe_filelink(), and remember_dir().
static void adjust_filelinks (void) [static]
Definition at line 450 of file sfsck.c.
References assert, count_files, diskread(), diskwrite(), EXIT_RECOV, inodememory::linkcount, ninodes, setbadness(), sfs_inode::sfi_linkcount, sfs_inode::sfi_type, SFS_TYPE_FILE, swapinode(), and warnx().
Referenced by main().
static void bitmap_init (uint32_t bitblocks) [static]
Definition at line 195 of file sfsck.c.
References bitmapdata, domalloc(), SFS_BLOCKSIZE, and tofreedata.
Referenced by check_sb().
static void bitmap_mark (uint32_t block, blockusage_t how, uint32_t howdesc) [static]
Definition at line 237 of file sfsck.c.
References B_PASTEND, B_TOFREE, bitmapdata, blockusagestr(), count_blocks, EXIT_UNRECOV, setbadness(), tofreedata, and warnx().
static const char* blockusagestr (blockusage_t how, uint32_t howdesc) [static]
Definition at line 207 of file sfsck.c.
References assert, B_BITBLOCK, B_DATA, B_DIRDATA, B_IBLOCK, B_INODE, B_PASTEND, B_SUPERBLOCK, B_TOFREE, and snprintf().
Referenced by bitmap_mark().
static void check_bitmap (void) [static]
Definition at line 304 of file sfsck.c.
References assert, bitblocks, bitmapdata, countbits(), diskread(), diskwrite(), EXIT_RECOV, reportbits(), setbadness(), SFS_BLOCKSIZE, SFS_MAP_LOCATION, swapbits(), tofreedata, and warnx().
Referenced by main().
static int check_dir (uint32_t ino, uint32_t parentino, const char * pathsofar) [static]
Definition at line 971 of file sfsck.c.
References assert, B_INODE, bitmap_mark(), bzero(), check_dir_entry(), check_inode_blocks(), count_dirs, dir_tryadd(), dirread(), dirwrite(), diskread(), diskwrite(), domalloc(), EXIT_RECOV, EXIT_UNRECOV, free(), observe_filelink(), remember_dir(), setbadness(), sfs_dir::sfd_ino, sfs_dir::sfd_name, sfs_inode::sfi_linkcount, sfs_inode::sfi_size, sfs_inode::sfi_type, SFS_BLOCKSIZE, SFS_NAMELEN, SFS_NOINO, SFS_ROUNDUP, SFS_TYPE_DIR, SFS_TYPE_FILE, snprintf(), sortdir(), strcmp(), strlen(), swapinode(), uniquecounter, and warnx().
Referenced by check_root_dir().
static int check_dir_entry (const char * pathsofar, uint32_t index, struct sfs_dir * sfd) [static]
Definition at line 923 of file sfsck.c.
References checkbadstring(), checknullstring(), EXIT_RECOV, setbadness(), sfs_dir::sfd_ino, sfs_dir::sfd_name, SFS_NOINO, snprintf(), uniquecounter, and warnx().
Referenced by check_dir().
static void check_indirect_block (uint32_t ino, uint32_t * ientry, uint32_t * blockp, uint32_t nblocks, uint32_t * badcountp, int isdir, int indirection) [static]
Definition at line 563 of file sfsck.c.
References assert, B_DATA, B_DIRDATA, B_IBLOCK, B_TOFREE, bitmap_mark(), diskread(), diskwrite(), SFS_DBPERIDB, and swapindir().
Referenced by check_inode_blocks().
static int check_inode_blocks (uint32_t ino, struct sfs_inode * sfi, int isdir) [static]
Definition at line 637 of file sfsck.c.
References B_DATA, B_DIRDATA, B_TOFREE, bitmap_mark(), check_indirect_block(), EXIT_RECOV, nblocks, setbadness(), sfs_inode::sfi_direct, sfs_inode::sfi_indirect, sfs_inode::sfi_size, SFS_BLOCKSIZE, SFS_NDIRECT, SFS_ROUNDUP, and warnx().
Referenced by check_dir().
static void check_root_dir (void) [static]
Definition at line 1215 of file sfsck.c.
References check_dir(), diskread(), diskwrite(), EXIT_RECOV, setbadness(), sfs_inode::sfi_type, SFS_ROOT_LOCATION, SFS_TYPE_DIR, SFS_TYPE_FILE, swapinode(), and warnx().
Referenced by main().
static void check_sb (void) [static]
Definition at line 513 of file sfsck.c.
References assert, B_BITBLOCK, B_PASTEND, B_SUPERBLOCK, bitblocks, bitmap_init(), bitmap_mark(), checkbadstring(), checknullstring(), diskread(), diskwrite(), errx(), EXIT_RECOV, EXIT_UNRECOV, nblocks, setbadness(), SFS_BITBLOCKS, SFS_BLOCKBITS, SFS_MAGIC, SFS_MAP_LOCATION, SFS_SB_LOCATION, sfs_super::sp_magic, sfs_super::sp_nblocks, sfs_super::sp_volname, swapsb(), and warnx().
Referenced by main().
static int checkbadstring (char * buf) [static]
Definition at line 495 of file sfsck.c.
Referenced by check_dir_entry(), and check_sb().
static int checknullstring (char * buf, size_t maxlen) [static]
Definition at line 481 of file sfsck.c.
Referenced by check_dir_entry(), and check_sb().
static int countbits (uint8_t val) [static]
Definition at line 275 of file sfsck.c.
Referenced by check_bitmap().
static int dir_tryadd (struct sfs_dir * d, int nd, const char * name, uint32_t ino) [static]
Definition at line 907 of file sfsck.c.
References assert, sfs_dir::sfd_ino, sfs_dir::sfd_name, SFS_NOINO, strcpy(), and strlen().
Referenced by check_dir().
static void dirread (struct sfs_inode * sfi, struct sfs_dir * d, unsigned nd) [static]
Definition at line 808 of file sfsck.c.
References bzero(), diskread(), dobmap(), nblocks, SFS_BLOCKSIZE, SFS_ROUNDUP, swapdir(), and warnx().
Referenced by check_dir().
static int dirsortfunc (const void * aa, const void * bb) [static]
Definition at line 866 of file sfsck.c.
References sfs_dir::sfd_name, and strcmp().
Referenced by sortdir().
static void dirwrite (const struct sfs_inode * sfi, struct sfs_dir * d, int nd) [static]
Definition at line 831 of file sfsck.c.
References diskwrite(), dobmap(), EXIT_UNRECOV, nblocks, setbadness(), sfs_dir::sfd_ino, sfs_dir::sfd_name, SFS_BLOCKSIZE, SFS_NOINO, SFS_ROUNDUP, swapdir(), and warnx().
Referenced by check_dir().
static uint32_t dobmap (const struct sfs_inode * sfi, uint32_t fileblock) [static]
Definition at line 781 of file sfsck.c.
References BMAP_D, BMAP_DMAX, BMAP_DSIZE, BMAP_I, BMAP_II, BMAP_III, BMAP_IIIMAX, BMAP_IIISIZE, BMAP_IIMAX, BMAP_IISIZE, BMAP_IMAX, BMAP_ISIZE, and ibmap().
Referenced by dirread(), and dirwrite().
static void* domalloc (size_t len) [static]
Definition at line 160 of file sfsck.c.
References errx(), EXIT_FATAL, malloc(), and NULL.
Referenced by addmemory(), bitmap_init(), and check_dir().
static uint32_t ibmap (uint32_t iblock, uint32_t offset, uint32_t entrysize) [static]
Definition at line 710 of file sfsck.c.
References assert, diskread(), SFS_DBPERIDB, and swapindir().
Referenced by dobmap().
int main (int argc, char ** argv)
Definition at line 1244 of file sfsck.c.
References adjust_filelinks(), assert, badness, check_bitmap(), check_root_dir(), check_sb(), closedisk(), count_blocks, count_dirs, count_files, errx(), EXIT_CLEAN, EXIT_FATAL, EXIT_RECOV, EXIT_UNRECOV, EXIT_USAGE, hostcompat_init(), nblocks, opendisk(), SFS_BLOCKSIZE, and warnx().
static void observe_filelink (uint32_t ino) [static]
Definition at line 434 of file sfsck.c.
References addmemory(), assert, B_INODE, bitmap_mark(), inodememory::linkcount, and ninodes.
Referenced by check_dir().
static void qsort (int * data, int num, size_t size, int(*)(const void *, const void *) f) [static]
Definition at line 878 of file sfsck.c.
References f.
Referenced by sortdir().
static int remember_dir (uint32_t ino, const char * pathsofar) [static]
Definition at line 413 of file sfsck.c.
References addmemory(), assert, inodememory::linkcount, and ninodes.
Referenced by check_dir().
static void reportbits (uint32_t bitblock, uint32_t byte, uint8_t val, const char * what) [static]
Definition at line 288 of file sfsck.c.
References CHAR_BIT, SFS_BLOCKBITS, and warnx().
Referenced by check_bitmap().
static void setbadness (int code) [static]
Definition at line 71 of file sfsck.c.
References badness.
Referenced by adjust_filelinks(), bitmap_mark(), check_bitmap(), check_dir(), check_dir_entry(), check_inode_blocks(), check_root_dir(), check_sb(), and dirwrite().
static void sortdir (int * vector, struct sfs_dir * d, int nd) [static]
Definition at line 898 of file sfsck.c.
References dirsortfunc(), and qsort().
Referenced by check_dir().
static void swapbits (uint8_t * bits) [static]
Definition at line 150 of file sfsck.c.
Referenced by check_bitmap().
static void swapdir (struct sfs_dir * sfd) [static]
Definition at line 133 of file sfsck.c.
References sfs_dir::sfd_ino, and SWAPL.
Referenced by dirread(), and dirwrite().
static void swapindir (uint32_t * entries) [static]
Definition at line 140 of file sfsck.c.
References SFS_DBPERIDB, and SWAPL.
Referenced by check_indirect_block(), and ibmap().
static void swapinode (struct sfs_inode * sfi) [static]
Definition at line 90 of file sfsck.c.
References sfs_inode::sfi_direct, sfs_inode::sfi_indirect, sfs_inode::sfi_linkcount, sfs_inode::sfi_size, sfs_inode::sfi_type, SFS_NDIRECT, SWAPL, and SWAPS.
Referenced by adjust_filelinks(), check_dir(), and check_root_dir().
static void swapsb (struct sfs_super * sp) [static]
Definition at line 82 of file sfsck.c.
References sfs_super::sp_magic, sfs_super::sp_nblocks, and SWAPL.
Referenced by check_sb().
Variable Documentation
int badness = 0 [static]
Definition at line 67 of file sfsck.c.
Referenced by main(), and setbadness().
uint32_t bitblocks [static]
Definition at line 183 of file sfsck.c.
Referenced by check_bitmap(), and check_sb().
uint8_t* bitmapdata [static]
Definition at line 190 of file sfsck.c.
Referenced by bitmap_init(), bitmap_mark(), and check_bitmap().
unsigned long count_blocks = 0 [static]
Definition at line 186 of file sfsck.c.
Referenced by bitmap_mark(), and main().
unsigned long count_dirs = 0 [static]
Definition at line 186 of file sfsck.c.
Referenced by check_dir(), and main().
unsigned long count_files = 0 [static]
Definition at line 186 of file sfsck.c.
Referenced by adjust_filelinks(), and main().
struct sfs_dir* global_sortdirs [static]
Definition at line 863 of file sfsck.c.
struct inodememory* inodes = NULL [static]
Definition at line 381 of file sfsck.c.
int maxinodes = 0 [static]
Definition at line 382 of file sfsck.c.
Referenced by addmemory().
uint32_t nblocks [static]
Definition at line 183 of file sfsck.c.
Referenced by check_inode_blocks(), check_sb(), dirread(), dirwrite(), and main().
int ninodes = 0 [static]
Definition at line 382 of file sfsck.c.
Referenced by addmemory(), adjust_filelinks(), observe_filelink(), and remember_dir().
uint8_t* tofreedata [static]
Definition at line 191 of file sfsck.c.
Referenced by bitmap_init(), bitmap_mark(), and check_bitmap().
uint32_t uniquecounter = 1 [static]
Definition at line 184 of file sfsck.c.
Referenced by check_dir(), and check_dir_entry().