Os/161: user/testbin/tail/tail.c File Reference
user/testbin/tail/tail.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <err.h>
Defines
#define BUFSIZE 1000
Functions
static void tail (int file, off_t where, const char *filename)
int main (int argc, char **argv)
Variables
char buffer [BUFSIZE]
Define Documentation
#define BUFSIZE 1000
Definition at line 43 of file tail.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 66 of file tail.c.
References atoi(), close(), err(), errx(), O_RDONLY, open(), and tail().
static void tail (int file, off_t where, const char * filename) [static]
Definition at line 52 of file tail.c.
References buffer, err(), lseek(), read(), SEEK_SET, STDOUT_FILENO, and write().
Referenced by main(), and strtok_r().
Variable Documentation
char buffer[BUFSIZE]
Definition at line 48 of file tail.c.
Referenced by tail().