Os/161: user/testbin/badcall/bad_dup2.c File Reference
user/testbin/badcall/bad_dup2.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void dup2_fd2 (int fd, const char *desc)
static void dup2_self (void)
void test_dup2 (void)
Function Documentation
static void dup2_fd2 (int fd, const char * desc) [static]
Definition at line 49 of file bad_dup2.c.
References close(), dup2(), EBADF, errno, report_test(), and STDIN_FILENO.
Referenced by test_dup2().
static void dup2_self (void) [static]
Definition at line 63 of file bad_dup2.c.
References close(), CLOSED_FD, dup2(), ENOSYS, errno, ESPIPE, EUNIMP, fstat(), lseek(), SEEK_CUR, STDIN_FILENO, warn(), and warnx().
Referenced by test_dup2().
void test_dup2 (void)
Definition at line 111 of file bad_dup2.c.
References dup2_fd2(), dup2_self(), IMPOSSIBLE_FD, OPEN_MAX, test_dup2_fd(), and warnx().