Os/161: user/testbin/badcall/bad_sbrk.c File Reference
user/testbin/badcall/bad_sbrk.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static int try_sbrk (long val)
static void enforce_sbrk (long val, const char *desc, int err)
static void sbrk_bigpos (void)
static void sbrk_bigneg (void)
static void sbrk_neg (void)
static void sbrk_unalignedpos (void)
static void sbrk_unalignedneg (void)
void test_sbrk (void)
Function Documentation
static void enforce_sbrk (long val, const char * desc, int err) [static]
Definition at line 60 of file bad_sbrk.c.
References errno, try_sbrk(), warn(), and warnx().
Referenced by sbrk_bigneg(), sbrk_bigpos(), and sbrk_neg().
static void sbrk_bigneg (void) [static]
Definition at line 86 of file bad_sbrk.c.
References EINVAL, and enforce_sbrk().
Referenced by test_sbrk().
static void sbrk_bigpos (void) [static]
Definition at line 79 of file bad_sbrk.c.
References enforce_sbrk(), and ENOMEM.
Referenced by test_sbrk().
static void sbrk_neg (void) [static]
Definition at line 93 of file bad_sbrk.c.
References EINVAL, and enforce_sbrk().
Referenced by test_sbrk().
static void sbrk_unalignedneg (void) [static]
Definition at line 115 of file bad_sbrk.c.
References EINVAL, try_sbrk(), warn(), and warnx().
Referenced by test_sbrk().
static void sbrk_unalignedpos (void) [static]
Definition at line 100 of file bad_sbrk.c.
References EINVAL, try_sbrk(), warn(), and warnx().
Referenced by test_sbrk().
void test_sbrk (void)
Definition at line 129 of file bad_sbrk.c.
References sbrk_bigneg(), sbrk_bigpos(), sbrk_neg(), sbrk_unalignedneg(), and sbrk_unalignedpos().
static int try_sbrk (long val) [static]
Definition at line 48 of file bad_sbrk.c.
References errno, and sbrk().
Referenced by enforce_sbrk(), sbrk_unalignedneg(), and sbrk_unalignedpos().