Os/161: user/testbin/badcall/bad_pipe.c File Reference
user/testbin/badcall/bad_pipe.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void pipe_badptr (void *ptr, const char *desc)
static void pipe_unaligned (void)
void test_pipe (void)
Function Documentation
static void pipe_badptr (void * ptr, const char * desc) [static]
Definition at line 48 of file bad_pipe.c.
References EFAULT, errno, pipe(), and report_test().
Referenced by test_pipe().
static void pipe_unaligned (void) [static]
Definition at line 58 of file bad_pipe.c.
References errno, pipe(), and report_survival().
Referenced by test_pipe().
void test_pipe (void)
Definition at line 71 of file bad_pipe.c.
References NULL, pipe_badptr(), and pipe_unaligned().