Os/161: user/lib/libc/stdlib/malloc.c File Reference
user/lib/libc/stdlib/malloc.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include <err.h>
#include <stdint.h>
Data Structures
struct mheader
Defines
#define M_NEXTOFF(mh) ((size_t)(((size_t)((mh)->mh_nextblock))<<MBLOCKSHIFT))
#define M_PREVOFF(mh) ((size_t)(((size_t)((mh)->mh_prevblock))<<MBLOCKSHIFT))
#define M_NEXT(mh) ((struct mheader *)(((char*)(mh))+M_NEXTOFF(mh)))
#define M_PREV(mh) ((struct mheader *)(((char*)(mh))-M_PREVOFF(mh)))
#define M_DATA(mh) ((void *)((mh)+1))
#define M_SIZE(mh) (M_NEXTOFF(mh)-MBLOCKSIZE)
#define M_OK(mh) ((mh)->mh_magic1==MMAGIC && (mh)->mh_magic2==MMAGIC)
#define M_MKFIELD(off) ((off)>>MBLOCKSHIFT)
Functions
static void __malloc_init (void)
static void * __malloc_sbrk (size_t size)
static void __malloc_split (struct mheader *mh, size_t size)
void * malloc (size_t size)
static void __malloc_deadbeef (void *ptr, size_t size)
static void __malloc_trymerge (struct mheader *mh, struct mheader *mhnext)
void free (void *x)
Variables
static uintptr_t __heapbase
static uintptr_t __heaptop
Define Documentation
#define M_DATA (mh) ((void *)((mh)+1))
Definition at line 129 of file malloc.c.
Referenced by free(), and malloc().
#define M_MKFIELD (off) ((off)>>MBLOCKSHIFT)
Definition at line 134 of file malloc.c.
Referenced by __malloc_split(), __malloc_trymerge(), and malloc().
#define M_NEXT (mh) ((struct mheader *)(((char*)(mh))+M_NEXTOFF(mh)))
Definition at line 126 of file malloc.c.
Referenced by __malloc_split(), __malloc_trymerge(), and free().
#define M_NEXTOFF (mh) ((size_t)(((size_t)((mh)->mh_nextblock))<<MBLOCKSHIFT))
Definition at line 124 of file malloc.c.
Referenced by malloc().
#define M_OK (mh) ((mh)->mh_magic1==MMAGIC && (mh)->mh_magic2==MMAGIC)
Definition at line 132 of file malloc.c.
Referenced by free(), and malloc().
#define M_PREV (mh) ((struct mheader *)(((char*)(mh))-M_PREVOFF(mh)))
Definition at line 127 of file malloc.c.
Referenced by free().
#define M_PREVOFF (mh) ((size_t)(((size_t)((mh)->mh_prevblock))<<MBLOCKSHIFT))
Definition at line 125 of file malloc.c.
#define M_SIZE (mh) (M_NEXTOFF(mh)-MBLOCKSIZE)
Definition at line 130 of file malloc.c.
Referenced by __malloc_split(), __malloc_trymerge(), free(), and malloc().
Function Documentation
static void __malloc_deadbeef (void * ptr, size_t size) [static]
Definition at line 438 of file malloc.c.
Referenced by __malloc_trymerge(), and free().
static void __malloc_init (void) [static]
Definition at line 148 of file malloc.c.
References __heapbase, __heaptop, err(), errx(), sbrk(), and warnx().
Referenced by malloc().
static void* __malloc_sbrk (size_t size) [static]
Definition at line 263 of file malloc.c.
References errx(), NULL, and sbrk().
Referenced by malloc().
static void __malloc_split (struct mheader * mh, size_t size) [static]
Definition at line 292 of file malloc.c.
References errx(), M_MKFIELD, M_NEXT, and M_SIZE.
Referenced by malloc().
static void __malloc_trymerge (struct mheader * mh, struct mheader * mhnext) [static]
Definition at line 452 of file malloc.c.
References __malloc_deadbeef(), errx(), M_MKFIELD, M_NEXT, and M_SIZE.
Referenced by free().
void free (void * x)
Definition at line 482 of file malloc.c.
References __heapbase, __malloc_deadbeef(), __malloc_trymerge(), errx(), M_DATA, M_NEXT, M_OK, M_PREV, M_SIZE, NULL, and warnx().
Referenced by addmemory(), check_dir(), test1(), test2(), test3(), test4(), and test567().
void* malloc (size_t size)
Definition at line 333 of file malloc.c.
References __heapbase, __malloc_init(), __malloc_sbrk(), __malloc_split(), errx(), M_DATA, M_MKFIELD, M_NEXTOFF, M_OK, M_SIZE, NULL, and warnx().
Referenced by domalloc(), test1(), test2(), test3(), test4(), and test567().
Variable Documentation
uintptr_t __heapbase [static]
Definition at line 141 of file malloc.c.
Referenced by __malloc_init(), free(), and malloc().
uintptr_t __heaptop [static]
Definition at line 141 of file malloc.c.
Referenced by __malloc_init().