Os/161: user/testbin/hash/hash.c File Reference
user/testbin/hash/hash.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <err.h>
Defines
#define HASHP 104729
Functions
int main (int argc, char *argv[])
Define Documentation
#define HASHP 104729
Definition at line 50 of file hash.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 53 of file hash.c.
References close(), err(), errx(), fd, HASHP, hostcompat_init(), O_RDONLY, open(), printf(), and read().