Os/161: user/testbin/testfile/testfile.c File Reference
user/testbin/testfile/testfile.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 15 of file testfile.c.
References close(), dup2(), fd, lseek(), NULL, O_RDWR, open(), printf(), read(), SEEK_CUR, SEEK_END, SEEK_SET, and write().