Os/161: user/testbin/badcall/common_buf.c File Reference
user/testbin/badcall/common_buf.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Data Structures
struct buftest
Defines
#define T(call)
Functions
static int read_setup (void)
static int read_badbuf (void *buf)
static void read_cleanup (void)
static int write_setup (void)
static int write_badbuf (void *ptr)
static void write_cleanup (void)
static int getdirentry_setup (void)
static int getdirentry_badbuf (void *ptr)
static void getdirentry_cleanup (void)
static int readlink_setup (void)
static int readlink_badbuf (void *buf)
static void readlink_cleanup (void)
static int getcwd_setup (void)
static void getcwd_cleanup (void)
static int getcwd_badbuf (void *buf)
static void common_badbuf (struct buftest *info, void *buf, const char *bufdesc)
static void any_badbuf (struct buftest *info)
T (read)
T (write)
T (getdirentry)
T (readlink)
T (getcwd)
Variables
static int buf_fd
Define Documentation
#define T (call)
Value:
void                                    \
  test_##call##_buf(void)               \
  {                                     \
        static struct buftest info = {  \
                call##_setup,           \
                call##_badbuf,          \
                call##_cleanup,         \
                #call,                  \
        };                              \
        any_badbuf(&info);              \
  }
Definition at line 203 of file common_buf.c.
Referenced by main().
Function Documentation
static void any_badbuf (struct buftest * info) [static]
Definition at line 194 of file common_buf.c.
References common_badbuf(), and NULL.
static void common_badbuf (struct buftest * info, void * buf, const char * bufdesc) [static]
Definition at line 179 of file common_buf.c.
References buftest::cleanup, EFAULT, errno, buftest::name, buftest::op, report_test(), buftest::setup, and snprintf().
Referenced by any_badbuf().
static int getcwd_badbuf (void * buf) [static]
Definition at line 170 of file common_buf.c.
References __getcwd().
static void getcwd_cleanup (void) [static]
Definition at line 166 of file common_buf.c.
static int getcwd_setup (void) [static]
Definition at line 165 of file common_buf.c.
static int getdirentry_badbuf (void * ptr) [static]
Definition at line 128 of file common_buf.c.
References buf_fd, and getdirentry().
static void getdirentry_cleanup (void) [static]
Definition at line 135 of file common_buf.c.
References buf_fd, and close().
static int getdirentry_setup (void) [static]
Definition at line 116 of file common_buf.c.
References buf_fd, O_RDONLY, open(), and warn().
static int read_badbuf (void * buf) [static]
Definition at line 71 of file common_buf.c.
References buf_fd, and read().
static void read_cleanup (void) [static]
Definition at line 78 of file common_buf.c.
References buf_fd, close(), and TESTFILE.
static int read_setup (void) [static]
Definition at line 60 of file common_buf.c.
References buf_fd, and open_testfile().
static int readlink_badbuf (void * buf) [static]
Definition at line 151 of file common_buf.c.
References readlink(), and TESTLINK.
static void readlink_cleanup (void) [static]
Definition at line 158 of file common_buf.c.
References TESTLINK.
static int readlink_setup (void) [static]
Definition at line 144 of file common_buf.c.
References create_testlink().
T (getcwd)
T (readlink)
T (getdirentry)
T (write)
T (read)
static int write_badbuf (void * ptr) [static]
Definition at line 99 of file common_buf.c.
References buf_fd, and write().
static void write_cleanup (void) [static]
Definition at line 106 of file common_buf.c.
References buf_fd, close(), and TESTFILE.
static int write_setup (void) [static]
Definition at line 88 of file common_buf.c.
References buf_fd, NULL, and open_testfile().
Variable Documentation
int buf_fd [static]
Definition at line 47 of file common_buf.c.
Referenced by getdirentry_badbuf(), getdirentry_cleanup(), getdirentry_setup(), read_badbuf(), read_cleanup(), read_setup(), write_badbuf(), write_cleanup(), and write_setup().