Os/161: user/testbin/farm/farm.c File Reference
user/testbin/farm/farm.c File Reference
#include <unistd.h>
#include <err.h>
Defines
#define MAXPROCS 6
Functions
static void spawnv (const char *prog, char **argv)
static void waitall (void)
static void hog (void)
static void cat (void)
int main ()
Variables
static char * hargv [2] = { (char *)"hog", NULL }
static char * cargv [3] = { (char *)"cat", (char *)"catfile", NULL }
static int pids [MAXPROCS]
static int npids
Define Documentation
#define MAXPROCS 6
Definition at line 46 of file farm.c.
Function Documentation
static void cat (void) [static]
Definition at line 95 of file farm.c.
References spawnv().
Referenced by main().
static void hog (void) [static]
Definition at line 88 of file farm.c.
References hargv, and spawnv().
Referenced by main().
int main (void)
Definition at line 101 of file farm.c.
References cat(), hog(), and waitall().
static void spawnv (const char * prog, char ** argv) [static]
Definition at line 51 of file farm.c.
References err(), execv(), fork(), and pid.
Referenced by cat(), and hog().
static void waitall (void) [static]
Definition at line 70 of file farm.c.
References waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by main().
Variable Documentation
char* cargv[3] = { (char *)"cat", (char *)"catfile", NULL } [static]
Definition at line 44 of file farm.c.
char* hargv[2] = { (char *)"hog", NULL } [static]
Definition at line 43 of file farm.c.
Referenced by hog().
int npids [static]
Definition at line 47 of file farm.c.
int pids[MAXPROCS] [static]
Definition at line 47 of file farm.c.
Referenced by doforkall(), makeprocs(), run(), triple(), wait_siblings(), and wait_siblings_child().