Os/161: user/testbin/kitchen/kitchen.c File Reference
user/testbin/kitchen/kitchen.c File Reference
#include <unistd.h>
#include <err.h>
Defines
#define MAXPROCS 6
Functions
static void sink (void)
static void waitall (void)
int main (void)
Variables
static char * sargv [2] = { (char *)"sink", NULL }
static int pids [MAXPROCS]
static int npids
Define Documentation
#define MAXPROCS 6
Definition at line 43 of file kitchen.c.
Function Documentation
int main (void)
Definition at line 85 of file kitchen.c.
References sink(), and waitall().
static void sink (void) [static]
Definition at line 48 of file kitchen.c.
References err(), execv(), fork(), pid, and sargv.
Referenced by main().
static void waitall (void) [static]
Definition at line 67 of file kitchen.c.
References waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by main().
Variable Documentation
int npids [static]
Definition at line 44 of file kitchen.c.
int pids[MAXPROCS] [static]
Definition at line 44 of file kitchen.c.
char* sargv[2] = { (char *)"sink", NULL } [static]
Definition at line 41 of file kitchen.c.
Referenced by sink().