Os/161: user/sbin/mksfs/disk.h File Reference
user/sbin/mksfs/disk.h File Reference
Functions
void opendisk (const char *path)
uint32_t diskblocksize (void)
uint32_t diskblocks (void)
void diskwrite (const void *data, uint32_t block)
void diskread (void *data, uint32_t block)
void closedisk (void)
Function Documentation
void closedisk (void)
Definition at line 174 of file disk.c.
References assert, close(), err(), and fd.
Referenced by main().
uint32_t diskblocks (void)
Definition at line 101 of file disk.c.
References assert, fd, and nblocks.
Referenced by main().
uint32_t diskblocksize (void)
Definition at line 94 of file disk.c.
References assert, BLOCKSIZE, and fd.
Referenced by main().
void diskread (void * data, uint32_t block)
Definition at line 141 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, fd, lseek(), read(), and SEEK_SET.
Referenced by adjust_filelinks(), check_bitmap(), check_dir(), check_indirect_block(), check_root_dir(), check_sb(), dirread(), dodirblock(), dumpbits(), dumpdir(), dumpsb(), and ibmap().
void diskwrite (const void * data, uint32_t block)
Definition at line 108 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, fd, lseek(), SEEK_SET, and write().
Referenced by adjust_filelinks(), check_bitmap(), check_dir(), check_indirect_block(), check_root_dir(), check_sb(), dirwrite(), writebitmap(), writerootdir(), and writesuper().
void opendisk (const char * path)
Definition at line 54 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, errx(), fd, fstat(), HOSTSTRING, nblocks, O_RDWR, open(), read(), stat::st_size, strcmp(), and strlen().
Referenced by main().