Os/161: user/testbin/dirseek/dirseek.c File Reference
user/testbin/dirseek/dirseek.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <err.h>
Defines
#define TESTDIR "seektestdir"
Functions
static int findentry (const char *name)
static void openit (void)
static void closeit (void)
static void readit (void)
static void firstread (void)
static void doreadat0 (void)
static void readone (const char *shouldbe)
static void doreadone (int which)
static void readallonebyone (void)
static void readallrandomly (void)
static void readateof (void)
static void doreadateof (void)
static void inval_read (void)
static void dobadreads (void)
static void dotest (void)
static void mkfile (const char *name)
static void setup (void)
static void cleanup (void)
int main ()
Variables
struct {
const char * name
int make_it
off_t pos
} testfiles []
static int dirfd
Define Documentation
#define TESTDIR "seektestdir"
Definition at line 57 of file dirseek.c.
Function Documentation
static void cleanup (void) [static]
Definition at line 517 of file dirseek.c.
References chdir(), err(), make_it, name, printf(), rmdir(), TESTDIR, and testfiles.
Referenced by main().
static void closeit (void) [static]
Definition at line 119 of file dirseek.c.
References close(), dirfd, and err().
Referenced by dotest().
static void dobadreads (void) [static]
Definition at line 362 of file dirseek.c.
References dirfd, err(), inval_read(), lseek(), pos, printf(), SEEK_END, SEEK_SET, and testfiles.
Referenced by dotest().
static void doreadat0 (void) [static]
Definition at line 215 of file dirseek.c.
References dirfd, err(), errx(), lseek(), pos, printf(), readit(), and SEEK_SET.
Referenced by dotest().
static void doreadateof (void) [static]
Definition at line 325 of file dirseek.c.
References dirfd, err(), errx(), lseek(), name, pos, printf(), readateof(), SEEK_END, and testfiles.
Referenced by dotest().
static void doreadone (int which) [static]
Definition at line 256 of file dirseek.c.
References dirfd, err(), errx(), lseek(), name, pos, readone(), SEEK_SET, and testfiles.
Referenced by readallonebyone(), and readallrandomly().
static void dotest (void) [static]
Definition at line 415 of file dirseek.c.
References closeit(), dobadreads(), doreadat0(), doreadateof(), firstread(), openit(), printf(), readallonebyone(), readallrandomly(), and readateof().
Referenced by main().
static int findentry (const char * name) [static]
Definition at line 95 of file dirseek.c.
References strcmp(), and testfiles.
Referenced by readit().
static void firstread (void) [static]
Definition at line 196 of file dirseek.c.
References dirfd, err(), errx(), lseek(), pos, printf(), readit(), and SEEK_CUR.
Referenced by dotest().
static void inval_read (void) [static]
Definition at line 349 of file dirseek.c.
References dirfd, and getdirentry().
Referenced by dobadreads().
int main (void)
Definition at line 545 of file dirseek.c.
References cleanup(), dotest(), and setup().
static void mkfile (const char * name) [static]
Definition at line 456 of file dirseek.c.
References close(), err(), errx(), fd, O_CREAT, O_EXCL, O_WRONLY, open(), strcat(), strlen(), and write().
Referenced by setup().
static void openit (void) [static]
Definition at line 109 of file dirseek.c.
References dirfd, err(), O_RDONLY, and open().
Referenced by dotest().
static void readallonebyone (void) [static]
Definition at line 273 of file dirseek.c.
References doreadone(), printf(), and testfiles.
Referenced by dotest().
static void readallrandomly (void) [static]
Definition at line 285 of file dirseek.c.
References doreadone(), printf(), random(), srandom(), and testfiles.
Referenced by dotest().
static void readateof (void) [static]
Definition at line 303 of file dirseek.c.
References dirfd, err(), errx(), and getdirentry().
Referenced by doreadateof(), and dotest().
static void readit (void) [static]
Definition at line 129 of file dirseek.c.
References dirfd, err(), errx(), findentry(), getdirentry(), lseek(), name, pos, SEEK_CUR, and testfiles.
Referenced by doreadat0(), and firstread().
static void readone (const char * shouldbe) [static]
Definition at line 234 of file dirseek.c.
References dirfd, err(), errx(), getdirentry(), and strcmp().
Referenced by doreadone().
static void setup (void) [static]
Definition at line 488 of file dirseek.c.
References chdir(), err(), make_it, mkdir(), mkfile(), name, printf(), TESTDIR, and testfiles.
Referenced by main().
Variable Documentation
int dirfd [static]
Definition at line 91 of file dirseek.c.
Referenced by closeit(), dobadreads(), doreadat0(), doreadateof(), doreadone(), firstread(), inval_read(), openit(), readateof(), readit(), and readone().
int make_it
Definition at line 61 of file dirseek.c.
Referenced by cleanup(), and setup().
const char* name
Definition at line 60 of file dirseek.c.
off_t pos
Definition at line 62 of file dirseek.c.
Referenced by dobadreads(), doreadat0(), doreadateof(), doreadone(), firstread(), fstest_write(), getcmd(), kgets(), lseek_loc_pasteof(), readit(), and vscomplain().
struct { ... } testfiles[] [static]
Referenced by cleanup(), dobadreads(), doreadateof(), doreadone(), findentry(), readallonebyone(), readallrandomly(), readit(), and setup().