Os/161: user/testbin/badcall/bad_execv.c File Reference
user/testbin/badcall/bad_execv.c File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static int exec_common_fork (void)
static void exec_badprog (const void *prog, const char *desc)
static void exec_emptyprog (void)
static void exec_badargs (void *args, const char *desc)
static void exec_onearg (void *ptr, const char *desc)
void test_execv (void)
Function Documentation
static void exec_badargs (void * args, const char * desc) [static]
Definition at line 109 of file bad_execv.c.
References EFAULT, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, and report_test().
Referenced by test_execv().
static void exec_badprog (const void * prog, const char * desc) [static]
Definition at line 73 of file bad_execv.c.
References EFAULT, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, NULL, and report_test().
Referenced by test_execv().
static int exec_common_fork (void) [static]
Definition at line 45 of file bad_execv.c.
References fork(), MAGIC_STATUS, pid, waitpid(), warn(), warnx(), WEXITSTATUS, and WIFEXITED.
Referenced by exec_badargs(), exec_badprog(), exec_emptyprog(), and exec_onearg().
static void exec_emptyprog (void) [static]
Definition at line 91 of file bad_execv.c.
References EINVAL, EISDIR, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, NULL, and report_test2().
Referenced by test_execv().
static void exec_onearg (void * ptr, const char * desc) [static]
Definition at line 124 of file bad_execv.c.
References EFAULT, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, NULL, and report_test().
Referenced by test_execv().
void test_execv (void)
Definition at line 143 of file bad_execv.c.
References exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), and NULL.