Os/161: user/testbin/f_test/f_write.c File Reference
user/testbin/f_test/f_write.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <err.h>
#include "f_hdr.h"
Defines
#define SectorSize 512
#define TMULT 50
#define FSIZE ((SectorSize + 1) * TMULT)
#define FNAME "f-testfile"
#define READCHAR 'r'
#define WRITECHAR 'w'
Functions
void subproc_write (void)
Variables
static char buffer [SectorSize+1]
Define Documentation
#define FNAME "f-testfile"
Definition at line 49 of file f_write.c.
#define FSIZE ((SectorSize + 1) * TMULT)
Definition at line 47 of file f_write.c.
#define READCHAR 'r'
Definition at line 50 of file f_write.c.
#define SectorSize 512
Definition at line 44 of file f_write.c.
#define TMULT 50
Definition at line 46 of file f_write.c.
#define WRITECHAR 'w'
Definition at line 51 of file f_write.c.
Function Documentation
void subproc_write (void)
Definition at line 61 of file f_write.c.
References buffer, close(), err(), fd, FNAME, O_WRONLY, open(), printf(), SectorSize, TMULT, write(), and WRITECHAR.
Referenced by concur().
Variable Documentation
char buffer[SectorSize+1] [static]
Definition at line 58 of file f_write.c.