Os/161: user/testbin/ctest/ctest.c File Reference
user/testbin/ctest/ctest.c File Reference
#include <stdio.h>
#include <stdlib.h>
Data Structures
struct entry
Defines
#define SIZE (1024*1024/sizeof(struct entry))
#define DEFAULT 477
Functions
int main (int argc, char **argv)
Variables
struct entry array [SIZE]
Define Documentation
#define DEFAULT 477
Definition at line 48 of file ctest.c.
Referenced by main().
#define SIZE (1024*1024/sizeof(struct entry))
Definition at line 47 of file ctest.c.
Referenced by check(), initarray(), main(), and sort().
Function Documentation
int main (int argc, char ** argv)
Definition at line 57 of file ctest.c.
References atoi(), DEFAULT, entry::e, printf(), putchar(), and SIZE.
Variable Documentation
struct entry array[SIZE]
Definition at line 54 of file ctest.c.