Os/161: user/testbin/badcall/bad_remove.c File Reference
user/testbin/badcall/bad_remove.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void remove_dir (void)
static void remove_dot (void)
static void remove_dotdot (void)
static void remove_empty (void)
void test_remove (void)
Function Documentation
static void remove_dir (void) [static]
Definition at line 48 of file bad_remove.c.
References create_testdir(), EISDIR, errno, report_test(), rmdir(), and TESTDIR.
Referenced by test_remove().
static void remove_dot (void) [static]
Definition at line 63 of file bad_remove.c.
References EINVAL, EISDIR, errno, and report_test2().
Referenced by test_remove().
static void remove_dotdot (void) [static]
Definition at line 72 of file bad_remove.c.
References EINVAL, EISDIR, errno, and report_test2().
Referenced by test_remove().
static void remove_empty (void) [static]
Definition at line 81 of file bad_remove.c.
References EINVAL, EISDIR, errno, and report_test2().
Referenced by test_remove().
void test_remove (void)
Definition at line 89 of file bad_remove.c.
References remove_dir(), remove_dot(), remove_dotdot(), remove_empty(), and test_remove_path().