#!/bin/bash
set -euo pipefail

echo "=============================="
echo "[*] Listing all registered OpenVPN AS users:"
echo "=============================="

# Get all users and their properties
sudo sacli UserPropGet | jq -r '
to_entries[] | 
"\(.key):
  type: \(.value.type // "N/A")
  superuser: \(.value.prop_superuser // "false")
  last login: \(.value.last_login // "N/A")
  autogenerated password: \(.value.prop_autogenerate // "false")
  password digest: \(.value.pvt_password_digest // "N/A")
"'
echo "=============================="
