

import { useMemo, useState, useEffect } from 'react';
import {
  BookOpen,
  Calendar,
  Clock,
  Download,
  ExternalLink,
  File,
  Folder,
  GraduationCap,
  Search,
  CreditCard,
  Users,
  ChevronRight,
  ChevronDown,
} from 'lucide-react';

/*
=====================================================
LESSONS PAGE
=====================================================

Designed for:

- GitHub Pages
- Static filesystem content
- Dynamic directory tree rendering
- Cal.com integration
- Downloadable lesson materials
- Modern UI

=====================================================
HOW IT WORKS
=====================================================

1. Put lessons inside:

public/lessons/

2. Generate lessons-tree.json automatically

3. React renders everything dynamically

=====================================================
EXAMPLE STRUCTURE
=====================================================

public/
└── lessons/
    ├── Programming/
    │   ├── C++/
    │   │   └── materials/
    │   │       ├── tutorials/
    │   │       ├── guides/
    │   │       ├── scripts/
    │   │       └── projects/
    │   │
    │   └── Python/
    │
    ├── Operating Systems/
    └── Networking/

=====================================================
*/

const CAL_TUTORING_LINK = "https://cal.com/giuseppe-pedone-28bua5/it-tutoring";
const CAL_CONSULTING_LINK = "https://cal.com/giuseppe-pedone-28bua5/it-consulting";


const [availabilityData, setAvailabilityData] = useState([]);
const [loadingAvailability, setLoadingAvailability] = useState(true);
const [bookingLoading, setBookingLoading] = useState(false);
const [error, setError] = useState(null);


const [lessonsTree, setLessonsTree] = useState(null);

useEffect(() => {
  async function loadAvailability() {
    try {
      setLoadingAvailability(true);

      const res = await fetch("/api/cal/availability");
      const data = await res.json();

      setAvailabilityData(data?.slots || []);
    } catch (err) {
      setError("Cannot load availability");
    } finally {
      setLoadingAvailability(false);
    }
  }

  loadAvailability();
}, []);


useEffect(() => {
// Fetch tree generated by your serverless backend
fetch('/api/lessons-tree')
    .then(res => res.json())
    .then(data => setLessonsTree(data))
    .catch(err => console.error('Failed to load lessons tree:', err));
}, []);

const subjects = [
  'Programming',
  'Operating Systems',
  'Networking',
  'Cybersecurity',
  'Algorithms',
  'Databases',
  'Artificial Intelligence',
];

const availability = [
  {
    day: 'Monday',
    slots: [
      { time: '09:00 - 11:00', available: true },
      { time: '15:00 - 17:00', available: false },
    ],
  },
  {
    day: 'Tuesday',
    slots: [
      { time: '10:00 - 12:00', available: true },
      { time: '16:00 - 18:00', available: true },
    ],
  },
  {
    day: 'Wednesday',
    slots: [
      { time: '14:00 - 16:00', available: false },
    ],
  },
];

const pricing = [
  {
    title: 'Single Lesson',
    price: '€35',
    description: '1 personalized lesson',
  },
  {
    title: '5 Lessons Package',
    price: '€160',
    description: 'Discounted package',
  },
  {
    title: '10 Lessons Package',
    price: '€300',
    description: 'Extended learning path',
  },
];

export default function Lessons() {
  const [search, setSearch] = useState('');

  const filteredSubjects = useMemo(() => {
    return subjects.filter(subject =>
      subject.toLowerCase().includes(search.toLowerCase())
    );
  }, [search]);

  return (
    <div className="min-h-screen bg-black text-white overflow-hidden">
      <HeroSection />

      <div className="max-w-7xl mx-auto px-6 py-16 space-y-20">
        <SubjectsSection
          search={search}
          setSearch={setSearch}
          subjects={filteredSubjects}
        />

        <LessonsInfoSection />

        <BookingSection />

        <AvailabilitySection availabilityData={availabilityData} loading={loadingAvailability} />

        <PricingSection />

        <MaterialsSection />
      </div>
    </div>
  );
}

function HeroSection() {
  return (
    <section className="relative border-b border-white/10">
      <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/10 via-transparent to-blue-500/10" />

      <div className="relative max-w-7xl mx-auto px-6 py-24">
        <div className="max-w-3xl">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 mb-8">
            <GraduationCap className="w-4 h-4" />
            <span className="text-sm text-zinc-300">
              Personalized Technical Lessons
            </span>
          </div>

          <h1 className="text-6xl font-black leading-tight mb-6">
            Learn.
            <br />
            Build.
            <br />
            Master.
          </h1>

          <p className="text-xl text-zinc-400 leading-relaxed mb-10">
            Advanced lessons and mentoring focused on programming,
            operating systems, cybersecurity, algorithms, networking,
            and software engineering.
          </p>

          <div className="flex flex-wrap gap-4">
            <a
              href={CAL_TUTORING_LINK}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-white text-black px-6 py-4 rounded-2xl font-semibold hover:scale-105 transition-all"
            >
              <Calendar className="w-5 h-5" />
              Book a Lesson
            </a>

            <a
              href="#materials"
              className="inline-flex items-center gap-2 border border-white/10 bg-white/5 px-6 py-4 rounded-2xl hover:bg-white/10 transition-all"
            >
              <BookOpen className="w-5 h-5" />
              Explore Materials
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}

function SubjectsSection({ search, setSearch, subjects }) {
  return (
    <section>
      <SectionTitle
        icon={<BookOpen className="w-6 h-6" />}
        title="Subjects & Topics"
      />

      <div className="bg-zinc-900/60 border border-white/10 rounded-3xl p-6 mt-8">
        <div className="relative mb-6">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-zinc-500" />

          <input
            type="text"
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search subjects..."
            className="w-full bg-black/40 border border-white/10 rounded-2xl pl-12 pr-4 py-4 outline-none focus:border-cyan-400 transition-all"
          />
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {subjects.map(subject => (
            <div
              key={subject}
              className="group bg-black/40 border border-white/10 rounded-2xl p-5 hover:border-cyan-400/50 transition-all"
            >
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-lg mb-2">{subject}</h3>

                  <p className="text-zinc-400 text-sm">
                    Personalized learning path and materials.
                  </p>
                </div>

                <ChevronRight className="w-5 h-5 text-zinc-500 group-hover:text-cyan-400 transition-all" />
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function LessonsInfoSection() {
  return (
    <section>
      <SectionTitle
        icon={<Users className="w-6 h-6" />}
        title="Lesson Information"
      />

      <div className="grid lg:grid-cols-2 gap-6 mt-8">
        <InfoCard
          title="Who These Lessons Are For"
          content={[
            'University students',
            'Beginners and advanced developers',
            'Professionals improving technical skills',
            'Students preparing exams or projects',
          ]}
        />

        <InfoCard
          title="What Lessons Include"
          content={[
            'Personalized lesson plan',
            'Exercises and guided projects',
            'Downloadable materials',
            'Code review and mentoring',
            'Technical support during the learning path',
          ]}
        />

        <InfoCard
          title="Lesson Duration"
          content={[
            'Standard lesson: 1 hour',
            'Extended lesson: 2 hours',
            'Custom intensive sessions available',
          ]}
        />

        <InfoCard
          title="Booking & Participation"
          content={[
            'Online lessons via video call',
            'Flexible scheduling',
            'Calendar integration via Cal.com',
            'Automatic availability management',
          ]}
        />
      </div>
    </section>
  );
}


async function bookSlot(slot) {
  setBookingLoading(true);

  try {
    const idempotencyKey = crypto.randomUUID();

    // 1. RESERVE SLOT
    const reserveRes = await fetch("/api/cal/reserve-slot", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        start: slot.startTime,
        idempotencyKey,
      }),
    });

    if (!reserveRes.ok) {
      const err = await reserveRes.json();
      alert(err.error || "Slot not available");
      return;
    }

    const { token } = await reserveRes.json();

    // 2. BOOK SLOT
    const bookRes = await fetch("/api/cal/book", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        start: slot.startTime,
        end: slot.endTime,
        name: "Student User",
        email: "student@email.com",
        title: "Lesson Booking",
        lockToken: token,
        idempotencyKey,
      }),
    });

    if (!bookRes.ok) {
      const err = await bookRes.json();
      alert(err.error || "Booking failed");
      return;
    }

    const data = await bookRes.json();

    // 3. SUCCESS ONLY
    window.open(CAL_TUTORING_LINK, "_blank");

  } catch (err) {
    alert(err.message || "Unexpected error");
  } finally {
    setBookingLoading(false);
  }
}

function BookingSection() {
  return (
    <section>
      <SectionTitle
        icon={<Calendar className="w-6 h-6" />}
        title="Book Your Lesson"
      />

      <div className="mt-8 bg-gradient-to-br from-cyan-500/10 to-blue-500/10 border border-cyan-400/20 rounded-3xl p-8">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-8">
          <div>
            <h3 className="text-3xl font-bold mb-4">
              Schedule a Personalized Session
            </h3>

            <p className="text-zinc-300 max-w-2xl leading-relaxed">
              Choose your subject, preferred topic, duration, and available
              time slot directly through the booking platform.
            </p>
          </div>

          <a
            href={CAL_TUTORING_LINK}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-3 bg-white text-black px-8 py-5 rounded-2xl font-semibold hover:scale-105 transition-all whitespace-nowrap"
          >
            <ExternalLink className="w-5 h-5" />
            Open Booking Page
          </a>
        </div>

        <div className="mt-10 bg-black/30 border border-white/10 rounded-2xl p-6">
          <p className="text-zinc-400 mb-4">
            Cal.com integration can automatically:
          </p>

          <div className="grid md:grid-cols-2 gap-4 text-sm">
            {[
              'Show real-time availability',
              'Prevent double bookings',
              'Handle timezone conversion',
              'Send automatic reminders',
              'Allow lesson customization',
              'Integrate Google Calendar',
            ].map(item => (
              <div
                key={item}
                className="bg-white/5 border border-white/10 rounded-xl px-4 py-3"
              >
                {item}
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

function AvailabilitySection({ availabilityData, loading }) {
  return (
    <section>
      <SectionTitle
        icon={<Clock className="w-6 h-6" />}
        title="Availability (Live)"
      />

      <div className="mt-8 border border-white/10 rounded-3xl p-6">
        {loading ? (
          <p className="text-zinc-400">Loading availability...</p>
        ) : availabilityData.length === 0 ? (
          <p className="text-zinc-400">No slots available</p>
        ) : (
          <div className="grid gap-3">
            {availabilityData.map((slot, i) => (
              <div
                key={i}
                className="flex justify-between items-center p-4 bg-white/5 border border-white/10 rounded-xl"
              >
                <div>
                  <div className="font-semibold">
                    {new Date(slot.startTime).toLocaleString()}
                  </div>
                  <div className="text-sm text-zinc-400">
                    {new Date(slot.endTime).toLocaleString()}
                  </div>
                </div>

                <button
                  className="bg-cyan-500 text-black px-4 py-2 rounded-xl font-semibold hover:scale-105 transition"
                  onClick={() => bookSlot(slot)}
                >
                  Book
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}



function PricingSection() {
  return (
    <section>
      <SectionTitle
        icon={<CreditCard className="w-6 h-6" />}
        title="Pricing & Payments"
      />

      <div className="grid lg:grid-cols-3 gap-6 mt-8">
        {pricing.map(plan => (
          <div
            key={plan.title}
            className="bg-zinc-900/70 border border-white/10 rounded-3xl p-8 hover:border-cyan-400/30 transition-all"
          >
            <h3 className="text-2xl font-bold mb-3">{plan.title}</h3>

            <div className="text-5xl font-black mb-4">{plan.price}</div>

            <p className="text-zinc-400 mb-8">{plan.description}</p>

            <button className="w-full bg-white text-black py-4 rounded-2xl font-semibold hover:scale-[1.02] transition-all">
              Select Plan
            </button>
          </div>
        ))}
      </div>

      <div className="mt-8 bg-zinc-900/50 border border-white/10 rounded-3xl p-6">
        <h4 className="font-semibold text-lg mb-4">
          Accepted Payment Methods
        </h4>

        <div className="flex flex-wrap gap-3">
          {[
            'PayPal',
            'Credit Card',
            'Bank Transfer',
            'Stripe',
            'Revolut',
          ].map(method => (
            <div
              key={method}
              className="px-4 py-3 bg-black/40 border border-white/10 rounded-xl"
            >
              {method}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function MaterialsSection() {
  return (
    <section id="materials">
      <SectionTitle
        icon={<Folder className="w-6 h-6" />}
        title="Lesson Materials"
      />

      <div className="mt-8 bg-zinc-900/60 border border-white/10 rounded-3xl p-6">
        <p className="text-zinc-400 mb-8 max-w-3xl leading-relaxed">
          Browse all available materials, tutorials, projects, code snippets,
          scripts, guides, and downloadable resources.
        </p>

        <DirectoryNode node={lessonsTree} level={0} />
      </div>
    </section>
  );
}

function DirectoryNode({ node, level }) {
  const [open, setOpen] = useState(level < 1);

  const isFolder = node.type === 'folder';

  return (
    <div className="ml-2">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-3 text-left px-4 py-3 rounded-2xl hover:bg-white/5 transition-all"
      >
        {isFolder ? (
          open ? (
            <ChevronDown className="w-5 h-5 text-zinc-400" />
          ) : (
            <ChevronRight className="w-5 h-5 text-zinc-400" />
          )
        ) : null}

        {isFolder ? (
          <Folder className="w-5 h-5 text-cyan-400" />
        ) : (
          <File className="w-5 h-5 text-zinc-400" />
        )}

        <span className={`${level === 0 ? 'font-bold text-lg' : ''}`}>
          {node.name}
        </span>
      </button>

      {isFolder && open && node.children && (
        <div className="ml-8 border-l border-white/10 pl-4 space-y-1 mt-2">
          {node.children.map((child, index) => (
            <div key={index}>
              {child.type === 'folder' ? (
                <DirectoryNode node={child} level={level + 1} />
              ) : (
                <FileItem file={child} />
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function FileItem({ file }) {
  return (
    <div className="group flex items-center justify-between gap-4 px-4 py-3 rounded-2xl hover:bg-white/5 transition-all">
      <div className="flex items-center gap-3 min-w-0">
        <File className="w-5 h-5 text-zinc-500" />

        <span className="truncate">{file.name}</span>
      </div>

      <a
        href={file.path}
        download
        className="opacity-0 group-hover:opacity-100 inline-flex items-center gap-2 px-4 py-2 bg-cyan-500/10 border border-cyan-400/20 rounded-xl text-cyan-300 transition-all"
      >
        <Download className="w-4 h-4" />
        Download
      </a>
    </div>
  );
}

function InfoCard({ title, content }) {
  return (
    <div className="bg-zinc-900/60 border border-white/10 rounded-3xl p-6">
      <h3 className="text-xl font-semibold mb-6">{title}</h3>

      <div className="space-y-3">
        {content.map(item => (
          <div
            key={item}
            className="flex items-start gap-3 text-zinc-300"
          >
            <div className="w-2 h-2 rounded-full bg-cyan-400 mt-2" />

            <span>{item}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function SectionTitle({ icon, title }) {
  return (
    <div className="flex items-center gap-4">
      <div className="w-14 h-14 rounded-2xl bg-cyan-500/10 border border-cyan-400/20 flex items-center justify-center text-cyan-300">
        {icon}
      </div>

      <div>
        <h2 className="text-4xl font-black">{title}</h2>
      </div>
    </div>
  );
}

/*
=====================================================
AUTO DIRECTORY TREE GENERATION
=====================================================

Create generate-tree.js

-----------------------------------------------------

import fs from 'fs';
import path from 'path';

function buildTree(dirPath) {
  const stats = fs.statSync(dirPath);

  if (stats.isFile()) {
    return {
      name: path.basename(dirPath),
      type: 'file',
      path: dirPath.replace('public', ''),
    };
  }

  return {
    name: path.basename(dirPath),
    type: 'folder',
    children: fs
      .readdirSync(dirPath)
      .map(child => buildTree(path.join(dirPath, child))),
  };
}

const tree = buildTree('./public/lessons');

fs.writeFileSync(
  './src/data/lessons-tree.json',
  JSON.stringify(tree, null, 2)
);

-----------------------------------------------------

Then import JSON dynamically:

import lessonsTree from '../data/lessons-tree.json';

=====================================================
GITHUB PAGES SUPPORT
=====================================================

This component works perfectly on GitHub Pages because:

- all assets are static
- materials are downloadable
- no backend required
- tree generated at build time

=====================================================
CAL.COM API INTEGRATION
=====================================================

The Lessons page is designed to integrate directly with Cal.com APIs.

GOALS:

- allow students to book lessons
- choose:
  - subject
  - topic
  - duration
  - date
  - time slot
- automatically sync availability
- automatically mark busy slots
- allow real-time scheduling
- receive booking notifications
- optionally populate external files/databases

=====================================================
SUGGESTED FLOW
=====================================================

Student opens Lessons page
        ↓
Chooses:

- Subject
- Topic
- Duration
- Time slot

        ↓
Lessons page calls Cal.com API
        ↓
Cal.com checks availability
        ↓
Available slots shown on calendar
        ↓
Student books lesson
        ↓
Cal.com:

- sends notification
- updates Google Calendar
- blocks occupied slots
- optionally triggers webhook

=====================================================
RECOMMENDED CAL.COM FEATURES
=====================================================

- Event Types
- API Routing Forms
- Availability API
- Bookings API
- Webhooks
- Google Calendar Sync
- Outlook Sync
- Zoom / Meet Integration

=====================================================
CALENDAR SYNCHRONIZATION
=====================================================

The availability section should:

1. fetch free/busy slots from Cal.com
2. render them dynamically
3. disable occupied slots
4. update automatically

=====================================================
EXAMPLE API FLOW
=====================================================

GET availability:

fetch('/api/cal/availability')

POST booking:

fetch('/api/cal/book', {
  method: 'POST',
  body: JSON.stringify({
    subject,
    topic,
    date,
    duration,
    student,
  })
})

=====================================================
WEBHOOKS
=====================================================

Recommended:

Cal.com → Webhook → Your backend

Possible actions:

- save booking in JSON
- save booking in database
- send email
- notify Telegram bot
- generate lesson ID
- attach materials
- generate invoice

=====================================================
DIRECTORY TREE STRUCTURE
=====================================================

The page is filesystem-driven.

You provide:

Materials/
└── Subject/
    └── Topic/
        ├── Material/
        │   ├── Tutorials/
        │   ├── Examples/
        │   ├── Projects/
        │   ├── Scripts/
        │   └── Guides/
        │
        └── License/
            └── LICENSE.md

The React component dynamically renders:

- subjects
- topics
- materials
- downloadable files
- licenses

WITHOUT hardcoding folder names.

=====================================================
DIRECTORY TREE FEATURES
=====================================================

The materials explorer supports:

- collapsible folders
- nested navigation
- recursive rendering
- file downloads
- modern explorer UI
- unlimited depth
- automatic updates
- GitHub Pages compatibility

=====================================================
AUTO TREE GENERATION
=====================================================

Filesystem changes:

- add folder
- rename folder
- delete file
- add topic
- add material

ONLY require regenerating:

lessons-tree.json

No React code modifications needed.

=====================================================
AVAILABILITY CALENDAR
=====================================================

The calendar section is designed to:

- display available slots
- display busy slots
- synchronize with Cal.com
- synchronize with Google Calendar
- update in real-time
- disable unavailable slots
- allow direct booking

=====================================================
BOOKING SECTION IMPROVEMENTS
=====================================================

Recommended future UI:

- embedded Cal.com widget
- subject selector
- topic selector
- lesson type selector
- duration selector
- real calendar grid
- timezone support
- recurring lessons
- package booking
- payment integration
- Stripe checkout

=====================================================
GITHUB PAGES SUPPORT
=====================================================

This architecture works on GitHub Pages because:

- lessons/materials are static
- directory tree is pre-generated
- React only renders JSON
- downloadable files are public assets

Dynamic features are delegated to:

- Cal.com APIs
- serverless functions
- webhooks

=====================================================
RECOMMENDED ARCHITECTURE
=====================================================

React Frontend
        ↓
Lessons Explorer
        ↓
Cal.com APIs
        ↓
Availability + Booking
        ↓
Webhook / Serverless Backend
        ↓
Notifications + Storage

=====================================================
ROUTING EXAMPLE
=====================================================

<Route path="/activities" element={<Activities />} />
<Route path="/activities/lessons" element={<Lessons />} />

=====================================================
*/
