Os/161: con_softc Struct Reference
con_softc Struct Reference
#include <console.h>
Data Fields
void * cs_devdata
void(* cs_send)(void *devdata, int ch)
void(* cs_sendpolled)(void *devdata, int ch)
void(* cs_startpolling)(void *devdata)
void(* cs_endpolling)(void *devdata)
struct semaphore * cs_rsem
struct semaphore * cs_wsem
unsigned char cs_gotchars [CONSOLE_INPUT_BUFFER_SIZE]
unsigned cs_gotchars_head
unsigned cs_gotchars_tail
Detailed Description
Definition at line 42 of file console.h.
Field Documentation
void* cs_devdata
Definition at line 44 of file console.h.
Referenced by attach_con_to_lscreen(), attach_con_to_lser(), putch_complete_polled(), putch_intr(), putch_polled(), and putch_prepare_polled().
void(* cs_endpolling)(void *devdata)
Referenced by attach_con_to_lscreen(), attach_con_to_lser(), and putch_complete_polled().
unsigned char cs_gotchars[CONSOLE_INPUT_BUFFER_SIZE]
Definition at line 53 of file console.h.
Referenced by con_input(), and getch_intr().
unsigned cs_gotchars_head
Definition at line 54 of file console.h.
Referenced by con_input(), and config_con().
unsigned cs_gotchars_tail
Definition at line 55 of file console.h.
Referenced by con_input(), config_con(), and getch_intr().
struct semaphore* cs_rsem [read]
Definition at line 51 of file console.h.
Referenced by con_input(), config_con(), and getch_intr().
void(* cs_send)(void *devdata, int ch)
Referenced by attach_con_to_lscreen(), attach_con_to_lser(), and putch_intr().
void(* cs_sendpolled)(void *devdata, int ch)
Referenced by attach_con_to_lscreen(), attach_con_to_lser(), and putch_polled().
void(* cs_startpolling)(void *devdata)
Referenced by attach_con_to_lscreen(), attach_con_to_lser(), and putch_prepare_polled().
struct semaphore* cs_wsem [read]
Definition at line 52 of file console.h.
Referenced by con_start(), config_con(), and putch_intr().
The documentation for this struct was generated from the following file:
kern/dev/generic/console.h