Os/161: build/install/hostinclude/hostcompat.h File Reference
build/install/hostinclude/hostcompat.h File Reference
#include <sys/types.h>
Functions
void hostcompat_init (int argc, char **argv)
time_t __time (time_t *secs, unsigned long *nsecs)
Function Documentation
time_t __time (time_t * secs, unsigned long * nsecs)
Definition at line 41 of file time.c.
Referenced by check_timing(), docommand(), time(), time_badnsecs(), time_badsecs(), and try___time().
void hostcompat_init (int argc, char ** argv)
Referenced by main().