Os/161: random_softc Struct Reference
random_softc Struct Reference
#include <random.h>
Data Fields
void * rs_devdata
uint32_t(* rs_random)(void *devdata)
uint32_t(* rs_randmax)(void *devdata)
int(* rs_read)(void *devdata, struct uio *uio)
struct device rs_dev
Detailed Description
Definition at line 36 of file random.h.
Field Documentation
struct device rs_dev [read]
Definition at line 43 of file random.h.
Referenced by config_random().
void* rs_devdata
Definition at line 38 of file random.h.
Referenced by attach_random_to_lrandom(), randio(), randmax(), and random().
uint32_t(* rs_randmax)(void *devdata)
Referenced by attach_random_to_lrandom(), and randmax().
uint32_t(* rs_random)(void *devdata)
Referenced by attach_random_to_lrandom(), and random().
int(* rs_read)(void *devdata, struct uio *uio)
Referenced by attach_random_to_lrandom(), and randio().
The documentation for this struct was generated from the following file:
kern/dev/generic/random.h