Os/161: build/install/include/stdio.h File Reference
build/install/include/stdio.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Defines
#define EOF (-1)
Functions
int __vprintf (void(*sendfunc)(void *clientdata, const char *, size_t len), void *clientdata, const char *fmt, __va_list ap)
int printf (const char *fmt,...)
int vprintf (const char *fmt, __va_list ap)
int snprintf (char *buf, size_t len, const char *fmt,...)
int vsnprintf (char *buf, size_t len, const char *fmt, __va_list ap)
int puts (const char *)
int __puts (const char *)
int putchar (int)
int getchar (void)
Define Documentation
#define EOF (-1)
Definition at line 42 of file stdio.h.
Referenced by getchar(), main(), putchar(), and read_string().
Function Documentation
int __puts (const char *)
Definition at line 40 of file __puts.c.
Referenced by puts().
int __vprintf (void(*)(void *clientdata, const char *, size_t len) sendfunc, void * clientdata, const char * fmt, __va_list ap)
Referenced by __printerr(), kprintf(), panic(), vprintf(), and vsnprintf().
int getchar (void)
Definition at line 39 of file getchar.c.
Referenced by getcmd(), geti(), main(), and read_string().
int printf (const char * fmt, ...)
Definition at line 55 of file printf.c.
Referenced by ask_yesno(), big_file(), BladeRunner(), checkblock(), cleanup(), cmd_chdir(), cmd_exit(), cmd_wait(), concur(), dir_test(), do_move(), dobadreads(), docommand(), dodirblock(), doreadat0(), doreadateof(), dotest(), dowait(), dowaitpoll(), dumpbits(), dumpdir(), dumpsb(), firstread(), geti(), interactive(), main(), makeprocs(), markblock(), menu(), print(), print_board(), print_instructions(), printheader(), printstatus(), readallonebyone(), readallrandomly(), runit(), setup(), subproc_read(), subproc_write(), test1(), test2(), test3(), test4(), test5(), test567(), test6(), test7(), ThreadRunner(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), and usage().
int putchar (int)
Definition at line 41 of file putchar.c.
Referenced by __printf_send(), __puts(), check_buffer(), getcmd(), geti(), main(), puts(), read_string(), and test().
int puts (const char *)
Definition at line 37 of file puts.c.
int snprintf (char * buf, size_t len, const char * fmt, ...)
Definition at line 148 of file snprintf.c.
Referenced by __bad_assert(), any_badfd(), any_empty(), binname(), blockusagestr(), check_dir(), check_dir_entry(), choose_name(), common_badbuf(), common_badpath(), config_emu(), config_lhd(), cpu_create(), createstress_thread(), fstest_makename(), killdir(), listdir(), main(), make_computes(), make_sleepalots(), mergedname(), one_ioctl_badbuf(), recursedir(), recursive_cleanup(), runthreads(), setup(), test3(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), validname(), vfs_setbootfs(), vscomplain(), and writestress_thread().
int vprintf (const char * fmt, __va_list ap)
Definition at line 67 of file printf.c.
Referenced by printf().
int vsnprintf (char * buf, size_t len, const char * fmt, __va_list ap)
Definition at line 99 of file snprintf.c.
Referenced by say(), snprintf(), and vscomplain().