Os/161: user/include/unistd.h File Reference
user/include/unistd.h File Reference
#include <sys/types.h>
#include <kern/fcntl.h>
#include <kern/ioctl.h>
#include <kern/reboot.h>
#include <kern/seek.h>
#include <kern/time.h>
#include <kern/unistd.h>
#include <kern/wait.h>
Defines
#define __DEAD
Functions
__DEAD void _exit (int code)
int execv (const char *prog, char *const *args)
pid_t fork (void)
int waitpid (pid_t pid, int *returncode, int flags)
int open (const char *filename, int flags,...)
int read (int filehandle, void *buf, size_t size)
int write (int filehandle, const void *buf, size_t size)
int close (int filehandle)
int reboot (int code)
int sync (void)
int rmdir (const char *dirname)
int getpid (void)
int ioctl (int filehandle, int code, void *buf)
off_t lseek (int filehandle, off_t pos, int code)
int fsync (int filehandle)
int ftruncate (int filehandle, off_t size)
int remove (const char *filename)
int rename (const char *oldfile, const char *newfile)
int link (const char *oldfile, const char *newfile)
int chdir (const char *path)
void * sbrk (int change)
int getdirentry (int filehandle, char *buf, size_t buflen)
int symlink (const char *target, const char *linkname)
int readlink (const char *path, char *buf, size_t buflen)
int dup2 (int filehandle, int newhandle)
int pipe (int filehandles[2])
time_t __time (time_t *seconds, unsigned long *nanoseconds)
int __getcwd (char *buf, size_t buflen)
char * getcwd (char *buf, size_t buflen)
time_t time (time_t *seconds)
Define Documentation
#define __DEAD
Definition at line 114 of file unistd.h.
Function Documentation
int __getcwd (char * buf, size_t buflen)
time_t __time (time_t * seconds, unsigned long * nanoseconds)
Definition at line 41 of file time.c.
__DEAD void _exit (int code)
Definition at line 30 of file exit_syscall.c.
References exit(), MAX_THREAD, NULL, thread::parent_id, pid_used, S_ZOMBIE, thread_exit(), thread::thread_id, and waitpid().
int chdir (const char * path)
int close (int filehandle)
int dup2 (int filehandle, int newhandle)
int execv (const char * prog, char *const * args)
pid_t fork (void)
int fsync (int filehandle)
int ftruncate (int filehandle, off_t size)
char* getcwd (char * buf, size_t buflen)
Definition at line 40 of file getcwd.c.
References __getcwd(), EINVAL, errno, and NULL.
int getdirentry (int filehandle, char * buf, size_t buflen)
int getpid (void)
int ioctl (int filehandle, int code, void * buf)
int link (const char * oldfile, const char * newfile)
off_t lseek (int filehandle, off_t pos, int code)
int open (const char * filename, int flags, ...)
int pipe (int filehandles[2])
int read (int filehandle, void * buf, size_t size)
int readlink (const char * path, char * buf, size_t buflen)
int reboot (int code)
int remove (const char * filename)
int rename (const char * oldfile, const char * newfile)
int rmdir (const char * dirname)
void* sbrk (int change)
int symlink (const char * target, const char * linkname)
int sync (void)
time_t time (time_t * seconds)
Definition at line 39 of file time.c.
References __time(), and NULL.
int waitpid (pid_t pid, int * returncode, int flags)
int write (int filehandle, const void * buf, size_t size)