Os/161: build/install/include/string.h File Reference
build/install/include/string.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Functions
char * strcat (char *, const char *)
char * strcpy (char *, const char *)
char * strchr (const char *, int)
char * strrchr (const char *, int)
int strcmp (const char *, const char *)
size_t strlen (const char *)
char * strtok_r (char *, const char *, char **)
char * strtok (char *, const char *)
void * memset (void *, int c, size_t)
void * memcpy (void *, const void *, size_t)
void * memmove (void *, const void *, size_t)
int memcmp (const void *, const void *, size_t)
const char * strerror (int errcode)
void bzero (void *, size_t)
Function Documentation
void bzero (void * , size_t)
Definition at line 49 of file bzero.c.
Referenced by as_zero_region(), bitmap_create(), check_dir(), dev_stat(), dirread(), emufs_stat(), enter_new_process(), lscreen_newline(), sfs_bmap(), sfs_dir_link(), sfs_dir_unlink(), sfs_partialio(), sfs_stat(), switchframe_init(), writerootdir(), and writesuper().
int memcmp (const void * , const void * , size_t)
Definition at line 38 of file memcmp.c.
void* memcpy (void * , const void * , size_t)
Definition at line 48 of file memcpy.c.
Referenced by addmemory(), array_setsize(), copyin(), copyout(), memmove(), and sort().
void* memmove (void * , const void * , size_t)
Definition at line 49 of file memmove.c.
Referenced by array_remove(), as_copy(), lscreen_newline(), thread_fork2(), and uiomove().
void* memset (void * , int c, size_t)
Definition at line 37 of file memset.c.
Referenced by main(), test4(), and write_badfd().
char* strcat (char * , const char *)
Definition at line 47 of file strcat.c.
Referenced by dir_test(), main(), mkfile(), mkrawname(), and vfs_setbootfs().
char* strchr (const char * , int)
Definition at line 47 of file strchr.c.
Referenced by __pf_send(), atoi(), main(), strtok_r(), and vfs_setbootfs().
int strcmp (const char * , const char *)
Definition at line 48 of file strcmp.c.
Referenced by cat(), check_dir(), cmd_dispatch(), cmd_mount(), dirsortfunc(), docommand(), findentry(), findmount(), fstest_read(), main(), opendisk(), readone(), recursedir(), samestring(), sfs_dir_findname(), test6(), vfs_getroot(), and vnode_check().
char* strcpy (char * , const char *)
Definition at line 46 of file strcpy.c.
Referenced by cmd_progthread(), dir_test(), dir_tryadd(), emu_open(), emufs_lookparent(), fstest_read(), fstest_remove(), fstest_write(), kstrdup(), main(), mkrawname(), printfile(), sfs_dir_link(), sfs_lookparent(), strcat(), system(), and writesuper().
const char* strerror (int errcode)
Definition at line 55 of file misc.c.
Referenced by __printerr(), cleanup_rmdir(), cmd_progthread(), cmd_pwd(), common_prog(), cpu_create(), cvtest(), dev_create_vnode(), devnull_create(), docreatestress(), dofork(), domkdir(), doreadstress(), dorename(), dormdir(), dowritestress(), dowritestress2(), fstest_read(), fstest_remove(), fstest_write(), locktest(), make_computes(), make_sleepalots(), mallocstress(), menu_execute(), printfile(), recursive_cleanup(), run(), runthreads(), semtest(), set_std_fd(), setup(), sfs_rename(), tryattach_beep_to_ltimer(), tryattach_con_to_lser(), tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), tryattach_ltrace_to_lamebus(), tryattach_random_to_lrandom(), tryattach_rtclock_to_ltimer(), vfs_unmountall(), vnode_decopen(), vnode_decref(), vscomplain(), and whalemating().
size_t strlen (const char *)
Definition at line 47 of file strlen.c.
Referenced by __bad_assert(), __pf_printstuff(), __senderrstr(), check_dir(), checkfilesystem(), cmd_bootfs(), cmd_mount(), cmd_progthread(), cmd_unmount(), complain(), complainx(), dev_lookup(), dir_test(), dir_tryadd(), emu_open(), emufs_lookparent(), fstest_makename(), fstest_read(), fstest_write(), kstrdup(), lseek_file_stdin(), lseek_loc_pasteof(), main(), mkfile(), mkrawname(), open_testfile(), opendisk(), runprogram(), say(), sfs_dir_link(), sfs_lookparent(), strcat(), strrchr(), sys_execv(), system(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_setbootfs(), vscomplain(), and writesuper().
char* strrchr (const char * , int)
Definition at line 47 of file strrchr.c.
Referenced by basename(), emufs_lookparent(), and initprogname().
char* strtok (char * , const char *)
Definition at line 35 of file strtok.c.
Referenced by docommand(), and system().
char* strtok_r (char * , const char * , char **)
Definition at line 50 of file strtok_r.c.
Referenced by cmd_dispatch(), menu_execute(), and strtok().