Os/161: build/install/include/unistd.h File Reference
build/install/include/unistd.h File Reference
#include <sys/types.h>
#include <kern/fcntl.h>
#include <kern/ioctl.h>
#include <kern/reboot.h>
#include <kern/seek.h>
#include <kern/time.h>
#include <kern/unistd.h>
#include <kern/wait.h>
Defines
#define __DEAD
Functions
__DEAD void _exit (int code)
int execv (const char *prog, char *const *args)
pid_t fork (void)
int waitpid (pid_t pid, int *returncode, int flags)
int open (const char *filename, int flags,...)
int read (int filehandle, void *buf, size_t size)
int write (int filehandle, const void *buf, size_t size)
int close (int filehandle)
int reboot (int code)
int sync (void)
int rmdir (const char *dirname)
int getpid (void)
int ioctl (int filehandle, int code, void *buf)
off_t lseek (int filehandle, off_t pos, int code)
int fsync (int filehandle)
int ftruncate (int filehandle, off_t size)
int remove (const char *filename)
int rename (const char *oldfile, const char *newfile)
int link (const char *oldfile, const char *newfile)
int chdir (const char *path)
void * sbrk (int change)
int getdirentry (int filehandle, char *buf, size_t buflen)
int symlink (const char *target, const char *linkname)
int readlink (const char *path, char *buf, size_t buflen)
int dup2 (int filehandle, int newhandle)
int pipe (int filehandles[2])
time_t __time (time_t *seconds, unsigned long *nanoseconds)
int __getcwd (char *buf, size_t buflen)
char * getcwd (char *buf, size_t buflen)
time_t time (time_t *seconds)
Define Documentation
#define __DEAD
Definition at line 114 of file unistd.h.
Function Documentation
int __getcwd (char * buf, size_t buflen)
Referenced by getcwd(), getcwd_badbuf(), and try___getcwd().
time_t __time (time_t * seconds, unsigned long * nanoseconds)
Definition at line 41 of file time.c.
__DEAD void _exit (int code)
Definition at line 30 of file exit_syscall.c.
Referenced by abort(), docommand(), dorm(), exit(), forkoff(), hostcompat_die(), lseek_file_stdin(), main(), syscall(), system(), wait_parent(), and wait_siblings().
int chdir (const char * path)
Referenced by chdir_badpath(), chdir_empty(), cleanup(), cmd_chdir(), finish(), setup(), startup(), and try_chdir().
int close (int filehandle)
Referenced by big_file(), cat(), close_badfd(), closedisk(), closeit(), concur(), copy(), create_testfile(), doclose(), dorm(), dup2_cleanup(), dup2_fd2(), dup2_self(), ftruncate_fd_device(), ftruncate_size_neg(), getdirentry_cleanup(), getsize(), isdir(), listdir(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), main(), mkfile(), open_empty(), open_testfile(), print(), read_cleanup(), readlink_file(), recursedir(), subproc_read(), subproc_write(), test2(), test3(), test4(), test6(), try_close(), wait_siblings(), wait_siblings_child(), and write_cleanup().
int dup2 (int filehandle, int newhandle)
Referenced by assemble(), dup2_badfd(), dup2_fd2(), dup2_self(), lseek_file_stdin(), main(), and try_dup2().
int execv (const char * prog, char *const * args)
Referenced by assemble(), docommand(), exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), hog(), main(), sink(), spawnv(), system(), and try_execv().
pid_t fork (void)
Referenced by docommand(), dofork(), dorm(), exec_common_fork(), forkoff(), hog(), lseek_file_stdin(), main(), makeprocs(), sink(), spawnv(), system(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), wait_badflags(), wait_badstatus(), wait_parent(), wait_siblings(), and wait_unaligned().
int fsync (int filehandle)
Referenced by fsync_badfd(), and try_fsync().
int ftruncate (int filehandle, off_t size)
Referenced by ftruncate_badfd(), ftruncate_fd_device(), ftruncate_size_neg(), and try_ftruncate().
char* getcwd (char * buf, size_t buflen)
Definition at line 40 of file getcwd.c.
Referenced by main(), startup(), and test7().
int getdirentry (int filehandle, char * buf, size_t buflen)
Referenced by getdirentry_badbuf(), getdirentry_badfd(), inval_read(), listdir(), readateof(), readit(), readone(), recursedir(), test6(), and try_getdirentry().
int getpid (void)
Referenced by check(), cleanup_rmdir(), domkdir(), dorename(), dormdir(), go(), hostcompat_die(), hostcompat_stop(), main(), mkdir_proc(), recursive_cleanup(), rename_proc(), rmdir_proc(), wait_parent(), wait_self(), and wait_siblings_child().
int ioctl (int filehandle, int code, void * buf)
Referenced by ioctl_badcode(), ioctl_badfd(), one_ioctl_badbuf(), and try_ioctl().
int link (const char * oldfile, const char * newfile)
Referenced by dohardlink(), link_badpath1(), link_badpath2(), link_dir(), link_empty1(), link_empty2(), and try_link().
off_t lseek (int filehandle, off_t pos, int code)
Referenced by diskread(), diskwrite(), dobadreads(), dolseek(), doreadat0(), doreadateof(), doreadone(), dup2_self(), firstread(), getsize(), lseek_badfd(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), main(), open_testfile(), readit(), tail(), try_lseek(), and wait_siblings_child().
int open (const char * filename, int flags, ...)
Referenced by big_file(), cat(), concur(), copy(), dir_test(), doopen(), ftruncate_fd_device(), getdirentry_setup(), isdir(), listdir(), lseek_fd_device(), main(), mkfile(), open_badflags(), open_badpath(), open_empty(), open_testfile(), opendisk(), openit(), print(), recursedir(), subproc_read(), subproc_write(), test2(), test3(), test4(), test6(), try_open(), and wait_siblings_child().
int pipe (int filehandles[2])
Referenced by pipe_badptr(), pipe_unaligned(), and try_pipe().
int read (int filehandle, void * buf, size_t size)
Referenced by big_file(), copy(), diskread(), docat(), doread(), getchar(), main(), opendisk(), read_badbuf(), read_badfd(), subproc_read(), tail(), test6(), try_read(), and wait_siblings_child().
int readlink (const char * path, char * buf, size_t buflen)
Referenced by readlink_badbuf(), readlink_badpath(), readlink_dir(), readlink_empty(), readlink_file(), and try_readlink().
int reboot (int code)
Referenced by main(), and reboot_badflags().
int remove (const char * filename)
int rename (const char * oldfile, const char * newfile)
Referenced by dorename(), rename_badpath1(), rename_badpath2(), rename_dot(), rename_dotdot(), rename_empty1(), rename_empty2(), and try_rename().
int rmdir (const char * dirname)
Referenced by cleanup(), cleanup_rmdir(), dir_test(), dormdir(), killdir(), link_empty2(), main(), recursive_cleanup(), remove_dir(), rename_empty2(), rmdir_badpath(), rmdir_dot(), rmdir_dotdot(), rmdir_empty(), rmdir_file(), try_rmdir(), and unsetdir().
void* sbrk (int change)
Referenced by __malloc_init(), __malloc_sbrk(), and try_sbrk().
int symlink (const char * target, const char * linkname)
Referenced by create_testlink(), dosymlink(), symlink_badpath1(), symlink_badpath2(), symlink_empty1(), symlink_empty2(), and try_symlink().
int sync (void)
Referenced by main().
time_t time (time_t * seconds)
Definition at line 39 of file time.c.
int waitpid (pid_t pid, int * returncode, int flags)
Referenced by _exit(), docommand(), dorm(), dowait(), dowaitpoll(), exec_common_fork(), lseek_file_stdin(), main(), makeprocs(), run(), syscall(), system(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), wait_badflags(), wait_badpid(), wait_badstatus(), wait_parent(), wait_self(), wait_siblings(), wait_siblings_child(), wait_unaligned(), and waitall().
int write (int filehandle, const void * buf, size_t size)
Referenced by __bad_assert(), __senderr(), big_file(), complain(), complainx(), concur(), copy(), diskwrite(), docat(), dowrite(), lseek_file_stdin(), main(), mkfile(), open_testfile(), putchar(), say(), subproc_write(), tail(), test4(), try_write(), wait_siblings(), write_badbuf(), and write_badfd().