Os/161: kern/include/sfs.h File Reference
kern/include/sfs.h File Reference
#include <fs.h>
#include <vnode.h>
#include <kern/sfs.h>
Data Structures
struct sfs_vnode
struct sfs_fs
Defines
#define SFSUIO(iov, uio, ptr, block, rw) uio_kinit(iov, uio, ptr, SFS_BLOCKSIZE, ((off_t)(block))*SFS_BLOCKSIZE, rw)
Functions
int sfs_mount (const char *device)
int sfs_rwblock (struct sfs_fs *sfs, struct uio *uio)
int sfs_rblock (struct sfs_fs *sfs, void *data, uint32_t block)
int sfs_wblock (struct sfs_fs *sfs, void *data, uint32_t block)
struct vnode * sfs_getroot (struct fs *fs)
Define Documentation
#define SFSUIO (iov, uio, ptr, block, rw) uio_kinit(iov, uio, ptr, SFS_BLOCKSIZE, ((off_t)(block))*SFS_BLOCKSIZE, rw)
Definition at line 79 of file sfs.h.
Referenced by sfs_rblock(), and sfs_wblock().
Function Documentation
struct vnode* sfs_getroot (struct fs * fs) [read]
Definition at line 1764 of file sfs_vnode.c.
References fs::fs_data, panic(), sfs_loadvnode(), SFS_ROOT_LOCATION, SFS_TYPE_INVAL, sfs_vnode::sv_v, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by sfs_domount().
int sfs_mount (const char * device)
Definition at line 373 of file sfs_fs.c.
References NULL, sfs_domount(), and vfs_mount().
int sfs_rblock (struct sfs_fs * sfs, void * data, uint32_t block)
Definition at line 90 of file sfs_io.c.
References sfs_rwblock(), SFSUIO, and UIO_READ.
Referenced by sfs_bmap(), sfs_domount(), sfs_loadvnode(), sfs_mapio(), sfs_partialio(), and sfs_truncate().
int sfs_rwblock (struct sfs_fs * sfs, struct uio * uio)
Definition at line 48 of file sfs_io.c.
References device::d_io, DB_SFS, DEBUG, EINVAL, EIO, KASSERT, kprintf(), panic(), SFS_BLOCKSIZE, sfs_fs::sfs_device, uio::uio_offset, UIO_READ, uio::uio_rw, and vfs_biglock_do_i_hold().
Referenced by sfs_blockio(), sfs_rblock(), and sfs_wblock().
int sfs_wblock (struct sfs_fs * sfs, void * data, uint32_t block)
Definition at line 100 of file sfs_io.c.
References sfs_rwblock(), SFSUIO, and UIO_WRITE.
Referenced by sfs_bmap(), sfs_clearblock(), sfs_mapio(), sfs_partialio(), sfs_sync(), sfs_sync_inode(), and sfs_truncate().