Os/161: kern/arch/mips/thread/switchframe.c File Reference
kern/arch/mips/thread/switchframe.c File Reference
#include <types.h>
#include <lib.h>
#include <thread.h>
#include <threadprivate.h>
#include "switchframe.h"
Functions
void mips_threadstart ()
void switchframe_init (struct thread *thread, void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
Function Documentation
void mips_threadstart ()
Referenced by switchframe_init().
void switchframe_init (struct thread * thread, void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 55 of file switchframe.c.
References bzero(), mips_threadstart(), switchframe::sf_ra, switchframe::sf_s0, switchframe::sf_s1, switchframe::sf_s2, STACK_SIZE, thread::t_context, and thread::t_stack.
Referenced by thread_fork(), and thread_fork2().