Os/161: kern/include/addrspace.h File Reference
kern/include/addrspace.h File Reference
#include <vm.h>
#include "opt-dumbvm.h"
Data Structures
struct addrspace
Functions
struct addrspace * as_create (void)
int as_copy (struct addrspace *src, struct addrspace **ret)
void as_activate (struct addrspace *)
void as_destroy (struct addrspace *)
int as_define_region (struct addrspace *as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
int as_prepare_load (struct addrspace *as)
int as_complete_load (struct addrspace *as)
int as_define_stack (struct addrspace *as, vaddr_t *initstackptr)
int load_elf (struct vnode *v, vaddr_t *entrypoint)
Function Documentation
void as_activate (struct addrspace *)
Definition at line 228 of file dumbvm.c.
References NUM_TLB, splhigh(), splx(), tlb_write(), TLBHI_INVALID, and TLBLO_INVALID.
Referenced by runprogram(), sys_execv(), thread_exit(), thread_startup(), and thread_switch().
int as_complete_load (struct addrspace * as)
Definition at line 320 of file dumbvm.c.
Referenced by load_elf().
int as_copy (struct addrspace * src, struct addrspace ** ret)
Definition at line 336 of file dumbvm.c.
References as_create(), as_destroy(), addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, as_prepare_load(), addrspace::as_stackpbase, addrspace::as_vbase1, addrspace::as_vbase2, DUMBVM_STACKPAGES, ENOMEM, KASSERT, memmove(), NULL, PADDR_TO_KVADDR, and PAGE_SIZE.
Referenced by thread_fork2().
struct addrspace* as_create (void) [read]
Definition at line 203 of file dumbvm.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, addrspace::as_stackpbase, addrspace::as_vbase1, addrspace::as_vbase2, kmalloc(), and NULL.
Referenced by as_copy(), runprogram(), and sys_execv().
int as_define_region (struct addrspace * as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
Definition at line 245 of file dumbvm.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_vbase1, addrspace::as_vbase2, EUNIMP, kprintf(), PAGE_FRAME, and PAGE_SIZE.
Referenced by load_elf().
int as_define_stack (struct addrspace * as, vaddr_t * initstackptr)
Definition at line 327 of file dumbvm.c.
References addrspace::as_stackpbase, KASSERT, and USERSTACK.
Referenced by runprogram(), and sys_execv().
void as_destroy (struct addrspace *)
Definition at line 222 of file dumbvm.c.
References kfree().
Referenced by as_copy(), sys_execv(), and thread_exit().
int as_prepare_load (struct addrspace * as)
Definition at line 291 of file dumbvm.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, addrspace::as_stackpbase, as_zero_region(), DUMBVM_STACKPAGES, ENOMEM, getppages(), and KASSERT.
Referenced by as_copy(), and load_elf().
int load_elf (struct vnode * v, vaddr_t * entrypoint)
Definition at line 153 of file loadelf.c.
References as_complete_load(), as_define_region(), as_prepare_load(), Elf32_Ehdr::e_entry, Elf32_Ehdr::e_ident, Elf32_Ehdr::e_machine, Elf32_Ehdr::e_phentsize, Elf32_Ehdr::e_phnum, Elf32_Ehdr::e_phoff, Elf32_Ehdr::e_type, Elf32_Ehdr::e_version, EI_CLASS, EI_DATA, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, EI_VERSION, ELFCLASS32, ELFDATA2MSB, ELFMAG0, ELFMAG1, ELFMAG2, ELFMAG3, EM_MACHINE, ENOEXEC, ET_EXEC, EV_CURRENT, kprintf(), load_segment(), Elf32_Phdr::p_filesz, Elf32_Phdr::p_flags, Elf32_Phdr::p_memsz, Elf32_Phdr::p_offset, Elf32_Phdr::p_type, Elf32_Phdr::p_vaddr, PF_R, PF_W, PF_X, PT_LOAD, PT_MIPS_REGINFO, PT_NULL, PT_PHDR, uio_kinit(), UIO_READ, uio::uio_resid, and VOP_READ.
Referenced by runprogram(), and sys_execv().