Os/161: common/libc/string/strcpy.c File Reference
common/libc/string/strcpy.c File Reference
#include <string.h>
Functions
char * strcpy (char *dest, const char *src)
Function Documentation
char* strcpy (char * dest, const char * src)
Definition at line 46 of file strcpy.c.
Referenced by cmd_progthread(), dir_test(), dir_tryadd(), emu_open(), emufs_lookparent(), fstest_read(), fstest_remove(), fstest_write(), kstrdup(), main(), mkrawname(), printfile(), sfs_dir_link(), sfs_lookparent(), strcat(), system(), and writesuper().