Os/161: kern/arch/mips/thread/cpu.c File Reference
kern/arch/mips/thread/cpu.c File Reference
#include <types.h>
#include <lib.h>
#include <mips/specialreg.h>
#include <mips/trapframe.h>
#include <platform/maxcpus.h>
#include <cpu.h>
#include <thread.h>
Defines
#define GET_STATUS(x) __asm volatile("mfc0 %0,$12" : "=r" (x))
#define SET_STATUS(x) __asm volatile("mtc0 %0,$12" :: "r" (x))
Functions
void cpu_machdep_init (struct cpu *c)
const char * cpu_identify (void)
void cpu_irqon (void)
void cpu_irqoff (void)
static void cpu_irqonoff (void)
static void wait (void)
void cpu_idle (void)
void cpu_halt (void)
Variables
vaddr_t cpustacks [MAXCPUS]
vaddr_t cputhreads [MAXCPUS]
Define Documentation
#define GET_STATUS (x) __asm volatile("mfc0 %0,$12" : "=r" (x))
Definition at line 130 of file cpu.c.
Referenced by cpu_irqoff(), cpu_irqon(), and cpu_irqonoff().
#define SET_STATUS (x) __asm volatile("mtc0 %0,$12" :: "r" (x))
Definition at line 131 of file cpu.c.
Referenced by cpu_irqoff(), cpu_irqon(), and cpu_irqonoff().
Function Documentation
void cpu_halt (void)
Definition at line 230 of file cpu.c.
References cpu_irqoff(), and wait().
Referenced by interprocessor_interrupt(), lamebus_poweroff(), and mainbus_halt().
const char* cpu_identify (void)
Definition at line 100 of file cpu.c.
Referenced by cpu_hatch(), and thread_start_cpus().
void cpu_idle (void)
Definition at line 220 of file cpu.c.
References cpu_irqonoff(), and wait().
Referenced by thread_switch().
void cpu_irqoff (void)
Definition at line 150 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by cpu_halt(), lamebus_poweroff(), mips_trap(), mips_usermode(), and splraise().
void cpu_irqon (void)
Definition at line 137 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by spllower().
static void cpu_irqonoff (void) [static]
Definition at line 164 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by cpu_idle().
void cpu_machdep_init (struct cpu * c)
Definition at line 68 of file cpu.c.
References cpu::c_curthread, cpu::c_number, cpustacks, cputhreads, KASSERT, MAXCPUS, NULL, STACK_SIZE, and thread::t_stack.
Referenced by cpu_create().
static void wait (void) [inline, static]
Definition at line 194 of file cpu.c.
Referenced by cpu_halt(), and cpu_idle().
Variable Documentation
vaddr_t cpustacks[MAXCPUS]
Definition at line 59 of file cpu.c.
Referenced by cpu_machdep_init(), mips_trap(), and mips_usermode().
vaddr_t cputhreads[MAXCPUS]
Definition at line 60 of file cpu.c.
Referenced by cpu_machdep_init(), mips_trap(), and mips_usermode().