Os/161: kern/dev/lamebus/lser.c File Reference
kern/dev/lamebus/lser.c File Reference
#include <types.h>
#include <lib.h>
#include <spinlock.h>
#include <platform/bus.h>
#include <lamebus/lser.h>
#include "autoconf.h"
Defines
#define LSER_REG_CHAR 0
#define LSER_REG_WIRQ 4
#define LSER_REG_RIRQ 8
#define LSER_IRQ_ENABLE 1
#define LSER_IRQ_ACTIVE 2
Functions
void lser_irq (void *vsc)
void lser_write (void *vls, int ch)
static void lser_poll_until_write (struct lser_softc *sc)
void lser_writepolled (void *vsc, int ch)
void lser_startpolling (void *vsc)
void lser_endpolling (void *vsc)
int config_lser (struct lser_softc *sc, int lserno)
Define Documentation
#define LSER_IRQ_ACTIVE 2
Definition at line 44 of file lser.c.
Referenced by lser_irq(), and lser_poll_until_write().
#define LSER_IRQ_ENABLE 1
Definition at line 43 of file lser.c.
Referenced by config_lser(), lser_irq(), and lser_writepolled().
#define LSER_REG_CHAR 0
Definition at line 38 of file lser.c.
Referenced by lser_irq(), lser_write(), and lser_writepolled().
#define LSER_REG_RIRQ 8
Definition at line 40 of file lser.c.
Referenced by config_lser(), and lser_irq().
#define LSER_REG_WIRQ 4
Definition at line 39 of file lser.c.
Referenced by config_lser(), lser_irq(), lser_poll_until_write(), and lser_writepolled().
Function Documentation
int config_lser (struct lser_softc * sc, int lserno)
Definition at line 184 of file lser.c.
References bus_write_register, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_IRQ_ENABLE, LSER_REG_RIRQ, LSER_REG_WIRQ, and spinlock_init().
Referenced by tryattach_lser_to_lamebus().
void lser_endpolling (void * vsc)
Definition at line 177 of file lser.c.
References lser_softc::ls_busdata, lser_softc::ls_buspos, and lser_softc::ls_unmaskinterrupt.
Referenced by attach_con_to_lser().
void lser_irq (void * vsc)
Definition at line 47 of file lser.c.
References bus_read_register, bus_write_register, ch, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_devdata, lser_softc::ls_input, lser_softc::ls_lock, lser_softc::ls_start, lser_softc::ls_wbusy, LSER_IRQ_ACTIVE, LSER_IRQ_ENABLE, LSER_REG_CHAR, LSER_REG_RIRQ, LSER_REG_WIRQ, NULL, spinlock_acquire(), and spinlock_release().
Referenced by attach_lser_to_lamebus().
static void lser_poll_until_write (struct lser_softc * sc) [static]
Definition at line 116 of file lser.c.
References bus_read_register, KASSERT, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, LSER_IRQ_ACTIVE, LSER_REG_WIRQ, and spinlock_do_i_hold().
Referenced by lser_writepolled().
void lser_startpolling (void * vsc)
Definition at line 170 of file lser.c.
References lser_softc::ls_busdata, lser_softc::ls_buspos, and lser_softc::ls_maskinterrupt.
Referenced by attach_con_to_lser().
void lser_write (void * vls, int ch)
Definition at line 87 of file lser.c.
References bus_write_register, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_REG_CHAR, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lser().
void lser_writepolled (void * vsc, int ch)
Definition at line 130 of file lser.c.
References bus_write_register, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_IRQ_ENABLE, lser_poll_until_write(), LSER_REG_CHAR, LSER_REG_WIRQ, spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lser().