Os/161: kern/dev/lamebus/lamebus.h File Reference
kern/dev/lamebus/lamebus.h File Reference
#include <cpu.h>
#include <spinlock.h>
Data Structures
struct lamebus_softc
Defines
#define LB_VENDOR_CS161 1
#define LBCS161_BUSCTL 1
#define LBCS161_TIMER 2
#define LBCS161_DISK 3
#define LBCS161_SERIAL 4
#define LBCS161_SCREEN 5
#define LBCS161_NET 6
#define LBCS161_EMUFS 7
#define LBCS161_TRACE 8
#define LBCS161_RANDOM 9
#define LB_CONTROLLER_SLOT 31
#define LB_NSLOTS 32
#define LB_CONFIG_SIZE 1024
#define LB_CTLCPU_SIZE 1024
#define LB_CTLCPU_OFFSET 32768
#define LB_SLOT_SIZE 65536
Typedefs
typedef void(* lb_irqfunc)(void *devdata)
Functions
struct lamebus_softc * lamebus_init (void)
void lamebus_find_cpus (struct lamebus_softc *lamebus)
void lamebus_start_cpus (struct lamebus_softc *lamebus)
int lamebus_probe (struct lamebus_softc *, uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t highver)
void lamebus_mark (struct lamebus_softc *, int slot)
void lamebus_unmark (struct lamebus_softc *, int slot)
void lamebus_attach_interrupt (struct lamebus_softc *, int slot, void *devdata, void(*irqfunc)(void *devdata))
void lamebus_detach_interrupt (struct lamebus_softc *, int slot)
void lamebus_mask_interrupt (struct lamebus_softc *, int slot)
void lamebus_unmask_interrupt (struct lamebus_softc *, int slot)
void lamebus_interrupt (struct lamebus_softc *)
void lamebus_poweroff (struct lamebus_softc *)
size_t lamebus_ramsize (void)
void lamebus_assert_ipi (struct lamebus_softc *, struct cpu *targetcpu)
void lamebus_clear_ipi (struct lamebus_softc *, struct cpu *targetcpu)
uint32_t lamebus_read_register (struct lamebus_softc *, int slot, uint32_t offset)
void lamebus_write_register (struct lamebus_softc *, int slot, uint32_t offset, uint32_t val)
void * lamebus_map_area (struct lamebus_softc *, int slot, uint32_t offset)
Define Documentation
#define LB_CONFIG_SIZE 1024
Definition at line 64 of file lamebus.h.
Referenced by read_cfg_register(), and write_cfg_register().
#define LB_CONTROLLER_SLOT 31
Definition at line 58 of file lamebus.h.
Referenced by lamebus_init(), lamebus_start_cpus(), read_cfg_register(), read_ctl_register(), write_cfg_register(), write_ctl_register(), and write_ctlcpu_register().
#define LB_CTLCPU_OFFSET 32768
Definition at line 70 of file lamebus.h.
Referenced by lamebus_start_cpus(), and write_ctlcpu_register().
#define LB_CTLCPU_SIZE 1024
Definition at line 67 of file lamebus.h.
Referenced by lamebus_start_cpus(), and write_ctlcpu_register().
#define LB_NSLOTS 32
Definition at line 61 of file lamebus.h.
Referenced by lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_init(), lamebus_interrupt(), lamebus_map_area(), lamebus_mark(), lamebus_mask_interrupt(), lamebus_probe(), lamebus_unmark(), and lamebus_unmask_interrupt().
#define LB_SLOT_SIZE 65536
Definition at line 73 of file lamebus.h.
Referenced by lamebus_map_area().
#define LB_VENDOR_CS161 1
Definition at line 44 of file lamebus.h.
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lnet_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
#define LBCS161_BUSCTL 1
Definition at line 47 of file lamebus.h.
#define LBCS161_DISK 3
Definition at line 49 of file lamebus.h.
Referenced by attach_lhd_to_lamebus().
#define LBCS161_EMUFS 7
Definition at line 53 of file lamebus.h.
Referenced by attach_emu_to_lamebus().
#define LBCS161_NET 6
Definition at line 52 of file lamebus.h.
Referenced by attach_lnet_to_lamebus().
#define LBCS161_RANDOM 9
Definition at line 55 of file lamebus.h.
Referenced by attach_lrandom_to_lamebus().
#define LBCS161_SCREEN 5
Definition at line 51 of file lamebus.h.
Referenced by attach_lscreen_to_lamebus().
#define LBCS161_SERIAL 4
Definition at line 50 of file lamebus.h.
Referenced by attach_lser_to_lamebus().
#define LBCS161_TIMER 2
Definition at line 48 of file lamebus.h.
Referenced by attach_ltimer_to_lamebus().
#define LBCS161_TRACE 8
Definition at line 54 of file lamebus.h.
Referenced by attach_ltrace_to_lamebus().
Typedef Documentation
typedef void(* lb_irqfunc)(void *devdata)
Definition at line 76 of file lamebus.h.
Function Documentation
void lamebus_assert_ipi (struct lamebus_softc * , struct cpu * targetcpu)
Definition at line 589 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, and write_ctlcpu_register().
Referenced by mainbus_send_ipi().
void lamebus_attach_interrupt (struct lamebus_softc * , int slot, void * devdata, void(*)(void *devdata) irqfunc)
Definition at line 325 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), and attach_ltimer_to_lamebus().
void lamebus_clear_ipi (struct lamebus_softc * , struct cpu * targetcpu)
Definition at line 596 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, and write_ctlcpu_register().
Referenced by mainbus_interrupt().
void lamebus_detach_interrupt (struct lamebus_softc * , int slot)
Definition at line 353 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
void lamebus_find_cpus (struct lamebus_softc * lamebus)
Definition at line 127 of file lamebus.c.
References cpu_create(), CTLCPU_CIRQE, CTLREG_CPUS, CTLREG_SELF, curcpu, read_ctl_register(), and write_ctlcpu_register().
Referenced by mainbus_bootstrap().
struct lamebus_softc* lamebus_init (void) [read]
Definition at line 607 of file lamebus.c.
References kmalloc(), lamebus, LB_CONTROLLER_SLOT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), and spinlock_init().
Referenced by mainbus_bootstrap().
void lamebus_interrupt (struct lamebus_softc *)
Definition at line 407 of file lamebus.c.
References CTLREG_IRQS, curcpu, KASSERT, kprintf(), LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), read_ctl_register(), spinlock_acquire(), and spinlock_release().
Referenced by mainbus_interrupt().
void* lamebus_map_area (struct lamebus_softc * , int slot, uint32_t offset)
Definition at line 134 of file lamebus_machdep.c.
References KASSERT, LB_BASEADDR, LB_NSLOTS, and LB_SLOT_SIZE.
Referenced by lamebus_read_register(), lamebus_start_cpus(), and lamebus_write_register().
void lamebus_mark (struct lamebus_softc * , int slot)
Definition at line 284 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
void lamebus_mask_interrupt (struct lamebus_softc * , int slot)
Definition at line 377 of file lamebus.c.
References CTLREG_IRQE, KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
Referenced by do_lamebus_mask_interrupt().
void lamebus_poweroff (struct lamebus_softc *)
Definition at line 556 of file lamebus.c.
References cpu_halt(), cpu_irqoff(), CTLREG_PWR, and write_ctl_register().
Referenced by mainbus_poweroff().
int lamebus_probe (struct lamebus_softc * , uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t highver)
Definition at line 228 of file lamebus.c.
References CFGREG_DID, CFGREG_DRL, CFGREG_VID, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, read_cfg_register(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lnet_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
size_t lamebus_ramsize (void)
Definition at line 573 of file lamebus.c.
References CTLREG_RAMSZ, NULL, and read_ctl_register().
Referenced by mainbus_ramsize().
uint32_t lamebus_read_register (struct lamebus_softc * , int slot, uint32_t offset)
Definition at line 150 of file lamebus_machdep.c.
References lamebus_map_area().
Referenced by read_cfg_register().
void lamebus_start_cpus (struct lamebus_softc * lamebus)
Definition at line 184 of file lamebus.c.
References cpu_start_secondary(), CTLCPU_CRAM, CTLREG_CPUE, CTLREG_CPUS, CTLREG_SELF, lamebus_map_area(), LB_CONTROLLER_SLOT, LB_CTLCPU_OFFSET, LB_CTLCPU_SIZE, read_ctl_register(), and write_ctl_register().
Referenced by mainbus_start_cpus().
void lamebus_unmark (struct lamebus_softc * , int slot)
Definition at line 304 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
void lamebus_unmask_interrupt (struct lamebus_softc * , int slot)
Definition at line 390 of file lamebus.c.
References CTLREG_IRQE, KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
Referenced by do_lamebus_unmask_interrupt().
void lamebus_write_register (struct lamebus_softc * , int slot, uint32_t offset, uint32_t val)
Definition at line 161 of file lamebus_machdep.c.
References lamebus_map_area().
Referenced by write_cfg_register(), and write_ctlcpu_register().