Os/161: kern/dev/lamebus/lhd.h File Reference
kern/dev/lamebus/lhd.h File Reference
#include <device.h>
Data Structures
struct lhd_softc
Defines
#define LHD_SECTSIZE 512
Functions
void lhd_irq (void *)
Define Documentation
#define LHD_SECTSIZE 512
Definition at line 38 of file lhd.h.
Referenced by config_lhd(), and lhd_io().
Function Documentation
void lhd_irq (void *)
Definition at line 115 of file lhd.c.
References lhd_code_to_errno(), LHD_IDLE, LHD_INVSECT, lhd_iodone(), LHD_MEDIA, LHD_OK, lhd_rdreg(), LHD_REG_STAT, LHD_STATEMASK, LHD_WORKING, and lhd_wreg().
Referenced by attach_lhd_to_lamebus().