Os/161: kern/dev/lamebus/random_lrandom.c File Reference
kern/dev/lamebus/random_lrandom.c File Reference
#include <types.h>
#include <lib.h>
#include <generic/random.h>
#include <lamebus/lrandom.h>
#include "autoconf.h"
Functions
struct random_softc * attach_random_to_lrandom (int randomno, struct lrandom_softc *ls)
Function Documentation
struct random_softc* attach_random_to_lrandom (int randomno, struct lrandom_softc * ls) [read]
Definition at line 42 of file random_lrandom.c.
References kmalloc(), lrandom_randmax(), lrandom_random(), lrandom_read(), NULL, random_softc::rs_devdata, random_softc::rs_randmax, random_softc::rs_random, and random_softc::rs_read.
Referenced by tryattach_random_to_lrandom().