Os/161: common/libc/string/strrchr.c File Reference
common/libc/string/strrchr.c File Reference
#include <string.h>
Functions
char * strrchr (const char *s, int ch_arg)
Function Documentation
char* strrchr (const char * s, int ch_arg)
Definition at line 47 of file strrchr.c.
References ch, NULL, and strlen().
Referenced by basename(), emufs_lookparent(), and initprogname().