Os/161: kern/fs/sfs/sfs_fs.c File Reference
kern/fs/sfs/sfs_fs.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
#include <bitmap.h>
#include <uio.h>
#include <vfs.h>
#include <device.h>
#include <sfs.h>
Defines
#define SFS_FS_BITMAPSIZE(sfs) SFS_BITMAPSIZE((sfs)->sfs_super.sp_nblocks)
#define SFS_FS_BITBLOCKS(sfs) SFS_BITBLOCKS((sfs)->sfs_super.sp_nblocks)
Functions
static int sfs_mapio (struct sfs_fs *sfs, enum uio_rw rw)
static int sfs_sync (struct fs *fs)
static const char * sfs_getvolname (struct fs *fs)
static int sfs_unmount (struct fs *fs)
static int sfs_domount (void *options, struct device *dev, struct fs **ret)
int sfs_mount (const char *device)
Define Documentation
#define SFS_FS_BITBLOCKS (sfs) SFS_BITBLOCKS((sfs)->sfs_super.sp_nblocks)
Definition at line 48 of file sfs_fs.c.
Referenced by sfs_mapio().
#define SFS_FS_BITMAPSIZE (sfs) SFS_BITMAPSIZE((sfs)->sfs_super.sp_nblocks)
Definition at line 47 of file sfs_fs.c.
Referenced by sfs_domount().
Function Documentation
static int sfs_domount (void * options, struct device * dev, struct fs ** ret) [static]
Definition at line 255 of file sfs_fs.c.
References bitmap_create(), bitmap_destroy(), device::d_blocks, device::d_blocksize, EINVAL, ENOMEM, ENXIO, fs::fs_data, fs::fs_getroot, fs::fs_getvolname, fs::fs_sync, fs::fs_unmount, KASSERT, kfree(), kmalloc(), kprintf(), NULL, sfs_fs::sfs_absfs, SFS_BLOCKSIZE, sfs_fs::sfs_device, sfs_fs::sfs_freemap, sfs_fs::sfs_freemapdirty, SFS_FS_BITMAPSIZE, sfs_getroot(), sfs_getvolname(), SFS_MAGIC, sfs_mapio(), sfs_rblock(), SFS_SB_LOCATION, sfs_fs::sfs_super, sfs_fs::sfs_superdirty, sfs_sync(), sfs_unmount(), sfs_fs::sfs_vnodes, sfs_super::sp_magic, sfs_super::sp_nblocks, sfs_super::sp_volname, UIO_READ, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by sfs_mount().
static const char* sfs_getvolname (struct fs * fs) [static]
Definition at line 189 of file sfs_fs.c.
References fs::fs_data, sfs_fs::sfs_super, sfs_super::sp_volname, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by sfs_domount().
static int sfs_mapio (struct sfs_fs * sfs, enum uio_rw rw) [static]
Definition at line 70 of file sfs_fs.c.
References bitmap_getdata(), SFS_BLOCKSIZE, sfs_fs::sfs_freemap, SFS_FS_BITBLOCKS, SFS_MAP_LOCATION, sfs_rblock(), sfs_wblock(), and UIO_READ.
Referenced by sfs_domount(), and sfs_sync().
int sfs_mount (const char * device)
Definition at line 373 of file sfs_fs.c.
References NULL, sfs_domount(), and vfs_mount().
static int sfs_sync (struct fs * fs) [static]
Definition at line 111 of file sfs_fs.c.
References fs::fs_data, num, sfs_fs::sfs_freemapdirty, sfs_mapio(), SFS_SB_LOCATION, sfs_fs::sfs_super, sfs_fs::sfs_superdirty, sfs_fs::sfs_vnodes, sfs_wblock(), UIO_WRITE, vfs_biglock_acquire(), vfs_biglock_release(), and VOP_FSYNC.
Referenced by sfs_domount().
static int sfs_unmount (struct fs * fs) [static]
Definition at line 208 of file sfs_fs.c.
References bitmap_destroy(), EBUSY, fs::fs_data, KASSERT, kfree(), sfs_fs::sfs_device, sfs_fs::sfs_freemap, sfs_fs::sfs_freemapdirty, sfs_fs::sfs_superdirty, sfs_fs::sfs_vnodes, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by sfs_domount().