Os/161: kern/arch/mips/vm/ram.c File Reference
kern/arch/mips/vm/ram.c File Reference
#include <types.h>
#include <lib.h>
#include <vm.h>
#include <mainbus.h>
Functions
void ram_bootstrap (void)
paddr_t ram_stealmem (unsigned long npages)
void ram_getsize (paddr_t *lo, paddr_t *hi)
Variables
vaddr_t firstfree
static paddr_t firstpaddr
static paddr_t lastpaddr
Function Documentation
void ram_bootstrap (void)
Definition at line 46 of file ram.c.
References firstfree, firstpaddr, kprintf(), lastpaddr, mainbus_ramsize(), and MIPS_KSEG0.
Referenced by boot().
void ram_getsize (paddr_t * lo, paddr_t * hi)
Definition at line 121 of file ram.c.
References firstpaddr, and lastpaddr.
paddr_t ram_stealmem (unsigned long npages)
Definition at line 95 of file ram.c.
References firstpaddr, lastpaddr, and PAGE_SIZE.
Referenced by getppages().
Variable Documentation
vaddr_t firstfree
Definition at line 36 of file ram.c.
Referenced by ram_bootstrap().
paddr_t firstpaddr [static]
Definition at line 38 of file ram.c.
Referenced by ram_bootstrap(), ram_getsize(), and ram_stealmem().
paddr_t lastpaddr [static]
Definition at line 39 of file ram.c.
Referenced by ram_bootstrap(), ram_getsize(), and ram_stealmem().