Os/161: common/libc/stdlib/atoi.c File Reference
common/libc/stdlib/atoi.c File Reference
#include <stdlib.h>
#include <string.h>
Functions
int atoi (const char *s)
Function Documentation
int atoi (const char * s)
Definition at line 50 of file atoi.c.
References NULL, and strchr().
Referenced by cmd_exit(), cmd_wait(), doargs(), main(), and threadtest3().