Os/161: common/libc/printf/__printf.c File Reference
common/libc/printf/__printf.c File Reference
#include <sys/types.h>
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
Data Structures
struct PF
Defines
#define USE_LONGLONG
#define INTTYPE long long
#define NUMBER_BUF_SIZE ((sizeof(INTTYPE) * CHAR_BIT) / 3 + 2)
Functions
static void __pf_print (PF *pf, const char *txt, size_t len)
static void __pf_endfield (PF *pf)
static void __pf_modifier (PF *pf, int ch)
static void __pf_getnum (PF *pf, int ch)
static void __pf_setbase (PF *pf, int ch)
static void __pf_fill (PF *pf, int spc)
static void __pf_printstuff (PF *pf, const char *prefix, const char *prefix2, const char *stuff)
static void __pf_printnum (PF *pf)
static void __pf_send (PF *pf, int ch)
int __vprintf (void(*func)(void *clientdata, const char *str, size_t len), void *clientdata, const char *format, va_list ap)
Define Documentation
#define INTTYPE long long
Definition at line 70 of file __printf.c.
Referenced by __pf_getnum(), and __pf_printnum().
#define NUMBER_BUF_SIZE ((sizeof(INTTYPE) * CHAR_BIT) / 3 + 2)
Definition at line 84 of file __printf.c.
Referenced by __pf_printnum().
#define USE_LONGLONG
Definition at line 64 of file __printf.c.
Function Documentation
static void __pf_endfield (PF * pf) [static]
Definition at line 156 of file __printf.c.
References PF::altformat, PF::base, PF::baseprefix, PF::fillchar, PF::in_pct, PF::num, PF::rightspc, PF::sign, PF::size, and PF::spacing.
Referenced by __pf_send(), and __vprintf().
static void __pf_fill (PF * pf, int spc) [static]
Definition at line 337 of file __printf.c.
References __pf_print(), f, and PF::fillchar.
Referenced by __pf_printstuff().
static void __pf_getnum (PF * pf, int ch) [static]
Definition at line 237 of file __printf.c.
References PF::ap, INTTYPE, PF::num, PF::sign, PF::size, and va_arg.
Referenced by __pf_send().
static void __pf_modifier (PF * pf, int ch) [static]
Definition at line 180 of file __printf.c.
References PF::altformat, assert, PF::fillchar, PF::rightspc, PF::size, and PF::spacing.
Referenced by __pf_send().
static void __pf_print (PF * pf, const char * txt, size_t len) [static]
Definition at line 145 of file __printf.c.
References PF::charcount, PF::clientdata, and PF::sendfunc.
Referenced by __pf_fill(), __pf_printstuff(), and __pf_send().
static void __pf_printnum (PF * pf) [static]
Definition at line 402 of file __printf.c.
References __pf_printstuff(), PF::base, PF::baseprefix, INTTYPE, PF::num, NUMBER_BUF_SIZE, and PF::sign.
Referenced by __pf_send().
static void __pf_printstuff (PF * pf, const char * prefix, const char * prefix2, const char * stuff) [static]
Definition at line 354 of file __printf.c.
References __pf_fill(), __pf_print(), PF::fillchar, PF::rightspc, PF::spacing, and strlen().
Referenced by __pf_printnum(), and __pf_send().
static void __pf_send (PF * pf, int ch) [static]
Definition at line 485 of file __printf.c.
References __pf_endfield(), __pf_getnum(), __pf_modifier(), __pf_print(), __pf_printnum(), __pf_printstuff(), __pf_setbase(), PF::ap, assert, PF::in_pct, NULL, strchr(), and va_arg.
Referenced by __vprintf().
static void __pf_setbase (PF * pf, int ch) [static]
Definition at line 312 of file __printf.c.
References PF::altformat, PF::base, and PF::baseprefix.
Referenced by __pf_send().
int __vprintf (void(*)(void *clientdata, const char *str, size_t len) func, void * clientdata, const char * format, va_list ap)
Definition at line 558 of file __printf.c.
References __pf_endfield(), __pf_send(), PF::ap, PF::charcount, PF::clientdata, and PF::sendfunc.