Os/161: kern/fs/sfs/sfs_io.c File Reference
kern/fs/sfs/sfs_io.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <vfs.h>
#include <device.h>
#include <sfs.h>
Functions
int sfs_rwblock (struct sfs_fs *sfs, struct uio *uio)
int sfs_rblock (struct sfs_fs *sfs, void *data, uint32_t block)
int sfs_wblock (struct sfs_fs *sfs, void *data, uint32_t block)
Function Documentation
int sfs_rblock (struct sfs_fs * sfs, void * data, uint32_t block)
Definition at line 90 of file sfs_io.c.
References sfs_rwblock(), SFSUIO, and UIO_READ.
Referenced by sfs_bmap(), sfs_domount(), sfs_loadvnode(), sfs_mapio(), sfs_partialio(), and sfs_truncate().
int sfs_rwblock (struct sfs_fs * sfs, struct uio * uio)
Definition at line 48 of file sfs_io.c.
References device::d_io, DB_SFS, DEBUG, EINVAL, EIO, KASSERT, kprintf(), panic(), SFS_BLOCKSIZE, sfs_fs::sfs_device, uio::uio_offset, UIO_READ, uio::uio_rw, and vfs_biglock_do_i_hold().
Referenced by sfs_blockio(), sfs_rblock(), and sfs_wblock().
int sfs_wblock (struct sfs_fs * sfs, void * data, uint32_t block)
Definition at line 100 of file sfs_io.c.
References sfs_rwblock(), SFSUIO, and UIO_WRITE.
Referenced by sfs_bmap(), sfs_clearblock(), sfs_mapio(), sfs_partialio(), sfs_sync(), sfs_sync_inode(), and sfs_truncate().