Os/161: kern/dev/lamebus/lser_att.c File Reference
kern/dev/lamebus/lser_att.c File Reference
#include <types.h>
#include <lib.h>
#include <lamebus/lamebus.h>
#include <lamebus/lser.h>
#include "autoconf.h"
Defines
#define LOW_VERSION 1
#define HIGH_VERSION 1
Functions
static void do_lamebus_mask_interrupt (void *bus, uint32_t buspos)
static void do_lamebus_unmask_interrupt (void *bus, uint32_t buspos)
struct lser_softc * attach_lser_to_lamebus (int lserno, struct lamebus_softc *sc)
Define Documentation
#define HIGH_VERSION 1
Definition at line 39 of file lser_att.c.
#define LOW_VERSION 1
Definition at line 37 of file lser_att.c.
Function Documentation
struct lser_softc* attach_lser_to_lamebus (int lserno, struct lamebus_softc * sc) [read]
Definition at line 64 of file lser_att.c.
References do_lamebus_mask_interrupt(), do_lamebus_unmask_interrupt(), HIGH_VERSION, kmalloc(), lamebus_attach_interrupt(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_SERIAL, LOW_VERSION, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_maskinterrupt, lser_softc::ls_unmaskinterrupt, lser_irq(), and NULL.
Referenced by tryattach_lser_to_lamebus().
static void do_lamebus_mask_interrupt (void * bus, uint32_t buspos) [static]
Definition at line 46 of file lser_att.c.
References lamebus_mask_interrupt().
Referenced by attach_lser_to_lamebus().
static void do_lamebus_unmask_interrupt (void * bus, uint32_t buspos) [static]
Definition at line 54 of file lser_att.c.
References lamebus_unmask_interrupt().
Referenced by attach_lser_to_lamebus().