Os/161: user/lib/libc/stdlib/random.c File Reference
user/lib/libc/stdlib/random.c File Reference
#include <assert.h>
#include <errno.h>
#include <stdlib.h>
Defines
#define LOCKME()
#define UNLOCKME()
#define TYPE_0 0
#define BREAK_0 8
#define DEG_0 0
#define SEP_0 0
#define TYPE_1 1
#define BREAK_1 32
#define DEG_1 7
#define SEP_1 3
#define TYPE_2 2
#define BREAK_2 64
#define DEG_2 15
#define SEP_2 1
#define TYPE_3 3
#define BREAK_3 128
#define DEG_3 31
#define SEP_3 3
#define TYPE_4 4
#define BREAK_4 256
#define DEG_4 63
#define SEP_4 1
#define MAX_TYPES 5
Functions
static void srandom_unlocked (unsigned long)
static long random_unlocked (void)
void srandom (unsigned long x)
char * initstate (unsigned long seed, char *arg_state, size_t n)
char * setstate (char *arg_state)
long random (void)
Variables
static const int degrees [MAX_TYPES] = { DEG_0, DEG_1, DEG_2, DEG_3, DEG_4 }
static const int seps [MAX_TYPES] = { SEP_0, SEP_1, SEP_2, SEP_3, SEP_4 }
static long randtbl [DEG_3+1]
static long * fptr = &randtbl[SEP_3 + 1]
static long * rptr = &randtbl[1]
static long * state = &randtbl[1]
static long rand_type = TYPE_3
static int rand_deg = DEG_3
static int rand_sep = SEP_3
static long * end_ptr = &randtbl[DEG_3 + 1]
Define Documentation
#define BREAK_0 8
Definition at line 123 of file random.c.
Referenced by initstate().
#define BREAK_1 32
Definition at line 128 of file random.c.
Referenced by initstate().
#define BREAK_2 64
Definition at line 133 of file random.c.
Referenced by initstate().
#define BREAK_3 128
Definition at line 138 of file random.c.
Referenced by initstate().
#define BREAK_4 256
Definition at line 143 of file random.c.
Referenced by initstate().
#define DEG_0 0
Definition at line 124 of file random.c.
Referenced by initstate().
#define DEG_1 7
Definition at line 129 of file random.c.
Referenced by initstate().
#define DEG_2 15
Definition at line 134 of file random.c.
Referenced by initstate().
#define DEG_3 31
Definition at line 139 of file random.c.
Referenced by initstate().
#define DEG_4 63
Definition at line 144 of file random.c.
Referenced by initstate().
#define LOCKME ()
Definition at line 49 of file random.c.
Referenced by initstate(), random(), setstate(), and srandom().
#define MAX_TYPES 5
Definition at line 151 of file random.c.
Referenced by initstate(), and setstate().
#define SEP_0 0
Definition at line 125 of file random.c.
Referenced by initstate().
#define SEP_1 3
Definition at line 130 of file random.c.
Referenced by initstate().
#define SEP_2 1
Definition at line 135 of file random.c.
Referenced by initstate().
#define SEP_3 3
Definition at line 140 of file random.c.
Referenced by initstate().
#define SEP_4 1
Definition at line 145 of file random.c.
Referenced by initstate().
#define TYPE_0 0
Definition at line 122 of file random.c.
Referenced by initstate(), random_unlocked(), setstate(), and srandom_unlocked().
#define TYPE_1 1
Definition at line 127 of file random.c.
Referenced by initstate(), and setstate().
#define TYPE_2 2
Definition at line 132 of file random.c.
Referenced by initstate(), and setstate().
#define TYPE_3 3
Definition at line 137 of file random.c.
Referenced by initstate(), and setstate().
#define TYPE_4 4
Definition at line 142 of file random.c.
Referenced by initstate(), and setstate().
#define UNLOCKME ()
Definition at line 50 of file random.c.
Referenced by initstate(), random(), setstate(), and srandom().
Function Documentation
char* initstate (unsigned long seed, char * arg_state, size_t n)
Definition at line 282 of file random.c.
References assert, BREAK_0, BREAK_1, BREAK_2, BREAK_3, BREAK_4, DEG_0, DEG_1, DEG_2, DEG_3, DEG_4, LOCKME, MAX_TYPES, NULL, SEP_0, SEP_1, SEP_2, SEP_3, SEP_4, srandom_unlocked(), TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
long random (void)
Definition at line 445 of file random.c.
References LOCKME, NULL, panic(), random_unlocked(), random_softc::rs_devdata, random_softc::rs_random, and UNLOCKME.
Referenced by bitmaptest(), choose_name(), compute_thread(), genkeys(), genkeys_sub(), initarray(), randchar(), readallrandomly(), sleepalot_thread(), test567(), testa(), thread_startup(), and waker_thread().
static long random_unlocked (void) [static]
Definition at line 415 of file random.c.
References f, L, and TYPE_0.
Referenced by random(), and srandom_unlocked().
char* setstate (char * arg_state)
Definition at line 354 of file random.c.
References assert, degrees, LOCKME, MAX_TYPES, NULL, seps, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
void srandom (unsigned long x)
Definition at line 250 of file random.c.
References LOCKME, srandom_unlocked(), and UNLOCKME.
Referenced by genkeys(), genkeys_sub(), initarray(), main(), readallrandomly(), and test567().
static void srandom_unlocked (unsigned long x) [static]
Definition at line 232 of file random.c.
References L, random_unlocked(), and TYPE_0.
Referenced by initstate(), and srandom().
Variable Documentation
const int degrees[MAX_TYPES] = { DEG_0, DEG_1, DEG_2, DEG_3, DEG_4 } [static]
Definition at line 153 of file random.c.
Referenced by setstate().
long* end_ptr = &randtbl[DEG_3 + 1] [static]
Definition at line 216 of file random.c.
long* fptr = &randtbl[SEP_3 + 1] [static]
Definition at line 199 of file random.c.
int rand_deg = DEG_3 [static]
Definition at line 214 of file random.c.
int rand_sep = SEP_3 [static]
Definition at line 215 of file random.c.
long rand_type = TYPE_3 [static]
Definition at line 213 of file random.c.
long randtbl[DEG_3+1] [static]
Initial value:
 {
        TYPE_3,
        (long)0x9a319039L, (long)0x32d9c024L, (long)0x9b663182L,
        (long)0x5da1f342L, (long)0xde3b81e0L, (long)0xdf0a6fb5L,
        (long)0xf103bc02L, (long)0x48f340fbL, (long)0x7449e56bL,
        (long)0xbeb1dbb0L, (long)0xab5c5918L, (long)0x946554fdL,
        (long)0x8c2e680fL, (long)0xeb3d799fL, (long)0xb11ee0b7L,
        (long)0x2d436b86L, (long)0xda672e2aL, (long)0x1588ca88L,
        (long)0xe369735dL, (long)0x904f35f7L, (long)0xd7158fd6L,
        (long)0x6fa6f051L, (long)0x616e6b96L, (long)0xac94efdcL,
        (long)0x36413f93L, (long)0xc622c298L, (long)0xf5a42ab8L,
        (long)0x8a88d77bL, (long)0xf5ad9d0eL, (long)0x8999220bL,
        (long)0x27fb47b9L,
}
Definition at line 170 of file random.c.
long* rptr = &randtbl[1] [static]
Definition at line 200 of file random.c.
const int seps[MAX_TYPES] = { SEP_0, SEP_1, SEP_2, SEP_3, SEP_4 } [static]
Definition at line 154 of file random.c.
Referenced by setstate().
long* state = &randtbl[1] [static]
Definition at line 212 of file random.c.