Os/161: kern/syscall/runprogram.c File Reference
kern/syscall/runprogram.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <lib.h>
#include <thread.h>
#include <current.h>
#include <addrspace.h>
#include <vm.h>
#include <vfs.h>
#include <syscall.h>
#include <test.h>
#include <copyinout.h>
Functions
int runprogram (char *progname, int nargs, char **args)
Function Documentation
int runprogram (char * progname, int nargs, char ** args)
Definition at line 56 of file runprogram.c.
References as_activate(), as_create(), as_define_stack(), copyout(), EINVAL, ENOMEM, enter_new_process(), KASSERT, kfree(), kmalloc(), kstrdup(), load_elf(), NULL, O_RDONLY, panic(), STACK_OFFSET, strlen(), vfs_close(), and vfs_open().
Referenced by cmd_progthread().