Os/161: kern/vfs/vfslist.c File Reference
kern/vfs/vfslist.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
#include <synch.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
#include <device.h>
Data Structures
struct knowndev
Defines
#define VFSINLINE
Functions
DECLARRAY (knowndev)
DEFARRAY (knowndev,)
void vfs_bootstrap (void)
void vfs_biglock_acquire (void)
void vfs_biglock_release (void)
bool vfs_biglock_do_i_hold (void)
int vfs_sync (void)
int vfs_getroot (const char *devname, struct vnode **result)
const char * vfs_getdevname (struct fs *fs)
static char * mkrawname (const char *name)
static int samestring (const char *a, const char *b)
static int samestring3 (const char *a, const char *b, const char *c, const char *d)
static int badnames (const char *n1, const char *n2, const char *n3)
static int vfs_doadd (const char *dname, int mountable, struct device *dev, struct fs *fs)
int vfs_adddev (const char *devname, struct device *dev, int mountable)
int vfs_addfs (const char *devname, struct fs *fs)
static int findmount (const char *devname, struct knowndev **result)
int vfs_mount (const char *devname, void *data, int(*mountfunc)(void *data, struct device *, struct fs **ret))
int vfs_unmount (const char *devname)
int vfs_unmountall (void)
Variables
static struct knowndevarray * knowndevs
static struct lock * vfs_biglock
static unsigned vfs_biglock_depth
Define Documentation
#define VFSINLINE
Definition at line 35 of file vfslist.c.
Function Documentation
static int badnames (const char * n1, const char * n2, const char * n3) [static]
Definition at line 335 of file vfslist.c.
References FSOP_GETVOLNAME, KASSERT, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndevs, num, samestring3(), and vfs_biglock_do_i_hold().
Referenced by vfs_doadd().
DECLARRAY (knowndev)
DEFARRAY (knowndev)
static int findmount (const char * devname, struct knowndev ** result) [static]
Definition at line 477 of file vfslist.c.
References ENODEV, KASSERT, knowndev::kd_name, knowndev::kd_rawname, knowndevs, NULL, num, strcmp(), and vfs_biglock_do_i_hold().
Referenced by vfs_mount(), and vfs_unmount().
static char* mkrawname (const char * name) [static]
Definition at line 289 of file vfslist.c.
References kmalloc(), NULL, strcat(), strcpy(), and strlen().
Referenced by vfs_doadd().
static int samestring (const char * a, const char * b) [inline, static]
Definition at line 308 of file vfslist.c.
References NULL, and strcmp().
Referenced by samestring3().
static int samestring3 (const char * a, const char * b, const char * c, const char * d) [inline, static]
Definition at line 323 of file vfslist.c.
References samestring().
Referenced by badnames().
int vfs_adddev (const char * devname, struct device * dev, int mountable)
Definition at line 453 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), and devnull_create().
int vfs_addfs (const char * devname, struct fs * fs)
Definition at line 464 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by emufs_addtovfs().
void vfs_biglock_acquire (void)
Definition at line 123 of file vfslist.c.
References lock_acquire(), lock_do_i_hold(), and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_truncate(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_sync(), vfs_unmount(), vfs_unmountall(), vnode_check(), vnode_decopen(), vnode_decref(), vnode_incopen(), and vnode_incref().
bool vfs_biglock_do_i_hold (void)
Definition at line 143 of file vfslist.c.
References lock_do_i_hold().
Referenced by badnames(), findmount(), getdevice(), sfs_rwblock(), vfs_getdevname(), and vfs_getroot().
void vfs_biglock_release (void)
Definition at line 132 of file vfslist.c.
References KASSERT, lock_do_i_hold(), lock_release(), and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_truncate(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_sync(), vfs_unmount(), vfs_unmountall(), vnode_check(), vnode_decopen(), vnode_decref(), vnode_incopen(), and vnode_incref().
void vfs_bootstrap (void)
Definition at line 99 of file vfslist.c.
References devnull_create(), knowndevs, lock_create(), NULL, panic(), and vfs_biglock_depth.
Referenced by boot().
static int vfs_doadd (const char * dname, int mountable, struct device * dev, struct fs * fs) [static]
Definition at line 372 of file vfslist.c.
References badnames(), device::d_devnumber, dev_create_vnode(), EEXIST, ENOMEM, FSOP_GETVOLNAME, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, kfree(), kmalloc(), knowndevs, kstrdup(), mkrawname(), name, NULL, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by vfs_adddev(), and vfs_addfs().
const char* vfs_getdevname (struct fs * fs)
Definition at line 257 of file vfslist.c.
References KASSERT, knowndev::kd_fs, knowndev::kd_name, knowndevs, NULL, num, and vfs_biglock_do_i_hold().
Referenced by vfs_getcwd().
int vfs_getroot (const char * devname, struct vnode ** result)
Definition at line 177 of file vfslist.c.
References ENODEV, ENXIO, FSOP_GETROOT, FSOP_GETVOLNAME, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, knowndevs, NULL, num, strcmp(), vfs_biglock_do_i_hold(), and VOP_INCREF.
Referenced by getdevice().
int vfs_mount (const char * devname, void * data, int(*)(void *data, struct device *, struct fs **ret) mountfunc)
Definition at line 509 of file vfslist.c.
References EBUSY, findmount(), FSOP_GETVOLNAME, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, kprintf(), NULL, vfs_biglock_acquire(), and vfs_biglock_release().
int vfs_sync (void)
Definition at line 152 of file vfslist.c.
References FSOP_SYNC, knowndev::kd_fs, knowndevs, NULL, num, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_quit(), cmd_sync(), and panic().
int vfs_unmount (const char * devname)
Definition at line 555 of file vfslist.c.
References EINVAL, fail(), findmount(), FSOP_SYNC, FSOP_UNMOUNT, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, kprintf(), NULL, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_unmount().
int vfs_unmountall (void)
Definition at line 600 of file vfslist.c.
References EBUSY, FSOP_SYNC, FSOP_UNMOUNT, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndevs, kprintf(), NULL, num, strerror(), vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by shutdown().
Variable Documentation
struct knowndevarray* knowndevs [static]
Definition at line 88 of file vfslist.c.
Referenced by badnames(), findmount(), vfs_bootstrap(), vfs_doadd(), vfs_getdevname(), vfs_getroot(), vfs_sync(), and vfs_unmountall().
struct lock* vfs_biglock [static]
Definition at line 91 of file vfslist.c.
unsigned vfs_biglock_depth [static]
Definition at line 92 of file vfslist.c.
Referenced by vfs_biglock_acquire(), vfs_biglock_release(), and vfs_bootstrap().