Os/161: kern/include/wchan.h File Reference
kern/include/wchan.h File Reference
Functions
struct wchan * wchan_create (const char *name)
void wchan_destroy (struct wchan *wc)
bool wchan_isempty (struct wchan *wc)
void wchan_lock (struct wchan *wc)
void wchan_unlock (struct wchan *wc)
void wchan_sleep (struct wchan *wc)
void wchan_wakeone (struct wchan *wc)
void wchan_wakeall (struct wchan *wc)
Function Documentation
struct wchan* wchan_create (const char * name) [read]
Definition at line 1060 of file thread.c.
References kmalloc(), NULL, spinlock_init(), threadlist_init(), wchan::wc_lock, wchan::wc_name, and wchan::wc_threads.
Referenced by hardclock_bootstrap(), sem_create(), and setup().
void wchan_destroy (struct wchan * wc)
Definition at line 1079 of file thread.c.
References kfree(), spinlock_cleanup(), threadlist_cleanup(), wchan::wc_lock, and wchan::wc_threads.
Referenced by sem_destroy().
bool wchan_isempty (struct wchan * wc)
Definition at line 1183 of file thread.c.
References spinlock_acquire(), spinlock_release(), threadlist_isempty(), wchan::wc_lock, and wchan::wc_threads.
void wchan_lock (struct wchan * wc)
Definition at line 1090 of file thread.c.
References spinlock_acquire(), and wchan::wc_lock.
Referenced by clocksleep(), P(), and sleepalot_thread().
void wchan_sleep (struct wchan * wc)
Definition at line 1108 of file thread.c.
References KASSERT, S_SLEEP, and thread_switch().
Referenced by clocksleep(), P(), and sleepalot_thread().
void wchan_unlock (struct wchan * wc)
Definition at line 1096 of file thread.c.
References spinlock_release(), and wchan::wc_lock.
Referenced by thread_switch().
void wchan_wakeall (struct wchan * wc)
Definition at line 1145 of file thread.c.
References NULL, spinlock_acquire(), spinlock_release(), thread_make_runnable(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_remhead(), wchan::wc_lock, and wchan::wc_threads.
Referenced by timerclock(), and waker_thread().
void wchan_wakeone (struct wchan * wc)
Definition at line 1120 of file thread.c.
References NULL, spinlock_acquire(), spinlock_release(), thread_make_runnable(), threadlist_remhead(), wchan::wc_lock, and wchan::wc_threads.
Referenced by V().