Os/161: kern/lib/uio.c File Reference
kern/lib/uio.c File Reference
#include <types.h>
#include <lib.h>
#include <uio.h>
#include <thread.h>
#include <current.h>
#include <copyinout.h>
Functions
int uiomove (void *ptr, size_t n, struct uio *uio)
int uiomovezeros (size_t n, struct uio *uio)
void uio_kinit (struct iovec *iov, struct uio *u, void *kbuf, size_t len, off_t pos, enum uio_rw rw)
Function Documentation
void uio_kinit (struct iovec * iov, struct uio * u, void * kbuf, size_t len, off_t pos, enum uio_rw rw)
Definition at line 153 of file uio.c.
References iovec::iov_len, NULL, uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, and UIO_SYSSPACE.
Referenced by cmd_pwd(), fstest_read(), fstest_write(), load_elf(), printfile(), sfs_readdir(), and sfs_writedir().
int uiomove (void * ptr, size_t n, struct uio * uio)
Definition at line 42 of file uio.c.
References copyin(), copyout(), iovec::iov_len, KASSERT, memmove(), NULL, panic(), uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, UIO_SYSSPACE, UIO_USERISPACE, UIO_USERSPACE, and UIO_WRITE.
Referenced by con_io(), emu_doread(), emu_write(), lhd_io(), lrandom_read(), sfs_partialio(), uiomovezeros(), and vfs_getcwd().
int uiomovezeros (size_t n, struct uio * uio)
Definition at line 123 of file uio.c.
References KASSERT, UIO_READ, uio::uio_rw, and uiomove().
Referenced by load_segment(), and sfs_blockio().