Os/161: user/bin/ln/ln.c File Reference
user/bin/ln/ln.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <err.h>
Functions
static void dosymlink (const char *text, const char *path)
static void dohardlink (const char *oldfile, const char *newfile)
int main (int argc, char *argv[])
Function Documentation
static void dohardlink (const char * oldfile, const char * newfile) [static]
Definition at line 65 of file ln.c.
References err(), exit(), and link().
Referenced by main().
static void dosymlink (const char * text, const char * path) [static]
Definition at line 51 of file ln.c.
References err(), and symlink().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 74 of file ln.c.
References dohardlink(), dosymlink(), errx(), strcmp(), and warnx().