Os/161: user/bin/sh/sh.c File Reference
user/bin/sh/sh.c File Reference
#include <sys/types.h>
#include <sys/wait.h>
#include <assert.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
Defines
#define NARG_MAX 1024
#define CMDLINE_MAX 4096
#define MAXBG 128
Functions
static int can_bg (void)
static void remember_bg (pid_t pid)
static void printstatus (int status)
static void dowait (pid_t pid)
static int dowaitpoll (pid_t pid)
static void waitpoll (void)
static int cmd_wait (int ac, char *av[])
static int cmd_chdir (int ac, char *av[])
static int cmd_exit (int ac, char *av[])
static int docommand (char *buf)
static void getcmd (char *buf, size_t len)
static void interactive (void)
static void check_timing (void)
int main (int argc, char *argv[])
Variables
static int timing = 0
static pid_t bgpids [MAXBG]
struct {
const char * name
int(* func)(int, char **)
} builtins []
Define Documentation
#define CMDLINE_MAX 4096
Definition at line 60 of file sh.c.
Referenced by interactive().
#define MAXBG 128
Definition at line 69 of file sh.c.
Referenced by can_bg(), cmd_wait(), remember_bg(), and waitpoll().
#define NARG_MAX 1024
Definition at line 55 of file sh.c.
Referenced by docommand().
Function Documentation
static int can_bg (void) [static]
Definition at line 78 of file sh.c.
References bgpids, and MAXBG.
Referenced by docommand().
static void check_timing (void) [static]
Definition at line 482 of file sh.c.
References __time(), timing, and warnx().
Referenced by main().
static int cmd_chdir (int ac, char * av[]) [static]
Definition at line 240 of file sh.c.
References chdir(), printf(), and warn().
static int cmd_exit (int ac, char * av[]) [static]
Definition at line 260 of file sh.c.
References atoi(), exit(), and printf().
static int cmd_wait (int ac, char * av[]) [static]
Definition at line 205 of file sh.c.
References atoi(), bgpids, dowait(), MAXBG, pid, and printf().
static int docommand (char * buf) [static]
Definition at line 304 of file sh.c.
References __time(), _exit(), _MKWAIT_EXIT, builtins, can_bg(), execv(), fork(), name, NARG_MAX, NULL, pid, printf(), remember_bg(), strcmp(), strtok(), timing, waitpid(), warn(), and warnx().
Referenced by interactive(), and main().
static void dowait (pid_t pid) [static]
Definition at line 141 of file sh.c.
References printf(), printstatus(), waitpid(), and warn().
Referenced by cmd_wait().
static int dowaitpoll (pid_t pid) [static]
Definition at line 161 of file sh.c.
References printf(), printstatus(), waitpid(), warn(), and WNOHANG.
Referenced by waitpoll().
static void getcmd (char * buf, size_t len) [static]
Definition at line 419 of file sh.c.
References ch, getchar(), pos, and putchar().
Referenced by interactive().
static void interactive (void) [static]
Definition at line 461 of file sh.c.
References CMDLINE_MAX, docommand(), getcmd(), printf(), printstatus(), and waitpoll().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 498 of file sh.c.
References check_timing(), docommand(), errx(), hostcompat_init(), interactive(), and strcmp().
static void printstatus (int status) [static]
Definition at line 116 of file sh.c.
References printf(), WCOREDUMP, WEXITSTATUS, WIFEXITED, WIFSIGNALED, WIFSTOPPED, WSTOPSIG, and WTERMSIG.
Referenced by dowait(), dowaitpoll(), and interactive().
static void remember_bg (pid_t pid) [static]
Definition at line 98 of file sh.c.
References assert, bgpids, and MAXBG.
Referenced by docommand().
static void waitpoll (void) [static]
Definition at line 184 of file sh.c.
References bgpids, dowaitpoll(), and MAXBG.
Referenced by interactive().
Variable Documentation
pid_t bgpids[MAXBG] [static]
Definition at line 70 of file sh.c.
Referenced by can_bg(), cmd_wait(), remember_bg(), and waitpoll().
struct { ... } builtins[] [static]
Referenced by docommand().
int(* func)(int, char **)
const char* name
Definition at line 285 of file sh.c.
int timing = 0 [static]
Definition at line 66 of file sh.c.
Referenced by check_timing(), and docommand().