Os/161: kern/vfs/devnull.c File Reference
kern/vfs/devnull.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <vfs.h>
#include <device.h>
Functions
static int nullopen (struct device *dev, int openflags)
static int nullclose (struct device *dev)
static int nullio (struct device *dev, struct uio *uio)
static int nullioctl (struct device *dev, int op, userptr_t data)
void devnull_create (void)
Function Documentation
void devnull_create (void)
Definition at line 100 of file devnull.c.
References device::d_blocks, device::d_blocksize, device::d_close, device::d_data, device::d_devnumber, device::d_io, device::d_ioctl, device::d_open, kmalloc(), NULL, nullclose(), nullio(), nullioctl(), nullopen(), panic(), strerror(), and vfs_adddev().
Referenced by vfs_bootstrap().
static int nullclose (struct device * dev) [static]
Definition at line 55 of file devnull.c.
Referenced by devnull_create().
static int nullio (struct device * dev, struct uio * uio) [static]
Definition at line 64 of file devnull.c.
References uio::uio_resid, uio::uio_rw, and UIO_WRITE.
Referenced by devnull_create().
static int nullioctl (struct device * dev, int op, userptr_t data) [static]
Definition at line 83 of file devnull.c.
References EINVAL.
Referenced by devnull_create().
static int nullopen (struct device * dev, int openflags) [static]
Definition at line 44 of file devnull.c.
Referenced by devnull_create().