Os/161: kern/syscall/dup2_syscall.c File Reference
kern/syscall/dup2_syscall.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <vm.h>
#include <mainbus.h>
#include <vfs.h>
#include <vnode.h>
#include <device.h>
#include <syscall.h>
#include <kern/fcntl.h>
#include <kern/file.h>
Functions
int sys_dup2 (int old_fd, int new_fd, int *retval)
Function Documentation
int sys_dup2 (int old_fd, int new_fd, int * retval)
Definition at line 36 of file dup2_syscall.c.
References EBADF, EMFILE, errno, kfree(), kmalloc(), MAX_FD, NULL, file::readable, vfs_close(), file::vfs_node, vnode_incopen(), vnode_incref(), and file::writeable.
Referenced by syscall().