Os/161: user/lib/hostcompat/host-err.h File Reference
user/lib/hostcompat/host-err.h File Reference
#include <stdarg.h>
Functions
void warn (const char *fmt,...)
void warnx (const char *fmt,...)
void err (int exitcode, const char *fmt,...)
void errx (int exitcode, const char *fmt,...)
void vwarn (const char *fmt, va_list)
void vwarnx (const char *fmt, va_list)
void verr (int exitcode, const char *fmt, va_list)
void verrx (int exitcode, const char *fmt, va_list)
Function Documentation
void err (int exitcode, const char * fmt, ...)
Definition at line 176 of file err.c.
References va_end, va_start, and verr().
void errx (int exitcode, const char * fmt, ...)
Definition at line 185 of file err.c.
References va_end, va_start, and verrx().
void verr (int exitcode, const char * fmt, va_list)
Definition at line 138 of file err.c.
References __printerr(), and exit().
void verrx (int exitcode, const char * fmt, va_list)
Definition at line 146 of file err.c.
References __printerr(), and exit().
void vwarn (const char * fmt, va_list)
Definition at line 124 of file err.c.
References __printerr().
void vwarnx (const char * fmt, va_list)
Definition at line 131 of file err.c.
References __printerr().
void warn (const char * fmt, ...)
Definition at line 158 of file err.c.
References va_end, va_start, and vwarn().
void warnx (const char * fmt, ...)
Definition at line 167 of file err.c.
References va_end, va_start, and vwarnx().