Os/161: kern/syscall/exit_syscall.c File Reference
kern/syscall/exit_syscall.c File Reference
#include <types.h>
#include <kern/unistd.h>
#include <kern/errno.h>
#include <lib.h>
#include <addrspace.h>
#include <thread.h>
#include <current.h>
#include <array.h>
#include <syscall.h>
#include <threadlist.h>
#include <threadprivate.h>
#include <spl.h>
Functions
void exorcise (void)
void _exit (int exitcode)
Variables
char pid_used [MAX_THREAD]
struct thread * thread_table [MAX_THREAD]
Function Documentation
void _exit (int exitcode)
Definition at line 30 of file exit_syscall.c.
References exit(), MAX_THREAD, NULL, thread::parent_id, pid_used, S_ZOMBIE, thread_exit(), thread::thread_id, and waitpid().
Referenced by abort(), docommand(), dorm(), exit(), forkoff(), hostcompat_die(), lseek_file_stdin(), main(), syscall(), system(), wait_parent(), and wait_siblings().
void exorcise (void)
Referenced by thread_startup(), and thread_switch().
Variable Documentation
char pid_used[MAX_THREAD]
Definition at line 58 of file thread.c.
Referenced by _exit(), find_nextpid(), thread_bootstrap(), thread_fork(), thread_fork2(), and waitpid().
struct thread* thread_table[MAX_THREAD]
Definition at line 64 of file thread.c.