Os/161: kern/test/malloctest.c File Reference
kern/test/malloctest.c File Reference
#include <types.h>
#include <lib.h>
#include <thread.h>
#include <synch.h>
#include <test.h>
Defines
#define NTRIES 1200
#define ITEMSIZE 997
#define NTHREADS 8
Functions
static void mallocthread (void *sm, unsigned long num)
int malloctest (int nargs, char **args)
int mallocstress (int nargs, char **args)
Define Documentation
#define ITEMSIZE 997
Definition at line 51 of file malloctest.c.
Referenced by mallocthread().
#define NTHREADS 8
Definition at line 52 of file malloctest.c.
#define NTRIES 1200
Definition at line 50 of file malloctest.c.
Referenced by mallocthread(), mkdir_proc(), rename_proc(), and rmdir_proc().
Function Documentation
int mallocstress (int nargs, char ** args)
Definition at line 107 of file malloctest.c.
References kprintf(), mallocthread(), NTHREADS, NULL, P(), panic(), sem_create(), sem_destroy(), strerror(), and thread_fork().
int malloctest (int nargs, char ** args)
Definition at line 94 of file malloctest.c.
References kprintf(), mallocthread(), and NULL.
static void mallocthread (void * sm, unsigned long num) [static]
Definition at line 56 of file malloctest.c.
References ITEMSIZE, kfree(), kmalloc(), kprintf(), NTRIES, NULL, and V().
Referenced by mallocstress(), and malloctest().