Os/161: kern/thread/spl.c File Reference
kern/thread/spl.c File Reference
#include <types.h>
#include <lib.h>
#include <cpu.h>
#include <spl.h>
#include <thread.h>
#include <current.h>
Defines
#define SPL_INLINE
Functions
void splraise (int oldspl, int newspl)
void spllower (int oldspl, int newspl)
int splx (int spl)
Define Documentation
#define SPL_INLINE
Definition at line 31 of file spl.c.
Function Documentation
void spllower (int oldspl, int newspl)
Definition at line 107 of file spl.c.
References cpu_irqon(), CURCPU_EXISTS, IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_release(), and splx().
void splraise (int oldspl, int newspl)
Definition at line 87 of file spl.c.
References cpu_irqoff(), CURCPU_EXISTS, IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_acquire(), and splx().
int splx (int spl)
Definition at line 132 of file spl.c.
References spllower(), splraise(), and thread::t_curspl.
Referenced by as_activate(), ltimer_gettime(), mips_trap(), spl0(), splhigh(), sys_read(), sys_write(), thread_fork2(), thread_switch(), vm_fault(), and waitpid().