Os/161: kern/vm/kmalloc.c File Reference
kern/vm/kmalloc.c File Reference
#include <types.h>
#include <lib.h>
#include <spinlock.h>
#include <vm.h>
Data Structures
struct freelist
struct pageref
Defines
#define NSIZES 8
#define SMALLEST_SUBPAGE_SIZE 16
#define LARGEST_SUBPAGE_SIZE 2048
#define INVALID_OFFSET (0xffff)
#define PR_PAGEADDR(pr) ((pr)->pageaddr_and_blocktype & PAGE_FRAME)
#define PR_BLOCKTYPE(pr) ((pr)->pageaddr_and_blocktype & ~PAGE_FRAME)
#define MKPAB(pa, blk) (((pa)&PAGE_FRAME) | ((blk) & ~PAGE_FRAME))
#define NPAGEREFS (PAGE_SIZE / sizeof(struct pageref))
#define INUSE_WORDS (NPAGEREFS/32)
#define checksubpage(pr) ((void)(pr))
#define checksubpages()
Functions
static void fill_deadbeef (void *vptr, size_t len)
static struct pageref * allocpageref (void)
static void freepageref (struct pageref *p)
static void dumpsubpage (struct pageref *pr)
void kheap_printstats (void)
static void remove_lists (struct pageref *pr, int blktype)
static int blocktype (size_t sz)
static void * subpage_kmalloc (size_t sz)
static int subpage_kfree (void *ptr)
void * kmalloc (size_t sz)
void kfree (void *ptr)
Variables
static const size_t sizes [NSIZES] = { 16, 32, 64, 128, 256, 512, 1024, 2048 }
static struct pageref pagerefs [NPAGEREFS]
static uint32_t pagerefs_inuse [INUSE_WORDS]
static struct pageref * sizebases [NSIZES]
static struct pageref * allbase
static struct spinlock kmalloc_spinlock = SPINLOCK_INITIALIZER
Define Documentation
#define checksubpage (pr) ((void)(pr))
Definition at line 246 of file kmalloc.c.
Referenced by dumpsubpage(), remove_lists(), subpage_kfree(), and subpage_kmalloc().
#define checksubpages ()
Definition at line 277 of file kmalloc.c.
Referenced by subpage_kfree(), and subpage_kmalloc().
#define INUSE_WORDS (NPAGEREFS/32)
Definition at line 141 of file kmalloc.c.
Referenced by allocpageref().
#define INVALID_OFFSET (0xffff)
Definition at line 112 of file kmalloc.c.
Referenced by dumpsubpage(), subpage_kfree(), and subpage_kmalloc().
#define LARGEST_SUBPAGE_SIZE 2048
Definition at line 90 of file kmalloc.c.
Referenced by kmalloc().
#define MKPAB (pa, blk) (((pa)&PAGE_FRAME) | ((blk) & ~PAGE_FRAME))
Definition at line 116 of file kmalloc.c.
Referenced by subpage_kmalloc().
#define NPAGEREFS (PAGE_SIZE / sizeof(struct pageref))
Definition at line 138 of file kmalloc.c.
Referenced by freepageref().
#define NSIZES 8
Definition at line 86 of file kmalloc.c.
Referenced by blocktype(), remove_lists(), and subpage_kfree().
#define PR_BLOCKTYPE (pr) ((pr)->pageaddr_and_blocktype & ~PAGE_FRAME)
Definition at line 115 of file kmalloc.c.
Referenced by dumpsubpage(), subpage_kfree(), and subpage_kmalloc().
#define PR_PAGEADDR (pr) ((pr)->pageaddr_and_blocktype & PAGE_FRAME)
Definition at line 114 of file kmalloc.c.
Referenced by dumpsubpage(), subpage_kfree(), and subpage_kmalloc().
#define SMALLEST_SUBPAGE_SIZE 16
Definition at line 89 of file kmalloc.c.
Referenced by dumpsubpage().
Function Documentation
static struct pageref* allocpageref (void) [static, read]
Definition at line 146 of file kmalloc.c.
References INUSE_WORDS, KASSERT, NULL, pagerefs, and pagerefs_inuse.
Referenced by subpage_kmalloc().
static int blocktype (size_t sz) [inline, static]
Definition at line 379 of file kmalloc.c.
References NSIZES, panic(), and sizes.
Referenced by subpage_kmalloc().
static void dumpsubpage (struct pageref * pr) [static]
Definition at line 284 of file kmalloc.c.
References checksubpage, pageref::freelist_offset, INVALID_OFFSET, KASSERT, kprintf(), freelist::next, pageref::nfree, NULL, PAGE_SIZE, PR_BLOCKTYPE, PR_PAGEADDR, sizes, SMALLEST_SUBPAGE_SIZE, and spinlock_do_i_hold().
Referenced by kheap_printstats().
static void fill_deadbeef (void * vptr, size_t len) [static]
Definition at line 42 of file kmalloc.c.
Referenced by subpage_kfree().
static void freepageref (struct pageref * p) [static]
Definition at line 171 of file kmalloc.c.
References KASSERT, NPAGEREFS, pagerefs, and pagerefs_inuse.
Referenced by subpage_kfree().
void kfree (void * ptr)
Definition at line 622 of file kmalloc.c.
References free_kpages(), KASSERT, NULL, PAGE_SIZE, and subpage_kfree().
Referenced by array_cleanup(), array_destroy(), array_setsize(), as_destroy(), attach_console_to_vfs(), bitmap_create(), bitmap_destroy(), compute_thread(), cv_create(), cv_destroy(), emufs_addtovfs(), emufs_loadvnode(), emufs_reclaim(), lock_create(), lock_destroy(), mallocthread(), runprogram(), sem_create(), sem_destroy(), set_std_fd(), sfs_domount(), sfs_loadvnode(), sfs_reclaim(), sfs_unmount(), sys_close(), sys_dup2(), sys_execv(), thread_create(), thread_destroy(), thread_exit(), thread_fork(), thread_fork2(), vfs_doadd(), and wchan_destroy().
void kheap_printstats (void)
Definition at line 334 of file kmalloc.c.
References dumpsubpage(), kprintf(), pageref::next_all, NULL, spinlock_acquire(), and spinlock_release().
Referenced by cmd_kheapstats().
void* kmalloc (size_t sz)
Definition at line 602 of file kmalloc.c.
References alloc_kpages(), LARGEST_SUBPAGE_SIZE, NULL, PAGE_SIZE, and subpage_kmalloc().
Referenced by array_create(), array_setsize(), as_create(), attach_beep_to_ltimer(), attach_con_to_lscreen(), attach_con_to_lser(), attach_console_to_vfs(), attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), attach_ltrace_to_lamebus(), attach_random_to_lrandom(), attach_rtclock_to_ltimer(), bitmap_create(), compute_thread(), cpu_create(), cv_create(), dev_create_vnode(), devnull_create(), emufs_addtovfs(), emufs_loadvnode(), kstrdup(), lamebus_init(), lock_create(), mallocthread(), mkrawname(), runprogram(), sem_create(), set_std_fd(), sfs_domount(), sfs_loadvnode(), sys_dup2(), sys_execv(), sys_open(), thread_create(), thread_fork(), thread_fork2(), vfs_doadd(), and wchan_create().
static void remove_lists (struct pageref * pr, int blktype) [static]
Definition at line 354 of file kmalloc.c.
References checksubpage, KASSERT, pageref::next_all, pageref::next_samesize, and NSIZES.
Referenced by subpage_kfree().
static int subpage_kfree (void * ptr) [static]
Definition at line 513 of file kmalloc.c.
References checksubpage, checksubpages, fill_deadbeef(), free_kpages(), pageref::freelist_offset, freepageref(), INVALID_OFFSET, KASSERT, freelist::next, pageref::next_all, pageref::nfree, NSIZES, NULL, PAGE_SIZE, panic(), PR_BLOCKTYPE, PR_PAGEADDR, remove_lists(), sizes, spinlock_acquire(), and spinlock_release().
Referenced by kfree().
static void* subpage_kmalloc (size_t sz) [static]
Definition at line 397 of file kmalloc.c.
References alloc_kpages(), allocpageref(), blocktype(), checksubpage, checksubpages, free_kpages(), pageref::freelist_offset, INVALID_OFFSET, KASSERT, kprintf(), MKPAB, freelist::next, pageref::next_all, pageref::next_samesize, pageref::nfree, NULL, PAGE_SIZE, pageref::pageaddr_and_blocktype, PR_BLOCKTYPE, PR_PAGEADDR, sizes, spinlock_acquire(), and spinlock_release().
Referenced by kmalloc().
Variable Documentation
struct pageref* allbase [static]
Definition at line 187 of file kmalloc.c.
struct spinlock kmalloc_spinlock = SPINLOCK_INITIALIZER [static]
Definition at line 198 of file kmalloc.c.
struct pageref pagerefs[NPAGEREFS] [static]
Definition at line 139 of file kmalloc.c.
Referenced by allocpageref(), and freepageref().
uint32_t pagerefs_inuse[INUSE_WORDS] [static]
Definition at line 142 of file kmalloc.c.
Referenced by allocpageref(), and freepageref().
struct pageref* sizebases[NSIZES] [static]
Definition at line 186 of file kmalloc.c.
const size_t sizes[NSIZES] = { 16, 32, 64, 128, 256, 512, 1024, 2048 } [static]
Definition at line 87 of file kmalloc.c.
Referenced by blocktype(), dumpsubpage(), subpage_kfree(), subpage_kmalloc(), and test567().