Os/161: kern/include/device.h File Reference
kern/include/device.h File Reference
Data Structures
struct device
Functions
struct vnode * dev_create_vnode (struct device *dev)
void devnull_create (void)
void dev_bootstrap (void)
Function Documentation
void dev_bootstrap (void)
struct vnode* dev_create_vnode (struct device * dev) [read]
Definition at line 448 of file device.c.
References kmalloc(), NULL, panic(), strerror(), and VOP_INIT.
Referenced by vfs_doadd().
void devnull_create (void)
Definition at line 100 of file devnull.c.
References device::d_blocks, device::d_blocksize, device::d_close, device::d_data, device::d_devnumber, device::d_io, device::d_ioctl, device::d_open, kmalloc(), NULL, nullclose(), nullio(), nullioctl(), nullopen(), panic(), strerror(), and vfs_adddev().
Referenced by vfs_bootstrap().