Os/161: kern/include/spl.h File Reference
kern/include/spl.h File Reference
#include <cdefs.h>
Defines
#define IPL_NONE 0
#define IPL_HIGH 1
#define SPL_INLINE INLINE
Functions
int spl0 (void)
int splhigh (void)
int splx (int)
void splraise (int oldipl, int newipl)
void spllower (int oldipl, int newipl)
Define Documentation
#define IPL_HIGH 1
Definition at line 73 of file spl.h.
Referenced by mips_trap(), spinlock_acquire(), spinlock_release(), splhigh(), spllower(), splraise(), and thread_create().
#define IPL_NONE 0
Definition at line 72 of file spl.h.
Referenced by spinlock_acquire(), spinlock_release(), spl0(), spllower(), and splraise().
#define SPL_INLINE INLINE
Definition at line 91 of file spl.h.
Function Documentation
SPL_INLINE int spl0 (void)
Definition at line 96 of file spl.h.
References IPL_NONE, and splx().
Referenced by cpu_hatch(), mainbus_bootstrap(), mips_usermode(), and thread_startup().
SPL_INLINE int splhigh (void)
Definition at line 103 of file spl.h.
References IPL_HIGH, and splx().
Referenced by as_activate(), ltimer_gettime(), mips_trap(), panic(), shutdown(), sys_read(), sys_write(), thread_exit(), thread_fork2(), thread_switch(), vm_fault(), and waitpid().
void spllower (int oldipl, int newipl)
Definition at line 107 of file spl.c.
References cpu_irqon(), CURCPU_EXISTS, IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_release(), and splx().
void splraise (int oldipl, int newipl)
Definition at line 87 of file spl.c.
References cpu_irqoff(), CURCPU_EXISTS, IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_acquire(), and splx().
int splx (int)
Definition at line 132 of file spl.c.
References spllower(), splraise(), and thread::t_curspl.
Referenced by as_activate(), ltimer_gettime(), mips_trap(), spl0(), splhigh(), sys_read(), sys_write(), thread_fork2(), thread_switch(), vm_fault(), and waitpid().