Os/161: kern/include/vfs.h File Reference
kern/include/vfs.h File Reference
#include <array.h>
Defines
#define VFSINLINE INLINE
Functions
int vfs_setcurdir (struct vnode *dir)
int vfs_clearcurdir (void)
int vfs_getcurdir (struct vnode **retdir)
int vfs_sync (void)
int vfs_getroot (const char *devname, struct vnode **result)
const char * vfs_getdevname (struct fs *fs)
int vfs_lookup (char *path, struct vnode **result)
int vfs_lookparent (char *path, struct vnode **result, char *buf, size_t buflen)
int vfs_open (char *path, int openflags, mode_t mode, struct vnode **ret)
void vfs_close (struct vnode *vn)
int vfs_readlink (char *path, struct uio *data)
int vfs_symlink (const char *contents, char *path)
int vfs_mkdir (char *path, mode_t mode)
int vfs_link (char *oldpath, char *newpath)
int vfs_remove (char *path)
int vfs_rmdir (char *path)
int vfs_rename (char *oldpath, char *newpath)
int vfs_chdir (char *path)
int vfs_getcwd (struct uio *buf)
void vfs_bootstrap (void)
int vfs_setbootfs (const char *fsname)
void vfs_clearbootfs (void)
int vfs_adddev (const char *devname, struct device *dev, int mountable)
int vfs_addfs (const char *devname, struct fs *fs)
int vfs_mount (const char *devname, void *data, int(*mountfunc)(void *data, struct device *dev, struct fs **result))
int vfs_unmount (const char *devname)
int vfs_unmountall (void)
DECLARRAY (vnode)
DEFARRAY (vnode, VFSINLINE)
void vfs_biglock_acquire (void)
void vfs_biglock_release (void)
bool vfs_biglock_do_i_hold (void)
Define Documentation
#define VFSINLINE INLINE
Definition at line 181 of file vfs.h.
Function Documentation
DECLARRAY (vnode)
DEFARRAY (vnode , VFSINLINE)
int vfs_adddev (const char * devname, struct device * dev, int mountable)
Definition at line 453 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), and devnull_create().
int vfs_addfs (const char * devname, struct fs * fs)
Definition at line 464 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by emufs_addtovfs().
void vfs_biglock_acquire (void)
Definition at line 123 of file vfslist.c.
References lock_acquire(), lock_do_i_hold(), and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_truncate(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_sync(), vfs_unmount(), vfs_unmountall(), vnode_check(), vnode_decopen(), vnode_decref(), vnode_incopen(), and vnode_incref().
bool vfs_biglock_do_i_hold (void)
Definition at line 143 of file vfslist.c.
References lock_do_i_hold().
Referenced by badnames(), findmount(), getdevice(), sfs_rwblock(), vfs_getdevname(), and vfs_getroot().
void vfs_biglock_release (void)
Definition at line 132 of file vfslist.c.
References KASSERT, lock_do_i_hold(), lock_release(), and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_truncate(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_sync(), vfs_unmount(), vfs_unmountall(), vnode_check(), vnode_decopen(), vnode_decref(), vnode_incopen(), and vnode_incref().
void vfs_bootstrap (void)
Definition at line 99 of file vfslist.c.
References devnull_create(), knowndevs, lock_create(), NULL, panic(), and vfs_biglock_depth.
Referenced by boot().
int vfs_chdir (char * path)
Definition at line 121 of file vfscwd.c.
References vfs_lookup(), vfs_setcurdir(), and VOP_DECREF.
Referenced by cmd_chdir(), and vfs_setbootfs().
void vfs_clearbootfs (void)
Definition at line 115 of file vfslookup.c.
References change_bootfs(), NULL, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by shutdown().
int vfs_clearcurdir (void)
Definition at line 102 of file vfscwd.c.
References NULL, and VOP_DECREF.
Referenced by shutdown().
void vfs_close (struct vnode * vn)
Definition at line 119 of file vfspath.c.
References VOP_DECOPEN, and VOP_DECREF.
Referenced by dowritestress2(), fstest_read(), fstest_write(), printfile(), runprogram(), sys_close(), sys_dup2(), and sys_execv().
int vfs_getcurdir (struct vnode ** retdir)
Definition at line 52 of file vfscwd.c.
References ENOENT, NULL, and VOP_INCREF.
Referenced by getdevice(), vfs_getcwd(), and vfs_setbootfs().
int vfs_getcwd (struct uio * buf)
Definition at line 141 of file vfscwd.c.
References FSOP_GETVOLNAME, KASSERT, name, NULL, strlen(), UIO_READ, uio::uio_rw, uiomove(), vfs_biglock_acquire(), vfs_biglock_release(), vfs_getcurdir(), vfs_getdevname(), vnode::vn_fs, VOP_DECREF, and VOP_NAMEFILE.
Referenced by cmd_pwd().
const char* vfs_getdevname (struct fs * fs)
Definition at line 257 of file vfslist.c.
References KASSERT, knowndev::kd_fs, knowndev::kd_name, knowndevs, NULL, num, and vfs_biglock_do_i_hold().
Referenced by vfs_getcwd().
int vfs_getroot (const char * devname, struct vnode ** result)
Definition at line 177 of file vfslist.c.
References ENODEV, ENXIO, FSOP_GETROOT, FSOP_GETVOLNAME, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, knowndevs, NULL, num, strcmp(), vfs_biglock_do_i_hold(), and VOP_INCREF.
Referenced by getdevice().
int vfs_link (char * oldpath, char * newpath)
Definition at line 195 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vfs_lookup(), vnode::vn_fs, VOP_DECREF, and VOP_LINK.
int vfs_lookparent (char * path, struct vnode ** result, char * buf, size_t buflen)
Definition at line 232 of file vfslookup.c.
References EINVAL, getdevice(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), VOP_DECREF, and VOP_LOOKPARENT.
Referenced by vfs_link(), vfs_mkdir(), vfs_open(), vfs_remove(), vfs_rename(), vfs_rmdir(), and vfs_symlink().
int vfs_lookup (char * path, struct vnode ** result)
Definition at line 265 of file vfslookup.c.
References getdevice(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), VOP_DECREF, and VOP_LOOKUP.
Referenced by vfs_chdir(), vfs_link(), vfs_open(), and vfs_readlink().
int vfs_mkdir (char * path, mode_t mode)
Definition at line 281 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_MKDIR.
int vfs_mount (const char * devname, void * data, int(*)(void *data, struct device *dev, struct fs **result) mountfunc)
Referenced by sfs_mount().
int vfs_open (char * path, int openflags, mode_t mode, struct vnode ** ret)
Definition at line 45 of file vfspath.c.
References EINVAL, KASSERT, name, NAME_MAX, NULL, O_ACCMODE, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, vfs_lookparent(), vfs_lookup(), VOP_CREAT, VOP_DECOPEN, VOP_DECREF, VOP_INCOPEN, VOP_OPEN, and VOP_TRUNCATE.
Referenced by dowritestress2(), fstest_read(), fstest_write(), printfile(), runprogram(), set_std_fd(), sys_execv(), and sys_open().
int vfs_readlink (char * path, struct uio * data)
Definition at line 260 of file vfspath.c.
References vfs_lookup(), VOP_DECREF, and VOP_READLINK.
int vfs_remove (char * path)
Definition at line 141 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_REMOVE.
Referenced by fstest_remove(), and fstest_write().
int vfs_rename (char * oldpath, char * newpath)
Definition at line 160 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vnode::vn_fs, VOP_DECREF, and VOP_RENAME.
int vfs_rmdir (char * path)
Definition at line 303 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_RMDIR.
int vfs_setbootfs (const char * fsname)
Definition at line 71 of file vfslookup.c.
References change_bootfs(), EINVAL, NAME_MAX, snprintf(), strcat(), strchr(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), vfs_chdir(), and vfs_getcurdir().
Referenced by boot(), and cmd_bootfs().
int vfs_setcurdir (struct vnode * dir)
Definition at line 72 of file vfscwd.c.
References ENOTDIR, NULL, S_IFDIR, VOP_DECREF, VOP_GETTYPE, and VOP_INCREF.
Referenced by vfs_chdir().
int vfs_symlink (const char * contents, char * path)
Definition at line 235 of file vfspath.c.
References NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_SYMLINK.
int vfs_sync (void)
Definition at line 152 of file vfslist.c.
References FSOP_SYNC, knowndev::kd_fs, knowndevs, NULL, num, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_quit(), cmd_sync(), and panic().
int vfs_unmount (const char * devname)
Definition at line 555 of file vfslist.c.
References EINVAL, fail(), findmount(), FSOP_SYNC, FSOP_UNMOUNT, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, kprintf(), NULL, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_unmount().
int vfs_unmountall (void)
Definition at line 600 of file vfslist.c.
References EBUSY, FSOP_SYNC, FSOP_UNMOUNT, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndevs, kprintf(), NULL, num, strerror(), vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by shutdown().