Os/161: user/testbin/malloctest/malloctest.c File Reference
user/testbin/malloctest/malloctest.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <err.h>
Data Structures
struct test3
Defines
#define _PATH_RANDOM "random:"
#define SMALLSIZE 72
#define MEDIUMSIZE 896
#define BIGSIZE 16384
#define HUGESIZE (1024 * 1024 * 1024)
#define OVERHEAD 32
#define ABSURD_OVERHEAD 256
Functions
static int geti (void)
static void markblock (volatile void *ptr, size_t size, unsigned bias, int doprint)
static int checkblock (volatile void *ptr, size_t size, unsigned bias, int doprint)
static void test1 (void)
static void test2 (void)
static void test3 (void)
static void test4 (void)
static void test567 (int testno, unsigned long seed)
static void test5 (void)
static void test6 (void)
static void test7 (void)
static int dotest (int tn)
int main (int argc, char *argv[])
Variables
struct {
int num
const char * desc
void(* func)(void)
} tests []
Define Documentation
#define _PATH_RANDOM "random:"
Definition at line 48 of file malloctest.c.
Referenced by test6().
#define ABSURD_OVERHEAD 256
Definition at line 59 of file malloctest.c.
Referenced by test4().
#define BIGSIZE 16384
Definition at line 52 of file malloctest.c.
Referenced by test1(), and test3().
#define HUGESIZE (1024 * 1024 * 1024)
Definition at line 53 of file malloctest.c.
Referenced by test2().
#define MEDIUMSIZE 896
Definition at line 51 of file malloctest.c.
Referenced by test3(), and test4().
#define OVERHEAD 32
Definition at line 56 of file malloctest.c.
Referenced by test4().
#define SMALLSIZE 72
Definition at line 50 of file malloctest.c.
Referenced by test3(), and test4().
Function Documentation
static int checkblock (volatile void * ptr, size_t size, unsigned bias, int doprint) [static]
Definition at line 128 of file malloctest.c.
References printf().
Referenced by test1(), test2(), test3(), and test567().
static int dotest (int tn) [static]
Definition at line 643 of file malloctest.c.
References num, and tests.
Referenced by main().
static int geti (void) [static]
Definition at line 63 of file malloctest.c.
References ch, getchar(), printf(), and putchar().
Referenced by main(), and test7().
int main (int argc, char * argv[])
Definition at line 656 of file malloctest.c.
References atoi(), desc, dotest(), geti(), menu(), num, printf(), and tests.
static void markblock (volatile void * ptr, size_t size, unsigned bias, int doprint) [static]
Definition at line 102 of file malloctest.c.
References printf().
Referenced by test1(), test2(), test3(), and test567().
static void test1 (void) [static]
Definition at line 172 of file malloctest.c.
References BIGSIZE, checkblock(), free(), malloc(), markblock(), NULL, and printf().
static void test2 (void) [static]
Definition at line 230 of file malloctest.c.
References checkblock(), free(), HUGESIZE, malloc(), markblock(), NULL, and printf().
static void test3 (void) [static]
Definition at line 295 of file malloctest.c.
References BIGSIZE, checkblock(), free(), test3::junk, malloc(), markblock(), MEDIUMSIZE, test3::next, NULL, printf(), and SMALLSIZE.
static void test4 (void) [static]
Definition at line 389 of file malloctest.c.
References ABSURD_OVERHEAD, free(), malloc(), MEDIUMSIZE, NULL, OVERHEAD, printf(), and SMALLSIZE.
static void test5 (void) [static]
Definition at line 579 of file malloctest.c.
References printf(), and test567().
static void test567 (int testno, unsigned long seed) [static]
Definition at line 518 of file malloctest.c.
References checkblock(), free(), malloc(), markblock(), NULL, printf(), random(), sizes, and srandom().
Referenced by test5(), test6(), and test7().
static void test6 (void) [static]
Definition at line 587 of file malloctest.c.
References _PATH_RANDOM, close(), err(), errx(), fd, O_RDONLY, open(), printf(), read(), and test567().
static void test7 (void) [static]
Definition at line 612 of file malloctest.c.
References geti(), printf(), and test567().
Variable Documentation
const char* desc
Definition at line 628 of file malloctest.c.
Referenced by any_empty(), main(), and one_ioctl_badbuf().
void(* func)(void)
int num
Definition at line 627 of file malloctest.c.
Referenced by array_get(), array_remove(), array_set(), badnames(), dotest(), emufs_loadvnode(), emufs_reclaim(), findmount(), main(), sfs_loadvnode(), sfs_reclaim(), sfs_sync(), vfs_getdevname(), vfs_getroot(), vfs_sync(), and vfs_unmountall().
struct { ... } tests[] [static]
Referenced by dotest(), and main().