Os/161: kern/lib/misc.c File Reference
kern/lib/misc.c File Reference
#include <types.h>
#include <kern/errmsg.h>
#include <lib.h>
Functions
char * kstrdup (const char *s)
const char * strerror (int errcode)
Function Documentation
char* kstrdup (const char * s)
Definition at line 38 of file misc.c.
References kmalloc(), NULL, strcpy(), and strlen().
Referenced by cv_create(), lock_create(), runprogram(), sem_create(), set_std_fd(), setup(), thread_create(), and vfs_doadd().
const char* strerror (int errcode)
Definition at line 55 of file misc.c.