Os/161: kern/vfs/vnode.c File Reference
kern/vfs/vnode.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <synch.h>
#include <vfs.h>
#include <vnode.h>
Functions
int vnode_init (struct vnode *vn, const struct vnode_ops *ops, struct fs *fs, void *fsdata)
void vnode_cleanup (struct vnode *vn)
void vnode_incref (struct vnode *vn)
void vnode_decref (struct vnode *vn)
void vnode_incopen (struct vnode *vn)
void vnode_decopen (struct vnode *vn)
void vnode_check (struct vnode *v, const char *opstr)
Function Documentation
void vnode_check (struct vnode * v, const char * opstr)
Definition at line 174 of file vnode.c.
References kprintf(), NULL, panic(), strcmp(), vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_fs, vnode::vn_opencount, vnode::vn_ops, vnode::vn_refcount, VOP_MAGIC, and vnode_ops::vop_magic.
void vnode_cleanup (struct vnode * vn)
Definition at line 64 of file vnode.c.
References KASSERT, NULL, vnode::vn_data, vnode::vn_fs, vnode::vn_opencount, vnode::vn_ops, and vnode::vn_refcount.
void vnode_decopen (struct vnode * vn)
Definition at line 142 of file vnode.c.
References KASSERT, kprintf(), NULL, strerror(), vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_opencount, and VOP_CLOSE.
void vnode_decref (struct vnode * vn)
Definition at line 99 of file vnode.c.
References EBUSY, KASSERT, kprintf(), NULL, strerror(), vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_refcount, and VOP_RECLAIM.
void vnode_incopen (struct vnode * vn)
Definition at line 128 of file vnode.c.
References KASSERT, NULL, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_opencount.
Referenced by sys_dup2().
void vnode_incref (struct vnode * vn)
Definition at line 82 of file vnode.c.
References KASSERT, NULL, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_refcount.
Referenced by sys_dup2().
int vnode_init (struct vnode * vn, const struct vnode_ops * ops, struct fs * fs, void * fsdata)
Definition at line 45 of file vnode.c.
References KASSERT, NULL, vnode::vn_data, vnode::vn_fs, vnode::vn_opencount, vnode::vn_ops, and vnode::vn_refcount.