Os/161: kern/thread/clock.c File Reference
kern/thread/clock.c File Reference
#include <types.h>
#include <lib.h>
#include <cpu.h>
#include <wchan.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
Defines
#define SCHEDULE_HARDCLOCKS 4
#define MIGRATE_HARDCLOCKS 16
Functions
void hardclock_bootstrap (void)
void timerclock (void)
void hardclock (void)
void clocksleep (int num_secs)
Variables
static struct wchan * lbolt
Define Documentation
#define MIGRATE_HARDCLOCKS 16
Definition at line 54 of file clock.c.
Referenced by hardclock().
#define SCHEDULE_HARDCLOCKS 4
Definition at line 53 of file clock.c.
Referenced by hardclock().
Function Documentation
void clocksleep (int num_secs)
Definition at line 109 of file clock.c.
References wchan_lock(), and wchan_sleep().
Referenced by waitpid().
void hardclock (void)
Definition at line 89 of file clock.c.
References curcpu, MIGRATE_HARDCLOCKS, schedule(), SCHEDULE_HARDCLOCKS, thread_consider_migration(), and thread_yield().
Referenced by ltimer_irq(), and mainbus_interrupt().
void hardclock_bootstrap (void)
Definition at line 65 of file clock.c.
References NULL, panic(), and wchan_create().
Referenced by boot().
void timerclock (void)
Definition at line 78 of file clock.c.
References wchan_wakeall().
Referenced by ltimer_irq().
Variable Documentation
struct wchan* lbolt [static]
Definition at line 59 of file clock.c.