Os/161: user/bin/cp/cp.c File Reference
user/bin/cp/cp.c File Reference
#include <unistd.h>
#include <err.h>
Functions
static void copy (const char *from, const char *to)
int main (int argc, char *argv[])
Function Documentation
static void copy (const char * from, const char * to) [static]
Definition at line 42 of file cp.c.
References close(), err(), O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), read(), and write().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 98 of file cp.c.
References copy(), and errx().