Os/161: kern/vfs/vfspath.c File Reference
kern/vfs/vfspath.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <limits.h>
#include <lib.h>
#include <vfs.h>
#include <vnode.h>
Functions
int vfs_open (char *path, int openflags, mode_t mode, struct vnode **ret)
void vfs_close (struct vnode *vn)
int vfs_remove (char *path)
int vfs_rename (char *oldpath, char *newpath)
int vfs_link (char *oldpath, char *newpath)
int vfs_symlink (const char *contents, char *path)
int vfs_readlink (char *path, struct uio *uio)
int vfs_mkdir (char *path, mode_t mode)
int vfs_rmdir (char *path)
Function Documentation
void vfs_close (struct vnode * vn)
Definition at line 119 of file vfspath.c.
References VOP_DECOPEN, and VOP_DECREF.
Referenced by dowritestress2(), fstest_read(), fstest_write(), printfile(), runprogram(), sys_close(), sys_dup2(), and sys_execv().
int vfs_link (char * oldpath, char * newpath)
Definition at line 195 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vfs_lookup(), vnode::vn_fs, VOP_DECREF, and VOP_LINK.
int vfs_mkdir (char * path, mode_t mode)
Definition at line 281 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_MKDIR.
int vfs_open (char * path, int openflags, mode_t mode, struct vnode ** ret)
Definition at line 45 of file vfspath.c.
References EINVAL, KASSERT, name, NAME_MAX, NULL, O_ACCMODE, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, vfs_lookparent(), vfs_lookup(), VOP_CREAT, VOP_DECOPEN, VOP_DECREF, VOP_INCOPEN, VOP_OPEN, and VOP_TRUNCATE.
Referenced by dowritestress2(), fstest_read(), fstest_write(), printfile(), runprogram(), set_std_fd(), sys_execv(), and sys_open().
int vfs_readlink (char * path, struct uio * uio)
Definition at line 260 of file vfspath.c.
References vfs_lookup(), VOP_DECREF, and VOP_READLINK.
int vfs_remove (char * path)
Definition at line 141 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_REMOVE.
Referenced by fstest_remove(), and fstest_write().
int vfs_rename (char * oldpath, char * newpath)
Definition at line 160 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vnode::vn_fs, VOP_DECREF, and VOP_RENAME.
int vfs_rmdir (char * path)
Definition at line 303 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_RMDIR.
int vfs_symlink (const char * contents, char * path)
Definition at line 235 of file vfspath.c.
References NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_SYMLINK.