Os/161: user/lib/libc/unix/err.c File Reference
user/lib/libc/unix/err.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include <errno.h>
Functions
static void __senderr (void *junk, const char *data, size_t len)
static void __senderrstr (const char *str)
static void __printerr (int use_errno, const char *fmt, va_list ap)
void vwarn (const char *fmt, va_list ap)
void vwarnx (const char *fmt, va_list ap)
void verr (int exitcode, const char *fmt, va_list ap)
void verrx (int exitcode, const char *fmt, va_list ap)
void warn (const char *fmt,...)
void warnx (const char *fmt,...)
void err (int exitcode, const char *fmt,...)
void errx (int exitcode, const char *fmt,...)
Variables
char ** __argv
Function Documentation
static void __printerr (int use_errno, const char * fmt, va_list ap) [static]
Definition at line 75 of file err.c.
References __argv, __senderr(), __senderrstr(), __vprintf(), errno, NULL, and strerror().
Referenced by verr(), verrx(), vwarn(), and vwarnx().
static void __senderr (void * junk, const char * data, size_t len) [static]
Definition at line 52 of file err.c.
References STDERR_FILENO, and write().
Referenced by __printerr(), and __senderrstr().
static void __senderrstr (const char * str) [static]
Definition at line 65 of file err.c.
References __senderr(), NULL, and strlen().
Referenced by __printerr().
void err (int exitcode, const char * fmt, ...)
Definition at line 176 of file err.c.
References va_end, va_start, and verr().
Referenced by __malloc_init(), big_file(), cat(), cleanup(), closedisk(), closeit(), complain(), concur(), copy(), dir_test(), diskread(), diskwrite(), dobadreads(), docat(), docreatestress(), dohardlink(), doreadat0(), doreadateof(), doreadone(), doreadstress(), doremove(), dorename(), dorm(), dosymlink(), dowritestress(), dowritestress2(), finish(), firstread(), fstest_read(), fstest_remove(), fstest_write(), hog(), isdir(), killdir(), listdir(), main(), makeprocs(), mkfile(), opendisk(), openit(), print(), readateof(), readit(), readone(), recursedir(), setup(), sink(), spawnv(), startup(), subproc_read(), subproc_write(), syscall(), tail(), test2(), test3(), test4(), test5(), test6(), test7(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), and whalemating().
void errx (int exitcode, const char * fmt, ...)
Definition at line 185 of file err.c.
References va_end, va_start, and verrx().
Referenced by __malloc_init(), __malloc_sbrk(), __malloc_split(), __malloc_trymerge(), addmemory(), big_file(), check(), check_buffer(), check_sb(), domalloc(), doreadat0(), doreadateof(), doreadone(), dumpsb(), firstread(), free(), main(), malloc(), mkfile(), opendisk(), option(), readateof(), readit(), readone(), subproc_read(), test3(), test6(), test7(), writebitmap(), and writesuper().
void verr (int exitcode, const char * fmt, va_list ap)
Definition at line 138 of file err.c.
References __printerr(), and exit().
Referenced by err().
void verrx (int exitcode, const char * fmt, va_list ap)
Definition at line 146 of file err.c.
References __printerr(), and exit().
Referenced by errx().
void vwarn (const char * fmt, va_list ap)
Definition at line 124 of file err.c.
References __printerr().
Referenced by warn().
void vwarnx (const char * fmt, va_list ap)
Definition at line 131 of file err.c.
References __printerr().
Referenced by warnx().
void warn (const char * fmt, ...)
Definition at line 158 of file err.c.
References va_end, va_start, and vwarn().
Referenced by cmd_chdir(), create_testdir(), create_testfile(), create_testlink(), docommand(), dofork(), dorm(), dowait(), dowaitpoll(), dup2_self(), enforce_sbrk(), exec_common_fork(), forkoff(), ftruncate_fd_device(), getdirentry_setup(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_pasteof(), main(), makeprocs(), open_testfile(), report_survival(), report_test(), report_test2(), sbrk_unalignedneg(), sbrk_unalignedpos(), wait_badflags(), wait_badstatus(), wait_parent(), wait_siblings(), wait_siblings_child(), wait_unaligned(), and waitall().
void warnx (const char * fmt, ...)
Definition at line 167 of file err.c.
References va_end, va_start, and vwarnx().
Referenced by __malloc_init(), adjust_filelinks(), bitmap_mark(), check(), check_bitmap(), check_dir(), check_dir_entry(), check_inode_blocks(), check_root_dir(), check_sb(), check_timing(), dirread(), dirwrite(), docommand(), dorm(), dowait(), dumpdir(), dup2_self(), enforce_sbrk(), exec_common_fork(), free(), lseek_file_stdin(), lseek_loc_pasteof(), main(), malloc(), open_testfile(), reboot_badflags(), report_test(), report_test2(), reportbits(), runtest(), sbrk_unalignedneg(), sbrk_unalignedpos(), test3(), test4(), test5(), test_dup2(), triple(), wait_siblings(), and waitall().
Variable Documentation
char** __argv
Definition at line 41 of file errno.c.
Referenced by __printerr().