Os/161: kern/vm/addrspace.c File Reference
kern/vm/addrspace.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <addrspace.h>
#include <vm.h>
Functions
struct addrspace * as_create (void)
int as_copy (struct addrspace *old, struct addrspace **ret)
void as_destroy (struct addrspace *as)
void as_activate (struct addrspace *as)
int as_define_region (struct addrspace *as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
int as_prepare_load (struct addrspace *as)
int as_complete_load (struct addrspace *as)
int as_define_stack (struct addrspace *as, vaddr_t *stackptr)
Function Documentation
void as_activate (struct addrspace * as)
Definition at line 90 of file addrspace.c.
References NUM_TLB, splhigh(), splx(), tlb_write(), TLBHI_INVALID, and TLBLO_INVALID.
int as_complete_load (struct addrspace * as)
Definition at line 138 of file addrspace.c.
int as_copy (struct addrspace * old, struct addrspace ** ret)
Definition at line 60 of file addrspace.c.
References as_create(), as_destroy(), addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, as_prepare_load(), addrspace::as_stackpbase, addrspace::as_vbase1, addrspace::as_vbase2, DUMBVM_STACKPAGES, ENOMEM, KASSERT, memmove(), NULL, PADDR_TO_KVADDR, and PAGE_SIZE.
struct addrspace* as_create (void) [read]
Definition at line 43 of file addrspace.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, addrspace::as_stackpbase, addrspace::as_vbase1, addrspace::as_vbase2, kmalloc(), and NULL.
int as_define_region (struct addrspace * as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
Definition at line 110 of file addrspace.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_vbase1, addrspace::as_vbase2, EUNIMP, kprintf(), PAGE_FRAME, and PAGE_SIZE.
int as_define_stack (struct addrspace * as, vaddr_t * stackptr)
Definition at line 149 of file addrspace.c.
References addrspace::as_stackpbase, KASSERT, and USERSTACK.
void as_destroy (struct addrspace * as)
Definition at line 80 of file addrspace.c.
References kfree().
int as_prepare_load (struct addrspace * as)
Definition at line 127 of file addrspace.c.
References addrspace::as_npages1, addrspace::as_npages2, addrspace::as_pbase1, addrspace::as_pbase2, addrspace::as_stackpbase, as_zero_region(), DUMBVM_STACKPAGES, ENOMEM, getppages(), and KASSERT.