Os/161: kern/include/copyinout.h File Reference
kern/include/copyinout.h File Reference
Functions
int copyin (const_userptr_t usersrc, void *dest, size_t len)
int copyout (const void *src, userptr_t userdest, size_t len)
int copyinstr (const_userptr_t usersrc, char *dest, size_t len, size_t *got)
int copyoutstr (const char *src, userptr_t userdest, size_t len, size_t *got)
Function Documentation
int copyin (const_userptr_t usersrc, void * dest, size_t len)
Definition at line 153 of file copyinout.c.
References copycheck(), copyfail(), EFAULT, memcpy(), NULL, and setjmp().
Referenced by syscall(), and uiomove().
int copyinstr (const_userptr_t usersrc, char * dest, size_t len, size_t * got)
Definition at line 266 of file copyinout.c.
References copycheck(), copyfail(), copystr(), EFAULT, NULL, and setjmp().
Referenced by sys_execv().
int copyout (const void * src, userptr_t userdest, size_t len)
Definition at line 189 of file copyinout.c.
References copycheck(), copyfail(), EFAULT, memcpy(), NULL, and setjmp().
Referenced by runprogram(), sys___time(), sys_execv(), and uiomove().
int copyoutstr (const char * src, userptr_t userdest, size_t len, size_t * got)
Definition at line 299 of file copyinout.c.
References copycheck(), copyfail(), copystr(), EFAULT, NULL, and setjmp().