Os/161: user/testbin/badcall/bad_symlink.c File Reference
user/testbin/badcall/bad_symlink.c File Reference
#include <unistd.h>
#include <errno.h>
#include "test.h"
Functions
static void symlink_empty1 (void)
static void symlink_empty2 (void)
void test_symlink (void)
Function Documentation
static void symlink_empty1 (void) [static]
Definition at line 41 of file bad_symlink.c.
References EINVAL, errno, report_test2(), symlink(), and TESTLINK.
Referenced by test_symlink().
static void symlink_empty2 (void) [static]
Definition at line 51 of file bad_symlink.c.
References EINVAL, errno, report_test(), and symlink().
Referenced by test_symlink().
void test_symlink (void)
Definition at line 59 of file bad_symlink.c.
References symlink_empty1(), symlink_empty2(), and test_symlink_paths().