Os/161: user/testbin/badcall/bad_readlink.c File Reference
user/testbin/badcall/bad_readlink.c File Reference
#include <unistd.h>
#include <errno.h>
#include "test.h"
Functions
static void readlink_file (void)
static void readlink_dir (void)
static void readlink_empty (void)
void test_readlink (void)
Function Documentation
static void readlink_dir (void) [static]
Definition at line 58 of file bad_readlink.c.
References EISDIR, errno, readlink(), and report_test().
Referenced by test_readlink().
static void readlink_empty (void) [static]
Definition at line 68 of file bad_readlink.c.
References EINVAL, EISDIR, errno, readlink(), and report_test2().
Referenced by test_readlink().
static void readlink_file (void) [static]
Definition at line 41 of file bad_readlink.c.
References close(), EINVAL, errno, fd, open_testfile(), readlink(), report_test(), and TESTFILE.
Referenced by test_readlink().
void test_readlink (void)
Definition at line 77 of file bad_readlink.c.
References readlink_dir(), readlink_empty(), readlink_file(), test_readlink_buf(), and test_readlink_path().