Os/161: user/testbin/sty/sty.c File Reference
user/testbin/sty/sty.c File Reference
#include <unistd.h>
#include <err.h>
Defines
#define MAXPROCS 6
Functions
static void hog (void)
static void waitall (void)
int main ()
Variables
static char * hargv [2] = { (char *)"hog", NULL }
static int pids [MAXPROCS]
static int npids
Define Documentation
#define MAXPROCS 6
Definition at line 44 of file sty.c.
Function Documentation
static void hog (void) [static]
Definition at line 49 of file sty.c.
References err(), execv(), fork(), hargv, and pid.
Referenced by main().
int main (void)
Definition at line 85 of file sty.c.
References hog(), and waitall().
static void waitall (void) [static]
Definition at line 68 of file sty.c.
References waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by main().
Variable Documentation
char* hargv[2] = { (char *)"hog", NULL } [static]
Definition at line 42 of file sty.c.
Referenced by hog().
int npids [static]
Definition at line 45 of file sty.c.
int pids[MAXPROCS] [static]
Definition at line 45 of file sty.c.