Os/161: user/testbin/badcall/bad_rename.c File Reference
user/testbin/badcall/bad_rename.c File Reference
#include <unistd.h>
#include <errno.h>
#include "test.h"
Functions
static void rename_dot (void)
static void rename_dotdot (void)
static void rename_empty1 (void)
static void rename_empty2 (void)
void test_rename (void)
Function Documentation
static void rename_dot (void) [static]
Definition at line 41 of file bad_rename.c.
References EINVAL, errno, rename(), report_test(), and TESTDIR.
Referenced by test_rename().
static void rename_dotdot (void) [static]
Definition at line 54 of file bad_rename.c.
References EINVAL, errno, rename(), report_test(), and TESTDIR.
Referenced by test_rename().
static void rename_empty1 (void) [static]
Definition at line 67 of file bad_rename.c.
References EINVAL, EISDIR, errno, rename(), report_test2(), and TESTDIR.
Referenced by test_rename().
static void rename_empty2 (void) [static]
Definition at line 80 of file bad_rename.c.
References create_testdir(), EINVAL, EISDIR, errno, rename(), report_test2(), rmdir(), and TESTDIR.
Referenced by test_rename().
void test_rename (void)
Definition at line 92 of file bad_rename.c.
References rename_dot(), rename_dotdot(), rename_empty1(), rename_empty2(), and test_rename_paths().