Os/161: user/lib/libc/stdlib/system.c File Reference
user/lib/libc/stdlib/system.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
Defines
#define MAXCMDSIZE 2048
#define MAXARGS 128
Functions
int system (const char *cmd)
Define Documentation
#define MAXARGS 128
Definition at line 42 of file system.c.
Referenced by system().
#define MAXCMDSIZE 2048
Definition at line 41 of file system.c.
Referenced by system().
Function Documentation
int system (const char * cmd)
Definition at line 45 of file system.c.
References _exit(), E2BIG, errno, execv(), fork(), MAXARGS, MAXCMDSIZE, NULL, pid, strcpy(), strlen(), strtok(), and waitpid().