Os/161: user/testbin/palin/palin.c File Reference
user/testbin/palin/palin.c File Reference
#include <stdio.h>
#include <string.h>
Functions
int main ()
Variables
char palindrome [1000]
Function Documentation
int main (void)
Definition at line 176 of file palin.c.
References palindrome, printf(), putchar(), and strlen().
Variable Documentation
char palindrome[1000]
Initial value:
"amanaplanacaretabanamyriadasumalacaliarahoopapintacatalpaagasanoil"
"abirdayellavatacawapaxawagataxanayaramacapayamagayatsarawalla"
Definition at line 87 of file palin.c.
Referenced by main().