Os/161: user/testbin/badcall/bad_ioctl.c File Reference
user/testbin/badcall/bad_ioctl.c File Reference
#include <sys/types.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <stdio.h>
#include <errno.h>
#include "config.h"
#include "test.h"
Defines
#define IOCTL(fd, sym) any_ioctl_badbuf(fd, sym, #sym)
Functions
static void one_ioctl_badbuf (int fd, int code, const char *codename, void *ptr, const char *ptrdesc)
static void any_ioctl_badbuf (int fd, int code, const char *codename)
static void ioctl_badbuf (void)
static void ioctl_badcode (void)
void test_ioctl (void)
Define Documentation
#define IOCTL (fd, sym) any_ioctl_badbuf(fd, sym, #sym)
Definition at line 65 of file bad_ioctl.c.
Function Documentation
static void any_ioctl_badbuf (int fd, int code, const char * codename) [static]
Definition at line 58 of file bad_ioctl.c.
References NULL, and one_ioctl_badbuf().
Referenced by ioctl_badbuf().
static void ioctl_badbuf (void) [static]
Definition at line 69 of file bad_ioctl.c.
References any_ioctl_badbuf().
Referenced by test_ioctl().
static void ioctl_badcode (void) [static]
Definition at line 87 of file bad_ioctl.c.
References EIOCTL, errno, ioctl(), NONEXIST_IOCTL, NULL, report_test(), and STDIN_FILENO.
Referenced by test_ioctl().
static void one_ioctl_badbuf (int fd, int code, const char * codename, void * ptr, const char * ptrdesc) [static]
Definition at line 45 of file bad_ioctl.c.
References desc, EFAULT, errno, ioctl(), report_test(), and snprintf().
Referenced by any_ioctl_badbuf().
void test_ioctl (void)
Definition at line 95 of file bad_ioctl.c.
References ioctl_badbuf(), ioctl_badcode(), and test_ioctl_fd().