Os/161: user/testbin/badcall/driver.c File Reference
user/testbin/badcall/driver.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Defines
#define LOWEST 'a'
#define HIGHEST '|'
Functions
static int finderror (int rv, int error)
void report_survival (int rv, int error, const char *desc)
void report_test (int rv, int error, int right_error, const char *desc)
void report_test2 (int rv, int error, int okerr1, int okerr2, const char *desc)
int open_testfile (const char *string)
int create_testfile (void)
int create_testdir (void)
int create_testlink (void)
static void menu (void)
static void runit (int op)
int main (int argc, char **argv)
Variables
struct {
int ch
int asst
const char * name
void(* f)(void)
} ops []
Define Documentation
#define HIGHEST '|'
Definition at line 221 of file driver.c.
Referenced by main(), and runit().
#define LOWEST 'a'
Definition at line 220 of file driver.c.
Referenced by main().
Function Documentation
int create_testdir (void)
Definition at line 157 of file driver.c.
References mkdir(), TESTDIR, and warn().
Referenced by link_empty2(), remove_dir(), and rename_empty2().
int create_testfile (void)
Definition at line 138 of file driver.c.
References close(), fd, NULL, open_testfile(), TESTFILE, and warn().
Referenced by common_badpath(), and rmdir_file().
int create_testlink (void)
Definition at line 169 of file driver.c.
References symlink(), TESTLINK, and warn().
Referenced by readlink_setup().
static int finderror (int rv, int error) [static]
Definition at line 46 of file driver.c.
Referenced by report_survival(), report_test(), and report_test2().
int main (int argc, char ** argv)
Definition at line 288 of file driver.c.
References EOF, getchar(), HIGHEST, LOWEST, menu(), printf(), and runit().
static void menu (void) [static]
Definition at line 225 of file driver.c.
References ch, name, ops, and printf().
int open_testfile (const char * string)
Definition at line 100 of file driver.c.
References close(), fd, lseek(), O_CREAT, O_RDWR, O_TRUNC, open(), SEEK_SET, strlen(), TESTFILE, warn(), warnx(), and write().
Referenced by create_testfile(), ftruncate_size_neg(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), read_setup(), readlink_file(), wait_siblings(), and write_setup().
void report_survival (int rv, int error, const char * desc)
Definition at line 57 of file driver.c.
References errno, finderror(), and warn().
Referenced by pipe_unaligned(), wait_parent(), wait_self(), wait_siblings_child(), and wait_unaligned().
void report_test (int rv, int error, int right_error, const char * desc)
Definition at line 65 of file driver.c.
References ENOSYS, errno, EUNIMP, finderror(), warn(), and warnx().
Referenced by any_badfd(), common_badbuf(), common_badpath(), dup2_fd2(), exec_badargs(), exec_badprog(), exec_onearg(), ftruncate_fd_device(), ftruncate_size_neg(), ioctl_badcode(), link_dir(), link_empty1(), link_empty2(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_whence_inval(), mkdir_dot(), mkdir_dotdot(), mkdir_empty(), one_ioctl_badbuf(), open_badflags(), pipe_badptr(), readlink_dir(), readlink_file(), reboot_badflags(), remove_dir(), rename_dot(), rename_dotdot(), rmdir_dot(), rmdir_empty(), rmdir_file(), symlink_empty2(), time_badnsecs(), time_badsecs(), wait_badflags(), and wait_badstatus().
void report_test2 (int rv, int error, int okerr1, int okerr2, const char * desc)
Definition at line 82 of file driver.c.
References ENOSYS, errno, EUNIMP, finderror(), warn(), and warnx().
Referenced by any_empty(), chdir_empty(), exec_emptyprog(), open_empty(), readlink_empty(), remove_dot(), remove_dotdot(), remove_empty(), rename_empty1(), rename_empty2(), rmdir_dotdot(), symlink_empty1(), and wait_badpid().
static void runit (int op) [static]
Definition at line 247 of file driver.c.
References asst, exit(), HIGHEST, menu(), name, ops, and printf().
Referenced by main().
Variable Documentation
int asst
Definition at line 185 of file driver.c.
Referenced by runit().
int ch
Definition at line 184 of file driver.c.
Referenced by check_buffer(), con_io(), doargs(), getchar(), getcmd(), geti(), kgets(), loudthread(), lscreen_irq(), lser_irq(), main(), menu(), quietthread(), rotate(), strchr(), and strrchr().
void(* f)(void)
Referenced by __pf_fill(), jump_to_inval(), jump_to_kernel(), jump_to_null(), qsort(), random_unlocked(), and sfs_link().
const char* name
Definition at line 186 of file driver.c.
struct { ... } ops[] [static]
Referenced by menu(), runit(), and sfs_loadvnode().