Os/161: user/testbin/badcall/bad_time.c File Reference
user/testbin/badcall/bad_time.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void time_badsecs (void *ptr, const char *desc)
static void time_badnsecs (void *ptr, const char *desc)
void test_time (void)
Function Documentation
void test_time (void)
Definition at line 67 of file bad_time.c.
References time_badnsecs(), and time_badsecs().
static void time_badnsecs (void * ptr, const char * desc) [static]
Definition at line 58 of file bad_time.c.
References __time(), EFAULT, errno, NULL, and report_test().
Referenced by test_time().
static void time_badsecs (void * ptr, const char * desc) [static]
Definition at line 48 of file bad_time.c.
References __time(), EFAULT, errno, NULL, and report_test().
Referenced by test_time().