Os/161: user/testbin/bigfile/bigfile.c File Reference
user/testbin/bigfile/bigfile.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
Functions
int main (int argc, char *argv[])
Variables
static char buffer [100]
Function Documentation
int main (int argc, char * argv[])
Definition at line 48 of file bigfile.c.
References atoi(), buffer, close(), err(), errx(), O_CREAT, O_TRUNC, O_WRONLY, open(), printf(), snprintf(), strlen(), and write().
Variable Documentation
char buffer[100] [static]
Definition at line 45 of file bigfile.c.
Referenced by check_buffer(), main(), subproc_read(), and subproc_write().