Os/161: user/testbin/badcall/bad_lseek.c File Reference
user/testbin/badcall/bad_lseek.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void lseek_fd_device (void)
static void lseek_file_stdin (void)
static void lseek_loc_negative (void)
static void lseek_whence_inval (void)
static void lseek_loc_pasteof (void)
void test_lseek (void)
Function Documentation
static void lseek_fd_device (void) [static]
Definition at line 48 of file bad_lseek.c.
References close(), errno, ESPIPE, fd, lseek(), O_RDONLY, open(), report_test(), SEEK_SET, and warn().
Referenced by test_lseek().
static void lseek_file_stdin (void) [static]
Definition at line 66 of file bad_lseek.c.
References _exit(), close(), dup2(), errno, fd, fork(), lseek(), NULL, open_testfile(), pid, report_test(), SEEK_END, SEEK_SET, STDIN_FILENO, strlen(), TESTFILE, waitpid(), warn(), warnx(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, write(), and WTERMSIG.
Referenced by test_lseek().
static void lseek_loc_negative (void) [static]
Definition at line 151 of file bad_lseek.c.
References close(), EINVAL, errno, fd, lseek(), NULL, open_testfile(), report_test(), SEEK_SET, and TESTFILE.
Referenced by test_lseek().
static void lseek_loc_pasteof (void) [static]
Definition at line 187 of file bad_lseek.c.
References close(), fd, lseek(), open_testfile(), pos, SEEK_CUR, SEEK_END, SEEK_SET, strlen(), TESTFILE, warn(), and warnx().
Referenced by test_lseek().
static void lseek_whence_inval (void) [static]
Definition at line 169 of file bad_lseek.c.
References close(), EINVAL, errno, fd, lseek(), open_testfile(), report_test(), and TESTFILE.
Referenced by test_lseek().
void test_lseek (void)
Definition at line 239 of file bad_lseek.c.
References lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), and test_lseek_fd().