Os/161: user/testbin/badcall/bad_open.c File Reference
user/testbin/badcall/bad_open.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void open_badflags (void)
static void open_empty (void)
void test_open (void)
Function Documentation
static void open_badflags (void) [static]
Definition at line 48 of file bad_open.c.
References EINVAL, errno, fd, open(), and report_test().
Referenced by test_open().
static void open_empty (void) [static]
Definition at line 58 of file bad_open.c.
References close(), EINVAL, errno, O_RDONLY, open(), and report_test2().
Referenced by test_open().
void test_open (void)
Definition at line 69 of file bad_open.c.
References open_badflags(), open_empty(), and test_open_path().