Os/161: user/lib/libc/string/strtok.c File Reference
user/lib/libc/string/strtok.c File Reference
#include <string.h>
Functions
char * strtok (char *str, const char *seps)
Variables
static char * __strtok_context
Function Documentation
char* strtok (char * str, const char * seps)
Definition at line 35 of file strtok.c.
References __strtok_context, and strtok_r().
Referenced by docommand(), and system().
Variable Documentation
char* __strtok_context [static]
Definition at line 32 of file strtok.c.
Referenced by strtok().