Os/161: user/testbin/userthreads/userthreads.c File Reference
user/testbin/userthreads/userthreads.c File Reference
#include <unistd.h>
#include <stdio.h>
Defines
#define NTHREADS 3
#define MAX 1<<25
Functions
void ThreadRunner (void)
void BladeRunner (void)
int main (int argc, char *argv[])
Variables
volatile int count = 0
Define Documentation
#define MAX 1<<25
Definition at line 56 of file userthreads.c.
Referenced by BladeRunner(), and ThreadRunner().
#define NTHREADS 3
Definition at line 55 of file userthreads.c.
Function Documentation
void BladeRunner (void)
Definition at line 92 of file userthreads.c.
References count, MAX, and printf().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 68 of file userthreads.c.
References BladeRunner(), NTHREADS, printf(), and ThreadRunner().
void ThreadRunner (void)
Definition at line 102 of file userthreads.c.
References count, MAX, and printf().
Referenced by main().
Variable Documentation
volatile int count = 0
Definition at line 61 of file userthreads.c.
Referenced by __puts(), BladeRunner(), checksum_file(), main(), and ThreadRunner().