Os/161: user/sbin/dumpsfs/dumpsfs.c File Reference
user/sbin/dumpsfs/dumpsfs.c File Reference
#include <sys/types.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <assert.h>
#include <limits.h>
#include <err.h>
#include "support.h"
#include "kern/sfs.h"
#include "disk.h"
Defines
#define SWAPL(x) (x)
#define SWAPS(x) (x)
Functions
static uint32_t dumpsb (void)
static void dodirblock (uint32_t block)
static void dumpdir (uint32_t ino)
static void dumpbits (uint32_t fsblocks)
int main (int argc, char **argv)
Define Documentation
#define SWAPL (x) (x)
Definition at line 52 of file dumpsfs.c.
Referenced by dodirblock(), dumpdir(), dumpsb(), swapdir(), swapindir(), swapinode(), swapsb(), writerootdir(), and writesuper().
#define SWAPS (x) (x)
Definition at line 53 of file dumpsfs.c.
Referenced by swapinode(), and writerootdir().
Function Documentation
static void dodirblock (uint32_t block) [static]
Definition at line 77 of file dumpsfs.c.
References diskread(), printf(), sfs_dir::sfd_ino, sfs_dir::sfd_name, SFS_NAMELEN, SFS_NOINO, and SWAPL.
Referenced by dumpdir().
static void dumpbits (uint32_t fsblocks) [static]
Definition at line 137 of file dumpsfs.c.
References diskread(), nblocks, printf(), SFS_BITBLOCKS, SFS_BITMAPSIZE, SFS_BLOCKBITS, SFS_BLOCKSIZE, and SFS_MAP_LOCATION.
Referenced by main().
static void dumpdir (uint32_t ino) [static]
Definition at line 100 of file dumpsfs.c.
References diskread(), dodirblock(), nblocks, printf(), sfs_inode::sfi_direct, sfs_inode::sfi_indirect, sfs_inode::sfi_size, SFS_DBPERIDB, SFS_NDIRECT, SWAPL, and warnx().
Referenced by main().
static uint32_t dumpsb (void) [static]
Definition at line 61 of file dumpsfs.c.
References diskread(), errx(), printf(), SFS_MAGIC, SFS_SB_LOCATION, sfs_super::sp_magic, sfs_super::sp_nblocks, sfs_super::sp_volname, and SWAPL.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 158 of file dumpsfs.c.
References closedisk(), dumpbits(), dumpdir(), dumpsb(), errx(), hostcompat_init(), nblocks, opendisk(), and SFS_ROOT_LOCATION.