Os/161: user/testbin/psort/psort.c File Reference
user/testbin/psort/psort.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
Defines
#define PATH_KEYS "sortkeys"
#define PATH_SORTED "output"
#define PATH_TESTDIR "psortdir"
#define PATH_RANDOM "rand:"
#define WORKNUM (128*1024)
#define NOBODY (-1)
Functions
static void sortints (int *v, int num)
static void initprogname (const char *av0)
static void vscomplain (char *buf, size_t len, const char *fmt, va_list ap, int err)
static void complainx (const char *fmt,...)
static void complain (const char *fmt,...)
static int doopen (const char *path, int flags, int mode)
static void doclose (const char *path, int fd)
static void docreate (const char *path)
static void doremove (const char *path)
static off_t getsize (const char *path)
static size_t doread (const char *path, int fd, void *buf, size_t len)
static void doexactread (const char *path, int fd, void *buf, size_t len)
static void dowrite (const char *path, int fd, const void *buf, size_t len)
static void dolseek (const char *name, int fd, off_t offset, int whence)
static pid_t dofork (void)
static int dowait (int guy, pid_t pid)
static void doforkall (const char *phasename, void(*func)(void))
static void seekmyplace (const char *name, int fd)
static int getmykeys (void)
static unsigned long checksum_file (const char *path)
static void genkeys_sub (void)
static void genkeys (void)
static const char * binname (int a, int b)
static const char * mergedname (int a)
static void bin (void)
static void sortbins (void)
static void mergebins (void)
static void assemble (void)
static void checksize_bins (void)
static void checksize_merge (void)
static void sort (void)
static const char * validname (int a)
static void checksize_valid (void)
static void dovalidate (void)
static void validate (void)
static void setdir (void)
static void unsetdir (void)
static void randomize (void)
static void usage (void)
static void doargs (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
static int workspace [WORKNUM]
static const char * progname
static int numprocs = 4
static int numkeys = 10000
static long randomseed = 15432753
static off_t correctsize
static unsigned long checksum
static int me = NOBODY
static long * seeds
Define Documentation
#define NOBODY (-1)
Definition at line 75 of file psort.c.
#define PATH_KEYS "sortkeys"
Definition at line 56 of file psort.c.
Referenced by bin(), genkeys(), genkeys_sub(), and unsetdir().
#define PATH_RANDOM "rand:"
Definition at line 59 of file psort.c.
Referenced by randomize().
#define PATH_SORTED "output"
Definition at line 57 of file psort.c.
Referenced by assemble(), dovalidate(), sort(), and unsetdir().
#define PATH_TESTDIR "psortdir"
Definition at line 58 of file psort.c.
Referenced by setdir(), and unsetdir().
#define WORKNUM (128*1024)
Definition at line 61 of file psort.c.
Referenced by bin(), dovalidate(), genkeys_sub(), and mergebins().
Function Documentation
static void assemble (void) [static]
Definition at line 773 of file psort.c.
References complain(), doclose(), dolseek(), doopen(), dup2(), execv(), exit(), fd, getsize(), me, mergedname(), NULL, O_WRONLY, PATH_SORTED, SEEK_SET, and STDOUT_FILENO.
Referenced by sort().
static void bin (void) [static]
Definition at line 606 of file psort.c.
References assert, binname(), complainx(), doclose(), doexactread(), doopen(), dowrite(), getmykeys(), me, name, numprocs, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, PATH_KEYS, RANDOM_MAX, seekmyplace(), WORKNUM, and workspace.
Referenced by sort().
static const char* binname (int a, int b) [static]
Definition at line 588 of file psort.c.
References snprintf().
Referenced by bin(), checksize_bins(), mergebins(), sort(), and sortbins().
static void checksize_bins (void) [static]
Definition at line 804 of file psort.c.
References binname(), complain(), correctsize, exit(), getsize(), and numprocs.
Referenced by sort().
static void checksize_merge (void) [static]
Definition at line 824 of file psort.c.
References complain(), correctsize, exit(), getsize(), mergedname(), and numprocs.
Referenced by sort().
static void checksize_valid (void) [static]
Definition at line 905 of file psort.c.
References complainx(), exit(), getsize(), numprocs, and validname().
Referenced by validate().
static unsigned long checksum_file (const char * path) [static]
Definition at line 487 of file psort.c.
References count, doclose(), doopen(), doread(), fd, and O_RDONLY.
Referenced by genkeys(), and sort().
static void complain (const char * fmt, ...) [static]
Definition at line 192 of file psort.c.
References err(), errno, STDERR_FILENO, strlen(), va_end, va_start, vscomplain(), and write().
Referenced by assemble(), checksize_bins(), checksize_merge(), doargs(), doclose(), dofork(), dolseek(), doopen(), doread(), doremove(), dovalidate(), dowait(), dowrite(), getsize(), unsetdir(), usage(), and validate().
static void complainx (const char * fmt, ...) [static]
Definition at line 177 of file psort.c.
References STDERR_FILENO, strlen(), va_end, va_start, vscomplain(), and write().
Referenced by bin(), checksize_valid(), doexactread(), doforkall(), dowait(), dowrite(), genkeys(), main(), mergebins(), sort(), sortbins(), and validate().
static void doargs (int argc, char * argv[]) [static]
Definition at line 1086 of file psort.c.
References assert, atoi(), ch, complain(), exit(), numkeys, numprocs, randomize(), randomseed, and usage().
Referenced by main().
static void doclose (const char * path, int fd) [static]
Definition at line 224 of file psort.c.
References close(), complain(), and exit().
Referenced by assemble(), bin(), checksum_file(), docreate(), dovalidate(), genkeys_sub(), mergebins(), randomize(), and sortbins().
static void docreate (const char * path) [static]
Definition at line 234 of file psort.c.
References doclose(), doopen(), fd, O_CREAT, O_TRUNC, and O_WRONLY.
Referenced by genkeys(), and sort().
static void doexactread (const char * path, int fd, void * buf, size_t len) [static]
Definition at line 323 of file psort.c.
References complainx(), doread(), and exit().
Referenced by bin(), dovalidate(), randomize(), sortbins(), and validate().
static pid_t dofork (void) [static]
Definition at line 385 of file psort.c.
References complain(), fork(), and pid.
Referenced by doforkall().
static void doforkall (const char * phasename, void(*)(void) func) [static]
Definition at line 426 of file psort.c.
References complainx(), dofork(), dowait(), exit(), me, numprocs, and pids.
Referenced by genkeys(), sort(), and validate().
static void dolseek (const char * name, int fd, off_t offset, int whence) [static]
Definition at line 353 of file psort.c.
References complain(), exit(), and lseek().
Referenced by assemble(), seekmyplace(), and sortbins().
static int doopen (const char * path, int flags, int mode) [static]
Definition at line 210 of file psort.c.
References complain(), exit(), fd, and open().
Referenced by assemble(), bin(), checksum_file(), docreate(), dovalidate(), genkeys_sub(), getsize(), mergebins(), randomize(), sortbins(), and validate().
static size_t doread (const char * path, int fd, void * buf, size_t len) [static]
Definition at line 309 of file psort.c.
References complain(), exit(), and read().
Referenced by checksum_file(), doexactread(), and mergebins().
static void doremove (const char * path) [static]
Definition at line 244 of file psort.c.
References complain(), ENOSYS, and errno.
Referenced by sort(), unsetdir(), and validate().
static void dovalidate (void) [static]
Definition at line 926 of file psort.c.
References complain(), doclose(), doexactread(), doopen(), dowrite(), exit(), fd, getmykeys(), me, name, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, PATH_SORTED, RANDOM_MAX, seekmyplace(), validname(), WORKNUM, and workspace.
Referenced by validate().
static int dowait (int guy, pid_t pid) [static]
Definition at line 402 of file psort.c.
References assert, complain(), complainx(), waitpid(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by doforkall().
static void dowrite (const char * path, int fd, const void * buf, size_t len) [static]
Definition at line 336 of file psort.c.
References complain(), complainx(), exit(), and write().
Referenced by bin(), dovalidate(), genkeys_sub(), mergebins(), and sortbins().
static void genkeys (void) [static]
Definition at line 554 of file psort.c.
References checksum, checksum_file(), complainx(), correctsize, docreate(), doforkall(), exit(), genkeys_sub(), getsize(), NULL, numprocs, PATH_KEYS, random(), randomseed, and srandom().
Referenced by main().
static void genkeys_sub (void) [static]
Definition at line 513 of file psort.c.
References assert, doclose(), doopen(), dowrite(), fd, getmykeys(), me, O_WRONLY, PATH_KEYS, random(), RANDOM_MAX, seekmyplace(), srandom(), WORKNUM, and workspace.
Referenced by genkeys().
static int getmykeys (void) [static]
Definition at line 472 of file psort.c.
References me, numkeys, and numprocs.
Referenced by bin(), dovalidate(), and genkeys_sub().
static off_t getsize (const char * path) [static]
Definition at line 263 of file psort.c.
References close(), complain(), doopen(), ENOSYS, errno, exit(), fd, fstat(), lseek(), O_RDONLY, SEEK_CUR, SEEK_END, stat::st_size, and stat().
Referenced by assemble(), checksize_bins(), checksize_merge(), checksize_valid(), genkeys(), sort(), and sortbins().
static void initprogname (const char * av0) [static]
Definition at line 134 of file psort.c.
References progname, and strrchr().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 1133 of file psort.c.
References complainx(), correctsize, doargs(), genkeys(), initprogname(), NULL, numkeys, setdir(), sort(), unsetdir(), and validate().
static void mergebins (void) [static]
Definition at line 691 of file psort.c.
References assert, binname(), complainx(), doclose(), doopen(), doread(), dowrite(), exit(), me, mergedname(), name, numprocs, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, WORKNUM, and workspace.
Referenced by sort().
static const char* mergedname (int a) [static]
Definition at line 597 of file psort.c.
References snprintf().
Referenced by assemble(), checksize_merge(), mergebins(), and sort().
static void randomize (void) [static]
Definition at line 1067 of file psort.c.
References doclose(), doexactread(), doopen(), fd, O_RDONLY, PATH_RANDOM, and randomseed.
Referenced by doargs().
static void seekmyplace (const char * name, int fd) [static]
Definition at line 458 of file psort.c.
References dolseek(), me, numkeys, numprocs, and SEEK_SET.
Referenced by bin(), dovalidate(), and genkeys_sub().
static void setdir (void) [static]
Definition at line 1039 of file psort.c.
References domkdir(), and PATH_TESTDIR.
Referenced by main().
static void sort (void) [static]
Definition at line 842 of file psort.c.
References assemble(), bin(), binname(), checksize_bins(), checksize_merge(), checksum, checksum_file(), complainx(), correctsize, docreate(), doforkall(), doremove(), exit(), getsize(), mergebins(), mergedname(), numprocs, PATH_SORTED, and sortbins().
Referenced by main().
static void sortbins (void) [static]
Definition at line 659 of file psort.c.
References binname(), complainx(), doclose(), doexactread(), dolseek(), doopen(), dowrite(), exit(), fd, getsize(), me, name, numprocs, O_RDWR, SEEK_SET, sortints(), and workspace.
Referenced by sort().
static void sortints (int * v, int num) [static]
Definition at line 82 of file psort.c.
References assert.
Referenced by sortbins().
static void unsetdir (void) [static]
Definition at line 1049 of file psort.c.
References complain(), doremove(), PATH_KEYS, PATH_SORTED, PATH_TESTDIR, and rmdir().
Referenced by main().
static void usage (void) [static]
Definition at line 1078 of file psort.c.
References complain(), exit(), and progname.
Referenced by doargs().
static void validate (void) [static]
Definition at line 987 of file psort.c.
References checksize_valid(), complain(), complainx(), doexactread(), doforkall(), doopen(), doremove(), dovalidate(), exit(), fd, name, numprocs, O_RDONLY, RANDOM_MAX, and validname().
Referenced by main().
static const char* validname (int a) [static]
Definition at line 896 of file psort.c.
References snprintf().
Referenced by checksize_valid(), dovalidate(), and validate().
static void vscomplain (char * buf, size_t len, const char * fmt, va_list ap, int err) [static]
Definition at line 152 of file psort.c.
References me, pos, progname, snprintf(), strerror(), strlen(), and vsnprintf().
Referenced by complain(), and complainx().
Variable Documentation
unsigned long checksum [static]
Definition at line 73 of file psort.c.
Referenced by genkeys(), and sort().
off_t correctsize [static]
Definition at line 72 of file psort.c.
Referenced by checksize_bins(), checksize_merge(), genkeys(), main(), and sort().
int me = NOBODY [static]
Definition at line 76 of file psort.c.
Referenced by assemble(), bin(), doforkall(), dovalidate(), genkeys_sub(), getmykeys(), mergebins(), seekmyplace(), sortbins(), and vscomplain().
int numkeys = 10000 [static]
Definition at line 69 of file psort.c.
Referenced by doargs(), getmykeys(), main(), and seekmyplace().
int numprocs = 4 [static]
Definition at line 68 of file psort.c.
Referenced by bin(), checksize_bins(), checksize_merge(), checksize_valid(), doargs(), doforkall(), genkeys(), getmykeys(), mergebins(), seekmyplace(), sort(), sortbins(), and validate().
const char* progname [static]
Definition at line 66 of file psort.c.
Referenced by cmd_progthread(), initprogname(), usage(), and vscomplain().
long randomseed = 15432753 [static]
Definition at line 70 of file psort.c.
Referenced by doargs(), genkeys(), and randomize().
long* seeds [static]
Definition at line 509 of file psort.c.
int workspace[WORKNUM] [static]
Definition at line 64 of file psort.c.
Referenced by bin(), dovalidate(), genkeys_sub(), mergebins(), and sortbins().