Os/161: user/lib/libc/stdlib/exit.c File Reference
user/lib/libc/stdlib/exit.c File Reference
#include <stdlib.h>
#include <unistd.h>
Functions
void exit (int code)
void __exit_hack (void)
Function Documentation
void __exit_hack (void)
Definition at line 76 of file exit.c.
void exit (int code)
Definition at line 38 of file exit.c.
References _exit().
Referenced by _exit(), assemble(), checksize_bins(), checksize_merge(), checksize_valid(), cmd_exit(), doargs(), doclose(), doexactread(), dofork(), doforkall(), dohardlink(), dolseek(), doopen(), doread(), dovalidate(), dowait(), dowrite(), exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), genkeys(), getsize(), go(), main(), makeprocs(), mergebins(), runit(), setup(), sort(), sortbins(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), usage(), validate(), verr(), verrx(), wait_badflags(), wait_badstatus(), and wait_unaligned().