Os/161: user/testbin/crash/crash.c File Reference
user/testbin/crash/crash.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>
#include <err.h>
Typedefs
typedef void(* func)(void)
Functions
static void read_from_null (void)
static void read_from_inval (void)
static void read_from_kernel (void)
static void write_to_null (void)
static void write_to_inval (void)
static void write_to_code (void)
static void write_to_kernel (void)
static void jump_to_null (void)
static void jump_to_inval (void)
static void jump_to_kernel (void)
static void illegal_instruction (void)
static void alignment_error (void)
static void divide_by_zero (void)
static void mod_by_zero (void)
static void recurse_inf (void)
int main (int argc, char **argv)
Variables
struct {
int ch
const char * name
func f
} ops []
Typedef Documentation
typedef void(* func)(void)
Definition at line 58 of file crash.c.
Function Documentation
static void alignment_error (void) [static]
Definition at line 157 of file crash.c.
static void divide_by_zero (void) [static]
Definition at line 169 of file crash.c.
static void illegal_instruction (void) [static]
Definition at line 146 of file crash.c.
static void jump_to_inval (void) [static]
Definition at line 129 of file crash.c.
References f.
static void jump_to_kernel (void) [static]
Definition at line 137 of file crash.c.
References f.
static void jump_to_null (void) [static]
Definition at line 121 of file crash.c.
References f, and NULL.
int main (int argc, char ** argv)
Definition at line 225 of file crash.c.
References _exit(), ch, fork(), getchar(), name, ops, pid, printf(), waitpid(), warn(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
static void mod_by_zero (void) [static]
Definition at line 180 of file crash.c.
static void read_from_inval (void) [static]
Definition at line 71 of file crash.c.
static void read_from_kernel (void) [static]
Definition at line 80 of file crash.c.
static void read_from_null (void) [static]
Definition at line 62 of file crash.c.
References NULL.
static void recurse_inf (void) [static]
Definition at line 191 of file crash.c.
static void write_to_code (void) [static]
Definition at line 105 of file crash.c.
static void write_to_inval (void) [static]
Definition at line 97 of file crash.c.
static void write_to_kernel (void) [static]
Definition at line 113 of file crash.c.
static void write_to_null (void) [static]
Definition at line 89 of file crash.c.
References NULL.
Variable Documentation
int ch
Definition at line 202 of file crash.c.
func f
Definition at line 204 of file crash.c.
const char* name
Definition at line 203 of file crash.c.
struct { ... } ops[] [static]
Referenced by main().