Os/161: user/testbin/sort/sort.c File Reference
user/testbin/sort/sort.c File Reference
#include <stdlib.h>
#include <string.h>
#include <err.h>
Defines
#define SIZE (144*1024)
Functions
static void sort (int *arr, int size)
static void initarray (void)
static void check (void)
int main (void)
Variables
static int A [SIZE]
Define Documentation
#define SIZE (144*1024)
Definition at line 44 of file sort.c.
Function Documentation
static void check (void) [static]
Definition at line 115 of file sort.c.
References A, errx(), SIZE, and warnx().
Referenced by main().
static void initarray (void) [static]
Definition at line 99 of file sort.c.
References A, random(), SIZE, and srandom().
Referenced by main().
int main (void)
Definition at line 129 of file sort.c.
References A, check(), initarray(), SIZE, and sort().
static void sort (int * arr, int size) [static]
Definition at line 59 of file sort.c.
References memcpy(), and SIZE.
Referenced by main().
Variable Documentation
int A[SIZE] [static]
Definition at line 95 of file sort.c.