Os/161: user/testbin/forktest/forktest.c File Reference
user/testbin/forktest/forktest.c File Reference
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <err.h>
Functions
static int dofork (void)
static void check (void)
static void dowait (int nowait, int pid)
static void test (int nowait)
int main (int argc, char *argv[])
Variables
static volatile int mypid
Function Documentation
static void check (void) [static]
Definition at line 73 of file forktest.c.
References errx(), getpid(), and mypid.
Referenced by test().
static int dofork (void) [static]
Definition at line 56 of file forktest.c.
References fork(), pid, and warn().
Referenced by test().
static void dowait (int nowait, int pid) [static]
Definition at line 102 of file forktest.c.
References exit(), waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by test().
int main (int argc, char * argv[])
Definition at line 170 of file forktest.c.
References strcmp(), test(), and warnx().
static void test (int nowait) [static]
Definition at line 133 of file forktest.c.
References check(), dofork(), dowait(), and putchar().
Referenced by main().
Variable Documentation
volatile int mypid [static]
Definition at line 49 of file forktest.c.
Referenced by check(), wait_parent(), and wait_siblings_child().